### ISSUE TITLE
feature request: ability to customize colors for files marked for cut/copy

### ISSUE THREAD

**Issue by kriansa** [nvim-tree/nvim-tree.lua#1079]
It would be good to have the possibility to customize visually the files that have been marked for copy or cut, so we can easily toggle between unwanted marked files. Is that something that interests you?

**Comment by kyazdani42** [comment]
would be feasible yes. But the renderer is a bit messy so adding features to it is not a good idea, but if you still wish to implement this, go for it :)

**Comment by cainnz** [comment]
hi, is it possible to change the colors of folders? is yes, which lines should I be looking at? thanks a lot for this awesome plugin

**Comment by kyazdani42** [comment]
hi @cainnz wdym by changing the colors of folders ? Do you mean changing it related to this feature request ?

**Comment by cainnz** [comment]
> hi @cainnz wdym by changing the colors of folders ? Do you mean changing it related to this feature request ?

Hi, yes, but I read in a Reddit post that the folder colors are defined by the theme that is being use. I use alacrity terminal.

**Comment by alex-courtis** [comment]
> Hi, yes, but I read in a Reddit post that the folder colors are defined by the theme that is being use. I use alacrity terminal.

Please link your sources. We cannot confirm or deny or provide useful feeedback on vague hearsay.

Not sure what you mean by "theme", however the nvim-tree colours are defined by its highlight groups. See `:help nvim-tree-highlight`. `NvimTreeFolderName` controls folder colours.

There is currently no group for files marked for cut/copy like `NvimTreeCut`. That is what this feature is requesting.
