### ISSUE TITLE
Feature Request: show image dimension info for <c-k>

### ISSUE THREAD

**Issue by maple-leaf** [nvim-tree/nvim-tree.lua#1189]
**Is your feature request related to a problem? Please describe.**
I want to know the image dimension when checking the file info. For now, we only have size, etc.
![image](https://user-images.githubusercontent.com/3980995/164955972-f703b036-eb5a-4a59-9dec-b879abec4231.png)

**Describe the solution you'd like**
show image dimension in the file info popup

This is an amazing plugin, works great and fast. Thank you.

**Comment by kyazdani42** [comment]
Hi ! You could write this if you wish :)

**Comment by alex-courtis** [comment]
Thanks for the feature request.

Unfortunately, this falls outside the scope of nvim-tree as a file explorer.

Please see [Roadmap](https://github.com/nvim-tree/nvim-tree.lua#roadmap).
