### ISSUE TITLE
Make git ignored file/folder in dim grey color

### ISSUE THREAD

**Issue by linrongbin16** [nvim-tree/nvim-tree.lua#1191]
**Is your feature request related to a problem? Please describe.**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/6496887/164968253-2915054a-6fa0-4cc3-a9c0-e76bf80be21a.png">

Git ignore icon "◌" is actually mixed with filetype/folder icon, some item has 1 icon on left side, some ignored item has 2 icons.
This looks no neat, not clear enough for user.

Although `g:nvim_tree_icons.git.ignored` could be configured as empty string `""`, but it will lose git ignored info to user.
<img width="818" alt="image" src="https://user-images.githubusercontent.com/6496887/164968568-db3d564b-1fe7-446c-9936-9f2874fd10a5.png">

**Describe the solution you'd like**

Make git ignored item (file/folder) in dim grey color (like coc-explorer).

**Describe alternatives you've considered**

Move all git status icons before folder structure indent line (like coc-explorer).

**Additional context**

coc-explorer: https://github.com/weirongxu/coc-explorer

**Comment by kyazdani42** [comment]
hi, seems like there is a missing NvimTreeGitIgnored highlight group for git highlighting. The renderer is currently under refactoring, it'll soon be possible to extend its capabilities :)

**Comment by alex-courtis** [comment]
`NvimTreeGitIgnored` has been added.
