### ISSUE TITLE
Combine arrows with indend markers

### ISSUE THREAD

**Issue by Shatur** [nvim-tree/nvim-tree.lua#1211]
**Is your feature request related to a problem? Please describe.**
Currently `'folder_arrows': 1` is incompatible with `renderer.indent_markers.enable`. 

**Describe the solution you'd like**
It would be great to combine it, just render an arrow as a first character as in https://github.com/nvim-neo-tree/neo-tree.nvim

**Comment by kyazdani42** [comment]
Indeed, it's not too hard to do, and now the renderer has been refactored it can be done !

**Comment by kyazdani42** [comment]
Working now. Closing
