### ISSUE TITLE
FindFile but not focus the tree

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-tree/nvim-tree.lua#1212]
Is it possible to run `NvimTreeFindFile` but keep the focus on the file buffer, i..e, not focus on the tree automatically? Thank you so much.

**Comment by kyazdani42** [comment]
`:NvimTreeFindFile | wincmd p` ?

**Comment by rockyzhang24** [comment]
Yes. This is exactly what I came up with. I am wondering whether it will be better to add an boolean argument for `find_file()` function like what `toggle()` does to control "focus or not"? Thanks.

**Comment by alex-courtis** [comment]
I know this does not exactly fit your requirement, however `update_focused_file.enable` will focus the tree on the file buffer without changing focus.

**Comment by kyazdani42** [comment]
@rockyzhang24 i think it could make sense yes :)

**Comment by naquad** [comment]
Is there any progress with this? Suggested options don't work I keep getting

```
Error detected while processing VimEnter Autocommands for "*":
Error executing Lua callback: ...fig/nvim/bundle/nvim-tree.lua/lua/nvim-tree/git/init.lua:99: table index is nil
stack traceback:
        ...fig/nvim/bundle/nvim-tree.lua/lua/nvim-tree/git/init.lua:99: in function 'load_project_status'
        ...vim/bundle/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:28: in function '_load'
        ...vim/bundle/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:22: in function 'new'
        ....config/nvim/bundle/nvim-tree.lua/lua/nvim-tree/core.lua:15: in function 'init'
        .../.config/nvim/bundle/nvim-tree.lua/lua/nvim-tree/lib.lua:98: in function 'open'
        ...quad/.config/nvim/bundle/nvim-tree.lua/lua/nvim-tree.lua:94: in function 'open'
        ...quad/.config/nvim/bundle/nvim-tree.lua/lua/nvim-tree.lua:293: in function <...quad/.config/nvim/bundle/nvim-tree.lua/lua/nvim-tree.lua:292>
Press ENTER or type command to continue
```

But the future would help a lot.

**Comment by alex-courtis** [comment]
A proper solution with `find_file(..., no_focus)` would be best.

PRs gratefully accepted :)

**Comment by alex-courtis** [comment]
Functionality added. Please see `:help nvim-tree-api`

**Comment by alex-courtis** [comment]
Tracked at #2011
