### ISSUE TITLE
Collected Diagnostic Sign Issues

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1216]
There are some issues with diagnostic sign visibility and correctness at fd2332a

Collect any bugs discovered in here.

I have seen some sporadic problems with signs not updating, however I have not been able to reproduce.

**Comment by alex-courtis** [comment]
#1157 (#1174) has been resolved

**Comment by alex-courtis** [comment]
#1213 has been raised however has no reproducer

**Comment by kyazdani42** [comment]
I think we could move the diagnostics update into the renderer actually, it'd be less inaccurate.

**Comment by alex-courtis** [comment]
> I think we could move the diagnostics update into the renderer actually, it'd be less inaccurate.

Yes.

Having the renderer able to render indicators in the signs column would be useful: we could then put other indicators e.g. git in there.

**Comment by alex-courtis** [comment]
There are timing issues with diagnostics, that we don't see with other signs e.g. git. The diagnostics are often not updated until _after_ the tree is rendered. This is a poor user experience.

We are able to handle git changes perfectly as we are reacting to all events that cause changes to git signs e.g. buffer writes. Diagnostics are lazy and late.

**Improvement:**
Render the diagnostics upon change, rather than just on tree render.
For nvim lsp we can use [vim.lsp.diagnostic.on_publish_diagnostics](https://neovim.io/doc/user/lsp.html)

**Comment by alex-courtis** [comment]
#1243 updates on CocDiagnosticChange

**Comment by kyazdani42** [comment]
During this week, i've experienced a few diagnostics issues, using the default lsp diagnostics provided by neovim. I had to manually refresh the tree because the diagnostics where not updated.
I'm not sure where this comes from, but i hope i can reproduce this more consistently.

**Comment by alex-courtis** [comment]
We are using the `DiagnosticChanged` for lsp updates. [vim.lsp.diagnostic.on_publish_diagnostics](https://neovim.io/doc/user/lsp.html) may provide more consistent timings and perhaps even allow us to see atomic updates.

Coc has no option but the `CocDiagnosticChange` event.

**Comment by kyazdani42** [comment]
ah i didn't know they added this method. I'll take a look at that.

**Comment by crosscode-nl** [comment]
@kyazdani42 Is this worked on, or a separate issue created? If it is not worked on, I think I can try to work on it because it is bothering me. :)

**Comment by alex-courtis** [comment]
> @kyazdani42 Is this worked on, or a separate issue created? If it is not worked on, I think I can try to work on it because it is bothering me. :)

Your assistance would be gratefully appreciated.

#1430 added throttling (debouncing) and some additional safety to diagnostics.

**Comment by alex-courtis** [comment]
Diagnostics appear stable and are no longer causing performance issues as they are debounced.

Please raise a new [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) if you encounter any problems.
