### ISSUE TITLE
[find file] when the file is not found, focus the potential parent folder

### ISSUE THREAD

**Issue by vanarok** [nvim-tree/nvim-tree.lua#1339]
At the moment it does not focus on the last visible directory if the file is out of sight(hidden).
![2022-06-12T12:39:58,235209814+04:00](https://user-images.githubusercontent.com/6105977/173224889-637c528a-98b6-4788-b8e8-2ffe6a867292.png)
The gray files are hidden when nvim tree starts and in this case it should focus on the "config" folder.

**Comment by kyazdani42** [comment]
hi, please elaborate, i don't understand you feature request.
-> current behavior for event/action
-> behavior wanted for event/action

**Comment by vanarok** [comment]
Current behavior. When the nvim tree is opened, the cursor will not focus on a file in the nvim tree tab if the file is hidden.
Behaviour wanted. When the nvim tree is opened, and the file is not visible in the nvim tree, the cursor should focus on the file's parent directory.

**Comment by kyazdani42** [comment]
I see now, this could be implemented in the find_file, i'll see when i have some time for this.

**Comment by alex-courtis** [comment]
This is a valid feature that improves the quality of life for users.

**Comment by alex-courtis** [comment]
This should be resolved via https://github.com/nvim-tree/nvim-tree.lua/issues/1785 and https://github.com/nvim-tree/nvim-tree.lua/pull/2261

Please reopen if this hasn't been resolved.
