### ISSUE TITLE
Floating window and preview

### ISSUE THREAD

**Issue by fragov** [nvim-tree/nvim-tree.lua#135]
Is there any chance to have nvim-tree in floating window with files preview in next versions?

**Comment by kyazdani42** [comment]
i don't think this is a goal i wish to acomplish, although it should be quite easy to do with the api i'll provide in the next version i'm working on.

**Comment by wkcosmology** [comment]
+1  Unlike the splitting window, the floating window won't mess the window layout.

**Comment by dennisfrostlander** [comment]
Hi @kyazdani42, did you by any chance already add the 

> i don't think this is a goal i wish to acomplish, although it should be quite easy to do with the api i'll provide in the next version i'm working on.

Hi @kyazdani42, did you by chance already add the api you've mentioned?

**Comment by kyazdani42** [comment]
hi, haven't really had the time to refactor this part yet :)

**Comment by fanliver** [comment]
Looking forward to this feature. I really miss this feature since switching from coc-explorer.

**Comment by stevenocchipinti** [comment]
Me too! `coc-explorer` is oddly the main thing keeping me from switching to neovim's native LSP 😅

**Comment by kyazdani42** [comment]
i guess i've rewritten the view handling enough so this can be tackled.
something like extending the `view.lua` file to handle a `popup` view basically :)

**Comment by tsakirist** [comment]
I would love that too, this is something that amazed me when I used coc-explorer and it's really helpful.
It would be great if you could add this :)

**Comment by fragov** [comment]
I tried to mess up with view.lua, but my LUA knowledge is almost zero. So I had to switch to lir. :(

**Comment by fragov** [comment]
Tried 3 another file-tree plugins and Telescope explorer and I'm back again. Too many bugs and issues. Last one had an interesting choice of hotkeys: d for creating a directory, and shift-d to delete a folder (and it even didn't ask if you really want to delete that folder). I deleted my work for full day today.

What a good way to learn how I can extend nvim-tree? Any suggestions?

**Comment by kyazdani42** [comment]
hi @fragov sorry for the late answer.
Well i believe the view should be refactored first before implementing this, i'm not sure it would be too easy to do in the current state of the plugin :)
This will land at some point

**Comment by alex-courtis** [comment]
@lu5je0 any chance you could put something together for this?

**Comment by alex-courtis** [comment]
Floating nvim-tree window has been implemented. `:help nvim-tree.view.float`.

It doesn't seem that floating preview has gained much interest. Please re-open / create a new PR if that's something you have a good use case for.

**Comment by lexuancuong** [comment]
I think `floating-window` is a good feature for `nvim-tree`.
If I have two panels simultaneously, a floating window makes it easier to view the file explorer.
Please keep supporting this feature.
Thank you so much.
<img width="1384" alt="image" src="https://github.com/nvim-tree/nvim-tree.lua/assets/57437020/8fbb13b9-3a1e-4d5f-8523-cbca294413e3">

**Comment by gegoune** [comment]
@lexuancuong it's implemented. See https://github.com/nvim-tree/nvim-tree.lua/issues/135#issuecomment-1288002079

**Comment by JMarkin** [comment]
I implemented float preview. Example (asciinema preview may broken, please open link)
[![asciicast](https://asciinema.org/a/590909.svg)](https://asciinema.org/a/590909)
Code available [floatpreview.lua](https://github.com/JMarkin/mynvim/blob/master/lua/custom/floatpreview.lua),[nvimtree attach](https://github.com/JMarkin/mynvim/blob/d733abb2ec72654211dafb089f237df9c2745758/lua/plugins/nvimtree.lua#L5).
Currently I don't know how to integrate with nvimtree code, but I try in future.

**Comment by alex-courtis** [comment]
> Code available [floatpreview.lua](https://github.com/JMarkin/mynvim/blob/master/lua/custom/floatpreview.lua),[nvimtree attach](https://github.com/JMarkin/mynvim/blob/d733abb2ec72654211dafb089f237df9c2745758/lua/plugins/nvimtree.lua#L5).

That's incredible! Can you please share this as a [Recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)?

> Currently I don't know how to integrate with nvimtree code, but I try in future.

That looks like it will fit nicely into open-file, minus the treesitter part ;)

Have a go, open a PR and we can help you.

**Comment by JMarkin** [comment]
Hello all, I created [PR](https://github.com/nvim-tree/nvim-tree.lua/pull/2290) and this plugin https://github.com/JMarkin/nvim-tree.lua-float-preview. May be to need only plugin and `Recipe` ? What do you think?

**Comment by tracyone** [comment]
Any official support ?

**Comment by alex-courtis** [comment]
Please acceptt my apologies @JMarkin, it was never added. It's present now: [Extension Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins)

Please do update the page with a better description.

**Comment by hopezh** [comment]
The nvim-tree-float-preview seems to be an amazing extension. 

However, I'm unable to follow the installation instruction to get it work. 

Hope @JMarkin can kindly elaborate on how it can be installed in the context of `lazy.nvim` and `lazyvim` with an example.

**Comment by JMarkin** [comment]
@hopezh I think [readme](https://github.com/JMarkin/nvim-tree.lua-float-preview/blob/master/README.md) has example for lazy.nvim, for lazyvim I don't know

**Comment by brandonpollack23** [comment]
Just tried it out to no effect. Not sure what's wrong but there's no preview at all. Perhaps I have some kind of conflict. I'll see what I can figure out

**Comment by brandonpollack23** [comment]
Got it, it works it's just my updatetime was set to default which is 4000, might want to mention for those who want to they should set updatetime to something like 100 in their on_attach function in the readme (4 seconds is a long time!) and resetting it on detach.

**Comment by alex-courtis** [comment]
> Got it, it works it's just my updatetime was set to default which is 4000, might want to mention for those who want to they should set updatetime to something like 100 in their on_attach function in the readme (4 seconds is a long time!) and resetting it on detach.
> 
> I actually can't quite get this working since I'm new to neovim and lua etc so I tried an autocommand for bufleave that is set to "once" but that executes right away in on_attach. Guidance here would be awesome because a 100ms swapdir write doesn't seem to be a great idea necessarily, but it probably won't matter.

What's the context here? Are you referring to nvim-tree-float-preview or nvim-tree itself?

If the former please raise an issue at [nvim-tree.lua-float-preview](https://github.com/JMarkin/nvim-tree.lua-float-preview)

**Comment by brandonpollack23** [comment]
The hover. I realized there was a gap in my knowledge and the value for
updatetime can easily just be low.

**Comment by alex-courtis** [comment]
> The hover. I realized there was a gap in my knowledge and the value for updatetime can easily just be low.

Which update time are you referring to? git is 400ms however I don't think that's it...

**Comment by matthewblott** [comment]
@alex-courtis it's the main Neovim `updatetime` value. I had the same issue, it was dog slow and I couldn't work out why. Then I set the `updatetime` value to `100` and the previewer suddenly worked like a charm. As mentioned above I should probably set it on attach but it's got me working for now :-)

**Comment by alex-courtis** [comment]
Today I Learned updatetime

**Comment by matthewblott** [comment]
@alex-courtis I learned about it yesterday 😂

**Comment by di3italis** [comment]
I modified the nvim-tree setup to float the window in the upper right, based on the @kryzar recipe:

https://github.com/nvim-tree/nvim-tree.lua/discussions/1765#discussioncomment-9087529

**Comment by b0o** [comment]
The nvim-tree.lua-float-preview plugin is really cool, but it didn't work exactly how I wanted, so I created my own little version. Here it is for anyone interested: https://gist.github.com/b0o/d45565c81dbc930a6e20513d05bfc69a

https://github.com/nvim-tree/nvim-tree.lua/assets/21299126/11300a88-4931-46a9-9f89-75b44739b949

**Comment by alex-courtis** [comment]
> The nvim-tree.lua-float-preview plugin is really cool, but it didn't work exactly how I wanted, so I created my own little version. Here it is for anyone interested: https://gist.github.com/b0o/d45565c81dbc930a6e20513d05bfc69a

Wow, that's really nice!

I'd be most grateful if you shared that on the [recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes) wiki page...

**Comment by b0o** [comment]
Done, I converted it to a [plugin](https://github.com/b0o/nvim-tree-preview.lua) and added it to [Extension-Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins).

**Comment by alex-courtis** [comment]
> Done, I converted it to a [plugin](https://github.com/b0o/nvim-tree-preview.lua) and added it to [wiki/Extension-Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins).

Wow! Many thanks!

**Comment by matthewblott** [comment]
@b0o This looks really cool and what I'm looking for. I'll give it a whirl later, well done :-)

**Comment by kryzar** [comment]
> Done, I converted it to a [plugin](https://github.com/b0o/nvim-tree-preview.lua) and added it to [wiki/Extension-Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins).

@alex-courtis and you doing the work of gods. Thanks a lot.

**Comment by evertonse** [comment]
> Done, I converted it to a [plugin](https://github.com/b0o/nvim-tree-preview.lua) and added it to [wiki/Extension-Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins).

That's hype ! Does it work with float tree view as well?

**Comment by TheNew1234** [comment]
> Done, I converted it to a [plugin](https://github.com/b0o/nvim-tree-preview.lua) and added it to [wiki/Extension-Plugins](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins).

Amazing!
