### ISSUE TITLE
lock the cursor on its current highlighted file when we toggle hidden/ignored files (pressing H or I)

### ISSUE THREAD

**Issue by sadtab** [nvim-tree/nvim-tree.lua#1380]
**Is your feature request related to a problem? Please describe.**
When we toggle hidden/ignored files by pressing H or I, the cursor stick to its current line rather than the current file

**Describe the solution you'd like**
It's a good idea that the cursor sticks to the file it's on rather than the line

**Describe alternatives you've considered**
NERDTree is a good example, when we press "I" to toggle the hidden files the cursor sticks to the currently highlighted file

**Comment by alex-courtis** [comment]
following in #1785
