### ISSUE TITLE
<TAB> Key mapping is case sensitive

### ISSUE THREAD

**Issue by sadtab** [nvim-tree/nvim-tree.lua#1401]
Great plugin with a very bright future to be gold standard default tree, 

**Is your feature request related to a problem? Please describe.**
\<TAB\> is treated different from \<Tab\>

**Describe the solution you'd like**
some <KEY> like <TAB> should be treated case-insensitive

**Comment by kyazdani42** [comment]
Thanks :)
I think this is an issue with the keybindings, a refactor is needed for this module anyway. I'll leave this open and might implement this when refactoring the keybindings module.

**Comment by alex-courtis** [comment]
See #877

**Comment by alex-courtis** [comment]
Larger bug #1676
