### ISSUE TITLE
[Followup] full migration to on_attach API mappings

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1475]
#1579

- [x] document default mappings
- [x] apply `remove_keymaps`
- [x] legacy migration #1464
- [x] help shows on_attach mappings
- [ ] update help
- [ ] write migration guide
- [ ] ensure `action=""` applied to migration

**Comment by kyazdani42** [comment]
legacy migration (under the hood, automated): https://github.com/kyazdani42/nvim-tree.lua/pull/1476

**Comment by alex-courtis** [comment]
Tracked a #1579
