### ISSUE TITLE
File created messages causes "press enter" problems with cmdheight=1

### ISSUE THREAD

**Issue by kubil6y** [nvim-tree/nvim-tree.lua#1506]
Creating, deleting files causes "press enter" errors because cmdheight is not big enough. I dont want to use cmdheight=2 because it is ugly and unnecessary.

```
- Event.FileCreated
                handler parameters:  
                  {fname}        `{string}` Absolute path to the created file
```

Instead of just absolute path i think it should be possible to use just the file/directory names. Because when you use cmdheight lower than 2, you need to press enter. Press enter makes cursor jump so you lose your flow.

**Comment by Shougo** [comment]
Related: https://github.com/kyazdani42/nvim-tree.lua/issues/1502

**Comment by alex-courtis** [comment]
I'm not seeing that behaviour with my setup nor an [nvt-min.lua](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) setup.

Please create an nvt-min.lua so that we may reproduce.

**Comment by gegoune** [comment]
Assuming it's no longer an issue. Please create new issue with minimal reproduction if it is.
