### ISSUE TITLE
Add nvim-tree.diagnostics.placement config option

### ISSUE THREAD

**Issue by serhez** [nvim-tree/nvim-tree.lua#1510]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be nice to have an option in the config such as `nvim-tree.diagnostics.placement`, which would act similarly to `nvim-tree.renderer.icons.git_placement`, with possible values `left` and `right`. This would allow the user to place diagnostic icons at the left/right end of the nvim-tree window; currently, this defaults to the left end of the window and cannot be changed (AFAIK).

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by alex-courtis** [comment]
Useful and consistent with git behaviour.

Default value `signcolumn` for current behaviour.

**Comment by alex-courtis** [comment]
Ensure we skip empty as per #1952

**Comment by alex-courtis** [comment]
Fixed at #2396
