### ISSUE TITLE
regex support for filters.exclude 

### ISSUE THREAD

**Issue by mcpeng** [nvim-tree/nvim-tree.lua#1511]
```lua
  filters = {
    dotfiles = true,
    custom = { "^node_modules$" },
    exclude = { ".gitignore$", "^\\.env" },
  },
  git = {
    enable = true,
    ignore = true,
    show_on_dirs = true,
    timeout = 400,
  },
```
I wanna show files like `.env` / `.env.prod` / `.env.xxxx` and hide files like `.pyenv`.
- `exclude ".gitignore$"` works correctly: hide file `.gitignore_global` & show file `.gitignore`
- I've tried exclude:
  - `".env"`: will show file `.zshenv`/`.pyenv` too
  - `"^\\.env"`: will hide file `.env` too

**Comment by alex-courtis** [comment]
`custom` regex PR #1112 

The impact of changing from a string to a regex was minimal, with only a few questions.

This can be done.
