### ISSUE TITLE
When new buffer opens from tree file list, it creates half-split ignoring width setting

### ISSUE THREAD

**Issue by flppv** [nvim-tree/nvim-tree.lua#1522]
### Description

When on the screen there is only a file tree, upon opening the file it opens a tab on the right half of the window, and nvim-tree takes a left half, even with width setting being set. Toggling nvim-tree twice (close-open) shrinks it to a width-value width.

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.4

### nvim-tree version

08ab346

### Minimal config

```lua
-
```

### Steps to reproduce

1) Open any directory with nvim
2) Select a file within nvim-tree sidebar
3) Hit Enter

### Expected behavior

Opened tab takes `full-width - nvim-tree-width` width, and nvim-tree takes `nvim-tree-width` width

### Actual behavior

Opened tab takes 50% width, and `nvim-tree` 50% width

**Comment by alex-courtis** [comment]
This sounds like a bug.

Please create a [minimal config](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) `nvt-min.lua` that we may use to replicate and (fix or provide a workaround for).

**Comment by 0styx0** [comment]
Lunarvim is extremely far from a minimal config. Open the link Alex gave you.

**Comment by pleshevskiy** [comment]
I think I'm facing the same problem

Steps to reproduce the issue:

1. Open directory as the following:
  ```sh
  nvim .
  ```
2. Then open any file (`Enter` or `o`).
3. ![image](https://user-images.githubusercontent.com/7839004/191226613-e1642602-46ba-4dd9-9d07-99e63902a3c3.png)

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/jnfqzl7lzqshbqfm9mkl27024nsbcgvz-neovim-unwrapped-0.7.2/share/nvim
"

Run :checkhealth for more info
```

[My neovim configuration](https://git.pleshevski.ru/mynix/neovim)

P.S. I tried neovim with a minimal configuration (only nvim-tree)

**Comment by pleshevskiy** [comment]
I found a workaround to use `<C-o>` to open the first file. But it would be great if `o` didn't push sidebar to the right.

**Comment by pleshevskiy** [comment]
https://github.com/kyazdani42/nvim-tree.lua/pull/1594 fixed my problem :)

**Comment by alex-courtis** [comment]
Thanks @pleshevskiy , merged.

@flppv please update nvim-tree.lua and see if it resolves the issue.

**Comment by alex-courtis** [comment]
> started using my own clean config

Fantastic! LunarVim does do a lot...
