### ISSUE TITLE
hijack netrw should include explore, vexplore,lex,vex

### ISSUE THREAD

**Issue by GNOMES** [nvim-tree/nvim-tree.lua#1527]
The hijack netrw options seems to only impact running "nvim ." (at least during my initial playing with plugin).

My expectation of "hijacking" netrw would be to replace it everywhere.

Is there a reason that running :Lex for example doesn't open Nvim-tree?

**Comment by alex-courtis** [comment]
> My expectation of "hijacking" netrw would be to replace it everywhere.

It should. See #1270 

Please try setting `g:loaded_netrw*` as per https://github.com/kyazdani42/nvim-tree.lua/issues/286#issuecomment-1208996663.

What is Lex? I'd like to attempt to reproduce.

**Comment by alex-courtis** [comment]
> :Lex forces a left sidebar of Netrw.
> 
> There is also :Vex for vertical.

nvim-tree hijacks netrw by intercepting `FileExplorer` events. `:Lex` bypasses netrw hijacking as it directly launches netrw without the event.

To completely disable netrw see `:help nvim-tree.disable_netrw`. You will lose `:Lex`.
