### ISSUE TITLE
Resize event not dispatched when resizing using mouse

### ISSUE THREAD

**Issue by Tcholly** [nvim-tree/nvim-tree.lua#1545]
In my init.vim script I subscribe to the resize event, if I use `:NvimTreeResize` the subscribed function gets called, but if I resize with the mouse it doesn't.

https://user-images.githubusercontent.com/35864488/186197406-3a3d54c5-176c-4295-90af-9bd987de25b6.mp4

From the above video you can see that if I use the command, the tabs above follow as well, but if I resize using the mouse they don't.
You can also see how I listen to the event.

**Comment by alex-courtis** [comment]
In the future please raise a bug report, not an empty issue.

We are firing resize events for all nvim-tree operations, including adaptive_size and friends.

Mouse and `<C-W><` do not fire events.

This fix should not cause any unwanted behavioural changes or break anyone.

**Comment by wlh320** [comment]
Hi! I noticed that recently neovim added a `WinResized` autocommand event in [neovim/neovim/issues/11532](https://github.com/neovim/neovim/issues/11532). This may be helpful for nvim-tree to firing Resize events for mouse and `<C-W>`.

**Comment by alex-courtis** [comment]
Fantastic! Thank you @wlh320
