### ISSUE TITLE
Duplicate or copy files (without clipboard operations)

### ISSUE THREAD

**Issue by mildred** [nvim-tree/nvim-tree.lua#1552]
**Is your feature request related to a problem? Please describe.**

Often, I want to create a new file that is similar to an existing file, and I'd like to copy the existing file to a new location in the same folder, just changing its name, to edit its content.

**Describe the solution you'd like**

A single command to doplicate or copy a file/directory. The command would prompt for a new file path (just like the rename command), but unlike the rename command, the file/directory would be copied to the new location instead of moved.

**Describe alternatives you've considered**

It's possible to copy the current file to the clipboard, then move up the containing directory, paste the file, and then answer the question to rename the file because there is already a file with the same name. This is cumbersome as it involves too much operations and a single shortcut would be more efficient.

**Additional context**

*none*

**Comment by alex-courtis** [comment]
I experience this use case a lot: `c p r` is a bit clunky but it does work.

A duplicate action would be useful. It should pre-populate the existing file name, to be consistent with other functionality like LSP rename.

**Comment by gegoune** [comment]
This should be closed by https://github.com/nvim-tree/nvim-tree.lua/issues/1605 when implemented. It seems that solution described in #1605 provides required flexibility and more. Closing this issue for now. Please feel free to reopen if you disagree with #1605 as solution.
