### ISSUE TITLE
Error detected while processing BufWipeout Autocommands for "NvimTree_*":

### ISSUE THREAD

**Issue by jeffschwartz** [nvim-tree/nvim-tree.lua#1588]
### Description

When opening nvim-tree the following occurs:

```
Error detected while processing BufWipeout Autocommands for "NvimTree_*":
Error executing lua callback: .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:318: attempt to index a nil value
stack traceback:
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:318: in function <.../share/nvim/plugged/nvim-tree.lua/lua/nvim
-tree/view.lua:315>
        [C]: at 0x01048c57b8
        [C]: in function 'pcall'
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:79: in function 'wipe_rogue_buffer'
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:85: in function 'create_buffer'
        .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:217: in function 'open'
        ...l/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:78: in function 'open_view_and_draw'
        ...l/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:105: in function 'open'
        ...local/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree.lua:95: in function 'open'
        ...local/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree.lua:79: in function 'toggle'
        ...local/share/nvim/plugged/nvim-tree.lua/lua/nvim-tree.lua:304: in function <...local/share/nvim/plugged/nvim-tree.lua/lua
/nvim-tree.lua:303>
```

### Neovim version

```text
NVIM v0.8.0-dev-2475-gc50460cf3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.5.1

### nvim-tree version

3e49d9b7484e21f0b24ebdf21b8b7af227ea97a6

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

Can't reproduce when running nvim -nu /tmp/nvt-min.lua.

### Expected behavior

Not to throw errors

### Actual behavior

Throws errors

**Comment by alex-courtis** [comment]
> Can't reproduce when running nvim -nu /tmp/nvt-min.lua.

We cannot resolve this issue without being able to reproduce.

Options for you to generate a reproducer:
1. Add you plugins and automations to nvt-min.lua until you can reproduce.
2. Remove plugins and automations from your configuration until the issue stops occurring. The last removal should indicate the source of the problem.

**Comment by jeffschwartz** [comment]
Hi @alex-courtis and thank you for your reply. Unfortunately I have over 40 plugins currently installed
```
cmp-buffer
cmp-path
markdown-preview.nvim
nvim-cmp
vim-ingo-library
plenary.nvim
refactoring.nvim
targets.vim
nightfox.nvim
nvim-tree.lua
neogen
cmp-git
nvim-treesitter
tokyonight.nvim
vim-SpellCheck
vim-repeat
nvim-web-devicons
vim-commentary
gruvbox
todo-comments.nvim
vim-gitgutter
vim-unimpaired
cmp-nvim-ultisnips
vimwiki
telescope.nvim
cmp-look
lspkind-nvim
indent-blankline.nvim
cosco.vim
ultisnips
vim-fugitive
emmet-ls
cmp-nvim-lsp
cmp-cmdline
lualine.nvim
vim-auto-save
calendar-vim
rust-tools.nvim
playground
nvim-lspconfig
vim-surround
vim-coloresque
auto-pairs
nvim-dap
```
and removing them one by one or adding them back one by one would be extremely time consuming and there is no guarantee that the effort would result in anything useful as the issue appears to be an optimistic bug.

As an open source developer and contributor I fully understand that everyone is under pressure and that it would always be nice if every issue could be framed by those reporting them by having them provide as much information as is possible. However I don't believe it is reasonable to dismiss an issue out of hand when such a request would amount to an unreasonable burden being placed on the reporter.

Regarding the stack trace that I provided, is it totally useless? Is there nothing to be gleaned from that?

**Comment by alex-courtis** [comment]
> Error detected while processing BufWipeout Autocommands for "NvimTree_*":
> Error executing lua callback: .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:318: attempt to index a nil value

The stack doesn't really help: it's just telling us that a window or buffer has disappeared from under us.

The problem is with running events: order is unpredictable, with many plugins triggering and acting on events. Some plugins will fire events as the result of another event. Some plugins disable events when handling an event, see `:help au`.

Without knowing what has happened to cause this issue, error handling that leaves nvim-tree in a consistent state cannot be devised.

> and removing them one by one or adding them back one by one would be extremely time consuming and there is no guarantee that the effort would result in anything useful as the issue appears to be an optimistic bug.

Removing plugins via Bisection would be a reasonable course of action.

**Comment by jeffschwartz** [comment]
Thank you @alex-courtis but I don't understand why nvim-tree isn't guarding against a nil value.

**Comment by alex-courtis** [comment]
> Thank you @alex-courtis but I don't understand why nvim-tree isn't guarding against a nil value.

The problem is how to handle the error. Is the tab visible and alive? Is the tree's window alive and visible? Is the tree's buffer alive?

Concerning case: resource leak of the tree's nodes, which is problematic as the file system / git watchers would still be alive.

If you could make an attempt to handle the error, in a way that results in a consistent tree state, we could raise a PR.

**Comment by jeffschwartz** [comment]
@alex-courtis thank you for your reply.

 My time right now is very limited due to a prior project commitment and I am sure you have heard that a zillion times already. Also I am not a Lua developer. I know just enough LuA to maintain my Neovim configuration. However, with that said, I will fork the project and snoop around a bit. I love finding bugs. That puts me at odds with a lot of developers who hate that aspect of what we do. Not promising anything though because again, I have so little free time at the moment. Are there facilities built into Neovim that would provide debugging capabilities, such as the ability to set breakpoints and view the runtime environment?

**Comment by alex-courtis** [comment]
> Are there facilities built into Neovim that would provide debugging capabilities, such as the ability to set breakpoints and view the runtime environment?

There are no such capabilites. Logging is all we have. See `:help nvim-tree.log`. Use the "dev" type.

To trace events, I use this little framework: [log.vim](https://github.com/alex-courtis/arch/blob/b32fd5ff53bdcbef88e77a6f5f4e561c18808c79/config/nvim/autoload/amc/log.vim)
[Start it in your init.vim](https://github.com/alex-courtis/arch/blob/180803140c1e329d333d9171cd28970df4722ccf/config/nvim/init.vim#L176)

**Comment by alex-courtis** [comment]
Suggestion: spend your time putting together a reproducer instead of fixing it yourself.

Worst case estimates:
* bisected commenting out / testing of 40 plugins: 5 bisections at 3 mins each
* progressive removal of your vim automation / configuration: 4 comment out at 3 mins each
* document and post the reproducer: 20 mins

It will be faster for me to fix the issue (once I have a reproducer) than for you to learn lua, nvim-tree and vim events.

In the time taken for you to write your comments on this issue you could have bisected and reproduced ;)

**Comment by jeffschwartz** [comment]
Wasn't there a horror movie about a person who bisected and then reproduced? Maybe I am confusing that with something else :)
