### ISSUE TITLE
show full root folder

### ISSUE THREAD

**Issue by AlexvZyl** [nvim-tree/nvim-tree.lua#1596]
**Is your feature request related to a problem? Please describe.**

Whenever the root folder is relatively short there is no problem with how it is currently being displayed.

![image](https://user-images.githubusercontent.com/81622310/191359254-fc6fa7d7-5e6b-44fc-b493-ddcf45cee4f0.png)

However, when it gets longer it is difficult to properly tell where you are.

![image](https://user-images.githubusercontent.com/81622310/191359293-97225780-48ae-4b62-8e4e-2e292f677797.png)

It would require the file explorer to be too large to see all of it.

![image](https://user-images.githubusercontent.com/81622310/191359367-0e88863b-f6a0-4dbd-beaf-521bcae008bb.png)

**Describe the solution you'd like**

Instead of aligning the root folder to the left of the window and have the right side truncated (or hidden by the window being too narrow), would it be possible to align it to the right and be truncated on the left side?  I am unsure how difficult it would be to implement this, I am guessing it would require the position of the root folder to be quite dynamic.

**Describe alternatives you've considered**

An easy workaround for would be to use the statusline to display the root folder, but this would not always display if you are using Neovim's global status line, like I am.  It only shows when I am actually inside the explorer (though, this is not that bad).

![image](https://user-images.githubusercontent.com/81622310/191360056-810660cd-fc94-4edb-a897-6eedcc49141c.png)

**Comment by alex-courtis** [comment]
Related: #1544

**Comment by alex-courtis** [comment]
Definite:
* long root name not shown on hover #1544 

Maybe (disruptive):
* window size to fit root #1544

Some or all of:
* right align root
* status line (not really used right now)

**Comment by gegoune** [comment]
Configurable by using function for `renderer.root_folder_label` after #1746.
