### ISSUE TITLE
Bug: nvim-tree does not respects the call functions when opening nvim `nvim .`

### ISSUE THREAD

**Issue by TheSafdarAwan** [nvim-tree/nvim-tree.lua#1602]
### Description

maybe this is not big issue for some one but i like to have **ColorColumn** enabled when i am writing code so that when i exceed 81 characters of code in one line it will show me a boundry but somehow nvim-trre does not respects that.

This is my config for the `colorcolumn`.
```lua
vim.cmd([[
    call matchadd('ColorColumn', '\%80v') 
    " this will use the Color defined in you theme for the ColorColumn
]])
```
this will only work when a line exceeds 81 characters of code on one line you can use the `set colorcolumn` if you want but the problem remains even after setting the normal option of `set colorcolumn`.

> NOTE: This is only issue with the **nvim-tree** when i open it using the `nvim .`.

### Neovim version

```text
NVIM v0.8.0-dev-1112-g6d557e324
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

5.17.15-1-MANJARO x86_64 GNU/Linux

### nvim-tree version

52b0c32

### Minimal config

```lua
require("nvim-tree").setup({
	auto_reload_on_write = true,
)}
```

### Steps to reproduce

1. Go to any code directory
2. start nvim using `nvim .` to start it in the current directory so that nvim-tree starts up.

### Expected behavior

Do not change the colorcolumn behavior

### Actual behavior

Nop

**Comment by alex-courtis** [comment]
FYI `auto_reload_on_write = true` is not normally required; nvim-tree watches the file system and refreshes its state automatically. That option should be removed at some poin, unless there is a workflow that we are unaware of.

**Comment by TheSafdarAwan** [comment]
> `auto_reload_on_write`

but what about the real question i asked

**Comment by alex-courtis** [comment]
I do not appear to understand the issue.

Attempted replication with 
[nvt-min.lua.txt](https://github.com/kyazdani42/nvim-tree.lua/files/9639907/nvt-min.lua.txt)

[![asciicast](https://asciinema.org/a/523573.svg)](https://asciinema.org/a/523573)

Please attempt to replicate using the above minimal config.

**Comment by TheSafdarAwan** [comment]
sir i said that you have to use `nvim .` do not open file immediately just let the nvim-tree hijack and by the way netrw should be disabled or maybe not at this point i am not on my computer so can't tell but you have to have the nvim-tree as a default file explorer when you open the nvim using a directory as an argument rather than a file. then if you had enabled colorcolumn it wont work.

**Comment by alex-courtis** [comment]
> sir i said that you have to use nvim .

Please watch the screencast carefully. The `.` is the last argument.

> just let the nvim-tree hijack and by the way netrw should be disabled

That was not present in your minimal configuration.

**Comment by alex-courtis** [comment]
We are making no progress:
* I do not understand the issue
* I cannot replicate the issue
* I do not know your configuration

Please provide:
* An `nvt-min.lua` as instructed in the [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) that I may use to replicate the issue
* Exact steps to replicate the issue.
* Current behaviour
* Desired behaviour

A [screencast](https://asciinema.org/) to accompany the above is useful.

This issue will be addressed again only after the above.

**Comment by Souhail-JAMHOUR** [comment]
Hey @alex-courtis i think i have the same issue, for me the ``` nvim foodirectory   
is not working
