### ISSUE TITLE
File opens on the same nvim-tree window when quit_on_open = true

### ISSUE THREAD

**Issue by Almo7aya** [nvim-tree/nvim-tree.lua#1628]
### Description

When opening a file using Telescope or :e [filename] while focusing on the nvim-tree window, the file opens the same window as nvim-tree

https://user-images.githubusercontent.com/17254073/194481452-6e013b10-c9b9-461d-872f-25c06bc40928.mp4

### Neovim version

```text
NVIM v0.9.0-dev-1214-ge54541f7f-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS 12.6

### nvim-tree version

main - 7282f7d

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    actions = {
      open_file = {
      quit_on_open = true
    }
  }
}
end
```

### Steps to reproduce

1- nvim -nu /tmp/nvt-min.lua
2- e ./nvt-min.lua
3- :NvimTreeOpen
4- e ./nvt-min.lua

**Comment by Almo7aya** [comment]
It seems that this bug is caused by this line https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree.lua#L382
after changing both cases to 
```lua
create_nvim_tree_autocmd("BufWipeout", { pattern = "NvimTree_*", callback = view._prevent_buffer_override })
```
it started working as expected

**Comment by alex-courtis** [comment]
Replicated. Does not appear to be a race condition.

Please:
* raise a PR
* test fix with
  * multiple tabs / trees
  * `open_on_tab`
  * `view.float` enabled

**Comment by Almo7aya** [comment]
@alex-courtis sure will test with these cases and open a PR

**Comment by Almo7aya** [comment]
I did my tests 
with multiple tabs it's working fine

when `open_on_tab = true` and `open_on_tab = true` and forcing on nvim-tree's window calling `:bnext` closes the window and jumps to the next buffer not sure if this is the expected behavior, I think both options are conflicting with each other

when `view.float` is enabled calling `:e [filename]` while focus is on nvim-tree's window with `open_on_tab = true` and `open_on_tab = true` opens the file in a new vsplit

the config i'm using with my fork on it
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"almo7aya/nvim-tree.lua",
			"kyazdani42/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		view = {
			float = {
				enable = true,
			},
		},
		open_on_tab = true,
		actions = {
			open_file = {
				quit_on_open = true,
			},
		},
	})
end

vim.api.nvim_set_keymap("n", "<Space>e", "<cmd>:NvimTreeToggle<CR>", {})
```

**Comment by kyazdani42** [comment]
@alex-courtis could this be caused by https://github.com/nvim-tree/nvim-tree.lua/pull/1618?

**Comment by alex-courtis** [comment]
> @alex-courtis could this be caused by #1618?

Unfortunately no; occurs at 7282f7d

Digging deeper: `_prevent_buffer_override` calls open-file which obeys `quit_on_open` and closes the window.

PR please.
