### ISSUE TITLE
`nvim NvimTree.lua` does not open

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-tree/nvim-tree.lua#1629]
### Description

I have some custom mappings stored in `nvim/after/ftplugin/NvimTree.lua` to run on filetype NvimTree. Opening this file via `nvim after/ftplugin/NvimTree.lua` actually opens NvimTree on that file and not the file itself.

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

arch

### nvim-tree version

7282f7d -n 1

### Minimal config

```lua
no config needed
```

### Steps to reproduce

1. NvimTreeOpen after/ftplugin/NvimTree.lua

### Expected behavior

nvim-tree actually opens the file NvimTree.lua

### Actual behavior

the plugin NvimTree itself opens, not the file

**Comment by alex-courtis** [comment]
This is working as intended. `:NvimTreeOpen` takes a path as the optional argument.

**Comment by barrett-ruth** [comment]
Actually, my "Steps to reproduce" had an error
What I meant to say was running

`nvim after/ftplugin/NvimTree.lua` 

opens NvimTree (and NOT the file), which seems to make no sense (the "NvimTreeOpen"  call in the issue was a typo)

I think this is still an issue so reopen it if you agree with the above correction.

**Comment by alex-courtis** [comment]
It is likely to do with runtime paths; there is already an `NvimTree.lua` present.

Rename it and you should be fine.

**Comment by barrett-ruth** [comment]
Then accessing NvimTree.lua file is impossible. Should I just change the contents into an autocmd?

**Comment by alex-courtis** [comment]
Apologies, I was incorrect... there is no other `NvimTree.lua`. I do not know what is going on.

Same thing occurs when opening `~/NvimTree.lua`

Changing to an autocmd should work if it's possible.

**Comment by kyazdani42** [comment]
caused by https://github.com/nvim-tree/nvim-tree.lua/pull/1618.

**Comment by alex-courtis** [comment]
@barrett-ruth please test fix branch:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1629-cannot-start-with-buffer-named-NvimTree
```

When you're done, checkout master or nightly.

**Comment by barrett-ruth** [comment]
Works perfectly. thanks!

**Comment by alex-courtis** [comment]
Unfortunately this change has been reverted due to many regressions: #1668

A new mechanism to control startup behaviour is under way: #1669
