### ISSUE TITLE
Close `nvim-tree` when not focused

### ISSUE THREAD

**Issue by jayp0521** [nvim-tree/nvim-tree.lua#1635]
**Is this a question?**
Please start a new [Q&A discussion](https://github.com/nvim-tree/nvim-tree.lua/discussions/new) instead of raising a feature request.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When the tree is not focused (aka when cursor is not in the tree), I wish the tree would close itself.

**Describe alternatives you've considered**
Have not

**Additional context**
N/A

**Comment by alex-courtis** [comment]
That functionality currently exists when using a floating window `:help nvim-tree.view.float.quit_on_focus_loss`.

It could be added when not floating.

**Comment by kyazdani42** [comment]
@alex-courtis i don't think this is what is asked here. 
But i think this should not be a feature in nvim-tree, it's too weird to implement, but can be easily implemented in your configuration (it's basically 2 lignes of code).
