### ISSUE TITLE
Rewrite Feature Request Template

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1654]
Nvim-tree is entering a stable state: #1652

The feature request template needs to be rewritten to reflect that.

**Comment by alex-courtis** [comment]
see #1655

**Comment by gegoune** [comment]
What changes did you have in mind for this one, Alex?

**Comment by alex-courtis** [comment]
I'm... really not sure. [Roadmap](https://github.com/nvim-tree/nvim-tree.lua#roadmap) is published but can always be changed.

I'd like feature requests to be realistic and achievable, not huge additions that we won't implement.

Preamble could be similar to bug, which seems to have been effective:

> Is this a question?
> * Please start a new [Q&A discussion](https://github.com/nvim-tree/nvim-tree.lua/discussions/new) instead of raising an issue.
> 
> Before reporting:
> * search [existing issues](https://github.com/nvim-tree/nvim-tree.lua/issues) for similar feature requests

We could do that now, if you're happy with that.

**Comment by alex-courtis** [comment]
Perhaps some sort of split between API and UX feature requests.
