### ISSUE TITLE
nvim-tree opening when editing non existant file with open_on_setup_file = false

### ISSUE THREAD

**Issue by LordMZTE** [nvim-tree/nvim-tree.lua#1663]
### Description

When starting nvim with the config below editing an empty/new file (`nvim empty-file.txt`), nvim tree will open despite the config saying it shouldn't.

### Neovim version

```text
NVIM v0.8.0-dev-1121-g10196f1b46
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.1-arch2-1

### nvim-tree version

c995ce0

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    open_on_setup = true,
    open_on_setup_file = false,
  }
end
```

### Steps to reproduce

1. `nvim some-empty-or-nonexistant-file`
2. tree opens

### Expected behavior

The tree stays close an the file is opened

### Actual behavior

The tree opens despite a file being edited

**Comment by LordMZTE** [comment]
This happens because nvim-tree checks for an empty buffer, and opens if it is empty before checking if the buffer is for a file.

**Comment by alex-courtis** [comment]
This is working as intended for empty buffers as documented `:help nvim-tree.open_on_setup`

This is not ideal and unfortunately there is currently no way to achieve this functionality.

I think an overhaul of the startup behaviour is needed so that we can explicitly specify all the combinations for open on setup behaviour. https://github.com/nvim-tree/nvim-tree.lua/issues/1664#issuecomment-1280108423

**Comment by LordMZTE** [comment]
Thanks for the explanation!

I would very much appreciate an overhaul of the configuration to allow for this!

**Comment by kyazdani42** [comment]
@alex-courtis looks like a bug to me, the tree should not open on a file if open_on_setup_file is disabled. I've noticed this since a week or two.

**Comment by kyazdani42** [comment]
The setup is very messy but this bug is quite disturbing i believe, maybe we should just revert to the old behavior until we properly refactor the setup ?

**Comment by alex-courtis** [comment]
Agreed.

#1668

**Comment by alex-courtis** [comment]
Tracked via #1669
