### ISSUE TITLE
chore: Startup Notifications

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1667]
It is necessary to communicate changes to the users.

A startup message is used in the case of legacy g: and other assorted. This is a standard vim (base and plugins) convention as it is the only means of such communication.

Users get upset with startup messages however they might just have to accept them.

Next use cases:
* file system watchers always enabled
* mapping -> on_attach

A mechanism to suppress may be created:
* Suppress all messages (user actually suggested this one). My opinion is that this is a bad idea that invites issues.
* Display the message once ever, using some sort of persistence mechanism.

Alternatively the users can just learn to live with it.

**Comment by gegoune** [comment]
If messages are detailed and clear enough we should enforce them. This is to cover our, well. (:)) We are preventing broken configurations which can result in undesirable behaviour (user changing non-existing setting hoping it will take effect) which leads to issues being created. Given stable status of the plugin there shouldn't be many more breaking changes requiring configuration change.
We could also start semversioning releases which will allow breaking changes without any regards to users (as harsh as it sounds I just couldn't find better phrasing) as we would bump major version indicating just that.

**Comment by alex-courtis** [comment]
> If messages are detailed and clear enough we should enforce them.

An experiment is is place with `focus_empty_on_setup` https://github.com/nvim-tree/nvim-tree.lua/commit/3a2f68b9d53fdf360beba222022868c527ae4d8a#diff-03ac6f248c5e9a780c36d8fd8b546a63c41123420f5abed16691b74392b889c0R300

Let's see how it goes.

> We could also start semversioning releases

Yes. At the moment we can only make minor or patch changes

**Comment by alex-courtis** [comment]
We can avoid some questions from lunarvim users by submitting a PR for the config changes before / at release.

They pin to a specific revision: https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/snapshots/default.json#L74

**Comment by gegoune** [comment]
It's unfeasible to notify all distributions. Interested parties should follow Breaking Changes (shall we create one?) issue or monitor commits with breaking changes markers in them. We should not worry about someone distributing broken configuration to their users - even to the point that we should close such issues with templated response stating that the issue is in the distribution they are using. We do require minimal configuration already - no distributions are included in minimal configuration and that in itself is a pretty good hint to where the problem lies.

**Comment by alex-courtis** [comment]
> Interested parties should follow Breaking Changes (shall we create one?) issue or monitor commits with breaking changes markers in them.

I like both of these options. Commit message is simple and reliable.

We could use BREAKING or DEPRECATED along with a link to an issue or wiki page if necessary.

> We should not worry about someone distributing broken configuration to their users - even to the point that we should close such issues with templated response stating that the issue is in the distribution they are using.

Perhaps add a question to the bug report: are you using a distribution such as LunarVIM? We can come up with a template if the situation arises.

**Comment by alex-courtis** [comment]
I reckon we're OK - deprecations, on_startup and on_attach worked nicely.
