### ISSUE TITLE
Disabling window picker causes splits to garble the layout

### ISSUE THREAD

**Issue by naquad** [nvim-tree/nvim-tree.lua#1671]
### Description

When disabling the window_picker NvimTree's open-in-a-split functionality opens new NvimTree windows and tries to create a split there.

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 5.19.12-zen1-1-zen

### nvim-tree version

2b970635d1ef531355a380258372411576ecad4d

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]

-- these give 100% reproducibility
-- I've been encountering the issue w/o these settings,
-- although sometimes it was working
vim.o.splitbelow = true
vim.o.splitright = true

-- optional
vim.o.background = 'dark'
vim.cmd [[ color slate ]]

local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    actions = {
      open_file = {
        window_picker = {
          enable = false
        }
      }
    }
  }
end
```

### Steps to reproduce

1. Open NeoVIM in the directory containing at least 4 files
2. NvimTreeOpen
3. Request NvimTree to open file1 (`<CR>`)
4. Switch back to NvimTree
5. Open file2 in the split (`<C-x>`)
6. Switch back to NvimTree
7. Open file3 in the split
8. Switch back to NvimTree
9. Open file4 in the split
10. Close all windows except any file and NvimTree
11. Switch back to NvimTree
12. Open some other file in a split

Screen recording: [![asciicast](https://asciinema.org/a/QC0g1u29HDtdALz5FcqJWYnrU.svg)](https://asciinema.org/a/QC0g1u29HDtdALz5FcqJWYnrU)

### Expected behavior

Expecting NvimTree to open the requested file as a split of another window.

### Actual behavior

NvimTree creates the second own window and splits it.

**Comment by r7vme** [comment]
affects me too, I'm on this commit 4e24505e2b30c4a8c35a3dfb4f564f14f6d9bfd4

```
NVIM v0.8.0-1210-gd367ed9b2
```

@naquad thanks for creating an issue

**Comment by alex-courtis** [comment]
Reliably reproduced:

`:NvimTreeOpen`
navigate to 1
`<CR>`
`<C-w>w`
navigate to 2
`<C-x>`
`:q`
`<C-w>w`
navigate to 3
`<C-x>`

**Comment by alex-courtis** [comment]
Possibly related #1675

**Comment by alex-courtis** [comment]
Reverting to 23a564f before #1626 results in the broken v/h split behaviour, however an extra tree is not opened.

**Comment by alex-courtis** [comment]
c4ac723 achieved an incorrect split as a side effect.

`edit` was called instead of a `split` https://github.com/nvim-tree/nvim-tree.lua/blob/e94f5177983c033aad340b5351bf65ef1fa9737a/lua/nvim-tree/actions/node/open-file.lua#L215

**Comment by alex-courtis** [comment]
@naquad @r7vme  I will be very grateful if you test this fix:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1671-split-fail-no-window-picker
```

When you're done, checkout master or nightly.

**Comment by naquad** [comment]
The fix is working as expected :) I've tried my case, right side, custom keys, and various combinations of splits and closed windows.

Screencast with the working version: [![asciicast](https://asciinema.org/a/kjr6wc09WbZqmqsLBLcex2sHv.svg)](https://asciinema.org/a/kjr6wc09WbZqmqsLBLcex2sHv)

**Comment by r7vme** [comment]
@alex-courtis https://github.com/nvim-tree/nvim-tree.lua/pull/1677 fixes issue for me. Thanks :pray:

**Comment by alex-courtis** [comment]
That's fantastic, thank you both!

I'll let this soak with you for a few days then merge.

**Comment by alex-courtis** [comment]
Soaked OK, merged.
