### ISSUE TITLE
[Bookmarks] save and toggle list

### ISSUE THREAD

**Issue by jinleileiking** [nvim-tree/nvim-tree.lua#1673]
1. Save bookmarks -- when nvim exits, the bookmarks are gone
2. A shortcut cmd to toggle bookmarks list in nvim-tree window like nerdtree

**Comment by alex-courtis** [comment]
I might split this feature request in two.

1 is clear

2 What does the toggle do? Does it hide all nodes of the tree that are not marked?

**Comment by pr4th4m** [comment]
Not sure how this is possible - can we display bookmarked files/directories as favourites in top section of nvim tree ?
ex
```
example/..
- - bookmarks/favourites
  - go.mod
  - README.md
------------------------
+ - .git
+ - appengine-hello
+ - gotypes
+ - hello
+ - outyet
+ - stringutil
+ - template
  - go.mod
  - go.sum
  - LICENSE
  - README.md
  - ◯ tmp
```

**Comment by alex-courtis** [comment]
> Not sure how this is possible - can we display bookmarked files/directories as favourites in top section of nvim tree ?

I'm not sure that's a direction we want to take nvim-tree, which is simply a file browser. There are no plans for any sort of alternate views.

Perhaps we could instead go in a direction like #1692 with a different window / plugin.

**Comment by kagbodji** [comment]
I like your idea of using a separate view for things like buffers / bookmarks. Perhaps nvim-tree could expose bookmarked files via some API, and another plugin can render those?

**Comment by alex-courtis** [comment]
> I like your idea of using a separate view for things like buffers / bookmarks. Perhaps nvim-tree could expose bookmarked files via some API, and another plugin can render those?

See `:help nvim-tree.api.marks` for get API.

**Comment by jinleileiking** [comment]
> I might split this feature request in two.
> 
> 1 is clear
> 
> 2 What does the toggle do? Does it hide all nodes of the tree that are not marked?

2. Just like this:

default:

```
Mark1
Mark2
Mark3

-----

Mark1
     + dir 1
     + dir 2

```

When hit  `m`


```

Mark1
     + dir 1
     + dir 2


```

m: show or hide bookmark list.

**Comment by alex-courtis** [comment]
> 2. Just like this

> Just like this:
> default:
>
> Mark1
> Mark2
> Mark3

That would work if we went with a separate window solution: #1692

In the meantime, we could implement a live toggle filter like:
`M : toggle_bookmarked`
Would that suit your use case?

**Comment by jinleileiking** [comment]
Yes! Waited it done.

**Comment by alex-courtis** [comment]
We have successfully added toggle filters `filters.git_clean`, `filters.no_buffer` for #1692 and similar.

Splitting feature.

**Comment by alex-courtis** [comment]
#1850 #1851
