### ISSUE TITLE
[Feature Request] Different highlight group for opened and unopened folder icons

### ISSUE THREAD

**Issue by KritPaoIn** [nvim-tree/nvim-tree.lua#1674]
What I have right now:
<img width="171" alt="Screen Shot 2022-10-21 at 10 44 08 PM" src="https://user-images.githubusercontent.com/92923965/197235866-396b267f-1f54-4f7c-998d-3c1cc5249ae1.png">

What I would like to get:
<img width="132" alt="Screen Shot 2022-10-21 at 10 42 52 PM" src="https://user-images.githubusercontent.com/92923965/197235594-087b0042-b100-4a44-a3c3-38cdd43c4f64.png">

**Comment by alex-courtis** [comment]
`NvimTreeOpenedFolderName` currently changes the opened folder text. `NvimTreeFolderIcon` applies to both open and closed icons.

Add `NvimTreeFolderIconOpen`, defaulting to `NvimTreeFolderIcon`.
