### ISSUE TITLE
Disable Mappings Case Sensitively

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1676]
**Is your feature request related to a problem? Please describe.**
#1647 shows that disabling a mapping is case sensitive.

**Describe the solution you'd like**
Case insensitive disabling via `mappings.list.n.key` and `remove_keymaps`.

**Comment by alex-courtis** [comment]
Affected: 
* `mappings.list` with empty `action`
* `remove_keymaps`

**Comment by kristijanhusak** [comment]
@alex-courtis I think it would be good to mention in some changelog or somewhere that case-sensitive mappings are no longer working. I had these before that worked perflectly:

```lua
        list = {
          { key = { 's' }, action = 'vsplit' },
          { key = { 'C' }, action = 'cd' },
          { key = { 'X' }, action = 'system_open' },
        },
```

But since the update lowercase mappings stopped working (copy and cut). Fix is to use the shift modifier in the mapping:

```
          { key = { 's' }, action = 'vsplit' },
          { key = { '<s-c>' }, action = 'cd' },
          { key = { '<s-x>' }, action = 'system_open' },
```

**Comment by pleshevskiy** [comment]
maybe a better solution would be to do lowercase what is wrapped in `<>`?

**Comment by kristijanhusak** [comment]
> maybe a better solution would be to do lowercase what is wrapped in `<>`?

That would be better, but requires checking if it's `<>`. 
Ideal solution is to directly map things how they are defined, and handle removing mappings in a different way.

**Comment by pleshevskiy** [comment]
I would prefer the following
```
vsplit = { 's' },
cd = { 'C' },
system_open = { 'X' }
```

I think it is convenient and intuitive for the end user and easy to implement

**Comment by alex-courtis** [comment]
Apologies, reverted.

The real problem are the `<something>` e.g. `<tab>`.

Perhaps just define defaults in lower case and note that lower case overrides are necessary.

**Comment by alex-courtis** [comment]
> I think it is convenient and intuitive for the end user and easy to implement

A change to mappings is incoming, see `:help nvim-tree.on_attach`. This will result in simpler unmappings and much more direct mappings. See #1475 #1579

**Comment by alex-courtis** [comment]
Updated documentation to clarify that an exact case match of key is required.

Any forms of case insensitive matching will be too fragile e.g. `<s-O>`.

Once again, please accept my apologies for introducing this breaking change.
