### ISSUE TITLE
Show node names longer than window width

### ISSUE THREAD

**Issue by przepompownia** [nvim-tree/nvim-tree.lua#1679]
**Is this a question?**
No

**Is your feature request related to a problem? Please describe.**
Node names are shown truncated if they exceed window.

**Describe the solution you'd like**
Add an autocommand that displays the full name of node under cursor. 
Looking at the solution for `fern.vim` I wrote a module in lua: https://github.com/przepompownia/vim-arctgx/blob/master/lua/arctgx/lineHover.lua It can be simply used without any modifications in nvim-tree:
```vim
lua vim.api.nvim_create_autocmd({'FileType'}, {pattern = 'NvimTree', callback = require('arctgx.lineHover').enableForWindow})
```
but IMHO this or similar function could be a basic option in nvim-tree. 

**Describe alternatives you've considered**
See also the example from [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/render/line_hover.lua) where the author of the plugin added copying extmarks from the original line. 

**Additional context**
On the below images the hover window shows only raw text so highlights are lost:
![image](https://user-images.githubusercontent.com/11404453/197401679-6a28c536-f883-4c97-9632-ae45db2791a6.png)
![image](https://user-images.githubusercontent.com/11404453/197401686-12bb784c-fcc3-4794-a094-23c9b2044122.png)

Edit: I see that `file-popup.lua` does similar job but for file details, not the full name.

**Comment by ssiyad** [comment]
Couldn't you just use `view = { adaptive_size = true }`?

**Comment by przepompownia** [comment]
> Couldn't you just use `view = { adaptive_size = true }`?

It can be usable for me in some cases, especially with closing NvimTree window right after opening some buffer from a node, but I don't like consuming too much space by the window if it stays open.

**Comment by jorgsk** [comment]
I just came here to make this feature request! I also sometimes have limited screen real estate and it would be great to view full file names.

**Comment by alex-courtis** [comment]
Does `:help nvim-tree.renderer.full_name` provide the functionality you desire?

**Comment by przepompownia** [comment]
It's exactly that! Thanks @alex-courtis

**Comment by pleshevskiy** [comment]
@alex-courtis
It doesn't work if only one character goes outside the width of the tree. 
![image](https://user-images.githubusercontent.com/7839004/197862671-8eb31601-07c2-4f49-ac53-6c3137845ca5.png)

but in other cases it works great!
![image](https://user-images.githubusercontent.com/7839004/197862804-d6ed4bf9-148e-4dd2-9e0a-8fb601dd5e67.png)
