### ISSUE TITLE
tabnew should focus existing tab if file already opened

### ISSUE THREAD

**Issue by thanhtran-ct** [nvim-tree/nvim-tree.lua#1687]
Currently, every time I execute `tabnew` on a file node, nvim will open a new tab regardless that file is already opened in another tab. I think it's likely a mistake that user open a file which is already opened and NVimTree should gracefully switch to the tab opening that file.

To avoid disruptive behavior, I think it can be done like [NERDTree](https://github.com/preservim/nerdtree) in which an additional [option like `'reuse': 'all'`](https://github.com/preservim/nerdtree/blob/master/doc/NERDTree.txt#L1296) can be supplemented to the `mappings` config.

With this additional option, users not only apply for `tabnew` but can choose to apply for `open` action as well.

**Comment by alex-courtis** [comment]
See #2255
