### ISSUE TITLE
Support for other `vim.notify` wrappers

### ISSUE THREAD

**Issue by gegoune** [nvim-tree/nvim-tree.lua#1697]
**Is your feature request related to a problem? Please describe.**
Currently only `nvim-notify` is supported. There are other plugins providing similar functionality, namely [vigoux/notifier.nvim](https://github.com/vigoux/notifier.nvim), [folke/noice.nvim](https://github.com/folke/noice.nvim) or [j-hui/fidget.nvim](https://github.com/j-hui/fidget.nvim).

`nvim-tree` only checks for existence of `nvim-notify` and if it's not installed all messages send via `vim.notify` will have  `[NvimTree]` prefix added (even if user has other plugin installed).

**Describe the solution you'd like**
Check if other notify plugins are installed, or if that is not feasible skip adding prefix and rely on `{title='NvimTree'}.

**Describe alternatives you've considered**
Perhaps some better mechanism exists.

**Comment by alex-courtis** [comment]
Perhaps a notify callback could be configured by the user. Something like:

```lua
function my_notify(msg, level, title)
```

**Comment by alex-courtis** [comment]
We can also add a `notify_once` callback, as we do have a couple of `vim.notify_once` added via #1693

**Comment by ghostbuster91** [comment]
I would like to add another perspective to that feature request. Some people might have `nvim-notify` on their runtime path, but it doesn't necessarily mean that messages should be routed there. For example noice can be used as a message router that routes messages to different notifiers, `nvim-notify` among them. 

In my case I have `nvim-notify` on my runtime path that is not easily remove-able (let's not go into the details :sweat_smile:), but I don't actually want to use it for any kind of notifications. 

Having said that, a callback like `my_notify` would solve the problem.

**Comment by alex-courtis** [comment]
> If no one is working on that at the moment I can give it a try in the upcoming days.

That would be fantastic! More configurable notifications and inputs would greatly improve UX.
