### ISSUE TITLE
Invalid window ID on colorscheme change

### ISSUE THREAD

**Issue by Davincible** [nvim-tree/nvim-tree.lua#1712]
### Description

I call `colorscheme` every x minutes, which now for some reason results in the error below. Used to work fine below.

I manually call `colorscheme xx` I also get it.

```console
Error detected while processing ColorScheme Autocommands for "*":
Error executing lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:442: Invalid window id: 1002
stack traceback:
        [C]: in function '__newindex'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:442: in function 'reset_winhl'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:195: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:193>
```

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

 6.0.2-2-MANJARO

### nvim-tree version

master

### Minimal config

```lua
not sure
```

### Steps to reproduce

1. Open nvim
2. Toggle tree to open
3. Toggle tree to close
4. `:colorscheme xyz`

**Comment by Davincible** [comment]
Can be fixed by checking if the window is valid on view.lua:441

```lua
-- used on ColorScheme event
function M.reset_winhl()
  if M.get_winnr() and vim.api.nvim_win_is_valid(M.get_winnr()) then
    vim.wo[M.get_winnr()].winhl = M.View.winopts.winhl
  end
end
```

**Comment by alex-courtis** [comment]
> Can be fixed by checking if the window is valid on view.lua:441
> 
> ```lua
> -- used on ColorScheme event
> function M.reset_winhl()
>   if M.get_winnr() and vim.api.nvim_win_is_valid(M.get_winnr()) then
>     vim.wo[M.get_winnr()].winhl = M.View.winopts.winhl
>   end
> end
> ```

Great digging. Please create a PR.

**Comment by Davincible** [comment]
I'm not sure if its specifically my setup, but I seem to get more of these kinds of errors;

```console
Error executing vim.schedule lua callback: ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:59: Invalid window id: 1053                                                                 
stack traceback:
        [C]: in function 'nvim_win_get_cursor'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:59: in function 'draw'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:117: in function 'reload_tree_at'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:150: in function 'callback'
        .../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lua:406: in function <.../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lua:405>
```

**Comment by alex-courtis** [comment]
> I'm not sure if its specifically my setup, but I seem to get more of these kinds of errors;

Let's track that separately.

Please raise a new bug report, this time with an nvt-min.lua that we can reproduce the problem with. `:colorscheme default` isn't a great test case...
