### ISSUE TITLE
Opening folder inside a folder containing `$`: `Can't find directory`

### ISSUE THREAD

**Issue by LostNeophyte** [nvim-tree/nvim-tree.lua#1728]
### Description

when opening nvim in a folder like `nvim \$abc/def` when using `vim.g.loaded_netrw = 1 and vim.g.loaded_netrwPlugin = 1`  there's an error. I believe it happens because of [vim.fn.expand here](https://github.com/nvim-tree/nvim-tree.lua/blob/7e892767bdd9660b7880cf3627d454cfbc701e9b/lua/nvim-tree.lua#L229).
`:lua print(vim.fn.expand("/$abc/def"))` returns `//def` as seen in the error `Can't find directory "/home/adam/Downloads//def"`. Full error is in actual behavior below

### Neovim version

```text
NVIM v0.9.0-dev+185-g3de2a7f6d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.19.16-200.fc36.x86_64

### nvim-tree version

7e89276

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end

if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

```
1.mkdir "\$abc/def/" -p
2.nvim -nu /tmp/nvt-min.lua \$abc/def
```

### Expected behavior

no errors

### Actual behavior

```Ready!
Error executing vim.schedule lua callback: ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:231: Vim(cd):E344: Can't find directory "/home/adam/Downloads//def" in cdpath
stack traceback:
        [C]: in function 'cmd'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:231: in function 'on_enter'
        ...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:788: in function <...n/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:787>```

**Comment by alex-courtis** [comment]
Confirmed: default config, netrw disabled

**Comment by alex-courtis** [comment]
Also affected: change-dir

**Comment by alex-courtis** [comment]
`:help expand`

		expand() can also be used to expand variables and environment
		variables that are only known in a shell.  But this can be
		slow, because a shell may be used to do the expansion.  See
		|expr-env-expand|.
		The expanded variable is still handled like a list of file
		names.  When an environment variable cannot be expanded, it is
		left unchanged.  Thus ":echo expand('$FOOBAR')" results in
		"$FOOBAR".

`:echo expand("$abc")` -> `$abc`
`:echo expand("$abc/def")` -> `/def`
`:echo expand("xyz/$abc/def")` -> `xyz//def`

Same behaviour in vim.

The doc is a little unclear.

**Comment by alex-courtis** [comment]
@LostNeophyte I will be most grateful if you can test the fix https://github.com/nvim-tree/nvim-tree.lua/pull/1729

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1728-open-folder-special-chars
```

**Comment by LostNeophyte** [comment]
Will do in a couple hours

**Comment by LostNeophyte** [comment]
> ```shell
> git checkout 1728-open-folder-special-chars
> ```

It does work :) Thanks for doing it so fast

**Comment by alex-courtis** [comment]
Thanks for testing. I'm going to soak this for a week before merging.
