### ISSUE TITLE
Optionally Indent Root Child Nodes

### ISSUE THREAD

**Issue by clarkwang** [nvim-tree/nvim-tree.lua#1737]
It would look a bit better if the root dir moves to the left most of the screen.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/157076/201008308-ec1e3ded-4538-4146-97c6-bc945a2e84b8.png">

**Comment by alex-courtis** [comment]
The 2 character gap before the root dir is the vim sign column, which can be removed `:help nvim-tree.view.signcolumn`

![20221112_114440 389x719](https://user-images.githubusercontent.com/1505378/201448256-d117b6d8-4d71-4cda-b23c-e9093f4b55d3.png)

However... I'm not sure that's quite what you are looking for.

**Comment by clarkwang** [comment]
With `signcolumn = 'no'` it becomes this:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/157076/201453076-155680b5-fcbd-4fae-934e-b6490890341c.png">

But I want this:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/157076/201453041-5f0354b8-e874-4e0c-a677-0113386af335.png">

My settings (with `BOOL_0 = false; BOOL_1 = true`):

~~~lua
    renderer = {
        group_empty = BOOL_1,
        highlight_git = BOOL_0,
        icons = {
            webdev_colors = BOOL_0,
            padding = " ",
            symlink_arrow = " -> ",
            show = {
                file = BOOL_1,
                folder = BOOL_1,
                folder_arrow = BOOL_0,
                git = BOOL_0,
            },
            glyphs = {
                default = "|",
                symlink = "@",
                bookmark = "|",
                folder = {
                    arrow_closed = ">",
                    arrow_open = "+",
                    default = ">",
                    open = "+",
                    empty = "-",
                    empty_open = "-",
                    symlink = "@",
                    symlink_open = "+",
                },
            },
        },
    },
    view = {
        adaptive_size = BOOL_0,
        centralize_selection = BOOL_1,
        hide_root_folder = BOOL_0,
        signcolumn = 'no',
        width = 30,
    }
~~~

**Comment by alex-courtis** [comment]
I see. We want the root node to behave like any other folder, indenting the folders inside it.

Updating title.

It could be done by optionally increasing the base indent level: https://github.com/nvim-tree/nvim-tree.lua/blob/951e10a64e0b03069f0f50ddc79d6a8ed8d23dec/lua/nvim-tree/renderer/builder.lua#L235

Much testing needed.

**Comment by alex-courtis** [comment]
More complete solution #2023
