### ISSUE TITLE
Remove “/..” from root directory if “restrict_above_cwd” is enabled

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1743]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/1735

<div type='discussions-op-text'>

<sup>Originally posted by **davilera** November  9, 2022</sup>
Currently, nvim-tree’s default behavior is to append `/..` to the root directory. This makes sense because the user can't browse one directory up. However, if `actions.change_dir.restrict_above_cwd` is enabled, this is no longer possible.

Therefore, I'd recommend appending `/..` in `local function format_root_name` if, and only if, `actions.change_dir.restrict_above_cwd` is **not** enabled. IMO, this would result in a better UX.</div>

**Comment by lmartinpierrat** [comment]
I would argue that you should be able to remove the /.. entirely even if you don't have restrict_above_cwd

I have no interest in having this added to the header, which I would rather have just the name of the directory I'm in, which  is always my project name.

I spent quite a while trying to find the right filename-modifiers to get rid of the /.. which lead me to look into the code and saw it was hardcoded unfortunately.

**Comment by alex-courtis** [comment]
> I would argue that you should be able to remove the /.. entirely even if you don't have restrict_above_cwd

I'm inclined to agree. It's not adding much value and removing it should not break anything.

The `cd` action will be a bit misleading as it will change to the root's parent rather than the root, however displaying the `/..` is also misleading as that is not the root's actual directory.

**Comment by davilera** [comment]
> I would argue that you should be able to remove the /.. entirely even if you don't have restrict_above_cwd

Should it have its own setting at least?

**Comment by alex-courtis** [comment]
> > I would argue that you should be able to remove the /.. entirely even if you don't have restrict_above_cwd
> 
> Should it have its own setting at least?

Usually yes, as this change would be a break to existing functionality.

However, as this is a more cosmetic change we could do it without a setting.
