### ISSUE TITLE
Expand all files containing modified folders - Toggle

### ISSUE THREAD

**Issue by rkulla** [nvim-tree/nvim-tree.lua#1747]
I often want to see all the files that were modified at once - from nvim-tree at a glance, rather than running `git status`

I love how Nvim-Tree shows git-integrated markers next to files that were modified, staged, etc. and even next to root level folders containing modified files. However, even nicer would be the ability to expand those folders to expose all the files that were modified at once.

I currently type `:G` in vim-fugitive to see it but it would be nice to also be able to see this from within Nvim-Tree.

**Comment by alex-courtis** [comment]
Yes. I would like functionality like that to quickly navigate to modified files but couldn't think of a nice way to do it. #1389

I use a combination of fugitive and fzf#gitfiles

This expand function would cover that nicely.

**Comment by alex-courtis** [comment]
We can do this now: Toggle Git Clean then Expand All
