### ISSUE TITLE
`q` key press after running `:version` closes NvimTree

### ISSUE THREAD

**Issue by Garz4** [nvim-tree/nvim-tree.lua#1766]
### Description

Pressing `q` after running `:version` command within Nvim closes NvimTree.

### Neovim version

```text
NVIM v0.8.0-dev+585-g782f72613
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 5.15.79-1-lts

### nvim-tree version

e204a7d

### Minimal config

```lua
require('nvim-tree').setup()
```

### Steps to reproduce

1. In your terminal, run: `nvim [file]` (note that `[file]` is not necessary)
2. Focus your cursor on NvimTree.
3. Run `:version` VIM command.
4. Press `q`.

### Expected behavior

Only close the window showing the version of Nvim.

### Actual behavior

Closes both the window showing the version of Nvim and NvimTree itself (please not that it will only close it if NvimTree is focused by the user cursor).

**Comment by alex-courtis** [comment]
Interesting. Happens for mappings other than `q`.

This does happen for other plugin windows e.g. fugitive `:version` `s` will stage the file under the cursor.

This also happens for regular buffer windows e.g. `:version` `i` enters insert mode and `q` starts macro recording.

I'm going to close this as "expected vim behaviour". Please reopen if you find any other cases that are nvim-tree specific only.

**Comment by Garz4** [comment]
Sure! Thanks for the update, it makes a lot of sense now.
