### ISSUE TITLE
dev icons not working

### ISSUE THREAD

**Issue by jaanauati** [nvim-tree/nvim-tree.lua#1773]
### Description

This was working just fine, but today, at some point after upgrading my deps, nvim-tree started to look as follows:

<img width="206" alt="image" src="https://user-images.githubusercontent.com/433609/204039450-bf8b73fe-04d2-451d-91bb-6ffde88da4e8.png">

my config is:
```
Plug 'nvim-tree/nvim-web-devicons' " optional, for file icons
Plug 'nvim-tree/nvim-tree.lua'
...

lua << EOF
require'nvim-tree'.setup {
  update_focused_file = {
    enable = true,
  },
}
EOF
```

Maybe I missing a config param or something else?

### Neovim version

```text
NVIM v0.8.0-dev+1883-g8ba64dd3a
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS Monterrey v12.5.1

### nvim-tree version

68a2a09

### Minimal config

```lua
Plug 'nvim-tree/nvim-web-devicons' " optional, for file icons
Plug 'nvim-tree/nvim-tree.lua'
...


lua << EOF
require'nvim-tree'.setup {
  update_focused_file = {
    enable = true,
  },
}
EOF
```
```


### Steps to reproduce

1. open nvim
2. open nvim-tree

### Expected behavior

Icons should be displayed.

### Actual behavior

Dev icons are not displayed, I see a `?` instead.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/433609/204039450-bf8b73fe-04d2-451d-91bb-6ffde88da4e8.png">

**Comment by bvdmitri** [comment]
The same on macOS 13.0.1, iTerm2

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura
```

**Comment by alex-courtis** [comment]
I see the common factor is macOS. Maybe iterm2.

The likely cause of the issue is that the icons from your nerd font are no longer displaying.

Suggestions:
* check your [patched nerd font](https://www.nerdfonts.com/) is correctly installed
* look for any changes to your terminal's configuration

For myself, chrome (linux) recently changed its font from Hack Nerd Font to Hack Font for unknown reasons. Manually changing it back in the settings resolved the issue.

**Comment by Yohnny777** [comment]
Same here, fresh setup today

**Comment by gegoune** [comment]
Are they showing at all outside of nvim tree? It's up to terminal to display those glyphs properly, nvim-tree does nothing specific here I think.

**Comment by alex-courtis** [comment]
You could try something like this to see if it's a vim problem or a terminal problem:

```sh
cat /path/to/nvim-tree.lua/doc/nvim-tree-lua.txt | grep -A 23 "glyphs = "
```

**Comment by Yohnny777** [comment]
What solved it for me is installing one of nerd fonts and then changing the terminal font to it. 

It isn't obvious for people new to Vim/Terminal, coming from VSCode. I assumed it comes with the extension somehow.

**Comment by alex-courtis** [comment]
> What solved it for me is installing one of nerd fonts and then changing the terminal font to it.
> 
> It isn't obvious for people new to Vim/Terminal, coming from VSCode. I assumed it comes with the extension somehow.

Explicitly specified in documentation: https://github.com/nvim-tree/nvim-tree.lua/commit/9f7bed5536521eca912a7663b11655d218acf013

Please add an entry to the [Troubleshooting](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting) wiki page. Something like:

> # File Icons Not Showing Under iTerm2
>
> iTerm2 must be explicitly configured to use the patched font:
>
> [Screenshot of the configuration]

**Comment by jaanauati** [comment]
@alex-courtis 
> I see the common factor is macOS. Maybe iterm2.
I typically use VimR, but I also tried iTerm2 and Alacritty and behavior is the the same in the three of them. I'm having the same results in two different macbooks.

> You could try something like this to see if it's a vim problem or a terminal problem:
>cat /path/to/nvim-tree.lua/doc/nvim-tree-lua.txt | grep -A 23 "glyphs = "

<img width="750" alt="image" src="https://user-images.githubusercontent.com/433609/204264420-1b07439e-74af-44a1-9b24-312ee9834523.png">

The Icons were showing up just fine until I decided to re-install all my plugins for which I manually wiped my plugins directory and reinstalled everything again (using Plug).

**Comment by gegoune** [comment]
This is clearly terminal emulator issue not displaying those glyphs. Nothing we can do about it - you must configure your terminal emulator fonts.

**Comment by jaanauati** [comment]
@Yohnny777 @gegoune 
> What solved it for me is installing one of nerd fonts and then changing the terminal font to it.
Can you please add some details or link me to a tutorial?, is not clear for me what to do here. As I mentioned before this was working fine until I reinstalled my plugins (3-4 days ago), and I never configured my terminal to use any fonts.

>  This is clearly terminal emulator issue not displaying those glyphs. Nothing we can do about it - you must configure your terminal emulator fonts.
maybe, but Im having issues with VimR as well.

**Comment by alex-courtis** [comment]
> Can you please add some details or link me to a tutorial?, is not clear for me what to do here. As I mentioned before this was working fine until I reinstalled my plugins (3-4 days ago), and I never configured my terminal to use any fonts.

I lack access to / expertise with macOS and iTerm. I have requested @Yohnny777 add to the wiki: https://github.com/nvim-tree/nvim-tree.lua/issues/1773#issuecomment-1328368752

**Comment by alex-courtis** [comment]
@gegoune I believe you are a macOS user... perhaps you could add to https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#icons-not-correctly-shown

**Comment by gegoune** [comment]
I am not sure how to set it up system wide, I always set it up in my terminals. Quick google didn't reveal anything either.

**Comment by alex-courtis** [comment]
> I am not sure how to set it up system wide, I always set it up in my terminals. Quick google didn't reveal anything either.

I imagine that system wide is not feasible. Maybe just a screenshot for iterm?

**Comment by gegoune** [comment]
I use wezterm which has a fallback mechanism including nerd icons. :) But will try to get iterm2 installed and put something together.

**Comment by gegoune** [comment]
Solution is to set font for non-ascii characters: https://github.com/ryanoasis/vim-devicons/issues/226#issuecomment-492783382

Or use patched font.

**Comment by jaanauati** [comment]
> Solution is to set font for non-ascii characters: https://github.com/ryanoasis/vim-devicons/issues/226#issuecomment-492783382
thank @gegoune, this fixed it!
