### ISSUE TITLE
show_on_dirs option for lowest visible only

### ISSUE THREAD

**Issue by ehaynes99** [nvim-tree/nvim-tree.lua#1781]
The git and diagnostics views both have a setting `show_on_dirs` which makes parent folders display the same icon as the file. This is extremely helpful when they're collapsed I.e. if there is an error in `/first/second/third.lua` and the tree is collapsed, there will be an error icon next to `first`, indicating that there's a problem in one of its children. However, if both `first` and `second` are expanded, the icon is displayed on both parents as well as the file. As a visual cue, it exaggerates the number of "things", particularly when the tree expands far enough that they're not all visible at the same time.

**Describe the solution you'd like**
It would be really nice to have an option to display the icon only on the lowest visible leaf. E.g.
* if `first` is collapsed, display it on `first`
* if first is expanded but `second` is collapsed, display it on `second`
* if all are expanded, display it on `third.lua`

**Comment by alex-courtis** [comment]
Wow... your timing is amazing. See #1778

**Comment by ehaynes99** [comment]
Talk about responsive... @chomosuke went back in time to resolve this issue half a day before I raised it! Or maybe it's telepathy, as I *thought* about filing it yesterday and just didn't get around to it. :-D

I did search for an existing issue, but didn't search the PRs. Great stuff!
