### ISSUE TITLE
Feature request: bulk rename 

### ISSUE THREAD

**Issue by Strongleong** [nvim-tree/nvim-tree.lua#1795]
**Is this a question?**
No, it isn't.

**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
I'd like to be able to somehow "select" files I want to rename (via visual mode or via separate "select for bulk renaming" button) and press "rename" button. 
After that something happens that will help me to rename all of selected files at one time.
Possible solutions:
1. New buffer opens where each line represents selected files names that I can edit. When I save this buffer selected files renames with string that lies on associated line.
2. Floating window opens with two "input fields" where I can type what string I want to search for in selected files names and what I want to replace it with.

**Describe alternatives you've considered**
`vifm` file manager can bulk rename files wilth method described in possible solution 1. But open `vifm` every time I want to rename some files is not really handy

**Additional context**
Sorry for bad English 😅

**Comment by alex-courtis** [comment]
That's a really nice idea.

1 might be preferable: users have the full power of a vim buffer to regex replace or use whatever method they prefer.

2: multiple input fields could be problematic and the user is a bit limited in what they can do.

Alternative alternative idea: nvim-tree delegates the bulk rename to vifm. nvim-tree should refresh with the changes with no action required. Caveat: I've not played with `vifm`...

**Comment by gegoune** [comment]
Does another plugin with such functionality exist already? How about `gabrielpoca/replacer.nvim`?

**Comment by alex-courtis** [comment]
It sounds like this task can be achieved completely via API using methods such as `api.marks.get()`

**Comment by Strongleong** [comment]
Why this feature request is closed?

**Comment by alex-courtis** [comment]
All the API to achieve this goal is present: `nvim-tree.api.marks` and `nvim-tree.api.fs`.

As this functionality is very niche and specific to each use case, pre-defined action/API for this functionality does not make sense.

Pragmatic solution: use https://github.com/gabrielpoca/replacer.nvim which provides rich functionality to achieve the exact mechanism to suit your use case.

**Comment by Strongleong** [comment]
To me this functionality as niche as bulk move, which is implemented. It looks logical to have same functionality for marked files as for just one file (move, open, *rename*, etc.)

Bloating neovim configuration with another plugin for functionality that **can** be done in plugin that I already have installed sound not really pragmatic (considering that this is plugin for managing files)
