### ISSUE TITLE
adaptive_size Maximum Width

### ISSUE THREAD

**Issue by nfwyst** [nvim-tree/nvim-tree.lua#1797]
it is too wide when the file name is long, so i'd like to limit the width when in adaptive_size mode

**Comment by alex-courtis** [comment]
In future, please raise a "Feature Request" issue.

**Comment by alex-courtis** [comment]
It looks like there are other users with the same requirements: #1776

**Comment by alex-courtis** [comment]
We could repurpose `view.width` to have it apply when using adaptive size. This will need further investigation.

A `view.max_width` with the same types as `view.width` is a pragmatic solution.
