### ISSUE TITLE
Vertical Splits resized when opening nvim tree

### ISSUE THREAD

**Issue by StaticESC** [nvim-tree/nvim-tree.lua#1799]
### Description

Say you have 2 splits (vertical split made using `:vsplit`) and you resize them such that their size proportion is not  50-50, rather, say 75-25. Upon doing `:NvimTreeToggle` (opening up Nvim tree), any vsplits which have been resized, get sized back to their original proportions, hence splits are back to 50-50

I am aware of `nvim-tree.view.preserve_window_proportions`, however that only fixes the issue for horizontal splits, not for vertical splits.

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.9-arch1-1, Arch Linux

### nvim-tree version

07149da

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua`
2. `:vsplit`
3. `vertical resize +10`
4. `NvimTreeToggle`
5. `NvimTreeToggle`

### Expected behavior

All splits must retain their original proportions

### Actual behavior

Splits go back to default proportions

**Comment by alex-courtis** [comment]
Wow... great timing. See #1798 : `:help 'equalalways'`

Please comment/reopen if that doesn't work for you.
