### ISSUE TITLE
bulk file deletion?

### ISSUE THREAD

**Issue by clanktron** [nvim-tree/nvim-tree.lua#1804]
It's stated in #221 that support was added for deleting/moving multiple files with the mark functionality but I'm not seeing anything in the readme or :help section that explains how to do so. Simply marking multiple files and then pressing 'd' or 'D' does not delete those marked and only deletes the file you're currently on.

That being said I think it might be more intuitive to be able to delete files using visual mode to select them. That's just my preference though. This issue is more meant to clarify how to use the existing functionality.

**Comment by alex-courtis** [comment]
Bulk delete would be very useful functionality.

Specific API is not available: `:help nvim-tree.api.marks`. It can be achieved via a custom action to `api.marks.get` and delete each of them however that's a pretty clunky and complex solution.

Proposal:
* Add `api.marks.bulk.delete`
* Add action like `bde` `bulk_delete`.

**Comment by alex-courtis** [comment]
See #1413

**Comment by alex-courtis** [comment]
Discussion on user implementation: https://github.com/nvim-tree/nvim-tree.lua/issues/1413#issuecomment-1354104872

**Comment by petobens** [comment]
Hi @alex-courtis so I took a (minor) stab at this and wrote the following function
```lua
function NvimTreeConfig.bulk_delete()
    local nodes = require('nvim-tree.api').marks.list()
    if next(nodes) == nil then
        table.insert(nodes, tree_api.get_node_under_cursor())
    end
    vim.ui.input(
        { prompt = string.format('Trash %s files? [y/n] ', #nodes) },
        function(input)
            if input == 'y' then
                vim.cmd('redraw!')
                for _, node in ipairs(nodes) do
                    vim.fn.jobstart('trash-put ' .. node.absolute_path)
                end
            end
        end
    )
end
```
However I'm having two issues:
1. Is it possible to reuse the builtin trash action? 
2. If I try to delete a directory with this then I get
```
[NvimTree] 'Failed reloading /home/pedro/Desktop/test-lua/f: "ENOENT: no such file or directory: /home/pedro/Desktop/test-lua/f"'
```
(however this also happens with the builtin trash action applied on a directory so it might be a more general bug)

Any pointers are greatly appreciated.

**Comment by alex-courtis** [comment]
> * Is it possible to reuse the builtin trash action?

Yes, you can use API: `:help nvim-tree.api.fs`

> * If I try to delete a directory with this then I get

Yes, that will happen when a directory is deleted from outside of vim. I'm not sure whether we should change that, as it's a reasonable message.

Providing you're using the API trash or remove you won't see it.

**Comment by petobens** [comment]
Mmm using `fs_api.trash(node)` still shows the directory error as in the GIF:

![treedelete](https://user-images.githubusercontent.com/2583971/208329482-87a8aab8-d5ca-4521-8fe4-0baabb967764.gif)

Also is it possible to avoid the confirm deletion message by pasing an argument to the trash function? (i.e without touching the general config option)

**Comment by alex-courtis** [comment]
> Mmm using fs_api.trash(node) still shows the directory error as in the GIF:

That's a bug, good catch! Occurs for directories when watchers are enabled. Fixed d949af7

> Also is it possible to avoid the confirm deletion message by pasing an argument to the trash function? (i.e without touching the general config option)

`:help nvim-tree.trash.require_confirm`

**Comment by alex-courtis** [comment]
Removed error messages as they are adding no value and were unreachable until #1831 diagnostics added.

547db6e

**Comment by petobens** [comment]
>That's a bug, good catch! Occurs for directories when watchers are enabled. Fixed https://github.com/nvim-tree/nvim-tree.lua/commit/d949af7245c04018e0b5ed3409c4e82c1303d2ea

Thank you!

> :help nvim-tree.trash.require_confirm

I do have:
```lua
    trash = {
        cmd = 'trash-put',
        require_confirm = true,
    },
```
in my config but I was wondering whether is was possible to override that within the lua function.. something like:
```lua
require('nvim-tree.api').fs.trash(node, false)
```

**Comment by alex-courtis** [comment]
> in my config but I was wondering whether is was possible to override that within the lua function.. something like:
> 
> ```lua
> require('nvim-tree.api').fs.trash(node, { require_confirm = false })
> ```

We could do that. PRs are gratefully appreciated :)
