### ISSUE TITLE
Nvim tree doesn't auto refresh for sshfs mounted filesystem

### ISSUE THREAD

**Issue by Blake227** [nvim-tree/nvim-tree.lua#1807]
### Description

I recently use neovim and sshfs to work on the remote workstation. Nvim Tree would auto refresh if I add or remove file in the fuse filesystem via terminal on the local machine, but it doesn't refresh if I add or remove files at the terminal of workstation. The fuse filesystem on the local machine would show the file added at the instant I create the file at the terminal of workstation, but nvim-tree wouldn't. Running :NvimTreeRefresh can correctly refresh the file tree. Is there any way to fix that?

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.10-arch2-1

### nvim-tree version

1837751

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. `sshfs remote-server local-directory`
2. `cd local-directory`
3. `nvim -nu /tmp/nvt-min.lua`
4. `:NvimTreeOpen`
5. `touch something` at the ssh session of the remote server

### Expected behavior

Nvim Tree would auto refresh the file tree in the local sshfs file system if there are changes at the remote server.

### Actual behavior

`:NvimTreeRefresh` is necessary to refresh the file tree.

**Comment by alex-courtis** [comment]
nvim-tree uses file system watchers to automatically update. Unfortunately that cannot work over sshfs.

Options:
1. set `filesystem_watchers.enable = false` and `auto_reload_on_write = true` to allow tree refresh following buffer write
2. build a mechanism to watch sshfs similar to filesystem watchers

Please try 1

I'm not sure if 2 is even possible, and we don't have resources to build this any time soon.
