### ISSUE TITLE
Deprecate `nvim-tree.view.hide_root_folder`

### ISSUE THREAD

**Issue by gegoune** [nvim-tree/nvim-tree.lua#1808]
We have `nvim-tree.renderer.root_folder_label` which controls what gets displayed as 'root_folder'. Setting it to false (and/or returning empty string) should hide it completely.

That would allow deprecation/removal of 

```
    *nvim-tree.view.hide_root_folder*
    Hide the path of the current working directory on top of the tree.
      Type: `boolean`, Default: `false`
```

_Originally posted by @gegoune in https://github.com/nvim-tree/nvim-tree.lua/issues/1803#issuecomment-1336477437_

**Comment by alex-courtis** [comment]
Absolutely. I'm sure we will find more.
