### ISSUE TITLE
Option to Pin the tree root to a directory

### ISSUE THREAD

**Issue by churtado** [nvim-tree/nvim-tree.lua#1823]
**Is this a question?**
No

**Can this functionality be implemented utilising API?**
nvim-tree exposes extensive API (see `:h nvim-tree-api`). Can it be used to achieve your goal? Is there a missing API that would make it possible?
Given stable status of nvim-tree it's preferred to add new API than new functionality.
I've tried every option I can think of using the existing API and cannot get the behaviour I want.

**Is your feature request related to a problem? Please describe.**
I have a directory that has 4 subdirectories, each a project of its own and each is a git repo. I'd like to pin the root of the tree to the parent directory of these 4 projects and not have the root change when I open a file from one of the subdirectories. When I open a file from one of the 4 subdirectories, the root directory changes to the directory containing the git repo (essentially the project root) of that file.

**Describe the solution you'd like**
An option to pin the root to a directory I specify, or an option within the API to not change the root directory when opening any file.

**Describe alternatives you've considered**
None I can think of. 

**Additional context**
I often work in what's called a "workspace" which is a directory that contains many subdirectories, each it's own "sub-project" and its own git repo. These git repos are tightly coupled, so I'd like to keep visibility of the whole structure as it makes it easier to navigate through the different project files.

**Comment by gegoune** [comment]
How are you setting up cwd? Seems more like a "project" configuration issue. If you are using nvim-tree's option to change cwd for you you can disable that functionality and manage it other way.

**Comment by gegoune** [comment]
That probably should be reported as separate issue. You raised a valid point here.

**Comment by alex-courtis** [comment]
> If you have `update_focused_file` enabled, it defaults the `update_root` setting to `true`. You can disable it here like:

Wow... that sounds like a bug.

**Comment by ehaynes99** [comment]
I guess I read that wrong... it says the default is false, and does appear that way. I definitely had issues with it hopping around before, but now I can't reproduce even with that removed.

However, the behavior the OP reports shouldn't be affected by that anyway.
> *nvim-tree.update_focused_file.update_root*  (previously `update_focused_file.update_cwd`)
>
>    Update the root directory of the tree if the file is not under current
    root directory.

Something is amiss, though. In the behavior that OP reports, it shouldn't matter even if that's enabled, as it would still be under the current root. @churtado can you share your config?

**Comment by alex-courtis** [comment]
I think this is resolved: the `update_focused_file` options along with `root_dirs` / `prefer_startup_root` and recent bugfixes should allow the desired behaviour.

Please raise a bug report with a reproducer if you encounter incorrect behaviour.
