### ISSUE TITLE
General View Debounce

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1836]
Many events such as buf write result in refresh / redraw. There are often many in quick succession e.g. telescope.

Add a generic `renderer.debounce_delay` at 15ms, as per `update_focused_file.debounce_delay`.

Silently migrate `update_focused_file.debounce_delay` to `renderer.debounce_delay`.

Candidates:
* #1835
* #1830

**Comment by alex-courtis** [comment]
`view.debounce_delay` would be a better option.

**Comment by chomosuke** [comment]
How about `diagnostics.debounce_delay` and `filesystem_watchers.ignore_dirs`? Do you think we should migrate them to `view.debounce_delay` as well?

**Comment by chomosuke** [comment]
And what do you think about just having `debounce_delay` instead of `view.debounce_delay`. I feel like that's more natural with `auto_reload_on_write` there as well.
