### ISSUE TITLE
Error when generating CMake files.

### ISSUE THREAD

**Issue by carlosdr02** [nvim-tree/nvim-tree.lua#1841]
### Description

I get an error when generating the CMake files through [this plugin](https://github.com/Shatur/neovim-tasks):

![image](https://user-images.githubusercontent.com/80007185/208337500-a43589c0-69c7-4947-a2d2-6d9f66413a8c.png)

I have started to use nvim-tree very recently so I don't know much about it, but I think this happens because after generating the CMake files, nvim-tree tries to reload itself and something goes wrong.

I've also opened an issue in the CMake plugin github page and the author told me: "Not sure why, but looks like its nvim-tree tries to reload after adding things to quickfix."

Although I've included my config and the steps to reproduce, I think developers of this plugin might just be able to tell what the problem is by just looking at the error message. The only thing I can think of is maybe set "auto_reload_on_write" to false, but that would also mean that git changes would not show in the tree when I save my files, am I wrong?

### Neovim version

```text
NVIM v0.8.1
```

### Operating system and version

Windows 11

### nvim-tree version

e0cfbbb

### Minimal config

```lua
require('packer').startup(function(use)
	use 'wbthomason/packer.nvim'
        use {
            'nvim-tree/nvim-tree.lua',
            requires = {
                'nvim-tree/nvim-web-devicons',
            },
            tag = 'nightly'
        }
        use 'Shatur/neovim-tasks'
end)

require('nvim-tree').setup()

local Path = require('plenary.path')
require('tasks').setup({
    default_params = {
    cmake = {
        cmd = 'cmake',
        build_dir = tostring(Path:new('{cwd}', 'build', '{os}-{build_type}')),
        build_type = 'Debug',
        dap_name = 'lldb',
        args = {
        configure = { '-D', 'CMAKE_EXPORT_COMPILE_COMMANDS=1', '-G', 'Ninja' },
    },
},
  },
  save_before_run = true,
  params_file = 'neovim.json',
  quickfix = {
      pos = 'botright',
      height = 12,
  },
  dap_open_command = function() return require('dap').repl.open() end,
})
```

### Steps to reproduce

1. On the root folder (where the `CMakeLists.txt` file is located) of a CMake project, run `:Task start cmake configure` to generate the CMake files.
2. Select the build target (e.i., the executable) by running `:Task set_module_param cmake target`.
3. Finally, build and run the project by running `:Task start cmake run`.
4. You should see the same error you saw on the image posted above.

**Comment by alex-courtis** [comment]
Thank you for raising. We do indeed refresh on quickfix window open. Happening since c5dc80c when `filters.no_buffer` enabled. Also occurs with 18272f8 when `highlight_opened_files` set.

#1830 will address this issue.

**Comment by alex-courtis** [comment]
@chomosuke I'd appreciate your thoughts.

It seems that we are responding to way too many unnecessary `BufReadPost` events.

Possibility: do nothing unless `vim.fn.filereadable`

**Comment by alex-courtis** [comment]
@carlosdr02 I would be most grateful if you tested the fix:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1841-do-not-reload-open-buffers-when-not-a-file-buffer
```

**Comment by alex-courtis** [comment]
I'd be grateful if you could test the fix on latest master.

**Comment by carlosdr02** [comment]
@alex-courtis Solved! Thank you sm :)
