### ISSUE TITLE
how to sort the tab by number?

### ISSUE THREAD

**Issue by sunxin18** [nvim-tree/nvim-tree.lua#1842]
**Is this a question?**
Please start a new [Q&A discussion](https://github.com/nvim-tree/nvim-tree.lua/discussions/new) instead of raising a feature request.

**Can this functionality be implemented utilising API?**
nvim-tree exposes extensive API (see `:h nvim-tree-api`). Can it be used to achieve your goal? Is there a missing API that would make it possible?
Given stable status of nvim-tree it's preferred to add new API than new functionality.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-courtis** [comment]
Please ask a [Q&A discussion](https://github.com/nvim-tree/nvim-tree.lua/discussions/new) and include more information.
