### ISSUE TITLE
Performance issue when working with telescope

### ISSUE THREAD

**Issue by ghostbuster91** [nvim-tree/nvim-tree.lua#1844]
### Description

First of all, thank you very much for this great plugin, I appreciate your effort.

After a recent update I started to observe some performance issues when switching files using telescope. After some debugging it turned out that this is only occurs if I had nvim-tree opened. The issue goes away when I disable git integration. However I don't think that this is solely related to git. The repository I work on is big, sure, but picking files using telescope shouldn't be affected by nvim-tree, as there is nothing that nvim-tree should be doing with that information. 

No delay:
![nvim-tree-old](https://user-images.githubusercontent.com/5662622/208501144-1b0f0a3b-bfac-4df9-9f46-28783ac81835.gif)
Here you can observe the delay:
![nvim-tree-new](https://user-images.githubusercontent.com/5662622/208501155-9d9a90f2-9c4a-42ef-a08d-efde15be396b.gif)

### Neovim version

```text
nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/zfyninsb38hzxkx3rxvwz3lxdxnsfz0j-neovim-unwrapped-0.8.1/share/nvim
"

Run :checkhealth for more info
```

### Operating system and version

Linux PCX0DX 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### nvim-tree version

87409bb4afd0093193e1364faa47327fbfdfca87

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({ function(use)
    use {"wbthomason/packer.nvim"}
    use {"nvim-tree/nvim-tree.lua",
	commit = '87409bb4afd0093193e1364faa47327fbfdfca87'
    }
    use {"nvim-tree/nvim-web-devicons"}
    use {'nvim-telescope/telescope.nvim', 
         commit = 'cabf991b1d3996fa6f3232327fc649bbdf676496',
         requires = { {'nvim-lua/plenary.nvim'} }
	}
  end
  ,
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
}
    })
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
  require("telescope").setup{}
end
```

### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua`
2. open a big repository like e.g. https://github.com/NixOS/nixpkg
3. open few files using telescope picker - no issue here
4. toggle nvim-tree
5. repeat step 3. - huge lags when opening new files

### Expected behavior

As there is nothing that interacts with nvim tree during this workflow I would expect it not to cause any delays. 

### Actual behavior

Opening telescope incurs a delay as well as opening new file using it. 
In the logs I can see multiple such blocks:
```
!! .idea/
!! nixpkgs.iml
[2022-12-19 19:19:26] [git] done
[2022-12-19 19:19:26] [profile] END   git job /home/kghost/workspace/nixpkgs nil  134ms
[2022-12-19 19:19:26] [git] job success    /home/kghost/workspace/nixpkgs nil
[2022-12-19 19:19:26] [profile] START reload /home/kghost/workspace/nixpkgs
[2022-12-19 19:19:26] [profile] END   reload /home/kghost/workspace/nixpkgs  0ms
[2022-12-19 19:19:26] [profile] START reload /home/kghost/workspace/nixpkgs/lib
[2022-12-19 19:19:26] [profile] END   reload /home/kghost/workspace/nixpkgs/lib  0ms
[2022-12-19 19:19:26] [profile] START draw
[2022-12-19 19:19:26] [profile] END   draw  1ms
[2022-12-19 19:19:26] [profile] START git job /home/kghost/workspace/nixpkgs nil
[2022-12-19 19:19:26] [git] running job with timeout 400ms
[2022-12-19 19:19:26] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
!! .idea/
!! nixpkgs.iml
[2022-12-19 19:19:26] [git] done
[2022-12-19 19:19:26] [profile] END   git job /home/kghost/workspace/nixpkgs nil  133ms
[2022-12-19 19:19:26] [git] job success    /home/kghost/workspace/nixpkgs nil
[2022-12-19 19:19:26] [profile] START reload /home/kghost/workspace/nixpkgs
[2022-12-19 19:19:26] [profile] END   reload /home/kghost/workspace/nixpkgs  0ms
[2022-12-19 19:19:26] [profile] START reload /home/kghost/workspace/nixpkgs/lib
[2022-12-19 19:19:26] [profile] END   reload /home/kghost/workspace/nixpkgs/lib  0ms
[2022-12-19 19:19:26] [profile] START draw
[2022-12-19 19:19:26] [profile] END   draw  1ms
[2022-12-19 19:19:26] [profile] START git job /home/kghost/workspace/nixpkgs nil
[2022-12-19 19:19:26] [git] running job with timeout 400ms
[2022-12-19 19:19:26] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
```

**Comment by ghostbuster91** [comment]
I think that it might be connected with https://github.com/nvim-tree/nvim-tree.lua/issues/1836 but since I wasn't sure I decided to open the issue anyway.

**Comment by alex-courtis** [comment]
There are a few issues around reload right now.

It looks like you are using all defaults i.e. not `update_focused_file.enable`. That narrows things down a bit.

**Comment by alex-courtis** [comment]
I haven't had a chance to replicate however please pull latest master and re-test.

#1841 fix may be related.

**Comment by ghostbuster91** [comment]
Wow, that was fast, thanks, I will try that and let you know.

**Comment by ghostbuster91** [comment]
Tested on 9e4c39572f631bb60ee15cb9d46e1daa9927a45e, the issue still occurs.

**Comment by brandonmbanks** [comment]
I'm also experiencing this. Took me a while to figure out it was related to nvim-tree. I have disabled nvim-tree and no longer have any delay in opening a new buffer with telescope in large projects.

I also want to say thank you for this plugin. Really appreciate the effort that has gone into it.

**Comment by chomosuke** [comment]
I'm fairly certain this is the same problem that #1855 tries to fix. There has been some delay on that PR and we haven't decided on where we should put the general debounce_delay yet. I was planning to open a PR for #1836 after #1835 has been merged.

**Comment by chomosuke** [comment]
@alex-courtis No worries man! You're entitled to enjoy your holiday :).

**Comment by chomosuke** [comment]
Hi @ghostbuster91, #1871 has been merged which closes #1836. We'd be grateful if you can confirm this issue is resolved :).

**Comment by ghostbuster91** [comment]
@chomosuke Yes, the issue is no longer there. Thanks a lot!

**Comment by brandonmbanks** [comment]
Thanks so much for the help on this!
