### ISSUE TITLE
Creating an actions menu using Telescope wiki recipe

### ISSUE THREAD

**Issue by Tolomeo** [nvim-tree/nvim-tree.lua#1849]
Following comments in [362](https://github.com/nvim-tree/nvim-tree.lua/issues/362#issuecomment-1356671674), I updated the wiki with the recipe for creating a menu containing nvim-tree actions using Telescope.
You will be able to find the updates [here](https://github.com/Tolomeo/nvim-tree.lua/wiki/Recipes#creating-an-actions-menu-using-telescope).
Please let me know if that is fine.

**Comment by alex-courtis** [comment]
That's incredible! Works beautifully.

The user can easily add more context based actions e.g. file vs folder

We don't even need to use inject_node as the node is passed to a mapping callback:
`{ key = "<C-Space>", action = "tree actions", action_cb = tree_actions_menu },`

Closing #362

**Comment by alex-courtis** [comment]
No need to fork the wiki; everyone has write access and your future contributions would be most appreciated.

Copied to nvim-tree.lua wiki. Added view.mappings.list option.

Many thanks!
