### ISSUE TITLE
Issues with Modes.nvim

### ISSUE THREAD

**Issue by ryujinscales** [nvim-tree/nvim-tree.lua#1853]
### Description

I use nvim-tree.lua open on startup with the following:
```vim
require("nvim-tree").setup{
  open_on_setup = false,
  ignore_buffer_on_setup = false,
  respect_buf_cwd = true,
  renderer = {
        group_empty = false,
        highlight_git = true,
        indent_width = 2,
        indent_markers = {
          enable = true,
          inline_arrows = false,
          icons = {
            corner = "└",
            edge = "│",
            item = "│",
            bottom = "─",
            none = " ",
          },
  }},
  hijack_directories = {
        enable = true,
        auto_open = true,
  },
  view = {
    adaptive_size = false,
    width = 30,
    mappings = {
      list = {
        { key = "u", action = "dir_up" },
      },
    },
  },
}
```
I use vim-startify as my dashboard and [modes.nvim](https://github.com/mvllow/modes.nvim) for line decorations
Vim-startify is focused on startup which is fine. I go into a file and if I press `d`, technically it should highlight the line red (and then again pressing `d` should delete the line). The deleting works fine but the line highlighting doesn't happen because nvim-tree seems to be focusing vim-startify window wrongly. If I disable nvim-tree.lua to open on startup, everything works just fine. How do I fix this as this seems to be an issue with nvim-tree itself?

### Neovim version

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603
```

### Operating system and version

Windows 10

### nvim-tree version

e0cfbbb

### Minimal config

```lua
For nvim-tree:

require("nvim-tree").setup{
  open_on_setup = false,
  ignore_buffer_on_setup = false,
  respect_buf_cwd = true,
  renderer = {
        group_empty = false,
        highlight_git = true,
        indent_width = 2,
        indent_markers = {
          enable = true,
          inline_arrows = false,
          icons = {
            corner = "└",
            edge = "│",
            item = "│",
            bottom = "─",
            none = " ",
          },
  }},
  hijack_directories = {
        enable = true,
        auto_open = true,
  },
  view = {
    adaptive_size = false,
    width = 30,
    mappings = {
      list = {
        { key = "u", action = "dir_up" },
      },
    },
  },
}
```
For modes.nvim
```
require('modes').setup({
  set_cursorline = true,
  set_cursor = true
})
```
All startify config is custom things and not required here
```


### Steps to reproduce

1. Open nvim in terminal with nvim-tree.lua open on setup
2. create new buffer and type anything
3. go to normal mode
4. press `d` to delete a line
5. modes.nvim doesnt work

### Expected behavior

Modes.nvim should make a line red when `d` is pressed but doesn't because startify is not the active window (even though the cursor is in it)

### Actual behavior

Modes.nvim doesn't work unless i disable nvim-tree open on startup or do `:PlugInstall` and then quit out of that window (or any other window)

**Comment by alex-courtis** [comment]
Please provide a complete [nvt-min.lua](https://github.com/nvim-tree/nvim-tree.lua/blob/master/.github/ISSUE_TEMPLATE/nvt-min.lua) with modes installed and configured so that we may replicate.

**Comment by ryujinscales** [comment]
> Please provide a complete [nvt-min.lua](https://github.com/nvim-tree/nvim-tree.lua/blob/master/.github/ISSUE_TEMPLATE/nvt-min.lua) with modes installed and configured so that we may replicate.

I’m busy, I’ll try my best to find free time
