### ISSUE TITLE
Do not close floating nvim-tree when doing rename/move with floating `vim.ui` components

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-tree/nvim-tree.lua#1861]
**Is this a question?**
No

**Can this functionality be implemented utilising API?**
Yes for simple actions like `rename`, but other actions are more complicated to hijack (like copy/paste + rename on duplicate).

**Is your feature request related to a problem? Please describe.**
I'm giving floating nvim-tree a test, and I noticed when I try to rename a file, floating nvim-tree closes because I have floating `vim.ui` components which basically takes over the focus. I'm aware of `quit_on_focus_loss` option but that introduces other side effects that are not suiting my needs.

**Describe the solution you'd like**
I would like to keep nvim-tree opened while doing any of these actions that open up any of `vim.ui` actions.

**Describe alternatives you've considered**
Probably giving a try to set up custom handlers that uses api, but I would need to investigate further.

**Additional context**
Here's a short gif that reproduces the "issue".

![nvim-tree](https://user-images.githubusercontent.com/1782860/209536485-157a854b-76ca-4745-9629-044e3abf4b47.gif)

I'm fully aware of why this is happening and that's why I opened this as a feature request. I know by default `vim.ui` uses `input()` function which opens up the prompt through cmd line and doesn't really cause this, but I believe a lot of people are using some kind of floating input prompt via different plugins and are affected by this.

Edit: 

This is an example how can it be done for rename (taken from [here](https://github.com/nvim-tree/nvim-tree.lua/blob/d85b6718cef7f27c603cf170fb5154d90356e90b/lua/nvim-tree/actions/node/open-file.lua#L197))

```lua
    on_attach = function(bufnr)
      vim.keymap.set('n', 'r', function()
        local eventignore = vim.opt.eventignore:get()
        vim.opt.eventignore:append('WinLeave')
        require('nvim-tree.api').fs.rename()
        vim.opt.eventignore = eventignore
      end, { buffer = bufnr })
    end,
```

**Comment by kristijanhusak** [comment]
Since I'm using a custom ui implementation as a workaround I added this eventignore into my code https://github.com/kristijanhusak/neovim-config/blob/master/nvim/after/plugin/ui.lua#L84, but I'm not sure how can this be done if someone is using a 3rd party plugin.

**Comment by alex-courtis** [comment]
I think #1803 should satisfy your requirements. Please reopen / comment if that's not correct.

**Comment by xvvhang** [comment]
Same problem. @kristijanhusak But I have no idea how to keep floating window open when rename or create files.

I tried config `on_attach` for rename and create actions but it doesn't work. (I don't know if I configured it in a proper way due to my poor Lua knowledge). It seems like I need to ignore the `WinLeave` event temporarily when rename or create files?

Would you please consider adding this feature? @alex-courtis
Or anyone has ideas on how to solve the problem with configs? Really appreciate it. 👍🏼

**Comment by alex-courtis** [comment]
> Would you please consider adding this feature? @alex-courtis Or anyone has ideas on how to solve the problem with configs? Really appreciate it. 👍🏼

Yes. Floating windows are a use case that we don't always handle well.

Please open a [Feature Request](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.md&title=). Please include [clean room steps](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) to reproduce the issue as well as the desired behaviour.

As usual, [Pull Requests](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md) are gratefully appreciated.
