### ISSUE TITLE
`sync_root_with_cwd = true` not working

### ISSUE THREAD

**Issue by AlexvZyl** [nvim-tree/nvim-tree.lua#1862]
### Description

When I open a file and Neovim changes cwd, nvim-tree does not follow.

### Neovim version

```text
NVIM v0.9.0-dev-565+gd215dae0e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux archlinux 5.15.85-1-lts #1 SMP Thu, 22 Dec 2022 06:22:00 +0000 x86_64 GNU/Linux

### nvim-tree version

9e4c395

### Minimal config

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require 'nvim-tree'.setup {
    sync_root_with_cwd = true
}
```

### Steps to reproduce

1. nvim ~
2. :e ~/.config/nvim/lua/alex/init.lua
3. :NvimTreeToggle

### Expected behavior

Nvim-tree should open up to where Neovim cwd is.

### Actual behavior

Nvim-tree opens up in the home directory (where neovim was started originally).

**Comment by alex-courtis** [comment]
I'm not quite sure I understand:

`:e ~/.config/nvim/lua/alex/init.lua` won't change global or local cwd. You'd need to `cd .config/nvim/lua` for the tree to change directory.

**Comment by AlexvZyl** [comment]
Apologies for the noise, this was completely my mistake.

**Comment by alex-courtis** [comment]
No worries. You might like to try out `:help update_focused_file` for more automated changes.
