### ISSUE TITLE
Silently open a new tab

### ISSUE THREAD

**Issue by TroyCode3** [nvim-tree/nvim-tree.lua#1866]
Please add an option to open a tab (when pressing <C-t>) silently. That is, staying on the current buffer rather than jumping to new tab's buffer.

Suggestion: create a new mapping <Shift-t> to this new feature.

**Comment by alex-courtis** [comment]
To confirm:
* user presses, say, `ts` on a file
* new tab is opened
* new tab contains one window with a new buffer with the file
* new tab is not visible as the user stays on the current tab
* tree window remains focused

You should be able to do that yourself with a custom action, see `:help nvim-tree-mappings` and user's [Recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)

If you can't please reopen / comment.

**Comment by TroyCode3** [comment]
I'm pretty new to lua. Can you show me the code?

**Comment by alex-courtis** [comment]
> I'm pretty new to lua. Can you show me the code?

Take a look at the recipes linked above. [Fix tab titles when opening file in new tab](https://github.com/nvim-tree/nvim-tree.lua/pull/1868/files#diff-b5b2d1abcb86ead5a2319f7e065a7545b834a407cc9f420590d7acebb285fca9) might be a good start.

**Comment by TroyCode3** [comment]
Thank you very much! I will do that. But I do believe that it will be much helpful if this mapping is in the official code.

**Comment by alex-courtis** [comment]
> Thank you very much! I will do that. But I do believe that it will be much helpful if this mapping is in the official code.

We are no longer adding specific new functionality: https://github.com/nvim-tree/nvim-tree.lua#roadmap

nvim-tree has suffered from feature creep and will only add QOL features that cannot be achieved via API.

**Comment by TroyCode3** [comment]
If not, can you please provide the config? I believe this feature is super useful for many users.

**Comment by alex-courtis** [comment]
Here's a quick implementation. You might need to tweak it a bit to better suit your needs.

```lua
local function open_tab_silent()
  local api = require("nvim-tree.api")

  api.node.open.tab()

  vim.cmd.tabprev()
end
---
      mappings = {
        list = {
          { key = "ts", action = "open_tab_silent", action_cb = open_tab_silent },
```

**Comment by TroyCode3** [comment]
Thank you so much!

**Comment by TroyCode3** [comment]
Somehow, the mapping doesn't work at all. I've copied and pasted your code, but it doesn't work.

**Comment by alex-courtis** [comment]
Glad to hear this worked.

Could you please add your final solution to the [Recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes) page?

I don't think the draft works very well around multiple tabs...
