### ISSUE TITLE
NvimTreeFindFile! doesn't update the tree's root when the tree is open

### ISSUE THREAD

**Issue by TroySigX** [nvim-tree/nvim-tree.lua#1873]
### Description

If the tree is closed before the command NvimTreeFindFile! is called, it works perfectly (goes to the current buffer's directory and update the tree's root to the dir). But if the tree is still open, that same command will only goes to the buffer's directory but not update the tree's root.

### Neovim version

```text
NVIM v0.8.2
```

### Operating system and version

Linux 6.1.1-arch1-1

### nvim-tree version

e322fbb

### Minimal config

```lua
require("nvim-tree").setup()
```

### Steps to reproduce

1. Open some file
2. Open nvim-tree
3. Go up some dir in tree (enter .. node at the top of the tree)
4. Go to that file (probably <C-l>)
5. :NvimTreeFindFile!

### Expected behavior

It is expected to also update the tree root

### Actual behavior

The cursor points to the buffer's dir but doesn't update the tree root.

**Comment by alex-courtis** [comment]
> doesn't update the tree root

Confirmed. The tree root is only updated when the file is not within the tree and not within vim's cwd.

That command is a little ambiguous. It sounds like it should change to the exact directory containing the file.

How would you expect it to work when `update_focused_file.update_root` is set? What about `prefer_startup_root`?

`prefer_startup_root` and `sync_root_with_cwd` will need to be sanity tested.

**Comment by TroyCode3** [comment]
I would expect it to update the root., but in fact, it doesn't.

**Comment by mario-amazing** [comment]
:NvimTreeFindFile not working if a tree is already opened
@alex-courtis, could you check? should I open a new bug?

**Comment by alex-courtis** [comment]
> :NvimTreeFindFile not working if a tree is already opened
> @alex-courtis, could you check? should I open a new bug?

That should be resolved by #2078

Please reply / comment if that's not the case.
