### ISSUE TITLE
Startup Autocommands

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1893]
It is necessary for the user to determine the loaded/setup status of nvim-tree. See https://github.com/nvim-tree/nvim-tree.lua/issues/1869#issuecomment-1369322729 for use case.

1. au for nvim-tree required
2. au for nvim-tree setup
3. `require("nvim-tree").is_setup()`

3 is not strictly necessary due to `Event.Ready` however is cheap and may be useful.

/cc @mrjones2014

**Comment by alex-courtis** [comment]
@mrjones2014 please review #1910

I've not added an `is_started` "API" as I'm struggling to see a use case: for those interested in startup the two aus should be sufficient. Happy to add it...

**Comment by mrjones2014** [comment]
> I'm struggling to see a use case

If nvim-tree loads before  legendary.nvim then I won't get the autocmd. Could you just set something like `vim.g.nvim_tree_attached = true`?

**Comment by mrjones2014** [comment]
This otherwise looks good. But I need a way to tell if the autocmds have already happened before I try to attach to them.

**Comment by alex-courtis** [comment]
> > I'm struggling to see a use case
> 
> If nvim-tree loads before legendary.nvim then I won't get the autocmd. Could you just set something like `vim.g.nvim_tree_attached = true`?

That makes good sense. I was thinking in terms of lua methods which did not feel right.

vim.g pairs well with each autocommand. They are outside of regular lua plugin operations which is necessary for this case.

Perhaps other lua plugins should do this. Perhaps some do already.

**Comment by alex-courtis** [comment]
Added #1912

**Comment by mrjones2014** [comment]
> Perhaps other lua plugins should do this. Perhaps some do already.

Many plugins use this pattern. Often in a `plugin/plugin_name.lua` file you’ll see something like 

```lua
if vim.g.plugin_name_loaded == true then
  return
end

vim.g.plugin_name_loaded = true
```

**Comment by alex-courtis** [comment]
:+1: merging
