### ISSUE TITLE
Reuse Buffer

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1895]
nvim-tree buffer will be wiped on window close as `bufhidden=wipe`

One buffer exists per tab:
name `"NvimTree_" .. vim.api.nvim_get_current_tabpage()`
`buftype=nofile`
`filetype=NvimTree`

The buffer could be reused when nvim-tree is reopened.

Context: https://github.com/nvim-tree/nvim-tree.lua/issues/1858#issuecomment-1370335847

**Comment by hinell** [comment]
Would also be cool to make a configurable synchronization of currently focused file across different `nvim-tree` buffers.

**Comment by alex-courtis** [comment]
That's a larger issue #457

**Comment by asmodeus812** [comment]
@alex-courtis is there any update on that, i think i am facing an issue related to that feature. When i have a second tab open with a buffer loaded (actual file), if i do :e {dir} and select file the tree closes, the tab closes and i am brought back to the first tab (prev tab)

**Comment by gegoune** [comment]
Does `api.node.open.replace_tree_buffer` do what you are after (mapped to `<C-e>` by default)?

**Comment by asmodeus812** [comment]
@gegoune indeed, is it safe to replace the default <CR> "edit" action with that one by default, what are the differences and possible implications ? Thanks !

**Comment by gegoune** [comment]
I can't think of downsides to any of these. You can override default mappings however you like.

**Comment by alex-courtis** [comment]
The original motivation for this enhancement is no longer valid following the change to legendary to use the new API `nvim-tree.api.config.mappings.get_keymap()`

Please report your findings @asmodeus812 ; I'll close this one if the above solution meets your needs.

**Comment by alex-courtis** [comment]
Let's track this at https://github.com/nvim-tree/nvim-tree.lua/issues/457

**Comment by alex-courtis** [comment]
Tracking at
- #2255
