### ISSUE TITLE
Jumping to commonly used folders

### ISSUE THREAD

**Issue by matu3ba** [nvim-tree/nvim-tree.lua#190]
1. I have a project with an annoyingly long tree for files due to cmake invoking an external project with nested files.
I would like to mark certain folders for fast jumping, for which I currently use shell aliases and new neovim instances.

What would you suggest to use for that? How should this be implemented in nvim-tree.lua and where would you suggest I start?

2. How should be interaction with nvim-tree be designed, ie when I want to create commands/shortcuts, like for jumping to the git root folder?

**Comment by kyazdani42** [comment]
Hi,
in the populate.lua file, you could tag nodes for jumping. Or create a jumplist of node references with a cursor. Then you could bind keybindings on `au Filetype` but this is a little clunky and should be addressed in a refactoring (basically, mappings are done the reversed way, and don't allow to easily modify keymaps).

**Comment by alex-courtis** [comment]
See WIP #612

**Comment by kyazdani42** [comment]
The PR should be rewritten, it has too many conflicts now. I think the API could be a bit better too

**Comment by alex-courtis** [comment]
Bookmarks feature has been implemented.

See `:help nvim-tree-bookmarks`
