### ISSUE TITLE
Calling open_replacing_current_buffer doesn't replace buffers not associated to files

### ISSUE THREAD

**Issue by rosds** [nvim-tree/nvim-tree.lua#1914]
### Description

When calling nvim without a file path and immediately calling `require 'nvim-tree'.open_replacing_current_buffer()` does not open `nvim-tree` in the current working directory. This also happens on empty new buffers like inside a `:e foobar`.

This is not necessary a bug, its the behavior I was expecting.

The workaround I'm using is to simply check after the call to `open_replacing_current_buffer` made the tree visible:

```lua
...
            tree.open_replacing_current_buffer()

            if not view.is_visible() then
                local win = vim.api.nvim_get_current_win()
                tree.open()
                vim.w.open_replacing_current_buffer = true
                vim.api.nvim_win_close(win, true)
            end
```

### Neovim version

```text
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 20.04.5 LTS

### nvim-tree version

3ce0a8e770f70a135ef969e0a640bd8d05baf42c

### Minimal config

```lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  nvim_tree = 'https://github.com/nvim-tree/nvim-tree.lua'
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('nvim-tree').setup{}
```

### Steps to reproduce

1. nvim --clean -u /tmp/nvt-min.lua
2. :lua require'nvim-tree'.open_replacing_current_buffer()

### Expected behavior

I'd expect `tree.open_replacing_current_buffer()` to always open `nvim-tree` even in buffers not associated to existing files.

### Actual behavior

`nvim-tree` is not opened on buffers not associated to files.

**Comment by alex-courtis** [comment]
`open_replacing_current_buffer` is quite legacy functionality that predates the API.

Unfortunately we don't have an equivalent API method: `api.tree.open` and `toggle` will always open a new left/right/float window. Raised #1918

In the meantime I'm happy for you to raise a PR. This is a bug in that it doesn't quite follow the (mostly undocmented) behaviour that can be reasonably expected.

**Comment by alex-courtis** [comment]
@rosds I'd be grateful if you could test:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout api-open-in-current-window
```

See `:help nvim-tree.api.tree.open()`

**Comment by rosds** [comment]
@alex-courtis looks pretty good! also the docs are nice. :+1:
