### ISSUE TITLE
Allow forward slash on Windows

### ISSUE THREAD

**Issue by LogicNg** [nvim-tree/nvim-tree.lua#1920]
On Windows machines, when creating a new folder, the prompt gives `C:\whatever\`, I have to type `C:\whatever\new\` but not `C:\whatever/new`, otherwise nvim-tree will return this error.

```
E5108: Error executing lua: ...d\nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:17: bad argument #1 to 'fs_close' (number expected, got nil)
stack traceback:
	[C]: in function 'fs_close'
	...d\nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:17: in function 'create_and_notify'
	...d\nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:32: in function 'create_file'
	...d\nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:94: in function 'on_confirm'
	C:\Program Files\Neovim\share\nvim\runtime/lua/vim/ui.lua:93: in function 'input'
	...d\nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:66: in function 'handle_tree_actions'
	...plugged\nvim-tree.lua/lua/nvim-tree/actions/dispatch.lua:123: in function 'dispatch'
	...ata\plugged\nvim-tree.lua/lua/nvim-tree/actions/init.lua:273: in function <...ata\plugged\nvim-tree.lua/lua/nvim-tree/actions/init.lua:272>
```
Is it possible for nvim-tree to parse `\` to `/` automatically, just like nerd-tree?

**Comment by alex-courtis** [comment]
This is very specific functionality that doesn't belong in nvim-tree.

You can, however, build this functionality yourself:
```lua
  local function my_create_cb(node)
    local api = require("nvim-tree.api")

    vim.ui.input({ prompt = "Create file: ", default = node.absolute_path }, function(my_file_path)

      -- TODO sanitise your slashes here

      -- create the file
      local ok, fd = pcall(vim.loop.fs_open, my_file_path, "w", 420)
      if not ok then
        vim.notify.error("Couldn't create file " .. my_file_path)
        return
      end
      vim.loop.fs_close(fd)

      -- open the node if it's a directory
      if node.type == "directory" then
        api.node.open.edit(node)
      end
    end)
  end
```

```lua
      mappings = {
        list = {
          { key = "A", action = "my_create", action_cb = my_create_cb, },
```

**Comment by alex-courtis** [comment]
However, there might be a more pragmatic solution:

What is your prompt? Is it `C:\whatever/` ?

**Comment by LogicNg** [comment]
It's `C:\whatever\`.

The main reason I suggest this feature is that `/` is easier to type. I don't have to stretch my pinky to `\` every time I create a new folder. I guess many Windows users are also bothered by that.

**Comment by alex-courtis** [comment]
Sorry mate, that's a very niche use case and nvim-tree doesn't need that complexity.

Vim doesn't allow forward slashes when, say, `:w` or `:e`.

**Comment by sewbacca** [comment]
> Sorry mate, that's a very niche use case and nvim-tree doesn't need that complexity.
> 
> Vim doesn't allow forward slashes when, say, `:w` or `:e`.

This is not true, if `vim.opt.shellslash` is set to `true`. With that option, `:w` and `:e` accept forward slashes.
