### ISSUE TITLE
Add option to not rendering specific git icon if the icon is explicitly not provided

### ISSUE THREAD

**Issue by alex35mil** [nvim-tree/nvim-tree.lua#1923]
**Is this a question?**
It is not.

**Can this functionality be implemented utilising API?**
AFAICT it's not possible with the current API.

**Is your feature request related to a problem? Please describe.**
I'm trying to hide some specific git icons in the tree, but looks like it is not possible.

```lua
git = {
    unstaged = "", -- renders empty clolumn
    unmerged = nil, -- renders default icon
    untracked = false, -- raises
}
```

**Describe the solution you'd like**
Don't render anything if the icon value is _not an icon_.

**Describe alternatives you've considered**
_none_

**Additional context**
_none_

**Comment by gegoune** [comment]
What is that you expect to happen exactly? You want to achieve "dont render anything", but setting `""` "renders empty column", isn't it what you want?

How about `nvim-tree.renderer.icons.glyphs.git.unstaged=" "`?

**Comment by alex35mil** [comment]
@gegoune In the case of empty string, it looks like this:

```
✓ staged.file
✓ staged.file
✓  staged.file.with.empty.column
✓ staged.file
```

I want to get rid of this space before `staged.file.with.empty.column` entry.

**Comment by gegoune** [comment]
`vim-tree.renderer.icons.glyphs.git.unstaged=""` removes the icon for me and does not render anything at all.

<img width="228" alt="nt" src="https://user-images.githubusercontent.com/69750637/213144034-6904ed75-98cf-4b2a-a1cb-366c37c1eff7.png">

`nvim-surround.lua` has staged changes
`nvim-tree.lua` has unstaged changes

**Comment by alex35mil** [comment]
@gegoune Could it be that this ghost space appears only when there is one icon with actual value rendered, but there is also another one applied with the icon set to an empty string?

**Comment by alex35mil** [comment]
@gegoune Reproduced:
<img width="177" alt="Screenshot 2023-01-18 at 14 34 24" src="https://user-images.githubusercontent.com/4244251/213149488-0c96760a-4f00-4c8a-b919-037774640fe9.png">

**Comment by alex35mil** [comment]
Config:

```
git = {
    staged = "✓",
    deleted = "",
    renamed = "➜",
    unstaged = "",
    unmerged = "",
    untracked = "",
    ignored = "",
},
```

Statuses:
<img width="166" alt="Screenshot 2023-01-18 at 14 46 01" src="https://user-images.githubusercontent.com/4244251/213151878-d06f8bc9-5987-497d-bc68-2a1f26050111.png">

**Comment by alex-courtis** [comment]
This might be a double width character issue. nvim lua isn't great at detecting and handling such cases.

Possible hacky workaround: find an empty or space double width character.

**Comment by alex-courtis** [comment]
It looks like it's actually a padding issue: when there are multiple git icons, `icons.padding` is inserted in between.

This is fine for files that are just unstaged `"✓"`
It's a problem when it's staged and unstaged `"✓" .. " " .. ""`

**Comment by alex-courtis** [comment]
@alex35mil I would be most grateful if you tested this fix:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1923-allow-empty-git-icons
```

**Comment by alex35mil** [comment]
@alex-courtis Sorry, my GH notifications are messed up. I just updated the plugin, and now the tree looks like this:

<img width="287" alt="Screenshot 2023-02-08 at 15 31 02" src="https://user-images.githubusercontent.com/4244251/217518352-31285d46-8438-4ee2-b59e-b247ba62e989.png">

**Comment by alex-courtis** [comment]
Please test fix:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1923-allow-empty-git-icons-2
```

**Comment by alex-courtis** [comment]
@alex35mil

**Comment by alex35mil** [comment]
@alex-courtis Looks like it works now, thanks!

<img width="224" alt="image" src="https://user-images.githubusercontent.com/4244251/218305435-92f222dc-391c-4c76-8ca3-3016245f0802.png">

P.S. `comment1.lua` is not colorized, even though it is staged, but it is probably another issue.

**Comment by alex-courtis** [comment]
> P.S. `comment1.lua` is not colorized, even though it is staged, but it is probably another issue.

Ensure that you have `renderer.highlight_git` set.

Also check `:hi NvimTreeFileStaged`. There might be another plugin like mini.base16 that is changing that.
