### ISSUE TITLE
An "unknown option" warning is reported, but values are required for tree to render as desired

### ISSUE THREAD

**Issue by ctrlplusb** [nvim-tree/nvim-tree.lua#1937]
### Description

I am creating a floating tree, and have some code to help me centre it and make it take up a portion of the available width/height;

```lua
      local gheight = vim.api.nvim_list_uis()[1].height
      local gwidth = vim.api.nvim_list_uis()[1].width
      local width = 90
      local height = math.floor(gheight * 0.9)

      require("nvim-tree").setup({
        sort_by = "case_sensitive",
        open_on_setup = false,
        open_on_setup_file = false,
        hijack_directories = {
          enable = false,
        },
        update_focused_file = {
          enable = true,
          update_cwd = false,
        },
        view = {
          adaptive_size = false,
          hide_root_folder = true,
          -- when i include these options i get the warnings printed
          -- but if i don't include them it doesn't render correctly
          -- 👇
          width = width,
          height = height,
          -- 👆
          float = {
            enable = true,
            open_win_config = {
              relative = "editor",
              width = width,
              height = height,
              row = (gheight - height) * 0.4,
              col = (gwidth - width) * 0.5,
              border = "rounded",
            },
          },
        },
```

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.6.1

### nvim-tree version

master, 16f2806

### Steps to reproduce

1. `:NvimTreeOpen`
2. See warning printed

### Expected behavior

Warning message should not be printed.

_or_ 

I should be able to just provide `view.float.open_win_config.width` and `view.float.open_win_config.height`, with the float having the correct dimensions.

**Comment by alex-courtis** [comment]
Your `row` and `col` values will be fixed at the time of setup; maybe zero?

You can set `open_win_config` to a function which dynamically calculates the entire nvim_open_win config and returns it as a table.

**Comment by alex-courtis** [comment]
Please reopen / comment if that doesn't work for you.
