### ISSUE TITLE
The nightly tag is causing vim-plug errors

### ISSUE THREAD

**Issue by reegnz** [nvim-tree/nvim-tree.lua#1944]
### Description

When updating the plugin with vim-plug I'm seeing this message every time I upgrade:

```
x nvim-tree.lua:
    From https://github.com/kyazdani42/nvim-tree.lua
     ! [rejected]        nightly    -> nightly  (would clobber existing tag)
```
Otherwise the master branch upgrades fine, it's just somewhat annoying to see this message.

I think the core issue is that the nightly build is re-tagging the repo, which goes against the basic git principle of tags being immutable. Switching over to a `nightly` branch instead, and merging into it every night should work better, as branch refs are meant to be mutable with git.

### Neovim version

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 13.1 22C65 x86_64

### nvim-tree version

f8489c9

### Minimal config

```lua
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . '  --create-dirs 
      \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  augroup install
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  augroup END
endif
unlet autoload_plug_path


call plug#begin()
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.vim
2. :PlugInstall
3. :PlugUpdate

### Expected behavior

When updating the plugin, this shows:
```
- nvim-tree.lua: Already up to date.
```

### Actual behavior

When updating the plugin, this shows:
```
x nvim-tree.lua:
    From https://github.com/kyazdani42/nvim-tree.lua
     ! [rejected]        nightly    -> nightly  (would clobber existing tag)
```

**Comment by gegoune** [comment]
There was a little force push incident short while ago. You can manually pull latest changes with rebase, or completely remove plugin and install it again. 

Apologies for any inconvenience caused.

**Comment by alex-courtis** [comment]
> Switching over to a `nightly` branch instead, and merging into it every night should work better, as branch refs are meant to be mutable with git.

Release versions / branches are a work in progress.

**Comment by alex-courtis** [comment]
Release and versioning strategy tracked elsewhere.
