### ISSUE TITLE
When I open a buffer in nvimtree, the root dir of nvimtree expands to become $home

### ISSUE THREAD

**Issue by dnxxymcj** [nvim-tree/nvim-tree.lua#1953]
### Description

When I open a buffer in nvimtree, the root dir of nvimtree expands to become $home

### Neovim version

```text
NVIM v0.9.0-dev-756+g0481f04ec-dirty
```

### Operating system and version

macOS 13.1

### nvim-tree version

branch master         commit e8a89db

### Minimal config

```lua
lvim.builtin.nvimtree = {
    active = true,
    on_config_done = nil,
    setup = {
      auto_reload_on_write = false,
      disable_netrw = false,
      hijack_cursor = false,
      hijack_netrw = true,
      hijack_unnamed_buffer_when_opening = false,
      ignore_buffer_on_setup = false,
      open_on_setup = false,
      open_on_setup_file = false,
      sort_by = "name",
      root_dirs = {},
      prefer_startup_root = false,
      sync_root_with_cwd = true,
      reload_on_bufenter = false,
      respect_buf_cwd = false,
      on_attach = "disable",
      remove_keymaps = false,
      select_prompts = false,
```

### Steps to reproduce

1.  `lvim .` in $HOME/.config/lvim 
2.  `<leader> e`  open the nvimtree
3. select a file and open it 
4. nvimtree is expanded

https://user-images.githubusercontent.com/7660888/215328930-08495d3f-c22e-496e-87e5-e92b4e214820.mov

**Comment by gegoune** [comment]
Sorry, but that isn't minimal reproducible configuration. Please check if issue exists without using any distributions.

**Comment by alex-courtis** [comment]
That's quite odd: when you first do something with `config.lua` it opens a new tree in a new window. What are you doing to make that happen? Maybe `<CR>` or `o`?

A minimal configuration to demonstrate the issue would be gratefully appreciated. Lunarvim is very complex and not something we can easily diagnose. See minimal config nvt-min.lua in the [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) template.

**Comment by dnxxymcj** [comment]
Sorry, it was my mistake. I reinstalled my OS, thanks!
