### ISSUE TITLE
nvim-tree doesn't open on directories

### ISSUE THREAD

**Issue by kiyoon** [nvim-tree/nvim-tree.lua#1956]
### Description

`nvim .` doesn't open nvim-tree anymore.

### Neovim version

```text
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/__w/neovim/neovim/.deps/usr/include -I/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include
Compiled by root@4ae72dcad031

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 22.04, macOS

### nvim-tree version

215b29bfad74518442621b9d0483a621483b066b

### Minimal config

```lua
-- Neovim init.lua
-- nvim-tree recommends disabling netrw, VIM's built-in file explorer
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

-- Remove the white status bar below
vim.o.laststatus = 0

-- lazy.nvim plugin manager
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
  "nvim-tree/nvim-web-devicons",
  {
    "nvim-tree/nvim-tree.lua",
    config = function()
      local nvim_tree = require "nvim-tree"

      nvim_tree.setup()
    end,
  },
}
```

### Steps to reproduce

1. `nvim -u /tmp/nvt-min.lua .`

### Expected behavior

Nvim-tree should open

### Actual behavior

A normal buffer is opened

**Comment by alex-courtis** [comment]
Unfortunately we have had to retire the "open at startup" behaviour as it was unreliable and problematic. It has been replaced via self-serve mechanisms: [Open At Startup](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup)

I've added a recipe for your use case: [Open For Directories And Change Neovim's Directory - Current Window](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup#open-for-directories-and-change-neovims-directory)

Apologies; as you are using the default configuration you did not receive the startup message informing you of this change.

**Comment by kiyoon** [comment]
Thank you, it worked!

By the way, if I don't want to configure it in `init.lua` but want to launch using the command line, is there a way to do it?  
`nvim . +NvimTreeOpen` will open as a side bar but I want to open it in full window.

**Comment by alex-courtis** [comment]
Try `vi +"lua require('nvim-tree.api').tree.open({current_window = true})"`

The commands do not have the full functionality of the API.

**Comment by kiyoon** [comment]
Thank you for your help 😊
