### ISSUE TITLE
NvimTree no longer opens automatically when starting neovim at a directory

### ISSUE THREAD

**Issue by tjex** [nvim-tree/nvim-tree.lua#1965]
### Description

I just updated Neovim and NvimTree and now when starting neovim at a directory, the tree starts in it's closed state.
Before it would always start in it's open state, when starting neovim at a directory.

I've been having a look at the recent commit history, and there's been a lot of editing going on with the `.open()` / `.toggle()` commands. So I'm wondering if something has gone funky.

But could well be because of 0.8.3, which got released 7 hours ago... classic 😅

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

### Operating system and version

macOS 12.6.1

### nvim-tree version

215b29b

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua ./
2. thats it... by my understanding, NvimTree should open automatically by default?

### Expected behavior

NvimTree opens it's tree automatically (magically by default) when starting neovim at a directory (as opposed to opening a file).

### Actual behavior

NvimTree (the actual sidebar tree) does not open. I only see the editing window. I tried to add some text and save the buffer as if it was a file, and I got the error message `./ is a directory`, confirming I had opened NvimTree at a directory and not a file / it thinks it's been opened at a file. 

<img width="1512" alt="Screen Shot 2023-02-02 at 21 53 05" src="https://user-images.githubusercontent.com/83029642/216446948-00170758-b7cd-45a1-b2d3-544257cb150f.png">

<img width="1512" alt="Screen Shot 2023-02-02 at 21 53 47" src="https://user-images.githubusercontent.com/83029642/216447082-a4036a9b-2cea-4e68-8faf-346219401249.png">

**Comment by lavabyrd** [comment]
I believe this is caused by https://github.com/nvim-tree/nvim-tree.lua/issues/1669#issue-1412350174 

you need to use the Open at Startup instead https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup

**Comment by tjex** [comment]
ah nice, thanks!
