### ISSUE TITLE
backwards compatibility issues post commit 1b13a49f913b58a5f1792ea81c13947a7988db8e 

### ISSUE THREAD

**Issue by leoentersthevoid** [nvim-tree/nvim-tree.lua#1967]
### Description

With commit 1b13a49f913b58a5f1792ea81c13947a7988db8e, nvim tree opened up the file explorer with the asked path. eg: 
Suppose we're in `/tmp`. If I would `nvim ~/path/to/something' it opened up the explorer with that directory focusd: 
![image](https://user-images.githubusercontent.com/62313634/216555879-723e325e-0dab-4289-b127-fb9e67e9594d.png)

With the latest updates (215b29bfad74518442621b9d0483a621483b066b), the explorer remains stuck in `/tmp` and the file explorer is no longer triggered: 
![image](https://user-images.githubusercontent.com/62313634/216556158-a0801b2b-125e-4301-9f52-9aaeafc05a09.png)

I've seen some variables were changed during the process, such as `update_focused_file.update_cwd` -> `update_focused_file.update_root`, however, I couldn't make it working with this change only. 

### Neovim version

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az190-151
features: +acl +iconv +tui
```

### Operating system and version

Ubuntu 20.04.5 LTS x86_64 

### nvim-tree version

215b29bfad74518442621b9d0483a621483b066b

### Minimal config

```lua
local status_ok, nvim_tree = pcall(require, "nvim-tree")
if not status_ok then
  return
end

local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
if not config_status_ok then
  return
end

local tree_cb = nvim_tree_config.nvim_tree_callback

nvim_tree.setup {
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
  renderer = {
    root_folder_modifier = ":t",
    icons = {
      glyphs = {
        default = "",
        symlink = "",
        folder = {
          arrow_open = "",
          arrow_closed = "",
          default = "",
          open = "",
          empty = "",
          empty_open = "",
          symlink = "",
          symlink_open = "",
        },
        git = {
          unstaged = "",
          staged = "S",
          unmerged = "",
          renamed = "➜",
          untracked = "U",
          deleted = "",
          ignored = "◌",
        },
      },
    },
  },
  diagnostics = {
    enable = true,
    show_on_dirs = true,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
  },
  view = {
    width = 30,
    side = "left",
    mappings = {
      list = {
        { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
        { key = "h", cb = tree_cb "close_node" },
        { key = "v", cb = tree_cb "vsplit" },
      },
    },
  },
}
```

### Steps to reproduce

```
cd /somewhere 
nvim ~/path/to/some/folder
```

**Comment by gegoune** [comment]
Please see https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup.

**Comment by leoentersthevoid** [comment]
@gegoune, thank you!

**Comment by gegoune** [comment]
You are very welcome. Do you think that breaking change could have been announced better? We would like to make sure all changes that are as disruptive to users as that one was are properly communicated. How could we improve?

**Comment by leoentersthevoid** [comment]
I can't talk for everyone, but personally it would definitely be helpful if you mention important changes first thing in the README, together with some support material to accomodate the new changes (as you did above).

**Comment by alex-courtis** [comment]
> I can't talk for everyone, but personally it would definitely be helpful if you mention important changes first thing in the README, together with some support material to accomodate the new changes (as you did above).

Unfortunately you "slipped through the cracks" here: there is a startup message with a wiki link only for users that have configured any of the open on setup options, which you are not using.

The pinned issue detailing this change is clearly not enough.

**Comment by leoentersthevoid** [comment]
It wasn't used it explicitly, true; it might have been because it was (I suppose) default behavior prior to these changes? For what matters, that was clearly the issue in my case, which I managed to fix with the link provided by @gegoune.

**Comment by alex-courtis** [comment]
> It wasn't used explicitly, true; it might have been because it was (I suppose) default behavior prior to these changes? For what matters, that was clearly the issue in my case, which I managed to fix with the link provided by @gegoune.

That is correct. It is default config ( i.e. `hijack_directories.enable = true` ) behaviour that changed in a breaking manner.

I cannot conceive of a means to notify the user in this case. Adding a note to the README.

**Comment by leoentersthevoid** [comment]
I'm glad I was able to help! Thank you for your work!
