### ISSUE TITLE
Doesn't open directory in nvim-tree when using lazy.nvim?

### ISSUE THREAD

**Issue by Ciel-MC** [nvim-tree/nvim-tree.lua#1973]
I recently migrated from Packer to lazy.nvim, but now when I launch nvim in a directory(e.g. `nvim ~/.config/nvim`), it opens the directory as a blank buffer, like this:
![image](https://user-images.githubusercontent.com/47144701/216829763-30fc2415-ebbc-40af-ab12-ed4bbb841e0a.png)

If I switch to the only buffer available in telescope, the file explorer opens normally.
This behavior only seems to happen when I switched to lazy.nvim(even though I have nvim-tree as `lazy = false`)

NVIM v0.9.0-dev-874+g5c4b503d3c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Linux 6.1.9-arch1-1

**Comment by mmk-1** [comment]
Hello, I had the exact same problem after I migrated to Lazy. I don't know what causes this issue but the solution is to configure nvim-tree to open on startup. Recently they have introduced a new way to do this which you could find here: [https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup](url)
This fixed the issue for me.

**Comment by gegoune** [comment]
Changing plugin manager must have coincided with that breaking change being introduced. Link above is the answer. Thanks!

**Comment by alex-courtis** [comment]
Lazy loading was extremely problematic with the old open on setup behaviour and the "straw that broke the camel's back".
