### ISSUE TITLE
File system watcher throws error when opening git repo with $GIT_DIR set

### ISSUE THREAD

**Issue by austin5627** [nvim-tree/nvim-tree.lua#1976]
### Description

When opening nvim in a git repo with `$GIT_DIR` set to something other than `.git` nvim-tree throws the error `[NvimTree] "Could not start the fs_event watcher for path <path_to_repo>/.git : ENOENT"`

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.1.9-arch1-1

### nvim-tree version

02fdc26

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. Make a git repo with `GIT_DIR=test git init`
2. Open nvim with `GIT_DIR=test GIT_WORK_TREE=. nvim`
3. Open NvimTree

**Comment by alex-courtis** [comment]
Confirmed. That has been hardcoded.

We should use `git -C /path/to/repo rev-parse --absolute-git-dir`

**Comment by mangelozzi** [comment]
Experiencing the same thing

**Comment by alex-courtis** [comment]
Any updates on this one @dmehala ?

**Comment by alex-courtis** [comment]
> I am going to work on it today smiley sorry for the delay.

No worries... there's no hurry.

**Comment by ninjaaaaah** [comment]
Hi, I'm having the same error. However, I'm running on Windows Terminal. 

Is this also the reason why Git Icons are not working despite them being enabled on nvim-tree config?

**Comment by dmehala** [comment]
> Is this also the reason why Git Icons are not working despite them being enabled on nvim-tree config?

No, you may need to install a [Nerd Font](https://github.com/ryanoasis/nerd-fonts) and configure Windows Terminal to use that font.

**Comment by ninjaaaaah** [comment]
> > Is this also the reason why Git Icons are not working despite them being enabled on nvim-tree config?
> 
> No, you may need to install a [Nerd Font](https://github.com/ryanoasis/nerd-fonts) and configure Windows Terminal to use it.

I'm already using a Nerd Font but the Git icons still don't show up. Other icons seem to be working fine though.

**Comment by alex-courtis** [comment]
> I'm already using a Nerd Font but the Git icons still don't show up. Other icons seem to be working fine though.
> 
> Also, the error also only shows up when I enable git in the config.

Please raise a [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a sample repository that demonstrates this problem.
