### ISSUE TITLE
NvimTree changes root in the other tab after it is reopened

### ISSUE THREAD

**Issue by carljohnson93** [nvim-tree/nvim-tree.lua#1978]
### Description

When nvim-tree is opened in one tab, then in the other and I change directory with `<c-]>` there, then go back to previous tab and reopen nvim-tree it loads the directory which I `cd`ed into from the other tab.

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Artix Linux latest release, also tested on macOS 10.15.7

### nvim-tree version

02fdc262eba188198a7deb2117b3b996e6763d65

### Minimal config

```lua
vim.cmd[[
call plug#begin()

Plug 'nvim-tree/nvim-tree.lua'

call plug#begin()
]]

require('nvim-tree').setup()
```

### Steps to reproduce

1. nvim
2. :NvimTreeToggle
3. :tabnew
4. :NvimTreeToggle
5. cd into any directory with `<c-]>`
6. :tabprev
7. :NvimTreeToggle
8. :NvimTreeToggle

### Expected behavior

Expected for nvim tree to reopen its window and load same directory I was in just before closing it in this tab

### Actual behavior

nvim-tree loads the last opened directory, in this case the one we `cd`ed into from the other tab

**Comment by alex-courtis** [comment]
See #1960

**Comment by alex-courtis** [comment]
Tracked at #457

**Comment by alex-courtis** [comment]
Tracking at
- #2255
