### ISSUE TITLE
Only default glyphs are being used

### ISSUE THREAD

**Issue by Victoriam7** [nvim-tree/nvim-tree.lua#1979]
### Description

When installing on a new system, I noticed that the devicons are not showing. Instead nvim-tree uses the default set of icons. For example all .lua files show as if they were a plain text file

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```

### Operating system and version

Arch Linux ARM aarch64

### nvim-tree version

02fdc26

### Minimal config

```lua
require"nvim-tree".setup({})
```

### Steps to reproduce

1, Open nvim
2. open nvim-tree
3. observe icons are incorrect

### Expected behavior

.lua files will have lua icon next to them

### Actual behavior

.lua files have the default file icon next to them

**Comment by alex-courtis** [comment]
Are you using `nvim-tree/nvim-web-devicons`? https://github.com/nvim-tree/nvim-tree.lua#install

See [Troubleshooting - Icons Not Correctly Shown](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#icons-not-correctly-shown) for assistance setting up fonts.

**Comment by Victoriam7** [comment]
I have it installed. Oddly enough, it started working on an x86 computer I have, but still not the arm. There is no difference between the configurations at least within nvim

**Comment by alex-courtis** [comment]
Let's check if your terminal can render the icons:

```sh
cd /path/to/nvim-web-devicons
cat lua/nvim-web-devicons.lua | grep "^    icon ="
```

**Comment by Victoriam7** [comment]
I don’t have access to the machine at the moment but I do know that the glyphs can render. I tested it by manually copying them into the terminal

**Comment by alex-courtis** [comment]
Please fully test the terminals on both machines. Please also `:help nvim-tree-introduction` and check that the folder icon is visible.

This appears to be a configuration issue. Please ensure nvim, terminal, font versions match and attempt to replicate with an [nvt-min.lua](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml)

**Comment by theyashpatel** [comment]
I do see the folder icon in help. I am having the same issue. I am not being able to change the folder and arrow icons.

**Comment by alex-courtis** [comment]
> I do see the folder icon in help. I am having the same issue. I am not being able to change the folder and arrow icons.

Are you using `renderer.icons.glyphs.folder.default` `.empty` `.open` and `.empty_open` to set the icons?

Please enable https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#diagnostic-logging with
```lua
log = {
  enable = true,
  truncate = true,
  types = {
    config = true,
  },
},
```

We can check whether your changes are being applied.

**Comment by alex-courtis** [comment]
Great news!
