### ISSUE TITLE
`full_rename` to create dirs as required

### ISSUE THREAD

**Issue by mangelozzi** [nvim-tree/nvim-tree.lua#1982]
`NerdTree` move command is very user friendly for moving files around. The closest I have found in NerdTree is `full_rename`, however say you try to move file to a dir , and that dir does not exist yet, it just gives an error.

**Describe the solution you'd like**
Maybe a move command that creates parents dirs as required, or that functionality to be added to `full_name`. Something like `mkdir -p`

**Describe alternatives you've considered**
```
`r`               rename              rename a file
`<C-r>`           full_rename         rename a file and omit the filename on input
`e`               rename_basename     rename a file with filename-modifiers ':t:r' without changing extension
```

**Comment by alex-courtis** [comment]
Create has this functionality, rename should have feature parity.

**Comment by alex-courtis** [comment]
See #1818

**Comment by alex-courtis** [comment]
`full_rename` is gone, however we can cover this use case in the above.
