### ISSUE TITLE
Topleftest Window Not Picked When `actions.open_file.window_picker.enable` false

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#1985]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/1983

<div type='discussions-op-text'>

<sup>Originally posted by **paulrouget** February 10, 2023</sup>
I have window_picker disabled. And the picked window is the most ancient window. Is it possible to automatically pick the most left-top window?</div>

**Comment by alex-courtis** [comment]
The topleftest window should be picked in this situation.

Looks like a bug with first_win_id not being called https://github.com/nvim-tree/nvim-tree.lua/blob/d85b6718cef7f27c603cf170fb5154d90356e90b/lua/nvim-tree/actions/node/open-file.lua#L167

**Comment by alex-courtis** [comment]
Further experimentation indicates that nvim-tree attempts to use the most recently used window, then the topleftest.

Most recently used is set on open, focus etc. but not when manually moving to the nvim-tree window.

**Comment by alex-courtis** [comment]
Tracking the previously focused window when entering the nvim-tree window is impractical via events.

Things are working exactly as per the doc, with the window from which the tree was opened being used:
```help
            *nvim-tree.actions.open_file.window_picker.enable*
            Enable the feature. If the feature is not enabled, files will open in window
            from which you last opened the tree.
              Type: `boolean`, Default: `true`
```

@paulrouget could you live with using `:NvimTreeFocus` to navigate to nvim-tree?

**Comment by paulrouget** [comment]
> @paulrouget could you live with using :NvimTreeFocus to navigate to nvim-tree?

Absolutely! Changed my bindings to use `:NvimTreeFocus` instead of jumping to the window, and it works perfectly.

Thank you.

**Comment by alex-courtis** [comment]
> > @paulrouget could you live with using :NvimTreeFocus to navigate to nvim-tree?
> 
> Absolutely! Changed my bindings to use `:NvimTreeFocus` instead of jumping to the window, and it works perfectly.
> 
> Thank you.

That's good to hear; there's no nice way to do it otherwise...

**Comment by alex-courtis** [comment]
@zhimsel it sounds like you have encountered a bug; the previously active window should be chosen when the window picker is disabled.

Please raise a [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) with minimal configuration and detailed replication instructions.

**Comment by zhimsel** [comment]
Done: https://github.com/nvim-tree/nvim-tree.lua/issues/2262
