### ISSUE TITLE
nvim-tree no longer works with rmagatti/auto-session following "Open At Startup" option removal.

### ISSUE THREAD

**Issue by Cudochi** [nvim-tree/nvim-tree.lua#1992]
### Description

I updated my nvim-tree plugin, and saw that the startup options had all been marked as deprecated.
I never had a problem with them, in fact, it's what made me migrate from NERDTree at the time : 
The ability to save and restore session with rmagatti/auto-session while always keeping a file tree on the side.

### Neovim version

```text
NVIM v0.8.0-dev-1081-g907fc8ac3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compilé par runner@fv-az202-333

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 22.04.1 LTS

### nvim-tree version

36e29c3

### Minimal config

```lua
Nvim-tree config :

require'nvim-tree'.setup { -- BEGIN_DEFAULT_OPTS
  sync_root_with_cwd = true,
  respect_buf_cwd = true,
  update_focused_file = {
    enable = true,
    update_root = true
  },
  update_cwd = true,
  respect_buf_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true
    },
  auto_reload_on_write = true,
  disable_netrw = false,
  hijack_cursor = false,
  hijack_netrw = true,
  hijack_unnamed_buffer_when_opening = false,
  ignore_buffer_on_setup = true,
  -- open_on_setup = true,
  -- open_on_setup_file = true,
  open_on_tab = true,
  sort_by = "name",
  update_cwd = false,
  view = {
    width = 25,
    -- height = 30,
    side = "left",
    preserve_window_proportions = false,
    number = false,
    relativenumber = false,
    signcolumn = "yes",
    mappings = {
      custom_only = false,
      list = {
        -- user mappings go here
        { key = "O", action = "cd" },
      },
    },
  },
  hijack_directories = {
    enable = true,
    auto_open = true,
  },
  update_focused_file = {
    enable = false,
    update_cwd = false,
    ignore_list = {},
  },
  ignore_ft_on_setup = {},
  system_open = {
    cmd = nil,
    args = {},
  },
  diagnostics = {
    enable = false,
    show_on_dirs = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
  },
  filters = {
    dotfiles = false,
    custom = {},
    exclude = {},
  },
  git = {
    enable = true,
    ignore = false,
    timeout = 400,
  },
  actions = {
    change_dir = {
      enable = true,
      global = false,
    },
    open_file = {
      quit_on_open = false,
      resize_window = false,
      window_picker = {
        enable = true,
        chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
        exclude = {
          filetype = { "notify", "packer", "qf", "diff", "fugitive", "fugitiveblame" },
          buftype = { "nofile", "terminal", "help" },
        },
      },
    },
  },
  trash = {
    cmd = "trash",
    require_confirm = true,
  },
  log = {
    enable = false,
    truncate = false,
    types = {
      all = false,
      config = false,
      copy_paste = false,
      git = false,
      profile = false,
    },
  },
  renderer = {
    indent_markers = {
      enable = true,
    }
  }
} -- END_DEFAULT_OPTS

local function open_nvim_tree(data)

  -- buffer is a real file on the disk
  local real_file = vim.fn.filereadable(data.file) == 1

  -- buffer is a [No Name]
  local no_name = data.file == "" and vim.bo[data.buf].buftype == ""

  -- only files please
  if not real_file and not no_name then
    return
  end

  -- open the tree but don't focus it
  require("nvim-tree.api").tree.toggle({ focus = false })
end
vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
```

### Steps to reproduce

1. Install both https://github.com/rmagatti/auto-session and Nvim-tree
2. Add the minimum configuration for both plugins : 
   -  `require("auto-session").setup{}` for auto-sesison 
   - The nvim-tree config is provided above. It's an old default config with minor changes and the startup options commented out. The function that is supposed to replace startup is at the end.

3. Go to a directory
4. Open Neovim, nvim-tree should appear
5. Open a file in any way you want.
6. Exit Neovim (auto-sessio should save the session)
7. Open Neovim again, an error message should appear : 
```
info:  Session restored from /home/foo/.local/share/nvim/sessions/\%home\%foo\%.config\%nvim.vim
Error detected while processing Autocommands VimEnter for "*" :
Error executing lua callback: [string ":lua"]:122: Invalid buffer id: 1
stack traceback:
        [C]: in function '__index'
        [string ":lua"]:122: in function <[string ":lua"]:116>
Press ENTER or type another command to continue
```

### Expected behavior

With the now deprecated options, Nvim-tree used to open at startup while staying out of focus, with no error message whatsoever.

**Comment by alex-courtis** [comment]
Some experimentation has shown inconsistent results, with this error also showing:
```
Error detected while processing VimEnter Autocommands for "*":
error:          Error restoring session! The session might be corrupted.
        Disabling auto save. Please check for errors in your config. Error:
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
      Vim(file):E95: Buffer with this name already exists
```

It seems that the VimEnter to open the tree is being called before auto-session's VimEnter. We have an unpredictably deterministic ordering situation. This sort of situation is why we had to remove the open on startup bits.

Experimentation with regular `:mksession` and `vi -S Session.vim` showed no issues.

A solution might be to run your `open_nvim_tree` after auto-session is done. There might be a callback or event from auto-session that you can use.

**Comment by alex-courtis** [comment]
Experimenting with standard session and auto-session:
* fugitive: both OK
* packer: throws exception when running any command

nvim-tree could be made to act as fugitive does.

**Comment by alex-courtis** [comment]
Experimenting with standard session and auto-session:

`vi -S Session.vim`: VimEnter is called after SessionLoadPost
auto-session: before

**Comment by alex-courtis** [comment]
fugitive is restoring its buffer on `BufReadCmd`, not `SessionLoadPost`.

Listening to `BufReadCmd` will suppresses the `"NvimTree_1" [New]` message on startup with a session, however that may not be worth the possible issues it may cause.

**Comment by alex-courtis** [comment]
@Cudochi I'd be grateful if you could experiment with your open function firing on the postrestore [command hook](https://github.com/rmagatti/auto-session#-command-hooks) instead of `VimEnter`.

If we see success there, we can implement session restoration on `SessionLoadPost`.

**Comment by Cudochi** [comment]
@alex-courtis Thank you for looking into this.
I will make the tests. Give me a day or two, tonight I won't be in front of my computer.

**Comment by Cudochi** [comment]
Thank you for your patience, I was able to dig the issue a bit.

> This sort of situation is why we had to remove the open on startup bits.

It's weird that I never had any problems like this with my old setup and the now _deprecated_ options.

```lua
require'nvim-tree'.setup { /* Big default config from earlier here */ }
 
local function restore_nvim_tree()
  require("nvim-tree.api").tree.open({ focus = false })
end

require('auto-session').setup {
    post_restore_cmds = {restore_nvim_tree}
}
```
This ^ works better. No more errors. But : 
- The cursor stays in nvim-tree regardless of the `focus = false`
- If Neovim is started without a session (after it's deleted, or started from a new folder) nvim-tree is not started.
  - Idea : A flag is set to false by default, the `post_restore_cmds` sets it to true. After the setup of auto-session, a piece of code checks the state of the flag. If false, start nvim-tree.

I'm not very good with lua and the Neovim API, but I'm sure those problems are solvable.

**Comment by alex-courtis** [comment]
> It's weird that I never had any problems like this with my old setup and the now _deprecated_ options

That's all down to the unpredictable order of events. It's the major factor as to why the old setup didn't work reliably for all users.

> If Neovim is started without a session (after it's deleted, or started from a new folder) nvim-tree is not started.
> 
>    Idea : A flag is set to false by default, the post_restore_cmds sets it to true. After the setup of auto-session, a piece of code checks the state of the flag. If false, start nvim-tree.

`SessionLoadPost` should be sufficient. I don't think we'd need an option for that; it's reasonable for a user restoring a session to expect the tree to open.

> I'm not very good with lua and the Neovim API, but I'm sure those problems are solvable.

Would you consider reopening #1742 ? It should resolve session restoration for auto-session and regular vim sessions. It can also be simplified. [nvim -S mysession.vim](https://github.com/nvim-tree/nvim-tree.lua/pull/1742#pullrequestreview-1196791550) won't be an issue any longer.

**Comment by alex-courtis** [comment]
> * The cursor stays in nvim-tree regardless of the `focus = false`

I reckon that might Go Away if we acting inside `SessionLoadPost`.

Desired end state:
* session restoration is completely handled by nvim-tree 
* session users can still use `VimEnter` to open the tree, they will just need to be mindful of event order and build conditions that suit their setup

**Comment by alex-courtis** [comment]
You've proven the concept, we can now implement a solution.

Don't worry about the awaiting feedback label; regular users don't have label permissions.

**Comment by Cudochi** [comment]
> I reckon that might Go Away if we acting inside `SessionLoadPost`.

I'm not sure if I know how to implement that.
I tried doing this, but restore_nvim_tree is a nil value : 
```
local function restore_nvim_tree()
  require("nvim-tree.api").tree.open({ focus = false })
end

vim.cmd("autocmd SessionLoadPost * lua restore_nvim_tree()")
```

Lua isn't my strong point, _Neovim lua_ even less so, and let's just not talk about VimScript.

As for the end state : 
- If I understand you correctly, you want to add a "session maganement" side to nvim-tree ?
- Won't it be a lot to think about for a basic user when they'll build their config ? (Neo)Vim lets the user configure everything, granted, but if the ratio amount of _energy spend to set up a feature / size of the feature_ is too high, people aren't going to do it.
 
PS: I don't think I have the permission to reopen the pull request https://github.com/nvim-tree/nvim-tree.lua/pull/1742.

**Comment by ehaynes99** [comment]
> Would you consider reopening #1742 ? It should resolve session restoration for auto-session and regular vim sessions. It can also be simplified. [nvim -S mysession.vim](https://github.com/nvim-tree/nvim-tree.lua/pull/1742#pullrequestreview-1196791550) won't be an issue any longer.

@alex-courtis who are you asking there?

There's an unsolvable chicken-and-egg problem with trying to implement this via events within the `nvim-tree` codebase in that you can't guarantee `nvim-tree` has been loaded before those events occur. For example, [lazy.nvim](https://github.com/folke/lazy.nvim) allows lazily loading plugins on a keystroke.

```lua
return {
  'nvim-tree/nvim-tree.lua',
  keys = {
    { '<leader>e', ':NvimTreeFocus<CR>', desc = 'Focus tree view' },
  },
  config = function()
    require('nvim-tree').setup({
      -- ...
    })
  end,
}
```
Before I dive too far down a dead-end, could we not check for an existing buffer in the current tab during: https://github.com/ehaynes99/nvim-tree.lua/blob/master/lua/nvim-tree/lib.lua#L159

**Comment by ehaynes99** [comment]
Also, it does not appear that `SessionLoadPost` events fire at all using `auto-session`. It restores the session via
```
silent source <SESSION_FILE>
```
here: https://github.com/rmagatti/auto-session/blob/main/lua/auto-session.lua#L499

I only see the event fired when starting nvim with `-S`

**Comment by ehaynes99** [comment]
I guess the load-on-keystroke behavior is just fundamentally at odds with "open on setup", but even less extreme examples of lazy loading are going to create a race condition for any of the initialization events. I would think the `VeryLazy` option a pretty common case for this plugin: https://github.com/folke/lazy.nvim#-user-events

**Comment by alex-courtis** [comment]
> There's an unsolvable chicken-and-egg problem with trying to implement this via events within the `nvim-tree` codebase in that you can't guarantee `nvim-tree` has been loaded before those events occur when lazy-loading is in use.
> 
> Also, it does not appear that `SessionLoadPost` events fire at all using `auto-session`. It restores the session via
> 
> ```
> silent source <SESSION_FILE>
> ```

I see... that is a problem. I had not thought that through. Session management event hooks aren't really going to solve anything.

The best option might just be to attempt to emulate fugitive behaviour, which seems to be action on `BufEnter` or similar. We'd need to be a bit clever around buftype / filetype that's persisted via the session but it should be achievable.

**Comment by ehaynes99** [comment]
Sorry I didn't get back to you sooner. I'm rather swamped right now, though, and I've spent more time on this than I really have right now... I can put together a PR for this 2 weeks from now, but no promises prior to that.

It's pretty broken as it is. The stray `NvimTree_X` windows can end up in odd places & sizes, and there are cases where it results in an error like "buffer with name already exists" when e.g. `NvimTree_1` exists on some other tabpage.

The simplest way out for auto-session is to just kill all of the windows prior to exit and let whatever user-defined "open on start" behavior is desired run again. I put this in my init, but nvim-tree could create such an autocommand whenever it creates a buffer. However, a session created manually with `:mksession` is still going to contain it:

```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = { 'NvimTree' },
  callback = function(args)
    vim.api.nvim_create_autocmd('VimLeavePre', {
      callback = function()
        vim.api.nvim_buf_delete(args.buf, { force = true })
        return true
      end
    })
  end,
})
```

This seems to work ok locally, but if the code lived in `nvim-tree`, it can't solve the issue of `nvim-tree` loading after the initial load:
```lua
vim.api.nvim_create_autocmd({ 'BufEnter' }, {
  pattern = 'NvimTree*',
  callback = function()
    local view = require('nvim-tree.view')
    local is_visible = view.is_visible()

    local api = require('nvim-tree.api')
    if not is_visible then
      api.tree.open()
    end
  end,
})
```

Observations:
* In order to have something that could be called from hooks like auto-session's `post_restore_cmds` that would work if `nvim-tree` wasn't loaded before then, there would need to be a way to populate all of the existing buffers. Ideally, this could be done to any arbitrary buffer without regard for focus. The original PR for #1742 actually opened each tabpage that had a tree window, then opened the tree. I think this was largely to rely on the behavior of the [global static state](https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/core.lua) in core around the cwd. This is not an acceptable solution, IMO. Opening all of the tabs on startup could trigger a lot of additional side-effects like LSP servers, plugins based on filetype, etc.
* I know you want to wash your hands of the whole set of behaviors because of these cases, which is totally understandable. TBH, this is a problem with a number of other plugins too. Sessions just don't work well with dynamic buffers. I think we'll need a more general solution for state restoration of any sort of dynamic buffer, because it's going to be a damned nightmare if everyone starts making up their own solution for persisting state to disk. @Cudochi 's claim that this used to work is only partially correct. Perhaps the tree was present, but it wasn't "restored".
* It's not really accurate to call it "session restore", because you don't have the necessary state. I tried sticking the state in buffer-local variables, but event with `localoptions` in the `sessionoptions` value, variables aren't persisted. The question then becomes, "what do we (re)open?". I think the `cwd` of tab is probably the only decent option, but particularly if someone has `sync_root_with_cwd` disabled, this could be entirely different from what was there before. And there's all of the other state like open directories, toggling hidden, etc.

**Comment by alex-courtis** [comment]
> The original PR for https://github.com/nvim-tree/nvim-tree.lua/pull/1742 actually opened each tabpage that had a tree window, then opened the tree. I think this was largely to rely on the behavior of the [global static state](https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/core.lua) in core around the cwd.

Reopening #1742, many of the pieces are there.

> Opening all of the tabs on startup could trigger a lot of additional side-effects like LSP servers, plugins based on filetype, etc.

> I know you want to wash your hands of the whole set of behaviors because of these cases, which is totally understandable. TBH, this is a problem with a number of other plugins too. Sessions just don't work well with dynamic buffers. I think we'll need a more general solution for state restoration of any sort of dynamic buffer, because it's going to be a damned nightmare if everyone starts making up their own solution for persisting state to disk.

This might not be too bad; much as I hate to add options, we could add a default false option for session restoration behaviour.

> @Cudochi 's claim that this used to work is only partially correct. Perhaps the tree was present, but it wasn't "restored".

Yes. It "worked" but only for some users; others experienced strange issues on startup.

> * I tried sticking the state in buffer-local variables, but event with `localoptions` in the `sessionoptions` value, variables aren't persisted.

Yes! I couldn't persist anything useful about the restored nvim-tree buffer for any of the session restore methods.

**Comment by charbelnicolas** [comment]
You can use both of these plugins and they work like a charm with NvimTree and `sync_root_with_cwd`:

[sessions.nvim](https://github.com/natecraddock/sessions.nvim)
[workspaces.nvim](https://github.com/natecraddock/workspaces.nvim)

```
require('sessions').setup({
	events = { 'BufEnter' },
	session_filepath = vim.fn.stdpath('data') .. '/sessions',
	absolute = true
})
```

```
require('workspaces').setup({
	hooks = {
		open_pre = { 'NvimTreeClose', 'SessionsStop', 'silent %bdelete!' },
		open = { function() require('sessions').load(nil, { silent = true }) end, 'NvimTreeOpen' }
	}
})
```

https://user-images.githubusercontent.com/14960414/221747174-a701d75b-5b68-4c26-a8c0-2d7857d05552.mp4

**Comment by alex-courtis** [comment]
That's great news! We will get this...

> open_pre = { 'NvimTreeClose', 'SessionsStop', 'silent %bdelete!' },

To clarify: this destroys the nvim-tree buffer.

What is opening it again? Does the open hook always open it, regardless of whether it was previously present in the session?

**Comment by charbelnicolas** [comment]
When it is going to load a workspace it first closes NvimTree, stops saving the session it is on (if any), then it deletes all buffers and then it loads the session along with a new NvimTree. It doesn't flash or anything, looks super smooth.

Yes, the open hook always opens NvimTree regardless of wether it was previously open or not in the previous session. You can omit the NvimTreeOpen and just open it with a keybind instead.

This is the setup that has caused the least amount of pain :)

**Comment by alex-courtis** [comment]
> I never find any stray NvimTree_ buffers anymore!

That's elegant and safe.

If only we could persist something in the session to indicate that nvim-tree was open...

**Comment by Cudochi** [comment]
I was so tired these last few days, I posted my response in this thread by mistake : https://github.com/nvim-tree/nvim-tree.lua/issues/1669

So, again, this time in the right place : 
For now, I think I'll stay on https://github.com/nvim-tree/nvim-tree.lua/commit/e14989c0eaa6f9c299d48f7e45ce1ed04b21180f
I have a setup that works perfectly across multiple machines (Ubuntu 20.04, Centos 8, 7 and 6), and there is no feature that I feel I might need. All of that makes me think that I don't have a real reason to update this plugin.

When this problem is solved, I'll update again.
It makes me wonder, though. What this plugin provides is standard in every other IDE I've come across. Neovim aims to be an aggressive refactor of Vim, but if we have trouble implementing something like this, is the refactor enough ?

**Comment by alex-courtis** [comment]
> What this plugin provides is standard in every other IDE I've come across. Neovim aims to be an aggressive refactor of Vim, but if we have trouble implementing something like this, is the refactor enough ?

neovim unfortunately carries a lot of vim legacy that it cannot break i.e. fix bugs/undesirable behaviour.

Hopefully nvim will eventually create a new event system that will allow us to reliably implement this sort of functionality.

**Comment by alex-courtis** [comment]
## Experimenting with [rmagatti/auto-session](https://github.com/rmagatti/auto-session):

* `BufAdd` i.e. session restore is called after user's `VimEnter`
* `BufAdd` can be heard by nvim-tree
* Event ordering is unpredictably deterministic, based on the order of setup calls, autocommand registration etc.

**Conclusion:** you're on your own here. You can't open nvim-tree during `VimEnter` as auto-session will try and fail to stomp on it. You'll need to craft your own solution using auto-session hooks such as https://github.com/nvim-tree/nvim-tree.lua/issues/1992#issuecomment-1447524017

## Regular vim sessions:

* `BufAdd` called before user's `VimEnter`
* `BufAdd` can be heard by nvim-tree
* Event ordering is more predictable; nvim sessions always occur immediately after init is done i.e. before any autocommands

**Conclusion:** we can do this via `BufAdd`. `BufReadPost` (as per fugitive) is unnecessary and not fired for the nvim-tree buffer in any case.

`restore_session = false` option can be added.

**Comment by nikolasmish** [comment]
> ```lua
> vim.api.nvim_create_autocmd('FileType', {
>   pattern = { 'NvimTree' },
>   callback = function(args)
>     vim.api.nvim_create_autocmd('VimLeavePre', {
>       callback = function()
>         vim.api.nvim_buf_delete(args.buf, { force = true })
>         return true
>       end
>     })
>   end,
> })
> ```
> 
> ```lua
> vim.api.nvim_create_autocmd({ 'BufEnter' }, {
>   pattern = 'NvimTree*',
>   callback = function()
>     local view = require('nvim-tree.view')
>     local is_visible = view.is_visible()
> 
>     local api = require('nvim-tree.api')
>     if not is_visible then
>       api.tree.open()
>     end
>   end,
> })
> ```

Both of these work perfectly with rmagatti/auto-session. Thanks!

**Comment by alex-courtis** [comment]
> Both of these work perfectly with rmagatti/auto-session. Thanks!

I think we need a wiki page... I'll add one following the addition of rudimentary `restore_session` handling.

**Comment by alex-courtis** [comment]
I'm not sure that session restoration is possible: I'm getting inconsistent/rubbish values for the winid, winnr and tabpage for the buffers restored via a standard session:

```
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1000 tabpage=1 1
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1001 tabpage=2 4
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1000 tabpage=1 1
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1000 tabpage=1 2 /home/alex/src/way-displays/NvimTree_1
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=2 winid=1002 tabpage=1 5
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1000 tabpage=1 2 /home/alex/src/way-displays/NvimTree_1
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden=wipe swapfile=true modifiable=true buflisted=true winnr=1 winid=1001 tabpage=2 4
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1001 tabpage=2 3 /home/alex/src/way-displays/NvimTree_2
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=2 winid=1003 tabpage=2 6
[2023-03-14 13:03:26] [dev]        BufEnter buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1001 tabpage=2 3 /home/alex/src/way-displays/NvimTree_2
[2023-03-14 13:03:26] [dev] SessionLoadPost buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=3 winid=1004 tabpage=2 2 /home/alex/src/way-displays/NvimTree_1
[2023-03-14 13:03:26] [dev] SessionLoadPost buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=3 winid=1004 tabpage=2 5
[2023-03-14 13:03:26] [dev] SessionLoadPost buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=2 winid=1003 tabpage=2 6
[2023-03-14 13:03:26] [dev] SessionLoadPost buftype= filetype= bufhidden= swapfile=true modifiable=true buflisted=true winnr=1 winid=1001 tabpage=2 3 /home/alex/src/way-displays/NvimTree_2
```

https://gist.github.com/alex-courtis/f82c6004b1ef64b8b778ef90e73aac07

**Comment by alex-courtis** [comment]
There is nothing we can do here. Most plugins do not support sessions, with many throwing errors on session restore.

Documenting lack of session support.

nvim-tree will happily open in the place of a buffer/window that was restored from the session. That can be automated by the user AFTER the session restore has occurred and nvim-tree has been loaded.

auto-session is operating at an inconsistent time, with the reported error being an issue with auto-session itself: it's trying to overwrite the nvim-tree window which already exists, as per the user's VimEnter.

@Cudochi @ehaynes99 @charbelnicolas @nikolasmish : is there anything we can do to make your session experience more tolerable e.g. deal with exceptions that we can safely handle?

**Comment by alex-courtis** [comment]
@charbelnicolas and @nikolasmish I would be most grateful if you could document your solutions on 
[wiki: Recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)

**Comment by nikolasmish** [comment]
@alex-courtis Added the workaround to wiki.

**Comment by alex-courtis** [comment]
> @alex-courtis Added the workaround to wiki.

Many thanks!

**Comment by alex-courtis** [comment]
@nikolasmish I note the use of non-API `require('nvim-tree.view').is_visible()`. We don't have such a method and we should add one.

Confirming: you need to test whether nvim-tree is open. What do you expect when nvim-tree is open in another tab? We can provide granular for that.

**Comment by alex-courtis** [comment]
We have a resolution / workaround / recipe. Closing.

Please raise a new issue if you have further questions / concerns / ideas.
