### ISSUE TITLE
Nvim-tree very slow to open

### ISSUE THREAD

**Issue by Raagh** [nvim-tree/nvim-tree.lua#1998]
### Description

When opening nvim-tree from a buffer it takes forever to load and forever to go back to the buffer (seems to happen on big projects only)

Locking the plugin to this commit solves the issue
https://github.com/nvim-tree/nvim-tree.lua/commit/f3b73725c5a007b8195118bec5868c32a5eff81f

![api-2023-02-14-09-18-17](https://user-images.githubusercontent.com/8405459/218680252-a25ab41b-9fe6-4529-9be4-3e6bb98e2093.gif)

### Neovim version

```text
NVIM v0.8.2
```

### Operating system and version

Windows 11 (WSL Ubuntu)

### nvim-tree version

latest

### Minimal config

```lua
-- each of these are documented in `:help nvim-tree.OPTION_NAME`
local status_ok, nvim_tree = pcall(require, "nvim-tree")
if not status_ok then
  return
end

local config_status_ok, _ = pcall(require, "nvim-tree.config")
if not config_status_ok then
  return
end

nvim_tree.setup {
  disable_netrw = true,
  hijack_netrw = true,
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
    ignore_list = {}
  },
  trash = {
    cmd = "trash",
    require_confirm = true,
  },
  actions = {
    open_file = {
      resize_window = false,
    }
  },
  view = {
    adaptive_size = true
  }
}
```

### Steps to reproduce

1. open nvim on a big project
2. open a file
3. open nvim-tree from the buffer

### Expected behavior

works fast as before

### Actual behavior

extremely slow to open and go back to buffer

**Comment by Bacbia3696** [comment]
yes, I have the same problem with nvim-tree, seem like the commit https://github.com/nvim-tree/nvim-tree.lua/commit/4222bb875d86a2a53069c75c4833e27f58e26d90 cause the issue. The workaround is use previous commit.
For lazy nvim, you would need to go to: .local/share/nvim/lazy/nvim-tree.lua, and checkout 8b8d457

**Comment by silvercircle** [comment]
Same here (on Linux). High CPU load and massive memory leaks when navigating directories. Definitely caused by 4222bb875d86a2a53069c75c4833e27f58e26d90. Everything before works normally.

**Comment by sungvadan** [comment]
Same problem (on mac).

**Comment by asher-gh** [comment]
same here on mac

**Comment by jhonrocha** [comment]
Same here. On Linux. 
Here is my config:
```
	{
		"kyazdani42/nvim-tree.lua",
		lazy = false,
		dependencies = { "kyazdani42/nvim-web-devicons", lazy = false },
		opts = {
			actions = { open_file = { quit_on_open = true } },
			update_focused_file = { enable = true },
			renderer = { highlight_opened_files = "icon" },
			-- git = { enable = false },
			log = {
				enable = true,
				truncate = true,
				types = {
					diagnostics = true,
					git = true,
					profile = true,
					watcher = true,
				},
			},
		},
		keys = {
			{ "<leader>d", "<Cmd>NvimTreeFindFileToggle<CR>", desc = "file drawer" },
		},
	},
```

Here is `nvim-tree.log`: https://pastebin.pl/view/41c33e51

**Comment by jhonrocha** [comment]
@Bacbia3696  Setting `commit = "8b8d457" on lazy.nvim does the rollback and fixes it:
```
	{
		"nvim-tree/nvim-tree.lua",
		commit = "8b8d457",
		dependencies = { "kyazdani42/nvim-web-devicons" },
		opts = {
			actions = { open_file = { quit_on_open = true } },
			update_focused_file = { enable = true },
			renderer = { highlight_opened_files = "icon" },
		},
		keys = {
			{ "<leader>d", "<Cmd>NvimTreeFindFileToggle<CR>", desc = "file drawer" },
		},
	},
```

**Comment by top4ek** [comment]
The same. Linux.
Rolling back to nightly "fixes" problem. 
```
tree.setup {
  sync_root_with_cwd = true,
  respect_buf_cwd = true,
  update_focused_file = {
    enable = true,
    update_root = true
  },
  filters = {
	  dotfiles = false
  },
  renderer = {
	  group_empty = true
  },
  git = {
	  ignore = false
  },
  auto_reload_on_write = true,
  create_in_closed_folder = false,
  disable_netrw = true,
  hijack_unnamed_buffer_when_opening = true,
  view = {
    width = 30,
    -- height = 30,
    hide_root_folder = false,
    side = "left",
    preserve_window_proportions = false,
    number = true,
    relativenumber = true,
    signcolumn = "yes"
  }
}
```

**Comment by sungvadan** [comment]
> @Bacbia3696 Setting `commit = "8b8d457"` on lazy.nvim does the rollback and fixes it:
> 
> ```
> 	{
> 		"nvim-tree/nvim-tree.lua",
> 		commit = "8b8d457",
> 		dependencies = { "kyazdani42/nvim-web-devicons" },
> 		opts = {
> 			actions = { open_file = { quit_on_open = true } },
> 			update_focused_file = { enable = true },
> 			renderer = { highlight_opened_files = "icon" },
> 		},
> 		keys = {
> 			{ "<leader>d", "<Cmd>NvimTreeFindFileToggle<CR>", desc = "file drawer" },
> 		},
> 	},
> ```

It works. Thanks a lot

**Comment by przepompownia** [comment]
For me:
- endless loading started to occur on 4222bb8 
- no such problem on 8b8d457

**Comment by alex-courtis** [comment]
Change reverted, please accept my apologies.
