### ISSUE TITLE
[BUG] Wrong path separator on windows if `vim.opt.shellslash = true`.

### ISSUE THREAD

**Issue by ysl2** [nvim-tree/nvim-tree.lua#2017]
### Description

I know there is a method in your code to specify the path separator:

https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/utils.lua#L32

But this can lead to a huge problem if you set `vim.opt.shellslash = true`, this option tells nvim to use `/` even on windows system (`:h shellslash`).

Unfortunately the bug occurred when I set this option, and I also set `sync_root_with_cwd` option, so now it always jump to the buffer location, this is a wired behavior beacuse I also have another plugin like `project.nvim` to pin my root directory. So the nvim-tree messed up the cwd. I traced to the code below:

https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree.lua#L30-L69

In fact the function always return on the last line, it bypass all if-else statement beacuse of the wrong slash `/`.

This is my solution, not very elegant, but can use.

```diff
diff --git a/lua/nvim-tree.lua b/lua/nvim-tree.lua
index 507855b..56bd48b 100644
--- a/lua/nvim-tree.lua
+++ b/lua/nvim-tree.lua
@@ -27,7 +27,16 @@ function M.focus()
   view.focus()
 end
 
+local function mysub(mystr)
+  if vim.fn.has('win32') == 1 and vim.opt.shellslash._value == true then
+    return mystr:gsub('/', package.config:sub(1, 1))
+  end
+  return mystr
+end
+
 function M.change_root(filepath, bufnr)
+  filepath = mysub(filepath)
+
   -- skip if current file is in ignore_list
   local ft = vim.api.nvim_buf_get_option(bufnr, "filetype") or ""
   for _, value in pairs(_config.update_focused_file.ignore_list) do
@@ -37,7 +46,7 @@ function M.change_root(filepath, bufnr)
   end
 
   local cwd = core.get_cwd()
-  local vim_cwd = vim.fn.getcwd()
+  local vim_cwd = mysub(vim.fn.getcwd())
 
   -- test if in vim_cwd
   if utils.path_relative(filepath, vim_cwd) ~= filepath then
@@ -52,7 +61,7 @@ function M.change_root(filepath, bufnr)
   end
 
   -- otherwise test M.init_root
-  if _config.prefer_startup_root and utils.path_relative(filepath, M.init_root) ~= filepath then
+  if _config.prefer_startup_root and utils.path_relative(filepath, mysub(M.init_root)) ~= filepath then
     change_dir.fn(M.init_root)
     return
   end
```

**Comment by alex-courtis** [comment]
> But this can lead to a huge problem if you set `vim.opt.shellslash = true`, this option tells nvim to use `/` even on windows system (`:h shellslash`).

Honestly, I never knew this existed.

Are there any issues with using this?

This _could_ make things easier: we could specify that windows users must set this option, removing the need for all the slash detection business.
