### ISSUE TITLE
How to restore nvim-tree on session restore?

### ISSUE THREAD

**Issue by xbladesub** [nvim-tree/nvim-tree.lua#2020]
I use auto-session plugin to manage my sessions. How can I restore the state of nvim-tree with it? Currently it restores empty buffer. Maybe there are some settings or maybe another session plugin which would work with nvim-tree in this case?

**Comment by charbelnicolas** [comment]
Yes it would be nice if nvim tree could remember its state on session restore

**Comment by alex-courtis** [comment]
Working on it #1992
