### ISSUE TITLE
Reopen window with another loaded buffer on :bd when tree is open

### ISSUE THREAD

**Issue by mikehaertl** [nvim-tree/nvim-tree.lua#2042]
### Current behavior

* Start nvim
* Open file `a.txt` with `:e a.txt`
* Open another file `b.txt` with `:e b.txt`
* Optional: open nvim-tree and switch back to window `b.txt`
* Delete buffer `b.txt` with `:bd`

**Result if nvim-tree was closed** (i.e. default vim/neovim w/o nvim-tree behavior)

One window with buffer `a.txt`.

**Result if nvim-tree was opened**

One window with nvim-tree.

### Suggested behavior

nvim-tree should reopen a window with buffer `a.txt`.

Right now it already does something similar if in the above situation a buffer is selected e.g. with `:bn`.

In general it should behave like `:bd`:

> :bd[elete][!] [N]
>             
> 		...  Any windows for this buffer are
>		closed.  If buffer [N] is the current buffer, another buffer
>		will be displayed instead.  This is the most recent entry in
>		the jump list that points into a loaded buffer.

**Comment by alex-courtis** [comment]
Unfortunately that is vim behaviour on `:bd` a buffer:
* last window remaining: switches to `#`, a.txt in this case
* many windows open: closes the window

There are ways around this, with a couple of plugins to correct this behaviour. See #2034

I have used`qpkorr/vim-bufkill` for many years now.

**Comment by mikehaertl** [comment]
@alex-courtis Hmm, but a very similar behavior seems to be already implemented: If the only window is nvim-tree and you switch to another buffer then nvim-tree seems to reopen itself right after the change.

Why can't the same be done a step before i.e. when nvim-tree is the only window left?

**Comment by alex-courtis** [comment]
This is nothing to do with nvim-tree. It can be demonstrated in a clean environment:

First window does not close:
```
nvim --clean
:e file1
<c-w><c-v>
:e file2
:bd
```

Left window closes:
```
nvim --clean
:e file1
<c-w><c-v>
:e file2
:bd
```

> Why can't the same be done a step before i.e. when nvim-tree is the only window left?

This is not practical and falls well outside of the scope of nvim-tree.

How do you determine if nvim-tree is the last window remaining? You can't reliably do so. See (wiki: Auto Close)[https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close)

**Comment by mikehaertl** [comment]
> This is nothing to do with nvim-tree. It can be demonstrated in a clean environment:

Thanks, but I think you misunderstand. Your demonstration does not exactly show what I meant:

* Open 2 files in 1 window. You see 1 window.
* Open nvim-tree. You see 2 windows:

![image](https://user-images.githubusercontent.com/675062/224928441-7acfe046-0458-49e3-a9e3-1cd98e696a79.png)

* Switch to the file window and close the buffer with `:bd`. Now you only have 1 window with nvim tree:

![image](https://user-images.githubusercontent.com/675062/224928544-a4ec5434-1feb-4b26-b44c-8409c602f036.png)

* **Now** use `:bn` and now you see that suddenly you have 2 windows again: nvim-tree on the left and the second file on the right:

![image](https://user-images.githubusercontent.com/675062/224928641-50de8252-aa43-4489-b0ec-6daffeb9e38d.png)

So nvim-tree somehow must have figured out that after `:bn` it has to create another new window for itself again. It must have figured that out somehow.

From the wiki I understand that it's an issue with unrealiable events. But can't something like `WinClosed` be used?

**Comment by alex-courtis** [comment]
> So nvim-tree somehow must have figured out that after :bn it has to create another new window for itself again.

That's expected behaviour: you're opening b.txt in the nvim-tree window. Opening a file in the nvim-tree window will "eject it" by opening another window and putting it in there.

> From the wiki I understand that it's an issue with unrealiable events. But can't something like WinClosed be used?

You can definitely implement this yourself: neovim events and the nvim-tree API are available to achieve this. If you do achieve a good solution, it would be great if you posted a [recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes) for it.

**Comment by alex-courtis** [comment]
The most pragmatic solution is simply to use `qpkorr/vim-bufkill` which is mature and reliable. See https://github.com/nvim-tree/nvim-tree.lua/discussions/2034#discussioncomment-5199392

Your desired behaviour is outside of the scope of nvim-tree, cannot be made reliable and is handled by other plugins. It will not be implemented in nvim-tree.

**Comment by mikehaertl** [comment]
> The most pragmatic solution is simply to use qpkorr/vim-bufkill which is mature and reliable.

Thanks maybe I'l try it. But it also changes the default behaviour and would *always keep split windows open*. I only want this to happen for the nvim-tree case above. 

Maybe I find a solution when it starts annoying me too much. 

Right now my procedure is:

 * Remember to close nvim-tree first
 * Close file B, which drops me back to file A
 * Reopen nvim-tree
 * Switch from nvim-tree window to file A window

**Comment by alex-courtis** [comment]
> Thanks maybe I'l try it. But it also changes the default behaviour and would _always keep split windows open_. I only want this to happen for the nvim-tree case above.

It doesn't change/override defaults.

Use `:BD` to delete in your custom situation, otherwise use `:bd`.

**Comment by mikehaertl** [comment]
I was not happy with vim-bufkill either: I always had to select what is the right command for the current situation: `:bd` or `:BD`.

It seems I now found a solution that does exactly what I want. I found this trick in the lspsaga plugin that solves a similar problem with `vim.defer_fn()`:

```lua
-- On :bd nvim-tree should behave as if it wasn't opened
vim.api.nvim_create_autocmd("BufEnter", {
  nested = true,
  callback = function()
    -- Only 1 window with nvim-tree left: we probably closed a file buffer
    if #vim.api.nvim_list_wins() == 1 and require("nvim-tree.utils").is_nvim_tree_buf() then
      local api = require('nvim-tree.api')
      -- Required to let the close event complete. An error is thrown without this.
      vim.defer_fn(function()
        -- close nvim-tree: will go to the last buffer used before closing
        api.tree.toggle({find_file = true, focus = true})
        -- re-open nivm-tree
        api.tree.toggle({find_file = true, focus = true})
        -- nvim-tree is still the active window. Go to the previous window.
        vim.cmd("wincmd p")
      end, 0)
    end
  end
})

```

**Comment by alex-courtis** [comment]
Nice one. Perhaps you might document a [Recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)

**Comment by mikehaertl** [comment]
Done.

**Comment by alex-courtis** [comment]
Many thanks

**Comment by mikehaertl** [comment]
Enhanced version that also deals with `:q`. Wiki recipe updated.

```lua
-- Make :bd and :q behave as usual when tree is visible
vim.api.nvim_create_autocmd({'BufEnter', 'QuitPre'}, {
  nested = false,
  callback = function(e)
    local tree = require('nvim-tree.api').tree

    -- Nothing to do if tree is not opened
    if not tree.is_visible() then
      return
    end

    -- How many windows do we have? (excluding floats e.g. from incline)
    local winCount = 0
    for _,winId in ipairs(vim.api.nvim_list_wins()) do
      if vim.api.nvim_win_get_config(winId).relative == '' then
        winCount = winCount + 1
      end
    end

    -- We want to quit and only one window besides tree is left
    if e.event == 'QuitPre' and winCount == 2 then
      vim.api.nvim_cmd({cmd = 'qall'}, {})
    end

    -- :bd was probably issued an only tree window is left
    -- Behave as if tree was closed (see `:h :bd`)
    if e.event == 'BufEnter' and winCount == 1 then
      -- Required to avoid "Vim:E444: Cannot close last window"
      vim.defer_fn(function()
        -- close nvim-tree: will go to the last buffer used before closing
        tree.toggle({find_file = true, focus = true})
        -- re-open nivm-tree
        tree.toggle({find_file = true, focus = false})
      end, 10)
    end
  end
})
```
