### ISSUE TITLE
Opening WSL directories fails 

### ISSUE THREAD

**Issue by gjm-p** [nvim-tree/nvim-tree.lua#2046]
### Description

I'm running Windows 10 but a lot of what I do is in WSL (more specifically, WSL2 rather than WSL1). I'm using the current stable version of nvim, 0.8.3, and nvim-tree as installed a few minutes ago using packer.

nvim can read and edit my WSL files just fine. It can see what's in WSL directories (e.g., `:e <tab>` shows me all the files in the current directory even if that's inside WSL). However, nvim-tree fails to show me the contents of WSL directories. Details of what it does instead are below.

I suspect an underlying nvim problem. In plain nvim, if I do `:e \\wsl$\Ubuntu-20.04\home\gareth` then I get (no error or warning messages, but) a "Netrw Directory Listing" whose header looks normal but which shows no actual files or directories. On the other hand, if I do the same thing in gvim then I get a correct directory listing. (nvim and traditional-vim are both using netrw v171, so this can't be a netrw difference.)

But it seems like nvim-tree should be able to do something more useful here. Its logs (see below) make it clear that it has in fact successfully looked at the directory I asked it to open and seen what files and directories are there. And the failure mode is arguably even more unfriendly than that of netrw, which likewise fails to show me the contents of the directory I asked for but at least _keeps that as the current directory_.

### Neovim version

```text
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
```

### Operating system and version

Windows 10 21H2 19044.2604

### nvim-tree version

bbb6d48

### Minimal config

```lua
(nvt-min.lua exactly as retrieved from issue-template link 2023-03-11)
```

### Steps to reproduce

1. cd [my temp directory]
2. nvim -nu nvt-min.lua
3. :e \\wsl$\Ubuntu-20.04\home\gareth

(In case it is not perfectly obvious, /home/gareth is my home directory in a WSL2 instance called Ubuntu-20.04. Symptoms are the same with other WSL directories.)

### Expected behavior

nvim-tree directory viewer for /home/gareth opens.

### Actual behavior

Status line says `NvimTree_1` (which I assume is normal).
Top line of editor window says `\\wsl$\Ubuntu-20.04\home\gareth\/..` (which may or may not be normal).
Contents of directory are not listed anywhere.
Message below status line, in red: `[NvimTree] "Could not start the fs_event watcher for path \\\\wsl$\\Ubuntu-20.04\\home\\gareth : EISDIR`.

At this point, hitting Enter moves up one directory level and does the same thing -- `\\wsl$\Ubuntu-20.04\home/..` on top line, error message at bottom same but with `\\gareth` removed. Hitting Enter again moves up one more directory level and does the same. Hitting Enter _again_ gives a longer error message:

    E5108: Error executing lua: ...\nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:50: Vim(lcd):E344: Cannot firectory "\\wsl$" in cdpath
    stack traceback:
            [C]: in function 'cmd'
            ...\nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:50: in function 'cd'
            ...\nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:67: in function 'f'
            ...\nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:60: in function 'force_dirchange'
            ...\nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:46: in function 'fn'
            ...te\pack\packer\start\nvim-tree.lua/lua/nvim-tree/api.lua:117: in function 'f'
            ...te\pack\packer\start\nvim-tree.lua/lua/nvim-tree/api.lua:15: in function <...te\pack\packer\start\nvim-tua/lua/nvim-tree/api.lua:13>

Hitting Enter _again_ leaves me with the empty nvim-tree window for `\\wsl$\Ubuntu-20.04/..`. At this point my current directory in nvim is (not the WSL directory I originally asked for, but) my WSL root directory (e.g., doing :e and hitting tab lists the contents of that directory).

Using a not-minimal configuration gives the exact same symptoms. In this context I tried running with nvim-tree logging enabled. I will not post the full output because this is a work computer and I probably shouldn't share exactly what's in my home directory, but it looks something like this:

    [2023-03-11 14:15:11] [profile] START change dir \\wsl$\Ubuntu-20.04\home\gareth\
    [2023-03-11 14:15:11] [profile] START core init \\wsl$\Ubuntu-20.04\home\gareth\
    [2023-03-11 14:15:11] [watcher] Watcher:new '\\wsl$\Ubuntu-20.04\home\gareth\' nil
    [2023-03-11 14:15:11] [watcher] Event:new '\\wsl$\Ubuntu-20.04\home\gareth\'
    [2023-03-11 14:15:11] [watcher] Event:start '\\wsl$\Ubuntu-20.04\home\gareth\'
    [2023-03-11 14:15:11] [profile] START git toplevel \\wsl$\Ubuntu-20.04\home\gareth\
    [2023-03-11 14:15:11] [git] { "git", "-C", "\\\\wsl$\\Ubuntu-20.04\\home\\gareth\\", "rev-parse", "--show-toplevel" }
    fatal: not a git repository (or any of the parent directories): .git
    [2023-03-11 14:15:12] [profile] END   git toplevel \\wsl$\Ubuntu-20.04\home\gareth\ 236ms
    [2023-03-11 14:15:12] [profile] START explore init \\wsl$\Ubuntu-20.04\home\gareth\
    [2023-03-11 14:15:12] [profile] START explore populate_children \\wsl$\Ubuntu-20.04\home\gareth\.python_history
    [2023-03-11 14:15:12] [profile] END   explore populate_children \\wsl$\Ubuntu-20.04\home\gareth\.python_history 8ms
    (similar entries for all the files and directories in my home directory, in random-looking order)
    [2023-03-11 14:15:12] [profile] END   explore init \\wsl$\Ubuntu-20.04\home\gareth\ 299ms
    [2023-03-11 14:15:12] [profile] END   core init \\wsl$\Ubuntu-20.04\home\gareth\ 564ms
    [2023-03-11 14:15:12] [profile] START draw
    [2023-03-11 14:15:12] [profile] END   draw 0ms
    [2023-03-11 14:15:12] [profile] END   change dir \\wsl$\Ubuntu-20.04\home\gareth\ 587ms
    (note the 3-second gap; I believe this is where I hit Enter and nvim-tree moved up one directory level)
    [2023-03-11 14:15:15] [profile] START change dir \\wsl$\Ubuntu-20.04\home
    [2023-03-11 14:15:15] [profile] START core init \\wsl$\Ubuntu-20.04\home
    (after this, we have basically the same as above but one directory level higher)
    (then again a delay of a couple of seconds while I hit Enter, and then same for root directory)
    (end of log file looks like this:)
    [2023-03-11 14:15:16] [profile] END   core init \\wsl$\Ubuntu-20.04 332ms
    [2023-03-11 14:15:16] [profile] START draw
    [2023-03-11 14:15:17] [profile] END   draw 0ms
    [2023-03-11 14:15:17] [profile] END   change dir \\wsl$\Ubuntu-20.04 343ms
    [2023-03-11 14:15:18] [profile] START change dir \\wsl$
    [2023-03-11 14:15:56] [profile] START view open
    [2023-03-11 14:15:56] [profile] END   view open 17ms
    [2023-03-11 14:15:56] [profile] START draw
    [2023-03-11 14:15:56] [profile] END   draw 2ms

**Comment by alex-courtis** [comment]
Please note that I don't have any windows knowledge nor access to a windows environment to experiment with / provide fixes with.

This is a "best effort" investigation: I'll need you to answer questions and perform experiments in order to track this issue down.

Does nvim-tree work anywhere for you, or does it always fail in this manner?

> I'm running Windows 10 but a lot of what I do is in WSL (more specifically, WSL2 rather than WSL1).

What is WSL2? Is that new? How is it different to WSL1?

What's the output of:

`:lua print(require("nvim-tree.utils").is_wsl)`

`:lua print(require("nvim-tree.utils").is_windows)`

`:lua print(require("nvim-tree.utils").is_unix)`

`:lua print(vim.fn.has("wsl"));`

`:lua print(vim.fn.has("wsl1"));`

`:lua print(vim.fn.has("wsl2"));`

Remember that I'm flying blind here.

> Status line says NvimTree_1 (which I assume is normal).
> Top line of editor window says \\wsl$\Ubuntu-20.04\home\gareth\/.. (which may or may not be normal).

That is normal.

> Message below status line, in red: [NvimTree] "Could not start the fs_event watcher for path \\\\wsl$\\Ubuntu-20.04\\home\\gareth : EISDIR.

That is unusual; this behaviour should be guarded against. Bad filesystem enumeration is silently squished and disabled due to myriad inconsistencies in windows environments. #1916

EISDIR is a libuv error: "illegal operation on a directory". It might be that we have permissions for that directory but cannot read it.

Please attempt:
`git.enable` false
`filesystem_watchers.enable` false

**Comment by gjm-p** [comment]
I understand that you're not a Windows user (and that you're providing this stuff free of charge) and will absolutely not be offended by whatever consequences that has :-).

I have installed nvim + nvim-tree on two Windows machines. Both are running Windows 10. One is my employer's and probably has all sorts of weird corporate spyware installed on it. The other is my own and definitely doesn't. They both show the exact same behaviour when trying to access files in WSL2.

I am not myself a WSL expert, but I think WSL1 works by implementing the Linux syscall interface on top of the Windows kernel, whereas WSL2 runs an actual Linux kernel in a sort of lightweight virtual machine. So there are big differences in how filesystems work, and maybe also in Windows/Linux filesystem interop. WSL2 was introduced in mid-2019 and I think most WSL users use WSL2 rather than WSL1 these days.

It is possible to switch between using WSL1 and using WSL2 (either globally or for a particular WSL instance on your Windows machine). I have done this on my non-corporate machine and it didn't make any difference to the behaviour of nvim-tree, so _probably_ the differences between WSL1 and WSL2 aren't actually relevant here. (I didn't do extensive experiments with WSL1, just tried the simplest case and observed it fail the same way as before.)

Immediately after launching Vim with minimal config (to be clear, this is Vim running natively on Windows, not inside WSL):

* :lua print(require("nvim-tree.utils").is_X): false for X=wsl, false for X=unix, true for X=windows.
* :lua print(vim.fn.has("X")): 0 for X being any of wsl, wsl1, wsl2.

If I modify the minimal config file to say

    require("nvim-tree").setup { filesystem_watchers = { enable = false } }

then on doing :e with a WSL directory name I _don't_ any longer get the EISDIR error message, but I also _don't_ see any files or directories displayed. If I also turn on nvim-tree logging, then the log looks basically the same as before except for the absence of the "Watcher" and "Event" lines.

If I also say `git = { enable = false }` then the visible behaviour is exactly the same as before, and the log looks the same except that now the lines explicitly referencing git are gone too.

It seems clear that at least to some extent nvim-tree _can_ read the directory, since its logs show the contents of the directory being enumerated. Also, EISDIR is surely complaining "this is a directory and I expected something else" rather than "I can't read this and expected to be able to". I don't know whether it's helpful, but I also tried running nvim as an administrator (this is a thing you can do in Windows, it kinda-sorta corresponds to running as root except that it changes your privileges without changing your identity) and it didn't make any difference to the behaviour.

**Comment by alex-courtis** [comment]
> :lua print(require("nvim-tree.utils").is_X): false for X=wsl, false for X=unix, true for X=windows.
> :lua print(vim.fn.has("X")): 0 for X being any of wsl, wsl1, wsl2.

That is very odd; vim should be reporting wsl. However, that shouldn't be an issue as there are currently no code paths that are wsl but not windows.

> In plain nvim, if I do :e \\wsl$\Ubuntu-20.04\home\gareth then I get (no error or warning messages, but) a "Netrw Directory Listing" whose header looks normal but which shows no actual files or directories.

Re-reading it does seem that it's an nvim problem: `nvim --clean /path/to/dir` or `nvim --clean .` should show a netrw directory listing. Apologies for mis-reading that yesterday.

If the above is indeed the case, I'm afraid you'll need to raise this to the neovim project.

What does `nvim --clean some-file.txt` do when you are inside one of the affected directories? That might be useful to include in your issue.

**Comment by alex-courtis** [comment]
Looking further into windows error handling: we cannot add any further messages around directory enumeration.

Windows often presents directories such as `AppData` that are not readable and we silently ignore. Presenting errors for those will result in a lot of unwanted error spam.

**Comment by gjm-p** [comment]
It's not clear from the documentation whether `vim.fn.has("wsl")` is meant to return true (1) when _on a Windows system that supports WSL_ or (2) when _nvim is running inside WSL_. In my case 1 holds but 2 doesn't.

If I do `nvim --clean \\wsl$\Ubuntu-20.04\home\gareth` then I get an empty editor window with that pathname in the status bar. If I do the same with a directory in the ordinary Windows filesystem then I get a netrw directory listing showing the right things. If I do `cd \\wsl$\Ubuntu-20.04\home\gareth` and then `nvim --clean .` then (1) if I'm using an old-style Windows "command prompt" then the first bit doesn't work because `cmd.exe` doesn't support UNC paths as working directories and (2) if I'm using PowerShell then I get an empty editor window with `.` in the status bar.

If I do either `nvim --clean \\wsl$\path\to\an\actual\file.txt` or (in PowerShell) `cd \\wsl$\path\to\an\actual` and `nvim --clean file.txt`, the file is opened just fine. It's specifically _directory-viewing_ that's failing, both with netrw and with nvim-tree.

I agree that it seems very plausible that it's an nvim problem. Or maybe a Windows problem that traditional vim is working around somehow and nvim isn't. The other possibility is that it's just something that's easy to get wrong and netrw and nvim-tree independently did the same wrong thing.

I'll file an nvim issue and see what happens there.

**Comment by alex-courtis** [comment]
> I'll file an nvim issue and see what happens there.

Thanks @gjm-p 

Windows neovim is quite problematic.

Perhaps you'd like to try another operating system ;)

**Comment by gjm-p** [comment]
It would make me very happy to use another operating system, and I mostly do when not at work, but alas commercial realities are what they are.
