### ISSUE TITLE
[Possible Regression?] Can no longer map `require("nvim-tree").toggle` to key

### ISSUE THREAD

**Issue by leon-richardt** [nvim-tree/nvim-tree.lua#2054]
### Description

After updating via `:PackerSync`, neovim complained with the following error on starting a new nvim instance:
```
Error in packer_compiled: vim/keymap.lua:0: rhs: expected string|function, got nil
Please check your config for correctness
```

It appears that `require("nvim-tree").toggle` can no longer be mapped to a key combination.

The last working commit is f0a1c6ae2eeaefcb693dc1a319150c52e64397b0 and fe980baa945100d92f77fe55e2ca113cae1b1bd3 is the first one to cause the error.

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux 6.2.2-arch2-1

### nvim-tree version

fe980ba

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup { }
  vim.keymap.set("n", "<Space>di", require("nvim-tree").toggle)
end
```

### Steps to reproduce

1. `nvim -nu tmp/nvt-min.lua`

### Expected behavior

Normal startup without errors, as prior to commit fe980ba.

**Comment by leon-richardt** [comment]
I think I solved this myself after looking into the docs a little longer. Defining the keymap like so resulted in expected behavior:
```lua
local api = require("nvim-tree.api")

vim.keymap.set("n", "<leader>di", api.tree.toggle)
```

I guess this was my bad for not sticking to the exposed stable API. Is this solution the correct one? If so, please feel free to close the issue, and sorry for the noise.

**Comment by gegoune** [comment]
This is correct indeed, commit you linked to shows
https://github.com/nvim-tree/nvim-tree.lua/commit/fe980baa945100d92f77fe55e2ca113cae1b1bd3#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aL362-L363
which is removal of various non-api functions that should have never been exposed in the first place.

Your solution is in correct.

**Comment by leon-richardt** [comment]
Thank you! Closing under the assumption that
> Your solution is in correct.
 
should evaluate to "indeed correct" and not "incorrect" :smile:

**Comment by alex-courtis** [comment]
> non-api functions that should have never been exposed in the first place.

Please accept my apologies: I did remove those non-API functions without notice: `require("nvim-tree").toggle` and `open`.

`find_files` was removed with a warning and grace period, I should have done the same for the above.

**Comment by leon-richardt** [comment]
No worries at all, my fault for not sticking to the documented behavior ;)

Hopefully this can serve as a google-able issue for others running into a similar issue.
