### ISSUE TITLE
change-dir have an error when open a new terminal

### ISSUE THREAD

**Issue by BYT0723** [nvim-tree/nvim-tree.lua#2057]
### Description

neovim report an error when open a terminal.
![图片](https://user-images.githubusercontent.com/59989961/224973532-f289e0fb-998e-440b-9960-f05ed60c6e9b.png)
Message means "Command execution failed"

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.1.19-1-lts

### nvim-tree version

1d79a64

### Minimal config

```lua
require("nvim-tree").setup({ -- BEGIN_DEFAULT_OPTS
	auto_reload_on_write = true,
	disable_netrw = false,
	hijack_cursor = false,
	hijack_netrw = true,
	hijack_unnamed_buffer_when_opening = false,
	ignore_buffer_on_setup = false,
	open_on_setup = false,
	open_on_setup_file = false,
	open_on_tab = false,
	sort_by = "name",
	respect_buf_cwd = false,
	view = {
		width = 40,
		hide_root_folder = false,
		side = "left",
		preserve_window_proportions = false,
		number = false,
		relativenumber = false,
		signcolumn = "yes",
		mappings = {
			custom_only = false,
			list = require("keybindings").nvim_tree(),
		},
	},
	renderer = {
		indent_markers = {
			enable = false,
			icons = {
				corner = "└ ",
				edge = "│ ",
				none = "  ",
			},
		},
		icons = theme.nvim_tree,
	},
	hijack_directories = {
		enable = true,
		auto_open = true,
	},
	update_focused_file = {
		enable = true,
		update_root = true,
		ignore_list = {},
	},
	ignore_ft_on_setup = {},
	system_open = {
		cmd = "xdg-open",
		args = {},
	},
	diagnostics = {
		enable = true,
		show_on_dirs = true,
		icons = {
			error = theme.diagnostic.error,
			warning = theme.diagnostic.warn,
			hint = theme.diagnostic.hint,
			info = theme.diagnostic.info,
		},
	},
	filters = {
		dotfiles = false,
		custom = {},
		exclude = {},
	},
	git = {
		enable = true,
		ignore = false,
		timeout = 400,
	},
	actions = {
		use_system_clipboard = true,
		change_dir = {
			enable = true,
			global = false,
			restrict_above_cwd = false,
		},
		open_file = {
			quit_on_open = true,
			resize_window = true,
			window_picker = {
				enable = true,
				chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
				exclude = {
					filetype = { "notify", "packer", "qf", "diff", "fugitive", "fugitiveblame" },
					buftype = { "nofile", "terminal", "help" },
				},
			},
		},
	},
	trash = {
		cmd = "gio trash",
		require_confirm = true,
	},
	log = {
		enable = false,
		truncate = false,
		types = {
			all = false,
			config = false,
			copy_paste = false,
			diagnostics = false,
			git = false,
			profile = false,
		},
	},
})
```

### Steps to reproduce

1. open neovim
2. NvimTreeOpen then open a terminal 

### Expected behavior

Errors will not affect the work of nvim-tree. when buftype is terminal, don't change-dir

**Comment by zLinz** [comment]
The same

**Comment by cabaret** [comment]
I'm also seeing this, I suppose since the last update?

I noticed this when running tests using vim-test, but that's the same case as OP describes: opening a new terminal with nvim-tree open.

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/625152/225439499-32fbf9d2-7720-47bb-8b1c-c2f8c8d6180c.png">

**Comment by efren-yuen** [comment]
![7](https://user-images.githubusercontent.com/39547112/225479183-fb4d2f1a-c40d-4fef-b191-ec1dea6c4a15.png)

**Comment by nshen** [comment]
same here, when open terminal for the first time

**Comment by AllenDang** [comment]
same here

**Comment by vukieuhaihoa** [comment]
![Screenshot from 2023-03-16 15-21-39](https://user-images.githubusercontent.com/48436562/225563406-831541bd-9bda-4b95-a57e-431b0e25a13b.png)
the same with me, when i open toggle terminal at the first time, but after that it does not appear

**Comment by BYT0723** [comment]
```lua
	update_focused_file = {
		enable = true,
		update_root = true,
		ignore_list = { "toggleterm" },
	},

```
just ignore termnial filetype

**Comment by BYT0723** [comment]
![图片](https://user-images.githubusercontent.com/59989961/225789208-29a6106d-510b-488a-a40f-3cfb8a32fc8e.png)
skip filetype of ignore_list, add skipping buftype, eg { terminal , notfile, quickfix }

**Comment by vukieuhaihoa** [comment]
> ```lua
> 	update_focused_file = {
> 		enable = true,
> 		update_root = true,
> 		ignore_list = { "toggleterm", "term" },
> 	},
> ```
> 
> just ignore termnial filetype

when you user default terminal instead using toggleterm, please using above config. Thank @BYT0723

**Comment by cptchuckles** [comment]
I get this error also, when using Hoffs/omnisharp-extended-lsp.nvim and opening metadata and source-generated C# buffers.

`$metadata$` buffers were easy enough to add to the `ignore_list`... But for generated source files, I don't see a reliable convention to base an `ignore_list` item on; they just look like regular C# files, except that they don't exist.

source-generated buffer:
![image](https://user-images.githubusercontent.com/32113038/225797602-22630a18-a363-47f4-bc50-998e462d772c.png)

**Comment by alex-courtis** [comment]
Minimum to replicate:

```lua
	update_focused_file = {
		enable = true,
		update_root = true,
	},
```
