### ISSUE TITLE
API: Tree Is Open

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2064]
view.is_open() can and is used: https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#workaround-when-using-rmagattiauto-session

There is no API to achieve this.

`api.tree.is_open` or `api.tree.state.open` might be appropriate.

Multiple tabs could be handled with, say, an argument current tab or all tabs.

See https://github.com/nvim-tree/nvim-tree.lua/issues/1992#issuecomment-1475456513

/cc @nikolasmish

**Comment by Juniokoi** [comment]
There is `require('nvim-tree.view').is_visible()`

**Comment by gegoune** [comment]
That's not part of contractual API though.

**Comment by alex-courtis** [comment]
> That's not part of contractual API though.

Yes. They would probably be the same under the hood.

**Comment by alex-courtis** [comment]
`nvim-tree-api.tree.is_visible()` was added.

**Comment by timblaktu** [comment]
@alex-courtis could you clarify how this new api affects [the workaround](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#workaround-when-using-rmagattiauto-session)?

**Comment by alex-courtis** [comment]
> @alex-courtis could you clarify how this new api affects [the workaround](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#workaround-when-using-rmagattiauto-session)? Would it be:

Yes. I thought I updated that, however it looks like it was recently changed.

Please test and update the wiki page on success.
