### ISSUE TITLE
[Discrepency] Refocusing open tree makes tree collapse on Window, but remains open on Linux

### ISSUE THREAD

**Issue by MostHated** [nvim-tree/nvim-tree.lua#2069]
Hey there,
I had a question about a discrepency that I am experiencing between linux and windows. I noticed it when I have the file tree open and have an additional split, so that there is the tree and two other buffers visible. 

If I am in a split code1 or code1 and I move the cursor back over to nvim-tree, on linux, everything is good. 
On my Windows work vm, the tree essentially is.. reset? I guess is best way to describe it. Once the tree is focused, all expanded folders are closed. If I move the cursor over to one of the open buffers, the folder that the file is located in expands again, but once I focus the tree again, they all close.

The settings for everything are exactly the same, as I have an autocommand that detects buffer write on my desktop, the linux host, which then uses rclone to sync my nvim config to a folder which is mounted in my Windows VM. 
Then upon opening a terminal in Windows, it checks for a .update file in that folder and copys the nvim files to the appropriate Windows nvim location, but this is configuration only, not runtime files, so the actual platform specific installation files of plugins are proper.

I have an example of the behavior below:

Linux:

https://i.imgur.com/CQ4ZzpC.gifv

Windows:

https://i.imgur.com/20UUWpB.gifv

I am not sure if this is considered a bug, or if there is even anything I can do to fix it, but I wanted to throw it out there in case anyone happens to have any suggestions, or came across this befoe and know of something I might be able to do to stop the behavior.

Thanks,
-MH

**Comment by alex-courtis** [comment]
Please raise a [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) and complete all the required fields.

When replicating this issue it is important to use [Clean Room Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) as it sounds like you have automation that may interfere with nvim-tree.

Please ensure that you are using the same versions of nvim, nvim-tree etc.
