### ISSUE TITLE
Have a way of sorting files with numbers naturally

### ISSUE THREAD

**Issue by Joemilne** [nvim-tree/nvim-tree.lua#2071]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have an option in setup to sort files that contain numbers naturally:

```
~/Folder/ 
    File1.txt  
    File2.txt  
    File5.txt  
    File8.txt  
    File12.txt  
    File15.txt  
    File24.txt  
    File25.txt  
    File26.txt
```

**Comment by gegoune** [comment]
Yes, it's because of how that example sorting works. Apologies for quick response earlier, should have added that you will need to write custom sorter that does exactly what you want. If I recall correctly someone already talked about it in some other issue. Worth searching through closed ones.

**Comment by Joemilne** [comment]
Ah I see. I had a look into it and came across this solution (although I believe its only half completed):

```
  local sort_by = function(nodes)
    table.sort(nodes, function(a, b)
      local a_num = string.match(a.name, "^[0-9]+")
      local b_num = string.match(b.name, "^[0-9]+")
      if a_num and b_num then
        return a_num < b_num
      else
        -- we need to do something here
        return false
      end
    end)
  end
```

However, I'm very new to Lua, and am unsure how to go about tackling this function, or implementing it into Nvim-tree.setup()

Is there any advice you could give me?
Thank you for your help and time

**Comment by gegoune** [comment]
Once you come up with function, such as above you can then assign it to `sort_by` like:

```lua
require('nvim-tree').setup({
  sort_by = sort_by
})
```
amongst other options you might be setting. Does that help?

**Comment by Joemilne** [comment]
Yes that helps! When it comes to the function, my understanding is that the comment under the else statement if for the cases when Nvim-tree is not trying to sort two nodes containing numbers. For example, comparing numbers to letters:

```
~/Folder/
    File1.txt
    FileA.txt
```

how would I complete this function if I wanted it to fall back to default `sort_by = "name"`?
Thank you!

**Comment by gegoune** [comment]
I am not sure what default sorting look like, you might be able to find it in code, but probably regular alphabetical sorting there should be fine.

**Comment by alex-courtis** [comment]
I recall some discussion of providing a fallback of sorts, by returning one of the built in strings from the function e.g. `"name"`, `"extension"`.

Looking.

**Comment by alex-courtis** [comment]
Couldn't find any discussions or issue; raised #2079
