### ISSUE TITLE
Error executing vim.schedule lua callback: .../nvim-tree.lua/lua/nvim-tree/actions/root/change-dir.lua:50: Vim(lcd):E472: Command failed

### ISSUE THREAD

**Issue by ichigo-dev** [nvim-tree/nvim-tree.lua#2074]
### Description

<img width="953" alt="nvim" src="https://user-images.githubusercontent.com/118079373/227207694-58f409e9-39d2-4fbf-b74e-9f650eac8e4c.png">

When I open Nvim's terminal mode after opening NvimTree, I get an error like the attached image.

Both Nvim's terminal mode and NvimTree are working fine, and this happens the moment I start them both. Even stranger, this only happens the first time the two elements are combined (and not the second time onwards).

I've also seen similar errors not only in Nvim's terminal mode, but also in combination with [FzfLua](https://github.com/ibhagwan/fzf-lua). That did not happen when using [Telescope](https://github.com/nvim-telescope/telescope.nvim).

Finally, thank you for developing this wonderful plugin! (Along with my poor English)

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

WSL2 version 1.1.3.0, ArchLinux version 2023.03.01

### nvim-tree version

1d79a64

### Minimal config

```lua
https://github.com/ichigo-dev/riovim

I'm sorry, I tried building a minimal configuration, but I couldn't reproduce it. The link above is all of my configurations.
```

### Steps to reproduce

1. Open NvimTree with `<cmd> NvimTreeToggle <CR>`
2. Open terminal mode with `<cmd> terminal <CR>`

**Comment by alex-courtis** [comment]
> Sincerest apologies. Resolved in this issue.
> 
> [#2057](https://github.com/nvim-tree/nvim-tree.lua/issues/2057)

No worries, thanks for reporting.
