### ISSUE TITLE
Add descriptions to commands via `vim.api.nvim_create_user_command`

### ISSUE THREAD

**Issue by mrjones2014** [nvim-tree/nvim-tree.lua#2076]
**Is your feature request related to a problem? Please describe.**

Trying to build a good `legendary.nvim` extension for `nvim-tree.lua`

**Describe the solution you'd like**

You create the commands here: https://github.com/nvim-tree/nvim-tree.lua/blob/aa9971768a08caa4f10f94ab84e48d2ceb30b1c0/lua/nvim-tree.lua#L245-L280

The `vim.api.nvim_create_user_command` function accepts a `desc` field to provide a description that will be shown if you look up the commands via the Neovim API.

**Describe alternatives you've considered**

Hard-coding the descriptions.

**Additional context**

https://github.com/mrjones2014/legendary.nvim/pull/320

**Comment by alex-courtis** [comment]
That's a great idea; thanks for letting me know that we can do this.
