### ISSUE TITLE
NvimTreeFindFile no longer keeps focus in tree buffer

### ISSUE THREAD

**Issue by drewbailey** [nvim-tree/nvim-tree.lua#2078]
### Description

Introduced in https://github.com/nvim-tree/nvim-tree.lua/pull/2039

:NvimTreeFindFile no longer keeps focus in the NvimTree view.

### Neovim version

```text
NVIM v0.9.0-dev-2079+g964ae205a-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macos

### nvim-tree version

f0a1c6a

### Minimal config

```lua
require('nvim-tree').setup()

local function open_nvim_tree(data)

  -- buffer is a directory
  local directory = vim.fn.isdirectory(data.file) == 1

  if not directory then
    return
  end

  -- change to the directory
  vim.cmd.cd(data.file)

  -- open the tree
  require("nvim-tree.api").tree.open()
end

vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
```

### Steps to reproduce

:NvimTreeFindFile

### Expected behavior

focus / cursor highlights file in nvim tree

### Actual behavior

Nvim tree directory opened to file, focus goes back to buffer

**Comment by gegoune** [comment]
You need to update your call to `open()`. As per `:h nvim-tree.api.tree.open()`:

```
      • {find_file}      (boolean, false) find the current buffer
```

**Comment by alex-courtis** [comment]
Apologies, that was a hardcoded effect of the command that wasn't migrated to the API call.

Please test the fix:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2078-NvimTreeFindFile-focus-tree
```
