### ISSUE TITLE
find_file does not check whether the bufname is readable now.

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2081]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/2077

<div type='discussions-op-text'>

<sup>Originally posted by **91he** March 24, 2023</sup>
Nvimtree changes root dir in spite of current buf's name is not a readable file. 
I am not sure if this is by design. But i think it would be better if we do a check before changing root.</div>

**Comment by alex-courtis** [comment]
Regression from fe980ba

**Comment by alex-courtis** [comment]
@91he I would be most grateful if you tested the fix:

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2081-find-file-ignore-inexistent-files
```

I may have missed a use case...

**Comment by 91he** [comment]
> @91he I would be most grateful if you tested the fix:
> 
> ```shell
> cd /path/to/nvim-tree.lua
> git pull
> git checkout 2081-find-file-ignore-inexistent-files
> ```
> 
> I may have missed a use case...

@alex-courtis It works. You solved my problem.
