### ISSUE TITLE
Allow user to supply their own `get_icon` function to set file icons and highlights

### ISSUE THREAD

**Issue by devkvlt** [nvim-tree/nvim-tree.lua#2085]
For example, add an option `renderer.icons.glyphs.get_icon_func` that expects a function that takes filename, extension and options(?) as input and returns an icon and a highlight group.

**Comment by alex-courtis** [comment]
That could work. I'd prefer not to expose the node, however we could clone most of the node's data.

Two callbacks might be preferable `get_icon` `get_hl`.

**Comment by alex-courtis** [comment]
#2415 `Decorator`s may be enhanced to with a user callback.

**Comment by alex-courtis** [comment]
Tracking at #2948
