### ISSUE TITLE
docs: improve `api.node.open.edit` and `api.node.open.preview`

### ISSUE THREAD

**Issue by gegoune** [nvim-tree/nvim-tree.lua#2105]
Testing with 9c97e64 (before on_attach): preview does nothing on the root directory.

However, the change-dir does make sense and brings it in line with open.

How about this help:
```help
api.node.open.edit()                          *nvim-tree.api.node.open.edit()*
    File:   open as per |nvim-tree.actions.open_file|
    Folder: expand or collapse
    Root:   change directory up

api.node.open.preview()                    *nvim-tree.api.node.open.preview()*
    Perform |nvim-tree.api.node.edit()|
    File buffer will have |bufhidden| set to `delete`.
```

_Originally posted by @alex-courtis in https://github.com/nvim-tree/nvim-tree.lua/pull/2099#discussion_r1155493047_

**Comment by gegoune** [comment]
Apologies @alex-courtis, have merged it on my phone without seeing those comments first.

**Comment by alex-courtis** [comment]
Heh no worries. I'm documenting some of the other api.node functions from the bottom up right now.

**Comment by alex-courtis** [comment]
It's done.
