### ISSUE TITLE
Mappings Executed In Help View

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2109]
### Description

Mappings are executed in help mode. Fails most actions e.g. `a`

`E5108: Error executing lua: ...t/nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:34: attempt to index field 'absolute_path' (a nil value)`

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux  6.2.9-arch1

### nvim-tree version

d1410cb

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

`g?`
`a`

### Expected behavior

No action.

### Actual behavior

`E5108: Error executing lua: ...t/nvim-tree.lua/lua/nvim-tree/actions/fs/create-file.lua:34: attempt to index field 'absolute_path' (a nil value)`

**Comment by alex-courtis** [comment]
Find file is also executed when the help view is active.

**Comment by alex-courtis** [comment]
Needed:
* disable all mappings in help view
* close help view when leaving tree

**Comment by alex-courtis** [comment]
Fixes to the help view are complex and problematic.

A more pragmatic solution might be a popup window.

**Comment by gegoune** [comment]
Could get floating window drawn over tree's window imitating current look. Not sure if floating windows inherit buffer local key mappings.

**Comment by alex-courtis** [comment]
> Not sure if floating windows inherit buffer local key mappings.

Created a scratch buffer which doesn't inherit any nvim-tree mappings: #2120

> imitating current look

That's a work in progress...
