### ISSUE TITLE
If a custom window_picker creates a new window for this buffer, nvim-tree doesn't use that new window

### ISSUE THREAD

**Issue by IndianBoy42** [nvim-tree/nvim-tree.lua#2126]
### Description

I have a fork of nvim-window-picker (https://github.com/IndianBoy42/nvim-window-picker/tree/pick_or_create) that supports a pick_or_create function. This would create a window if the correct labels are used and returns that window id.  I tried to use that for the nvim-tree window picker:
```
  actions = {
    open_file = {
      window_picker = {
        picker = function() return require("window-picker").pick_or_create() end,
      },
    },
  },
```
The problem is that it assumes this window id is invalid because it didn't exist before picker was called, so it just creates a new window. I don't think this behaviour is a good idea, at most a warning could be given if a window is chosen that seems invalid. If the default picker is used then by construction the window id is invalid. If a custom picker is used then clearly that's what the user wanted, or its a bug in the picker that nvim-tree doesn't have to try and work around. The only condition that the window id should meet is that its possible to switch to it and run `:edit`, this condition can be checked by just trying to do those things within pcall

I can submit a PR for this I just wanted to know what approach you think is right? how much 'error checking' should be done on the target_winid returned by pickers

### Neovim version

```text
NVIM v0.9.0-dev-1350+gdd80ee0ca
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

6.2.6-76060206-generic

### nvim-tree version

d1410cb

### Minimal config

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"nvim-tree/nvim-tree.lua",
			"nvim-tree/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
			{ "indianboy42/nvim-window-picker", branch = "release/2.0" },
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("window-picker").setup()
	require("nvim-tree").setup({
		actions = {
			open_file = {
				window_picker = {
					picker = function()
						return require("window-picker").pick_or_create()
					end,
				},
			},
		},
	})
end
```

### Steps to reproduce

1. `nvim -u /tmp/nvt-min.lua`
2. `:NvimTreeOpen`
3. navigate to any file and `<CR>`
4. Use the labels to create a new window, one of  `hjkl` if only one existing window or `hjkl+` a label at the center of a window

### Expected behavior

New window is created in the direction specified by the labels (this happens because window-picker is responsible for it), and the file chosen in nvim-tree is opened in that new window

### Actual behavior

A new window right next to the nvim-tree is created with the file chosen in nvim-tree

[Screencast from 04-11-2023 09:40:57 PM.webm](https://user-images.githubusercontent.com/5981889/231181850-75082b4f-7382-47dd-aec4-a1087846ccd4.webm)

the labels I used for the picker were `j` and `js` respectively, you can see the new window created but the file going to a completely new window

**Comment by alex-courtis** [comment]
The picker is working correctly with the default and s1n7ax/nvim-window-picker - they does exactly what is specified: picking an existing window.

Creating a window is not behaviour we anticipated or expected.

May I suggest a pragmatic workaround:
* `window_picker.enable = false`
* map an nvim-tree open function:
  * create a window via `pick_or_create`
  * select that window
  * open the file

I'm happy to take a look at a PR, however it would need to be completely non-intrusive as to not break existing users.
