### ISSUE TITLE
When opening files within folders named like: (app) the files are not showing any contents.

### ISSUE THREAD

**Issue by tgienger** [nvim-tree/nvim-tree.lua#2137]
### Description

I started using nvim-tree because in sveltekit the folder names contain [id] for routing and (app) for custom layouts. Netrw does not show the contents of folders with [brackets] and now for some reason when I open a file using nvim-tree and telescope the file itself is blank. Like it's just an empty buffer? I'm still very new to this stuff so I'm not sure what's going on. 

Netrw on the other hand displayes the (folder) files and opens them properly. So for now I have both :(

### Neovim version

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### nvim-tree version

latest

### Minimal config

```lua
require('nvim-tree').setup()
```

### Steps to reproduce

create a folder in parenthesis (folder) and place a text file inside. Open the file through nvim-tree 

### Expected behavior

The file should open and you should see it's contents.

### Actual behavior

The file seemingly opens, but it appears completely blank.

**Comment by alex-courtis** [comment]
> Netrw does not show the contents of folders with [brackets] and now for some reason when I open a file using nvim-tree and telescope the file itself is blank.

This does not appear to be an nvim-tree issue, as it affects netrw and telescope. This indicates that neovim is having difficulties seeing and opening files with special characters.

Closing this; please raise an issue at https://github.com/neovim/neovim outlining the steps to reproduce the issue via netrw.
