### ISSUE TITLE
API tree.toggle() not working after the udpate.

### ISSUE THREAD

**Issue by AGou-ops** [nvim-tree/nvim-tree.lua#2139]
### Description

```lua
require("nvim-tree.api").tree.toggle(false, true)
```

Not working after commit [f3dbddf](https://github.com/nvim-tree/nvim-tree.lua/commit/f3dbddf8b3fbd5de7c8838eafc1b3b72cd30c73e).

https://user-images.githubusercontent.com/57939102/232204835-65c28a86-4a46-4dc7-9e93-a19aac0058a6.mp4

### Neovim version

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

MacOS 13.3.1

### nvim-tree version

6ad5c26

### Minimal config

```lua
local function open_nvim_tree(data)
    local IGNORED_FT = { 'dashboard' }

    -- buffer is a real file on the disk
    -- local real_file = vim.fn.filereadable(data.file) == 1

    -- buffer is a [No Name]
    -- local no_name = data.file == '' and vim.bo[data.buf].buftype == ''

    -- &ft
    local filetype = vim.bo[data.buf].ft

    -- only files please
    -- if not real_file and not no_name then
    --     return
    -- end

    -- skip ignored filetypes
    if vim.tbl_contains(IGNORED_FT, filetype) then
        return
    end

    -- open the tree but don't focus it
    require('nvim-tree.api').tree.toggle(false, true)
end

vim.api.nvim_create_autocmd({ 'VimEnter' }, { callback = open_nvim_tree })

function M.config()
    if vim.g.started_by_firenvim then
        return
    end

    local status_ok, nvim_tree = pcall(require, 'nvim-tree')
    if not status_ok then
        return
    end

    -- setup with all defaults
    -- each of these are documented in `:help nvim-tree.OPTION_NAME`
    nvim_tree.setup({)}
end
```

Link to this issue #2138.

**Comment by gegoune** [comment]
You must run setup before calling any api functions.

**Comment by AGou-ops** [comment]
Not work, it's same.

**Comment by cevhyruz** [comment]
I think this is because the arguments were not being passed from the wrapper function.

Can you confirm if #2141 resolve the issue for you?

**Comment by AGou-ops** [comment]
@cevhyruz Yes, it works.

**Comment by gegoune** [comment]
I have just tested it and running
```lua
require("nvim-tree.api").tree.toggle(false, true)
```
on my personal configuration (after `setup()`)and it works.

Also, please notice that this usage pattern is obsolete:

```lua
---Toggle the tree.
---@param opts ApiTreeToggleOpts|nil|boolean legacy -> opts.find_file
---@param no_focus string|nil legacy -> opts.focus
---@param cwd boolean|nil legacy -> opts.path
---@param bang boolean|nil legacy -> opts.update_root
```

What you want is
```lua
require("nvim-tree.api").tree.toggle({find_file=false, focus=true})
```

Going to close this issue as it seems to be user configuration problem, since:

```sh
nvim --clean --noplugin -c 'set rtp+=~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua' -c 'lua require("nvim-tree").setup({})' -c 'lua require("nvim-tree.api").tree.toggle({find_file=false, focus=true})'
```
works as expected and no replication steps were provided.

**Comment by AGou-ops** [comment]
@gegoune Thanks.

I copied that config from `wiki Tops`.🤣

https://github.com/nvim-tree/nvim-tree.lua/wiki/Tips#toggle-tree-without-focusing-explorer

**Comment by gegoune** [comment]
Ah, I see. Thanks for letting us know. I have updated wiki, but it feels like duplicating documentation.

Did you manage to solve your issue? I would start by running command I pasted in previous comment, that should work without errors, if so then issue is somewhere within your configuration.

**Comment by alex-courtis** [comment]
> Ah, I see. Thanks for letting us know. I have updated wiki, but it feels like duplicating documentation.

Some of those are a bit out of date - pre API.

I might tidy some of those e.g. vinegar
