### ISSUE TITLE
Support for git's `worktrees`

### ISSUE THREAD

**Issue by pseudoparenchymatous** [nvim-tree/nvim-tree.lua#2142]
**Is this a question?**
No. 

**Can this functionality be implemented utilising API?**
No. 

**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
[Gitsigns](https://github.com/lewis6991/gitsigns.nvim/ ) has this feature. 
```lua
require('gitsigns').setup({
    worktrees = {
        {
            toplevel = '~/projects/sample/', 
            gitdir = '~/projects/sample/.not-defaut-gitdir/',
        }, 
        { ... },
    }
}
```
In case getting git info fails, it will try to look at these worktrees with basically a custom name of the `.git` directory (bare-repository). Nvim-tree having the same feature would be 😍. 

**Describe alternatives you've considered**
I tried looking at the source code to try to hard code it but I don't understand your implementation lol. I managed to hard-code it in [lualine](https://github.com/nvim-lualine/lualine.nvim) (that plugin also doesn't support this feature).

**Comment by pseudoparenchymatous** [comment]
Here's an example:
![IMG_20230417_151132](https://user-images.githubusercontent.com/105337186/232412341-c9281446-e3de-470e-bbd5-499803d2c280.jpg)

Both `file.txt` are untracked but only the one in `traditional_repository` has a star sign. That's because it's assumed that the `.git` directory is inside the `traditional_repository` and it is indeed found. The presumed `.git` directory for `actual_repository` is actually outside of the nested directory and its actual name is `.bare_repo` not `.git`.

If want to do git work on `actual_repository`, I have to do:
```sh
$ git --git-dir ../../../.bare_repo --work-tree . status
$ git --git-dir ../../../.bare_repo --work-tree . add file.txt
$ git --git-dir ../../../.bare_repo --work-tree . commit -m 'git message' 
$ git --git-dir ../../../.bare_repo --work-tree . log
```

So what gitsigns is doing is letting users give arguments to the `--git-dir` and `--work-tree` flags to its git runner.

**Comment by alex-courtis** [comment]
Failed attempt at replication:

```sh
:; mkdir 2142
:; cd 2142
:; mkdir master
:; cd master
:; git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/alex/2142/master/.git/
:; echo foo > bar
:; echo foo > baz
:; git add bar baz
:; git commit -a -m "add two files"
[master (root-commit) 1daa303] add two files
 2 files changed, 2 insertions(+)
 create mode 100644 bar
 create mode 100644 baz

:; git worktree add ../one -b one
Preparing worktree (new branch 'one')
HEAD is now at 1daa303 add two files
:; git worktree add ../two -b two
Preparing worktree (new branch 'two')
HEAD is now at 1daa303 add two files

:; cd ..
:; vi

modify master/bar
modify one/baz
add master/foo
add one/oof
```

![20230418_121013](https://user-images.githubusercontent.com/1505378/232651945-481baf23-3442-4882-a17c-91ae289d9110.png)

**Comment by alex-courtis** [comment]
Please do not take offense:

Perhaps your workflow is incorrect:
* there are multiple plugins that do not support your needs
* operations such as find file (

**Comment by alex-courtis** [comment]
Please do not take offense:

Perhaps your workflow is incorrect:
* there are multiple plugins that do not support your needs
* operations such as opening a file via, say, telescope plugin or `:e **/` are difficult as they will match the file in all worktrees
* LSP

**Comment by alex-courtis** [comment]
This is an edge case that has only been reported by yourself.

I'll accept a PR to support this providing:
1. It does not affect existing functionality
2. No additional git operations are executed

**Comment by pseudoparenchymatous** [comment]
I mean all I'm asking is whenever `nvim-tree` runs a `git` command under the hood and it fails (i.e. not on a git repo), run the `git` command again but this time supply the `--git-dir` and `--work-tree` flags to the `git` command according to the the options given to `nvim-tree.setup()`. 
I'm still studying your implementation of the git feature, so I might come up with a PR for this when I fully understand it. But thanks for listening to my problem 🥲

**Comment by alex-courtis** [comment]
> run the `git` command again but this time supply the `--git-dir` and `--work-tree` flags to the `git` command according to the the options given to `nvim-tree.setup()`.

I'm not sure we can do that; we cannot afford the overhead of extra git calls.

I don't quite understand your use case and the problem itself. If you supply a reproducer as per my attempt here https://github.com/nvim-tree/nvim-tree.lua/issues/2142#issuecomment-1512336781 we might come to a simple resolution.

**Comment by alex-courtis** [comment]
Please note that if a PR is submitted a reproducer is required so that it may be tested.

**Comment by pseudoparenchymatous** [comment]
Reproduce with this (you are at the home directory `~` and using `bash`) 
```bash
$ mkdir example
$ cd example
$ git init --bare sample-bare
$ mkdir -p nested/dir/ect/ory/work
$ cd nested/dir/ect/ory/work
$ alias git-bare="git --git-dir ~/example/sample-bare --work-tree ~/example/nested/dir/ect/ory/work"
$ echo foo > bar
$ echo foo > baz
$ git-bare add bar baz
$ git-bare commit -m 'add two files'
$ vim
modify work/bar
add work/foo
```
Now `nvim-tree` will look something like this:
![IMG_20230418_185727](https://user-images.githubusercontent.com/105337186/232758222-12b3eeca-1529-45a0-b0d9-2e21e6f354d0.jpg)
But I want it to look like so, and this commit 36aa86a made it work:
![IMG_20230418_185853](https://user-images.githubusercontent.com/105337186/232758839-e28410cb-3c82-4576-acda-d632f86101fb.jpg)

If you're wondering why I have this workflow it's because of [this](https://www.atlassian.com/git/tutorials/dotfiles) and managing dotfiles like this isn't that [uncommon](https://github.com/lewis6991/gitsigns.nvim/blob/372d5cb485f2062ac74abc5b33054abac21d8b58/doc/gitsigns.txt#L568).

I hope I managed to explain my problem clearly with no confusion 🙏

**Comment by alex-courtis** [comment]
Thank you, that home directory is the missing piece. I'll attempt a replicator this weekend.

Possibly related #1966

**Comment by salimhamed** [comment]
This feature is helpful when your git folder is not located in `.git/` at the root of the project. An example use-case I'm running into is using [`yadm`](https://yadm.io/) for version controlling dotfiles. `yadm` uses a non standard `GIT_DIR` located at `.local/share/yadm/repo.git`. As a result, git annotations for files tracked with `yadm` are not showing up in nvim-tree.

[gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim/) was mentioned in the original post, so it's worth noting [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim/) has native support for yadm through the plugin configuration options.

**Comment by alex-courtis** [comment]
> `yadm` uses a non standard `GIT_DIR` located at `.local/share/yadm/repo.git`.

That may be resolved via #2012

**Comment by alex-courtis** [comment]
> I hope I managed to explain my problem clearly with no confusion pray

I've replicated that nicely. Git status cannot be seen by:
* nvim-tree
* gitsigns
* fugitive

After setting the following:
```sh
GIT_DIR=/home/alex/example/sample-bare
GIT_WORK_TREE=/home/alex/example/nested/dir/ect/ory/work
```
* nvim-tree OK
* gitsigns OK
* fugitive doesn't see the worktree but does see the apparently empty repo

**Comment by alex-courtis** [comment]
There is no reference to `nested/dir/ect/ory/work` anywhere in `sample-bare`, nor any reference to `sample-bare` in the worktree.
=> automatic detection cannot be achieved.

Pragmatic solution:
Set `GIT_DIR` and `GIT_WORK_TREE`.
You are already using an alias with those values; set them at the time you create the alias.
The alias is hardcoded, implying that you change it to suit the repo you are working within. Setting the environment variable at the same time is acceptable.
You could actually improve your workflow by removing the alias and using environment variables instead.

**Comment by alex-courtis** [comment]
Unless we can achieve completely automatic detection, this should not go in nvim-tree.

Adding nvim-tree configuration to set git dir and worktree for hardcoded paths is outside of the responsibility of nvim-tree. It can be achieved without nvim-tree.

Here's an example you can start with:

```lua
vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = function(data)
  print(vim.fn.getcwd())
  -- decide these based on cwd
  vim.env.GIT_DIR = "/home/alex/example/sample-bare"
  vim.env.GIT_WORK_TREE = "/home/alex/example/nested/dir/ect/ory/work"
end })

vim.api.nvim_create_autocmd({ "DirChanged" }, { callback = function(data)
  print("new directory " .. data.file)
  -- decide these based on data.file or vim.fn.getcwd()
  vim.env.GIT_DIR = "something"
  vim.env.GIT_WORK_TREE = "something"
end })
```

**Comment by pseudoparenchymatous** [comment]
> Unless we can achieve completely automatic detection, this should not go in nvim-tree.
> 
> Adding nvim-tree configuration to set git dir and worktree for hardcoded paths is outside of the responsibility of nvim-tree. It can be achieved without nvim-tree.
> 
> Here's an example you can start with:
> 
> ```lua
> vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = function(data)
>   print(vim.fn.getcwd())
>   -- decide these based on cwd
>   vim.env.GIT_DIR = "/home/alex/example/sample-bare"
>   vim.env.GIT_WORK_TREE = "/home/alex/example/nested/dir/ect/ory/work"
> end })
> 
> vim.api.nvim_create_autocmd({ "DirChanged" }, { callback = function(data)
>   print("new directory " .. data.file)
>   -- decide these based on data.file or vim.fn.getcwd()
>   vim.env.GIT_DIR = "something"
>   vim.env.GIT_WORK_TREE = "something"
> end })
> ```

Doing this makes the git feature not work when viewing `work` while `cwd` is not related to `work` or `example`
![IMG_20230422_165831](https://user-images.githubusercontent.com/105337186/233774520-0ff3337b-e459-4b0f-90bc-180510c27008.jpg)
Should be
![IMG_20230422_165919](https://user-images.githubusercontent.com/105337186/233774531-1993e359-4e5b-4c6c-ae9f-0d78e6401f70.jpg)
Also does not work on normal git repos that are sibling directory to `work`
Like:
```sh
$ cd ~/example/nested/dir/ect/ory
$ mkdir work2
$ cd work2
$ git init
$ touch foo
$ cd ..
$ vim
```
![IMG_20230422_170052](https://user-images.githubusercontent.com/105337186/233774588-ae8a93b5-6dd9-4315-b929-27e0bbfdeee2.jpg)
Should have
![IMG_20230422_170502](https://user-images.githubusercontent.com/105337186/233774670-92c64637-2857-49fe-9414-dea1f862d248.jpg)

**Comment by pseudoparenchymatous** [comment]
But nvim-tree's git runner doesn't depend on cwd of vim/buffers/files so if those environment variables are only set on certain directories and you're not on those directories and wants to view `work` without changing the `cwd`, those environment variables remain unset thus nvim-tree still can't fetch git status.

Also if those environment variables are indeed set and the git feature works when `cwd` is somewhere inside `~/example`, you can view `work` without problem. But if `work` has a sibling directory and that sibling is a normal git repo, the git feature will not work when viewing that normal git repo. Like
```sh
$ cd ~/example/nested/dir/ect/ory
$ mkdir work2 
$ cd work2 
$ git init 
$ touch foo 
$ vim
```
![IMG_20230422_170052](https://user-images.githubusercontent.com/105337186/233775618-a0fbcd62-edc6-4256-810c-556041986e2d.jpg)

When the git runner for `work2` runs it assumes the environment variables

**Comment by alex-courtis** [comment]
> But nvim-tree's git runner doesn't depend on cwd of vim/buffers/files so if those environment variables are only set on certain directories and you're not on those directories and wants to view work without changing the cwd, those environment variables remain unset thus nvim-tree still can't fetch git status.

I see. vim's (and thus the shell's) cwd will be constant.

What is your workflow when using git from a shell? How do you dynamically set `--git-dir` and `--work-tree`? Following that workflow would be preferable.

**Comment by alex-courtis** [comment]
This allows git to determine `--git-dir`
```sh
cd /home/alex/example/nested/dir/ect/ory/work
echo "gitdir: /home/alex/example/sample-bare" > .git
```

Removing the "bareness" of the repo allows us to work as normal without `--git-dir` and `--work-tree`:
```sh
git --work-tree /home/alex/example/nested/dir/ect/ory/work config --replace-all core.bare false
```

However, that may breaks your use case.

**Comment by alex-courtis** [comment]
If there is _absolutely no other way_ to achieve this we can add this functionality to nvim-tree:

```lua
  git = {
    enable = true,
    ignore = true,
    show_on_dirs = true,
    show_on_open_dirs = true,
    timeout = 400,
    worktrees = {
      {
        git_dir = "/home/user/example/sample-bare",
        work_tree = "/home/user/example/nested/dir/ect/ory/work",
      },
    },
  },
```

Please submit a PR.

**Comment by pseudoparenchymatous** [comment]
> 

Yes! This indeed fixes my problem. Thanks a ton, bro! I dunno if I could've found these commands even if I read the git documentation so thanks, and apologies for being a noob with git 🥺. Though I'm now extra satisfied with the plugin, submitting a PR could be fun ~~if I don't get lazy 🫣~~.

**Comment by alex-courtis** [comment]
> found these commands even if I read the git documentation so thanks, and apologies for being a noob with git

The `gitdir: ` is very backdoor (kind of documented) and the bareness is a hack.

> submitting a PR could be fun

That would be fantastic!
