### ISSUE TITLE
:NvimTreeGenerateOnAttach On Windows Not Functioning

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2157]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/2155

<div type='discussions-op-text'>

<sup>Originally posted by **Nazaroni** April 22, 2023</sup>
When I try to generate ":NvimTreeGenerateOnAttach", by default it uses "/tmp/my_on_attach.lua" file path... but I'm on Windows 10 😅.
Is it possible to generate this file on Windows?</div>

**Comment by alex-courtis** [comment]
Windows will be the death of me. POSIX compliance is a lie.

@Nazaroni I'd be most grateful if you tested a fix:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2157-generate-on-attach-windows
```

**Comment by Strongleong** [comment]
@alex-courtis I checked, it worked. 
Need to update migration guide to say that on Windows `my_on_attach.lua` generates in `%TEMP%\nvim\`

**Comment by Nazaroni** [comment]
> Windows will be the death of me. POSIX compliance is a lie.
> 
> @Nazaroni I'd be most grateful if you tested a fix:
> 
> ```shell
> cd /path/to/nvim-tree.lua
> git pull
> git checkout 2157-generate-on-attach-windows
> ```

It works! 🥳😇
The newly generated file is located there: "%TEMP%\nvim\my_on_attach.lua"
