### ISSUE TITLE
collapse deep folders

### ISSUE THREAD

**Issue by gsahbi** [nvim-tree/nvim-tree.lua#2172]
If a directory has a single directory as a child, please provide an option for showing them merged together in the file tree. So, instead of showing this-

```
+ com
  + domain
    + app
       File1
       File2
```
the file tree will look like-
```
+ com/domain/app
   File1
   File2
```
This is useful for java developers

**Comment by gegoune** [comment]
Check help file for `nvim-tree.renderer.group_empty`.
