### ISSUE TITLE
Color display is not normal

### ISSUE THREAD

**Issue by JiuRanYa** [nvim-tree/nvim-tree.lua#2183]
### Description

I update neovim and nvim-tree

The color display is not normal, has no theme or other plugin, only use nvim-tree

![image](https://user-images.githubusercontent.com/58846658/236111279-c14d58d1-2a2e-485e-8976-1d28ff83e039.png)

As you can see above, some file looks like 'red', some file looks normally.

### Neovim version

```text
NVIM 0.9.0
```

### Operating system and version

Mac

### nvim-tree version

Ahead version

### Minimal config

```lua
local status, nvimTree = pcall(require, "nvim-tree")

if not status then
  vim.notify("没有找到 nvimTree")
  return
end

nvimTree.setup({
  view = {
    side = "left",
  },
  -- project.nvim need this
  sync_root_with_cwd = true,
  respect_buf_cwd = true,
  update_focused_file = {
    enable = true,
    update_root = true
  },
})
```

### Steps to reproduce

1. just use nvim-tree in neovim0.9.0+

**Comment by crusj** [comment]
so?
