### ISSUE TITLE
Set a ratio for width and height of floating window

### ISSUE THREAD

**Issue by Johnson0907** [nvim-tree/nvim-tree.lua#2195]
I want the configuration to allows user to set ratio for width and height of floating window.

Refer to the telescope.nvim plugin, which allows the user to set a ratio for width and height of the window and update the width and height when the terminal resizes.

```
require("nvim-tree").setup({
  view = {
    float = {
      enable = true,
      quit_on_focus_loss = true,
      open_win_config = {
	width = 30,  -- set a ratio such as 0.5 or 0.8
	height = 30, -- now only numbers larger than 1 are allowed
      },
    },
  },
})
```

**Comment by alex-courtis** [comment]
Could you achieve your desired functionality with an `open_win_config` function that returns dynamic values? You could close/open the tree to apply the values.

This isn't a complete solution, however would achieve your goal.

**Comment by alex-courtis** [comment]
It may be possible to use a dynamic value for normal/float `view.width` however that's a large piece of work.

**Comment by Johnson0907** [comment]
I try this configuration to set a ratio for height, but i don't know how to make it update when terminal resizes.

```
local function set_win()
  local ratio = 0.8
  local lines = vim.opt.lines:get() - vim.opt.cmdheight:get()
  local window_h = math.floor(lines * ratio)
  local center_y = math.floor(((vim.opt.lines:get() - window_h) / 2) - vim.opt.cmdheight:get())
  return {
    relative = "editor",
    border = "rounded",
    width = 30,
    height = window_h,
    row = center_y,
    col = 1,
  }
end

require("nvim-tree").setup({
  view = {
    float = {
      enable = true,
      quit_on_focus_loss = true,
      open_win_config = set_win(),
    },
  },
})
```

**Comment by alex-courtis** [comment]
You could close/open nvim-tree, maybe finding the file.

As I said, it's not ideal, but may be Good Enough.

**Comment by alex-courtis** [comment]
`:help VimResized` looks like the event to use - that's how telescope is doing it.

I reckon you could just call set_win on that event.

Closing, please comment if you have any issues.

**Comment by aaron-loa** [comment]
I was trying to solve the same problem, and  came across this issue.
Managed to solve it in a similar way as OP, and made it resize on VimResized event according to what Alex wrote.
Doesn't work very well on small window sizes, but good enough.
 
I will leave it here if anyone wants to use it:
```
local width_ratio = 0.5
local heigth_ratio = 0.8

local function set_win()
  local lines = vim.opt.lines:get() - vim.opt.cmdheight:get()
  local columns = vim.opt.columns:get()

  local columns_width = math.floor(columns * width_ratio)
  local padding_x = columns - columns_width
  local start_column = math.floor(padding_x / 2)

  local window_height = math.floor(lines * heigth_ratio)
  local padding_y = lines - window_height
  local start_row = math.floor(padding_y / 2)

  return {
    relative = "editor",
    border = "rounded",
    width = columns_width,
    height = window_height,
    row = start_row,
    col = start_column,
  }
end
```
Set open_win_config to this:
`open_win_config = function() return set_win() end`

Add the autocmd to resize the window:
```

local tree_api = require("nvim-tree")
local tree_view = require("nvim-tree.view")

vim.api.nvim_create_augroup("NvimTreeResize", {
  clear = true,
})

vim.api.nvim_create_autocmd({ "VimResized" }, {
  group = "NvimTreeResize",
  callback = function()
    if tree_view.is_visible() then
      tree_view.close()
      tree_api.open()
    end
  end
})
```

**Comment by alex-courtis** [comment]
> I will leave it here if anyone wants to use it:

That's fantastic!

It would be great if you could add that to the wiki [Recipes](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)

**Comment by aaron-loa** [comment]
I noticed there was already a recipe for centering the floating window, so i only added the autocmd to resize the window automatically.

**Comment by alex-courtis** [comment]
> I noticed there was already a recipe for centering the floating window, so i only added the autocmd to resize the window automatically.

Thanks mate.
