### ISSUE TITLE
Error executing lua: attempt to call a number value

### ISSUE THREAD

**Issue by cppcoffee** [nvim-tree/nvim-tree.lua#2201]
### Description

Run `nvim .` After that, an error is prompted in vim:

<img width="930" alt="截屏2023-05-10 15 25 09" src="https://github.com/nvim-tree/nvim-tree.lua/assets/6635286/626face5-5396-4987-92b5-19f4cbdb6cc9">

### Neovim version

```text
% nvim --version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

maxOS 13.3.1

### nvim-tree version

"nvim-tree.lua": { "branch": "master", "commit": "270c95556cad96d18ca547d86ae65927334b108b" }

### Minimal config

```lua
return {
    'nvim-tree/nvim-tree.lua',
    event = 'VeryLazy',
    dependencies = 'nvim-tree/nvim-web-devicons',
    init = function()
        local function open_nvim_tree()
            require("nvim-tree.api").tree.find_file({ open = true })
        end

        local function close_nvim_tree()
            local layout = vim.api.nvim_call_function("winlayout", {})
            if layout[1] == "leaf"
                and vim.api.nvim_buf_get_option(vim.api.nvim_win_get_buf(layout[2]), "filetype") == "NvimTree"
                and layout[3] == nil then
                vim.cmd("confirm quit")
            end
        end

        vim.api.nvim_create_autocmd('VimEnter', { callback = open_nvim_tree })
        vim.api.nvim_create_autocmd("BufEnter", { callback = close_nvim_tree })
    end,
    opts = {
        on_attach = function(bufnr)
            local map = require('utils').map
            local api = require('nvim-tree.api')
            api.config.mappings.default_on_attach(bufnr)
            map('n', '<C-v>', api.node.open.vertical, { buffer = bufnr })
            map('n', '<C-s>', api.node.open.horizontal, { buffer = bufnr })
            map('n', 'v', api.node.open.vertical, { buffer = bufnr })
            map('n', 's', api.node.open.horizontal, { buffer = bufnr })
            map('n', '<C-t>', ":ToggleTerm<CR>", { buffer = bufnr })
            map('n', '-', "<Plug>(choosewin)", { buffer = bufnr })
            map('n', '[d', api.node.navigate.diagnostics.prev, { buffer = bufnr })
            map('n', ']d', api.node.navigate.diagnostics.next, { buffer = bufnr })
            map('n', 'r', api.fs.rename_sub, { buffer = bufnr })
        end,
        renderer = {
            indent_markers = {
                enable = true,
                icons = {
                    item = '|',
                    edge = "|",
                    corner = "┗",
                }
            },
            highlight_git = true,
            highlight_opened_files = '1',
            icons = {
                git_placement = "after",
                glyphs = {
                    symlink = '',
                    git = {
                        deleted = '',
                        ignored = '◌',
                        renamed = '➜',
                        staged = '+',
                        unmerged = '',
                        untracked = '?',
                        -- unstaged = 'ϟ',
                    },
                    folder = {
                        arrow_open = '',
                        arrow_closed = '',
                        default = '',
                        open = '',
                        empty = '',
                        empty_open = '',
                        symlink = '',
                        symlink_open = '',
                    },
                }
            }
        },
        view = {
            width = 35,
            side = 'left',
        },
        diagnostics = {
            enable = true,
            icons = {
                error = '',
                warning = '',
                info = '',
                hint = '',
            },
        },
        update_focused_file = {
            enable = true,
        },
        hijack_netrw = true,
        update_cwd = true,
        reload_on_bufenter = true,
    }
}
```

### Steps to reproduce

`nvim .`

### Expected behavior

no error, no warnning.

### Actual behavior

Error: Unknow plugin

**Comment by cppcoffee** [comment]
Minimal reproduction configuration https://github.com/cppcoffee/nvim-plugin-conflict, include treesitter/bufferline/gitsigns/tree/treesitter plugins, just disable one of them and no error message will be displayed.

**Comment by alex-courtis** [comment]
> Minimal reproduction configuration https://github.com/cppcoffee/nvim-plugin-conflict, include treesitter/bufferline/gitsigns/tree/treesitter plugins, just disable one of them and no error message will be displayed.

There is too much happening in there. Please create a ["Clean Room" Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) and post it here.

**Comment by cppcoffee** [comment]
This may be a bug in nvim 0.8.0, it runs fine in nvim 0.9.0. I will watch for a while longer.

**Comment by cppcoffee** [comment]
This is a problem with the brew installation of nvim, which is not a problem with the official nvim. close issue.

**Comment by codebysandwich** [comment]
> This is a problem with the brew installation of nvim, which is not a problem with the official nvim. close issue.

i found the same question, nvim version 0.9.5, any solution about brew installation?

**Comment by cppcoffee** [comment]
> > This is a problem with the brew installation of nvim, which is not a problem with the official nvim. close issue.
> 
> i found the same question, nvim version 0.9.5, any solution about brew installation?

You can try official nvim version.

**Comment by codebysandwich** [comment]
> > > This is a problem with the brew installation of nvim, which is not a problem with the official nvim. close issue.
> > 
> > 
> > i found the same question, nvim version 0.9.5, any solution about brew installation?
> 
> You can try official nvim version.

OK, official nvim i tried is OK, i replaced brew installation bin/nvim with official nvim-macos/bin/nvim, LGTM, I will watch for longer.

**Comment by cppcoffee** [comment]
I'm not sure what differences there are with nvim installed via brew that could have led to this issue.

**Comment by gegoune** [comment]
Nothing can be done about this until Alex's request https://github.com/nvim-tree/nvim-tree.lua/issues/2201#issuecomment-1546784901 gets responded to.

**Comment by alex-courtis** [comment]
Maybe there's some default plugin that's installed with that variant of nvim.
