### ISSUE TITLE
A BIG THANKYOU FOR MAINTAINER MONTH

### ISSUE THREAD

**Issue by tjex** [nvim-tree/nvim-tree.lua#2205]
It's maintainer month this month of may and wanted to extend a huge thank you to @kyazdani42 and @alex-courtis for their sweat, tears and possibly some blood(?) that have gone into nvim-tree. 

It's super rough to imagine a neovim world without a kickass file browser. And I've tried a few.
The amount of excellence in developer experience, productivity and just plain old fun you guys enable with nvim-tree the plugin _and_ its thoughtful and thorough documentation is totally outstanding. 

So, thank you again! 
Anyone who feels the same, please chime in! This month in particular is the moment for it! 
And if you've been considering sponsoring this (or any other) project, do it! It feels good and it's the right way forward to maintain the possibility of developing software in a world where we the community control the tools!

**Comment by alex-courtis** [comment]
Many thanks to @gegoune  for _greatly_ improving nvim-tree devspeed and always pushing to Get It Done.

**Comment by tjex** [comment]
I've also put a reminder in for myself to close this issue at the end of the month. Would be weird to make a post like this only to create extra work for you, the maintainers 😂
