### ISSUE TITLE
Render git ignored files in highlight `NvimTreeGitIgnored`

### ISSUE THREAD

**Issue by vollowx** [nvim-tree/nvim-tree.lua#2208]
**Is this a question?**
No.

**Can this functionality be implemented utilising API?**
Maybe not.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Render filenames of git ignored files in highlight `NvimTreeGitIgnored` or another darker highlight.

**Describe alternatives you've considered**
Maybe have not.

**Additional context**
No.

**Comment by alex-courtis** [comment]
This would bring git to parity with `NvimTreeModifiedFile` `NvimTreeOpenedFile` etc.

The documentation is a little ambiguous:
```
There are also links for file highlight with git properties, linked to their
Git equivalent:

NvimTreeFileDirty       (NvimTreeGitDirty)
```

This implies that `NvimTreeFileDirty` sets file highlighting rather than icon highlighting. I'm happy to class this as a bug.

**Comment by huge-pancake** [comment]
Well... I didn't find this is a bug before :thinking: 

I'll keep waiting (hope things work out quickly :smile_cat: )

**Comment by alex-courtis** [comment]
Pull requests are gratefully appreciated. See [Development](https://github.com/nvim-tree/nvim-tree.lua/wiki/Development)

**Comment by vollowx** [comment]
Sorry, I just found that I didn't turn the option `highlight_git` so that it doesn't work.
