### ISSUE TITLE
Ability to run custom commands on node full paths directly

### ISSUE THREAD

**Issue by agnjunio** [nvim-tree/nvim-tree.lua#2230]
**Is your feature request related to a problem? Please describe.**
It's similar to `api.node.run.cmd`, but you can pass a command as a parameter (for instance `api.node.run.cmd("Git add")`) to instantly run said command into the selected node.

**Describe the solution you'd like**
By the example you can see where I'm going with this.

**Describe alternatives you've considered**
Currently I have to wrap it in a function like this:

```
  vim.keymap.set('n', 'ga', function()
    local node = api.tree.get_node_under_cursor()
    vim.cmd('G add ' .. node.absolute_path)
  end, opts('Run Command'))
```

Which can be cleaner of course.

**Comment by alex-courtis** [comment]
You missed the question:   **Can this functionality be implemented utilising API?**

Yes it can, as you have done. It could be implemented in your `on_attach` so as not to pollute the global mapping space.

**Comment by alex-courtis** [comment]
Draft:
```lua
  vim.keymap.set("n", "ga", function()
    api.node.run.cmd({ command = { cmd = "G", args = { "add" } } })
  end, opts("Git Add"))
```
`command` would be the same argument as `vim.cmd()`, with the current node's absolute path appended.

Contrast that to the simpler:
```lua
  vim.keymap.set("n", "ga", function()
    vim.cmd("G add " .. api.tree.get_node_under_cursor().absolute_path)
  end, opts("Git Add"))
```

We don't really gain anything from this addition, just complications around nargs expected by the commands.

It's a no unless I've missed something and you have a better idea.

**Comment by agnjunio** [comment]
I was thinking of something like:
```
vim.keymap.set("n", "ga", api.node.run.cmd({ command = { cmd = "G", args = { "add" } } }), opts("Git Add"))
```

Where the function returns the function to be used for the keymap. But looking at that draft, its not very readable so I agree that is may not make sense.
