### ISSUE TITLE
Norton commander-like mode

### ISSUE THREAD

**Issue by eyalk11** [nvim-tree/nvim-tree.lua#2252]
Allow you to open two nvim-tree instances in split-window and copy files from one instance to the other. https://github.com/ipod825/vim-netranger has this feature.

**Comment by alex-courtis** [comment]
We do have plans to allow multiple, discrete trees across windows and tabs #457 Closing this issue to track there.

That is a large piece of functionality that will likely not be delivered soon.

**Comment by alex-courtis** [comment]
Tracking at
- #457
