### ISSUE TITLE
Why icons are cut off and how to fix it?

### ISSUE THREAD

**Issue by syavabrazzzers** [nvim-tree/nvim-tree.lua#2253]
### Description

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/48682042/56248c31-3093-406b-bf6f-0a39a626aae1)

### Neovim version

```text
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.15.0-69-generic

### nvim-tree version

latest

### Minimal config

```lua
use{ 'nvim-tree/nvim-tree.lua',
      requires = 'nvim-tree/nvim-web-devicons',
      config = function() require'nvim-tree'.setup {
      } end, }
```

### Steps to reproduce

1. :NvimTreeOpen

**Comment by gegoune** [comment]
This seems to be an issue with your terminal, terminal configuration, font, font configuration or combination of those. Try tinkering a bit, different font, different terminal emulator. I am pretty confident this isn't actual issue with nvim-tree.

**Comment by alex-courtis** [comment]
See https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#icons-not-correctly-shown for picking the "correct" font variant.
