### ISSUE TITLE
Toggling folder expansion in one tab's tree affects the tree in another tab

### ISSUE THREAD

**Issue by no-more-secrets** [nvim-tree/nvim-tree.lua#2257]
### Description

There is some part of the opened/closed state of a folder that is being shared by trees in multiple tabs (though they are not visually in sync).

### Neovim version

```text
v0.9.1
```

### Operating system and version

Pop!_OS

### nvim-tree version

latest

### Minimal config

```lua
If you're unable to reproduce let me know and I will provide a minimal config.
```

### Steps to reproduce

To reproduce:
  1. Open two tabs, and open nvim-tree in both.
  2. In tab 1, expand folder xyz (pick a folder that exists for you).
  3. Go to tab 2 and try to expand the same folder, nothing happens. // bug
  4. Try again on tab 2 to expand that folder, and it expands.
  5. Close the folder on tab 2, it works.
  6. Go to tab 1 and try closing that folder, does not work the first time. // bug
  7. Try again in tab 1 to close the folder, it works.

The bug manifests in steps 3 & 6.

**Comment by alex-courtis** [comment]
Thanks for raising.

Added to
- https://github.com/nvim-tree/nvim-tree.lua/issues/2255
