### ISSUE TITLE
Tree only displays 2 subdirectories when 100+ are available.

### ISSUE THREAD

**Issue by MontyTHall** [nvim-tree/nvim-tree.lua#2269]
### Description

I have a directory, let's call it ROOT, with at least 100+ sub directories.  If I "cd ROOT" and fire up nvim and then do a :NvimTreeToggle.  Note - NONE of the subdirectory names are dot files and are not hiddle.  I only see 2 subdirs.

If I "cd ROOT/somesubdir", I can actually see all the sub directories (19 of them). 

### Neovim version

```text
NVIM v0.10.0-dev-508+gd3b9feccb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/xzcjml/src/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/xzcjml/src/neovim/.deps/usr/include -I/home/xzcjml/src/neovim/build/src/nvim/auto -I/home/xzcjml/src/neovim/build/include -I/home/xzcjml/src/neovim/build/cmake.config -I/home/xzcjml/src/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### Operating system and version

Ubuntu 20.0.4.6 LTS

### nvim-tree version

master, e0c7eb5

### Minimal config

```lua
call plug#begin()
	Plug 'nvim-tree/nvim-tree.lua'
	Plug 'nvim-tree/nvim-web-devicons'
call plug#end()

let g:python3_host_prog='/usr/bin/python3'

"
" nvim-tree
"
lua <<EOF
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
require("nvim-tree").setup({
  sort_by = "case_sensitive",
  view = {
    width = 30,
  },
  renderer = {
    group_empty = true,
  },
  filters = {
    dotfiles = true,
  }
})
EOF
```

### Steps to reproduce

1. cd <<the directory with 100+ directories - call this ROOT>>
2. nvim
3. :NvmTreeToggle

### Expected behavior

I should see at least 100+ subdirectories in ROOT.  I'd show you a screen shot but the directory names are sensitivie.  "cd ROOT; ls" I see a ton of subdirs that I don't tree from NvimTree.

### Actual behavior

I see 2 subdirectories and a bunch of files in ROOT
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/12861452/2700265a-7d08-4a5f-9d4f-c6a5beccbb98)

**Comment by gegoune** [comment]
Make sure paths you are not seeing are not git ignored (press `I` - default mapping for toggling git ignored files).

**Comment by MontyTHall** [comment]
That fixed it.

**Comment by MontyTHall** [comment]
Close
