### ISSUE TITLE
Option to use file/directory names instead of absolute paths for notifications

### ISSUE THREAD

**Issue by asror1** [nvim-tree/nvim-tree.lua#2270]
### Issue
When using a notification plugin like [vim-notify](https://github.com/rcarriga/nvim-notify) that has floating window notifications, using absolute paths in the messages of the notifications take up too much of the available horizontal window space, which could be quite distracting. 

### Feature Request
Having shorter notification messages that will take up _less_ of the window space when using notification manager plugin with floating windows. 

### Potential Solution
Adding a boolean option to `opts.notify` that will be set to *false* by **default**. When enabled it will have the file system actions use file/directory names in the notification messages, and use absolute paths by default. 

### Drawbacks
When the option for using file/directory names is enabled, people who are using `nvim-tree.api`, more specifically the file system actions API, without visual context of the current file system, the notification messages might be quite ambiguous if there are files or directories with the same name within their file system. However, I don't believe that this is a significant limitation by any means, since the proposed solution will **not** be a breaking change.   

### References
#2266

**Comment by alex-courtis** [comment]
Perhaps the option might be `notify.absolute_path`, defaulting to true.

**Comment by asror1** [comment]
> Perhaps the option might be `notify.absolute_path`, defaulting to true.

Yup, that does read slightly better than `notify.name_only`. I'll change it in my implementation. I'll raise a PR soon.
