### ISSUE TITLE
Please add tags to repo

### ISSUE THREAD

**Issue by mixmix** [nvim-tree/nvim-tree.lua#2272]
I just upgraded this plugin, and it doesn't work in nvim 0.7
I am find downgrading, but it's hard to because I can't see any tags pushed to this repo

<3
Thanks for the lovely plugin

**Comment by mixmix** [comment]
For anyone trying to get this plugin working on nvim 0.7 , pinning it to this commit worked for me:
```
  Plug 'nvim-tree/nvim-tree.lua', { 'commit': '949913f1860eb85024fa1967dbd89ac797777b0d' }
```

**Comment by alex-courtis** [comment]
I assume there is a good reason to stick to an older neovim version that we haven't considered.

What do you think @geg

**Comment by alex-courtis** [comment]
I assume there is a good reason to stick to an older neovim version that we haven't considered.

What do you think @gegoune ? We could:
2. add tags like `last-neovim-0.7`
3. add a note to the readme

**Comment by gegoune** [comment]
Rather than that we should come up with required version that we support. Adding tag is no different to users using commit sha's but might give false impression that there might be some backporting in the future. 
If we gonna add tags for latest supported versions we should probably call them `compat-<version>`.

**Comment by alex-courtis** [comment]
This looks to be the last supported older versions:
949913f1860eb85024fa1967dbd89ac797777b0d `compat-nvim-0.7`
90d7b8edb1d715086b34572a0fb742faf23a271b `compat-nvim-0.6`

What do we do with `compat-nvim-0.8`? Do we add that when we bump our requirement to 0.9? Maintaining that tag before that might be... difficult.

**Comment by gegoune** [comment]
I think it's polite to support latest and one before versions, so perhaps we try to keep 0.8 out for now?

**Comment by alex-courtis** [comment]
> I think it's polite to support latest and one before versions, so perhaps we try to keep 0.8 out for now?

Sensible.

Added 0.6 and 0.7 and [wiki: Older neovim Versions](https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation#older-neovim-versions)
