### ISSUE TITLE
Toggle floating tree

### ISSUE THREAD

**Issue by joelpeapen** [nvim-tree/nvim-tree.lua#2289]
**Can this functionality be implemented utilising API?**
```nvim-tree.api.tree.toggle()``` doesn't have an option for floating windows.

Sometimes it's useful to open the tree without interfering with the buffers, especially when using zen mode. I've done something simlilar to open floating terminals in zen mode, I'd like to do the same with nvim-tree.

```lua
local function vertical()
    if ZEN then
        vim.cmd(("ToggleTerm dir=p direction=float")
    else
        vim.cmd(("ToggleTerm size=70 dir=p direction=vertical")
    end
end
```

**Comment by alex-courtis** [comment]
Unfortunately floating is an all-or-nothing option: `view.float.enable` and doesn't change during the session.

It could be done: `tree.open`, `tree.toggle` and `tree.find_file` could have an option added.

I'm not sure how this would behave until we try it out... Some exploration by changing the value of `view.float.enable` at runtime would be useful before adding the API options.
