### ISSUE TITLE
`nvim -num /nvt-min.lua` with `hijack_netrw = true` failed to edit a directory immediately.

### ISSUE THREAD

**Issue by otakutyrant** [nvim-tree/nvim-tree.lua#2296]
### Description

There is my `nvt-min.lua`. You can see netrw is disabled from the begining and there is `disable_netrw = true,
 hijack_netrw = true` in config.

However, when I execute `nvim -nu /tmp/nvt-min.lua /tmp`, the neovim show empty context. After I execute `:e` again, it shows the nvim-tree finally.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### Operating system and version

Arch Linux

### nvim-tree version

3cc698b

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
      disable_netrw = true,
      hijack_netrw = true,
  }
end
```
```


### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua /tmp`
2. Execute `:e` inside.

### Expected behavior

Show nvim-tree immediately, like netrw when editing a directory.

### Actual behavior

Show empty context.

**Comment by alex-courtis** [comment]
That is working as intended:
* nvim-tree does nothing at startup. See [wiki: Open At Startup](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup) for a full explanation.
* `:e` to open the `/tmp` buffer results in nvim-tree opening, as `hijack_directories.enable` is `true` by default

 You'll need to configure neovim to open nvim-tree when you start up in a directory. See [wiki: Open For Directories And Change Neovim's Directory](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup#open-for-directories-and-change-neovims-directory) for an example.

**Comment by otakutyrant** [comment]
I configured as you advised and it worked. Now I wonder what the point of `hijack_netrw` is. The doc of doesn't explain much.

**Comment by otakutyrant** [comment]
Sorry, I missed "hijack_netrw will replace netrw buffers with nvim-tree.". It seems that when netrw is enabled and `hijack_netrw` is true, I can open a directory with nvim-tree imediately. However the doc said that it is strongly recommend to disable netrw due to race condition. I think it means netrw also suffers the same startup issue.

Thank you!

**Comment by alex-courtis** [comment]
> I think it means netrw also suffers the same startup issue.

Indeed. It's not a regular plugin and it's startup behaviour is very unpredictable.
