### ISSUE TITLE
background transparency of non-tree windows is disabled when tree open

### ISSUE THREAD

**Issue by smashaal** [nvim-tree/nvim-tree.lua#2300]
### Description

opening the tree disables my transparent background, closing it resumes the transparent background.
opening and closing the tree should not affect my transparent background

https://github.com/nvim-tree/nvim-tree.lua/assets/115570265/6c92e1fc-088f-434f-9340-618ae5578934

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

### Operating system and version

macOS ventura 13.4

### nvim-tree version

e2a4c9d

### Clean room replication

```lua
lua << EOF
require'nvim-tree'.setup{}
EOF

hi Normal ctermbg=NONE
hi NonText ctermbg=NONE
hi Normal guibg=NONE
hi NonText guibg=NONE
```

### Steps to reproduce

1. :NvimTreeToggle

### Expected behavior

background of non-tree windows unaffected

### Actual behavior

background of non-tree windows are not transparent while tree is open

**Comment by alex-courtis** [comment]
Unfortunately I cannot replicate this with a clean room configuration [nvt-min.lua.gz](https://github.com/nvim-tree/nvim-tree.lua/files/11924176/nvt-min.lua.gz).

Is there perhaps another plugin that is setting your colours? I use `"echasnovski/mini.base16"` which overrides _everything_.

https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/85916b2c-6ae6-444a-ad85-72237e80941e

```
:; nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

Alacritty:
```yaml
colors:
  # Default colors
  primary:
    background: '0x220000'
    foreground: '0xe0e0e0'
```

**Comment by smashaal** [comment]
ahh, the offending plugin is [tokyonight](https://github.com/folke/tokyonight.nvim)
