### ISSUE TITLE
After creating a directory, two folders are displayed.

### ISSUE THREAD

**Issue by virezox** [nvim-tree/nvim-tree.lua#2305]
### Description

I've enabled the `renderer.group_empty` option. After I created a directory, two folders are displayed. This is only a visual issue.

https://github.com/nvim-tree/nvim-tree.lua/assets/8643866/b247ea16-bbdd-4f33-9ba7-2dd9b812cf1d

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4.1

### nvim-tree version

4af572246ce49883e2a52c49203a19984454f2e0

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"nvim-tree/nvim-tree.lua",
			"nvim-tree/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		renderer = {
			group_empty = true,
		},
	})
end
```

### Steps to reproduce

1. nvim -nu nvt-min.lua directory_with_an_empty_folder_inside
2. press "A" to create a directory at the same level with that empty folder
3. move back to see what's the that folder

**Comment by alex-courtis** [comment]
Thanks for the detailed reproducer.

Confirmed, files and directories:
* `mkdir -p a b/A/i b/A/ii b/A/iii c`
* open b
* `a` `b/B`
* open b

Refresh resolves the duplicate.

**Comment by pritom-5** [comment]
Having this same problem since couple of days.

**Comment by alex-courtis** [comment]
Regression since 1fe3228

**Comment by alex-courtis** [comment]
This has surfaced an issue with grouped nodes:

Manual refresh when watchers disabled will not ungroup nodes.

**Comment by alex-courtis** [comment]
@virezox @pritom-5 I'd be most grateful if you could test this branch. The tree structure will be properly updated following creation.

cd /path/to/nvim-tree.lua
git pull
git checkout 2305-grouped-extra-created-nodes

**Comment by alex-courtis** [comment]
@virezox @pritom-5 I'd be most grateful if you could test this branch. The tree structure will be properly updated following creation.

cd /path/to/nvim-tree.lua
git pull
git checkout 2305-grouped-extra-created-nodes

**Comment by alex-courtis** [comment]
> As tested, this issue appears to have already been fixed.

Many thanks. I'll soak that for a few more days.
