### ISSUE TITLE
Document consequences of disabling netrw

### ISSUE THREAD

**Issue by EdmundsEcho** [nvim-tree/nvim-tree.lua#2309]
This is a solid addition to my neovim experience.  Thank you!

**Is your feature request related to a problem? Please describe.**
Per the recommendation, I disabled `netrw`.  I went to use the `RustExternalDocs` command which failed.  With a little digging I have learned it is b/c I disabled `netrw`.   Along the way (in my searching), I encountered others that complained about not being able to open a browser with the url under their cursor... For that precise issue, "there is a plugin for that" :))

**Describe the solution you'd like**
It may be helpful to add your understanding of what it might mean to a user when they go ahead and follow the advice to disable `netrwr`.  It will help better understand what to expect.  In my case, it would have short-circuited my figuring out what happened.  

Thank you for this solid and pleasant file manager.

**Comment by gegoune** [comment]
Isn't https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L2277-L2297 enough? What else would you like to be mentioned there? Is it perhaps discoverability of it? It's linked from readme though.

**Comment by EdmundsEcho** [comment]
Nicely documented!  I did not see this.  I did not think to look. 

In the Readme where you have: 

> Disabling [netrw](https://neovim.io/doc/user/pi_netrw.html) is strongly advised, see [:help nvim-tree-netrw](https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt)

Maybe say: 
> Disabling [netrw](https://neovim.io/doc/user/pi_netrw.html) is strongly advised.  Doing so has the unfortunate side effect of disabling the ability launch a browser from within neovim.  Checkout [:help nvim-tree-netrw](https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt) to learn more.

**Comment by gegoune** [comment]
Issue at hand is actually fixed in nightly neovim, which now ships `gx` mapping outside of `netrw` plugin, so disabling `netrw` will no longer cause issue you experienced. Please mind that this is only available on nightly builds at the moment. As far as I am concerned we can get away with not updating readme and just waiting for status quo to change, but feel free to send PR and update readme. :)

**Comment by EdmundsEcho** [comment]
Sounds like if I were to update the Readme I might be adding to the confusion once the neovim updates proliferate over time.  I'll close the issue.

**Comment by gegoune** [comment]
Thanks for reporting anyway. Documentation can always be improved.

**Comment by alex-courtis** [comment]
> Issue at hand is actually fixed in nightly neovim, which now ships `gx` mapping outside of `netrw` plugin

That is fantastic news! netrw will go away eventually...
