### ISSUE TITLE
custom_only causes directory confusion

### ISSUE THREAD

**Issue by fengwk** [nvim-tree/nvim-tree.lua#2310]
### Description

I set `custom_only=true`, but the directory structure is messed up, this is not inevitable only in some of my projects, the details can be seen in the picture below, I confirm that this problem is introduced by 1fe32286db79719dd6e52236f82c5b52df3ccaa9 commit.

Wrong directory structure 1fe32286db79719dd6e52236f82c5b52df3ccaa9:

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/25793618/8cb90b40-a55b-4adc-b106-0b12f85a9be0)

Right directory structure 3cc698b35b0a67792c61e1726830bb9ecfc4c9f4:

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/25793618/78dd3c5a-d7ad-484b-b124-09215e1e4de0)

### Neovim version

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux arch 6.1.37-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 17:31:09 +0000 x86_64 GNU/Linux

### nvim-tree version

master

### Clean room replication

```lua
require"nvim-tree".setup({
  renderer = {
    group_empty = true,
  }
})

vim.keymap.set("n", "<leader>e", function()
  require"nvim-tree.api".tree.toggle({
    focus = true,
    find_file = true,
  })
end, { desc = "NvimTree Find File Toggle" })
```

`find_file = true` is a necessary condition to trigger the problem.

### Steps to reproduce

1. Use the minimum configuration above
2. <leader>e

### Expected behavior

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/25793618/78dd3c5a-d7ad-484b-b124-09215e1e4de0)

### Actual behavior

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/25793618/8cb90b40-a55b-4adc-b106-0b12f85a9be0)

**Comment by alex-courtis** [comment]
Possibly related: #2305

**Comment by alex-courtis** [comment]
@fengwk please re-test. There have been significant changes recently that may address this.

**Comment by fengwk** [comment]
The latest version has no recurrence issues.
