### ISSUE TITLE
Don't sort directories first

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2313]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/2311

<div type='discussions-op-text'>

<sup>Originally posted by **kirasok** July  9, 2023</sup>
Is there way to make nvim-tree *not* to sort directories first?

Like this:
```
a/
a.txt
bcd/
bcd.txt
e.txt
rtx/
```

instead of
```
a/
bcd/
rtx/
a.txt
bcd.txt
e.txt
```</div>

**Comment by alex-courtis** [comment]
No such functionality exists; folders are always placed before files for all sorting methods.

It _appears_ to be possible if we change the 4 available sort methods.

**Comment by gegoune** [comment]
Shall we introduce `sort` key and nest those options there? Could move `sort`_by in there eventually too. 

```
sort = {
  sorter = foo,
  group_directories = bool,
```
Or something like that. I just like good organisation. :)

**Comment by alex-courtis** [comment]
Yes! That would be much clearer.

There would be no backwards compatibility issues either, due to unique names. I'll update the PR.
