### ISSUE TITLE
Use different highlight groups for folder arrows and indent markers

### ISSUE THREAD

**Issue by anna328p** [nvim-tree/nvim-tree.lua#2316]
**Is this a question?**
No

**Can this functionality be implemented utilising API?**
No

**Is your feature request related to a problem? Please describe.**
Currently indent markers and folder arrows are both rendered as part of line padding, and have the highlight group `NvimTreeIndentMarker` ([code here](https://github.com/nvim-tree/nvim-tree.lua/blob/a708bd2413d467929b5019ec1bce7b1f428438bc/lua/nvim-tree/renderer/components/padding.lua#L95)). There is no way to make the indent lines and the folder arrows different colors. This is especially relevant when `inline_arrows = true`.

**Describe the solution you'd like**
A change to the renderer that displays padding and indent markers using different highlight groups so that they can be configured separately. For backwards compatibility, the arrows' highlight group could be linked to `NvimTreeIndentMarker` by default.

**Describe alternatives you've considered**
Tried messing around with configs for a while. Also tried displaying arrows as folder icons; however this breaks inline arrows.

**Additional context**

The arrows and indent markers are the same color here:

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/9790772/7136b5e4-6cd9-4173-9cef-a03574813c72)

**Comment by alex-courtis** [comment]
This can be done. Perhaps `NvimTreeFolderArrow`

**Comment by anna328p** [comment]
thank you!!
