### ISSUE TITLE
Trash files on Windows as well as Unix system

### ISSUE THREAD

**Issue by cworld1** [nvim-tree/nvim-tree.lua#2331]
**Is this a question?**
Move to Windows recycle bin instead of deleting files completely as I need to delete files. I know there is a function 'Trash' with shortcut `D`, but it told me:

> Trash is currently a UNIX only feature!

**Can this functionality be implemented utilising API?**
Sorry I'm not good at it and I don't know about it... But I know there's a PowerShell script can do that:

```powershell
$sh = new-object -comobject "Shell.Application"
$ns = $sh.Namespace(0).ParseName("PATH\TO\FILE\TO\DELETE")
$ns.InvokeVerb("delete")
```

**Is your feature request related to a problem? Please describe.**
Add Windows support of command 'Trash'.

**Describe the solution you'd like**
Add Windows support of command 'Trash'.

**Describe alternatives you've considered**
#279 Shows the way I used it on WSL.

**Additional context**
Nothing.

**Comment by alex-courtis** [comment]
nvim-tree developers do not have access to or expertise with windows, however windows changes are welcome.

[Pull requests](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md) are very gratefully appreciated providing:
* functionality is behind the utils is_windows feature flag
* you are able to resolve / fix issues with this functionality

**Comment by alex-courtis** [comment]
#2335 adds synchronized trash support
