### ISSUE TITLE
`open_file` opens file in last used buffer when `window_picker` is disabled.

### ISSUE THREAD

**Issue by hdelan** [nvim-tree/nvim-tree.lua#2338]
Personally I don't like having to specify which window I want to open a file in (if `window_picker.enable` is set to true. It would be great if the new buffer could open in the last used window when `window_picker.enable` is `false`, instead of the window where `nvim-tree` was last opened.

**Comment by alex-courtis** [comment]
I've not been reliably able to reproduce this behaviour, however it is a known problem: #2262

Let's track this one in there.
