### ISSUE TITLE
Significant lag when changing into directory with several subdirectories

### ISSUE THREAD

**Issue by johnmutuma5** [nvim-tree/nvim-tree.lua#2342]
### Description

I  have been experiencing a significant lag when changing directory in a Lerna monorepo. About 45secs on average.

This happens when changing from into `packages` directory  from my monorepo-root, (`gardmade` in the logs). `gardmade ==> packages`.

There are about 2000 subdirectories in the packages folder. The subdirectories are npm packages. The lag is present even when all `node_modules` in the subdirectories are deleted and even when the `.git` folder is deleted.

I don't experience any lag when I `cd` all the way from `/Users/johnmm/Documents/Projects/Work/Zentex/allJS/gardmade/`. That's where trouble begins.

[1.cd_packages_nvim-tree.log](https://github.com/nvim-tree/nvim-tree.lua/files/12195897/1.cd_packages_nvim-tree.log)

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4.1

On a 32GB Ram Intel Core i9, as well as 64GB Ram Apple M1 Max

### nvim-tree version

273c170

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"nvim-tree/nvim-tree.lua",
			"nvim-tree/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		filters = {
			exclude = { "node_modules", "string-resources", "lib" },
		},
		filesystem_watchers = {
			enable = false,
		},
		log = {
			enable = true,
			truncate = true,
			types = {
				diagnostics = true,
				git = false,
				profile = true,
				watcher = true,
			},
		},
	})
end

```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua
2. NvimTreeToggle
3. cd into monorepo root
4.  find packages directory, and  `C-]` to explore packages

### Expected behavior

List all approx. 2000 subdirectories without hanging.

### Actual behavior

NeoVim completes hangs for about 45 seconds.
[1.cd_packages_nvim-tree.log](https://github.com/nvim-tree/nvim-tree.lua/files/12195897/1.cd_packages_nvim-tree.log)

Additionally, after cd packages via NvimTree, quitting NeoVim becomes very expensive hanging for about 45secs after `:qa`.

**Comment by alex-courtis** [comment]
That's a lot of filesystem events.

There have been and will continue to be issues when there are huge numbers of events such as #1931

There have recently been some file system and libuv performance / resource leak changes in neovim. You're running latest so they should be present.

Please provide a reproducer: I have not heard of lerna... full instructions on how I can set this up and reproduce would be gratefully appreciated.

**Comment by johnmutuma5** [comment]
Thanks Alex.

I've tried to repro this with simple directories.

I have a bash script to generate 2000 empty directories into a `packages` folder below, and follow the next steps:


1. I create a new folder call it `testing` and `cd` into it
2. I create a `create_empty_dirs.sh` file there
3. Run `chmod +x create_empty_dirs.sh` in the terminal inside the `testing` directory
4. Execute the script `./create_empty_dirs.sh`. Once this succeeds, I have inside `testing` a `packages` directory with 2000 empty folders
5. I open `nvim` from `testing` and open nvim-tree
6. Locate the created `packages` folder in the tree and hit `C-]` to `cd` into packages
7. NeoVim hangs for at least 30 seconds
8. Once the operation is complete, I'm now inside `packages`
9. Run NeoVim command `:qa` to exit NeoViim, it hangs once more for some about 30sec too before exit is done


```bash
#!/bin/bash

# Function to create a directory with src folder and package.json file
create_directory() {
    local dir_name="packages/$1"
    mkdir -p "$dir_name"
}

# Main script
for ((i = 1; i <= 2000; i++)); do
    dir_name="package_$i"
    create_directory "$dir_name"
done

echo "2000 empty directories created."
```

**Comment by alex-courtis** [comment]
Unfortunately I'm not able to replicate. I even created 100 files in each directory:

```sh
#!/bin/bash

# Function to create empty dirs inside a packages folder
create_directory() {
    local dir_name="packages/$1"
    mkdir -p "$dir_name"
}

create_file() {
    local file_name="packages/$1/$2"
        touch "$file_name"
}

# Main script
for ((i = 1; i <= 2000; i++)); do
    dir_name="package_$i"
    create_directory "$dir_name"
        for ((j = 1; j <= 100; j++)); do
                create_file "$dir_name" "$j"
        done
done
```

Log is quite sparse, with no action following the change dir: 
[nvim-tree.log](https://github.com/nvim-tree/nvim-tree.lua/files/12208409/nvim-tree.log)

Have you got a linux machine you could test this on?

**Comment by johnmutuma5** [comment]
Hello Alex.

The testing is not in a git repo.

I tested the lag in a Linux running inside Virtualbox and it seems to be performant in that environment. Looks like it's a macOS problem.

**Comment by alex-courtis** [comment]
Do you have any disk encryption active?

Unfortunately there's not much I can do here. Please do reopen if you can identify a reproducer.
