### ISSUE TITLE
group_empty produces duplicates directories

### ISSUE THREAD

**Issue by Pieter-JanLavaerts** [nvim-tree/nvim-tree.lua#2347]
### Description

For example WelzijnsaspectController.java is opened up 4 times in this image.
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/42444653/6a35fb24-83ca-429a-9c32-c985f9281d36)

init.lua
```lua
  vim.g.loaded_netrw = 1
  vim.g.loaded_netrwPlugin = 1
  -- set termguicolors to enable highlight groups
  vim.opt.termguicolors = true
  require('nvim-tree').setup({
      sort = {
          sorter = 'case_sensitive',
      },
      view = {
          width = 50,
      },
      renderer = {
          group_empty = true,
      },
      filters = {
          dotfiles = true,
      },
  })
  ```
  I really don't see what I'm doing wrong here.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS: Darwin BE-FNLWFRV0GK 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### nvim-tree version

4bd30f0

### Clean room replication

```lua
I'll do this properly later.

init.lua

  vim.g.loaded_netrw = 1
  vim.g.loaded_netrwPlugin = 1
  -- set termguicolors to enable highlight groups
  vim.opt.termguicolors = true
  require('nvim-tree').setup({
      sort = {
          sorter = 'case_sensitive',
      },
      view = {
          width = 50,
      },
      renderer = {
          group_empty = true,
      },
      filters = {
          dotfiles = true,
      },
  })
```

### Steps to reproduce

nvim

### Expected behavior

No duplicated directories in tree

### Actual behavior

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/42444653/6a35fb24-83ca-429a-9c32-c985f9281d36)

**Comment by alex-courtis** [comment]
Likely related #2305

**Comment by Pieter-JanLavaerts** [comment]
I just added a reload call to my keybinding to toggle the tree and that fixed it!
thanks 👍

**Comment by alex-courtis** [comment]
> I just added a reload call to my keybinding to toggle the tree and that fixed it!
> thanks +1

That's not really a good solution. This needs to be fixed properly.

**Comment by alex-courtis** [comment]
@Pieter-JanLavaerts I'd be most grateful if you could test this branch. The tree structure will be properly updated following creation.

cd /path/to/nvim-tree.lua
git pull
git checkout 2305-grouped-extra-created-nodes
