### ISSUE TITLE
Diff to a different git base

### ISSUE THREAD

**Issue by devenv** [nvim-tree/nvim-tree.lua#2351]
**Is this a question?**
Is there a way to show the git icons based on a diff against something else but `HEAD`? e.g. `origin/main`

**Can this functionality be implemented utilising API?**
nope

**Is your feature request related to a problem? Please describe.**
I use gitsigns which allows to change git base to `main`, which is very useful in many situations.

**Describe the solution you'd like**
api function `api.git.change_base(str)`, `reset_base()`

**Comment by alex-courtis** [comment]
I'm afraid that is well outside the scope of nvim-tree, which simply shows the current git state. Telescope and gitsigns have the same limitation.

Suggestions:
* CLI `git diff origin/main`
* [vim-fugitive](https://github.com/tpope/vim-fugitive) plugin has a lot of functionality and might allow such features, but only within itself

**Comment by devenv** [comment]
Not sure what you mean by `gitsigns have the same limitation`, gitsigns is where I noticed this feature in the first place: https://github.com/lewis6991/gitsigns.nvim/blob/main/doc/gitsigns.txt#L255

**Comment by alex-courtis** [comment]
> Not sure what you mean by `gitsigns have the same limitation`, gitsigns is where I noticed this feature in the first place: https://github.com/lewis6991/gitsigns.nvim/blob/main/doc/gitsigns.txt#L255

Wow, that's a nice feature. It's still outside of the scope of nvim-tree.

**Comment by devenv** [comment]
Yep, when you are on an Xth commit in a branch and want to check the full diff for many reasons - lifesaver.

**Comment by alex-courtis** [comment]
Unfortunately nvim-tree works via status, not diff.

I don't even think it would be feasible to use diffs to show the state of the whole repository via diff.
