### ISSUE TITLE
Cannot open file whose filename or folder name has parenthesis "(" on Windows

### ISSUE THREAD

**Issue by xarthurx** [nvim-tree/nvim-tree.lua#2352]
### Description

As the title says, I cannot open files that have "(" or ")" in their file name or folder structure.
It looks like the path xxx\(abc)\(edf).jsx will be interpreted incorrectly due to the "escaping" effect.

All file paths like xxx\(index)\(index).jsx will be interpreted to xxx(index)(index).jsx due to the "char escaping" mechanism...

See description and replies here:
https://github.com/neovim/neovim/issues/24542

But even when I `set shellslash`, and can open those files with `:e <filename>`, I still cannot open the files in `nvim-tree`.
It seems `nvim-tree` does not follow the setting of `shellslash`

### Neovim version

```text
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### nvim-tree version

0a89dcb

### Clean room replication

```lua
raw nvim with nvim-tree.
```

### Steps to reproduce

- create a folder/file with path like: xxx\(index)\(index).jsx
- Open the file in `nvim-tree`.
- The file cannot be opened/showing empty file.

### Expected behavior

the file should be opened correctly.

### Actual behavior

nvim shows an empty file -- this should be caused by the "escape" issue.

**Comment by Angelelz** [comment]
Confirm this is an issue in windows. I've re-enabled netrw for the time being.

**Comment by davisthedev** [comment]
I have this issue as well. If I set shellslash to true and then open a directory with nvim . I am able to navigate to directories that have the "(". However if I open nvimtree explorer sidebar I am not able to open files in a directory with "(".

Is there any reason the default explorer would respect shellslash and the sidebar would not?

**Comment by alex-courtis** [comment]
nvim-tree developers do not have access to or expertise with windows, however windows changes are welcome.

[Pull requests](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md) are very gratefully appreciated providing:
* functionality is behind the utils is_windows feature flag
* you are able to resolve / fix issues with this functionality

**Comment by davisthedev** [comment]
I will work on a pr to try and resolve this. To try and save myself some time, Could you provide files or locations where the file open code is? Essentially all I need to do is intercept the path and escape/replace the problematic characters.

**Comment by davisthedev** [comment]
I have it narrowed down to open-file.lua line 299: pcall(vim.cmd, cmd).
So I now belive there is no issue with nvim-tree and the escaping is happening somewhere after this command. I was able to run the command without nvim-tree active and the path still got escaped.

I think this can be closed.

**Comment by davisthedev** [comment]
I have a pr. This only fixes a specific situation that was affecting me. If there are other windows tickets I am happy to take a look.

#2374
