### ISSUE TITLE
User should be able to change default icon even if nvim-web-devicons is available

### ISSUE THREAD

**Issue by 2ax3ax5** [nvim-tree/nvim-tree.lua#2361]
I'd like to set the nvim-tree.renderer.icons.glyphs.default to a desired value even if nvim-web-devicons are available.

From the docs
```
*nvim-tree.renderer.icons.glyphs.default*
Glyph for files. Will be overridden by `nvim-web-devicons` if available.
Type: `string`, Default: `""`
```

Note that this is the only icons.glyphs "option" that behaves that way and the user cannot custom it (if nvim-web-devicons are available).

**Comment by alex-courtis** [comment]
> I'd like to set the nvim-tree.renderer.icons.glyphs.default to a desired value even if nvim-web-devicons are available.

Which functionality do you still require from nvim-web-devicons, if you are overriding the files?

**Comment by alex-courtis** [comment]
The above change should enable your desired behaviour. Please comment if you experience issues.
