### ISSUE TITLE
E492: Not an editor command: NvimTreeGenerateOnAttach

### ISSUE THREAD

**Issue by kohane27** [nvim-tree/nvim-tree.lua#2378]
### Description

I got the following warning today due to 18c7a3119839adc4599d838726deae662859c8b2:

```
[NvimTree] unknown option: view.mappings | see :help nvim-tree-setup for available configuration options
```

According to [Generation](https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach#generation),

```
Run :NvimTreeGenerateOnAttach to create and open nvim-tree-on-attach.lua. Usually in $XDG_CACHE_HOME/nvim or %TEMP%\nvim\my_on_attach.lua
```

But `:NvimTreeGenerateOnAttach` yields `E492: Not an editor command: NvimTreeGenerateOnAttach`

Any input is much appreciated. Thank you.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.1.44-1-lts

### nvim-tree version

main

### Clean room replication

```lua
N/A
```

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by alex-courtis** [comment]
There have been months of warning that this change was needed: `"view.mappings.list has been deprecated in favour of on_attach. Please run :NvimTreeGenerateOnAttach and visit https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach"`

@gegoune what do you think of this:
1. revert 18c7a31
2. change the warning to a hard fail
3. `:NvimTreeGenerateOnAttach` can still be run

**Comment by alex-courtis** [comment]
@kohane27 please temprarily revert to ace6422 so that you may generate your mappings OR simply create new mappings as per `:help nvim-tree-quickstart`

**Comment by voice0726** [comment]
Not only `:NvimTreeGenerateOnAttach` but also all `:NvimTree*` commands are not recognized as an editor command after updating to 18c7a3119839adc4599d838726deae662859c8b2.
When I rolled back to 0a54dcb76b02f3a4e2da370c7a3f6f2b7b43ef01, there is no problem. I did not make any change on config before and after update. Is this related to the reported problem?

**Comment by kohane27** [comment]
@alex-courtis Thank you very much for such a quick reply. After temporarily reverted back to `ace6422`, I could ran the command `NvimTreeGenerateOnAttach` and have migrated successfully. Thank you again! I'll leave this issue option as per @voice0726 issue.

**Comment by alex-courtis** [comment]
> Not only `:NvimTreeGenerateOnAttach` but also all `:NvimTree*` commands are not recognized as an editor command after updating to [18c7a31](https://github.com/nvim-tree/nvim-tree.lua/commit/18c7a3119839adc4599d838726deae662859c8b2).

Were there any errors reported? `:messages`

**Comment by 0xatulpatil** [comment]
Hey facing the same problem. 
After I enter `:NvimTreeToggle` it says `not and editor command`. 

What do I do?

**Comment by gegoune** [comment]
@alex-courtis Doesn't seem like there is a great number of affected users - most are likely have migrated by now. We can help those which haven't yet here.

> Hey facing the same problem. After I enter `:NvimTreeToggle` it says `not and editor command`.
> 
> How do I revert back to an older version of the plugin ?

Please consult you plugin's manager documentation if you are using one.

**Comment by pferraggi** [comment]
> @alex-courtis Doesn't seem like there is a great number of affected users - most are likely have migrated by now. We can help those which haven't yet here.
> 
> > Hey facing the same problem. After I enter `:NvimTreeToggle` it says `not and editor command`.
> > How do I revert back to an older version of the plugin ?
> 
> Please consult you plugin's manager documentation if you are using one.

Why? what has packer to do with this?

I am also facing the NvimTreeToggle command missing. I have migrated to on attach and it was working fine till I just updated.

this command still is in the documentation so it should be available no?

**Comment by voice0726** [comment]
[alex-courtis](https://github.com/alex-courtis)
> Were there any errors reported? `:messages`
Just saying `E492: Not an editor command: NvimTree`.

I am also trying to reproduce creating a minimal config.
So far, the very minimal config below works fine, implying the problem lies in my own existing config.
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	{ "nvim-tree/nvim-tree.lua" },
	config = require("nvim-tree").setup()
})
```

My existing config has been already migrated to on_attach.

**Comment by voice0726** [comment]
Finally I found out the problem in my config. When I commented out, it works without problem in the latest version.
```
local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
if not config_status_ok then
  return
end
```

**Comment by omarabid** [comment]
I'm having the same issue. I'm using Lazy to load the plugin.

**Comment by alex-courtis** [comment]
> Finally I found out the problem in my config. When I commented out, it works without problem in the latest version.
> 
> ```
> local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
> if not config_status_ok then
>   return
> end
> ```

Fantastic. nvim-tree.config was removed as it was a legacy holdover from over a year ago.

If you want to know whether nvim-tree has been loaded, you can use the `Ready` event or the `NvimTreeRequired` autocommand. See `:help nvim-tree-events`

**Comment by alex-courtis** [comment]
> > @alex-courtis Doesn't seem like there is a great number of affected users - most are likely have migrated by now. We can help those which haven't yet here.
> > > Hey facing the same problem. After I enter `:NvimTreeToggle` it says `not and editor command`.
> > > How do I revert back to an older version of the plugin ?
> > 
> > 
> > Please consult you plugin's manager documentation if you are using one.
> 
> I am also facing the NvimTreeToggle command missing. I have migrated to on attach and it was working fine till I just updated.
> 
> this command still is in the documentation so it should be available no?

@pferraggi 

Please open a new [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) so that we may reproduce your issue.

Please include the output of `:messages`

**Comment by alex-courtis** [comment]
> I'm having the same issue. I'm using Lazy to load the plugin.

@omarabid 

Please open a new [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) so that we may reproduce your issue.

Please include the output of `:messages`

**Comment by alex-courtis** [comment]
> @alex-courtis Doesn't seem like there is a great number of affected users - most are likely have migrated by now. We can help those which haven't yet here.

@gegoune 

Yes. It doesn't seem to be a migration, on_attach or setup issue. It appears to be user configuration e.g. using the non-api `nvim-tree.config`.

Any other users encountering this or similar problems: Please open a new [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) so that we may reproduce your issue.
