### ISSUE TITLE
quit_on_open is false, but still close file explorer when open file

### ISSUE THREAD

**Issue by zshnb** [nvim-tree/nvim-tree.lua#2379]
### Description

 i set quit_on_open = false, but when i open a file, the panel still closed

### Neovim version

```text
nvim v0.9.1
```

### Operating system and version

macOS 12.3

### nvim-tree version

master

### Clean room replication

```lua
actions = {
    open_file = {
      -- È¶ñÊ¨°ÊâìÂºÄÂ§ßÂ∞èÈÄÇÈÖç
      resize_window = true,
      -- ÊâìÂºÄÊñá‰ª∂Êó∂ÂÖ≥Èó≠
      quit_on_open = false,
    },
  },
```

### Steps to reproduce

1. open nvim-tree
2. open a file
3. the panel will be closed

### Expected behavior

nvim-tree doesn't close

### Actual behavior

nvim-tree close

**Comment by gegoune** [comment]
Please provide all information as outlined in https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication, not just an excerpt, and full steps required to reproduce.

**Comment by alex-courtis** [comment]
Closing, insufficient information.
