### ISSUE TITLE
Nvim-Tree Keeps Creating "Zombie" Buffers?

### ISSUE THREAD

**Issue by eyalz800** [nvim-tree/nvim-tree.lua#2383]
### Description

Recently I found that in my workflow there are many unnamed buffers created, I tried to isolate the issue and I believe I came to the conclusion that this is caused by Nvim-Tree:

Here are the steps to repro:
```
1. $ nvim
2. :NvimTreeOpen
3. :below copen
4. :wincmd J
6. :NvimTreeClose
7. :ls 
8. :NvimTreeOpen
9. :ls
```
Step 8 here creates a new unnamed buffer as you can see the difference between steps 7 and 9 output.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.5

### nvim-tree version

920868d

### Clean room replication

```lua
Just NvimTree installed
```

### Steps to reproduce

```
1. $ nvim
2. :NvimTreeOpen
3. :below copen
4. :wincmd J
6. :NvimTreeClose
7. :ls 
8. :NvimTreeOpen
9. :ls
```
Step 8 here creates a new unnamed buffer as you can see the difference between steps 7 and 9 output.

### Expected behavior

No additional buffers are created

### Actual behavior

Additional buffers are created every time this is done

**Comment by alex-courtis** [comment]
```
:copen
:NvimTreeOpen
:ls!
```
```
  1  a   "[No Name]"                    line 1
  2  a-  "[Quickfix List]"              line 0
  3u%a-  "NvimTree_1"                   line 1
  4 #h   "[No Name]"                    line 1
```

Opening from QF seems to be the issue.

**Comment by alex-courtis** [comment]
view open_window executes a `:vsp`  which will create a new buffer when in a quickfix buffer window.

**Comment by alex-courtis** [comment]
We could do something like

```lua
vim.api.nvim_buf_get_name(bufnr) == "" and not vim.bo[bufnr].modified
```

to detect whether the buffer is a no-name-new and delete it.

**Comment by alex-courtis** [comment]
I've had a go at this and the complexity and risk is too great: detecting the no name new is somewhat reliable, however finding a point at which to perform this delete/wipe is problematic and can result in closed windows e.g. quickfix.

I'm afraid we will just have to live with this one.
