### ISSUE TITLE
Tab mapping override

### ISSUE THREAD

**Issue by oscarmlage** [nvim-tree/nvim-tree.lua#2385]
### Description

I've recently updated the `nvim-tree plugin` and now the `<Tab>` key can't be unmapped / remapped inside the `nvim-tree` window. My config (`lazy.nvim`):

```lua
return {
    'nvim-tree/nvim-tree.lua',
    dependencies = {
        'nvim-tree/nvim-web-devicons',
    },
    lazy = false,
    keys = {
        { "<Tab>", ":NvimTreeToggle<CR>", desc = "Tree toogle" },
        { "<S-r>", ":NvimTreeFindFile<CR>", desc = "Tree toogle" },
    },
    opts = {
        sort_by = "case_sensitive",
        on_attach = on_attach,
        open_on_tab = false,
        view = {
            width = 30,
            adaptive_size = false,
            mappings = {
                list = {
                  { key = "<Tab>", action = "" },
                },
            },
        },
    [...]
    },
    config = function(_, opts)
        require("nvim-tree").setup(opts)
    end,
}
```

In previous versions (commit `a708bd2`) it works like a charm but if I update (commit `18c7a31`) it's not working anymore, Tab is always doing the Preview instead of `:NvimTreeToggle<CR>`. Is there any change I must take in account in the configuration? (thanks in advance).

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4

### nvim-tree version

18c7a31

### Clean room replication

```lua
return {
    'nvim-tree/nvim-tree.lua',
    dependencies = {
        'nvim-tree/nvim-web-devicons',
    },
    lazy = false,
    keys = {
        { "<Tab>", ":NvimTreeToggle<CR>", desc = "Tree toogle" },
        { "<S-r>", ":NvimTreeFindFile<CR>", desc = "Tree toogle" },
    },
    opts = {
        sort_by = "case_sensitive",
        on_attach = on_attach,
        open_on_tab = false,
        view = {
            width = 30,
            adaptive_size = false,
            mappings = {
                list = {
                  { key = "<Tab>", action = "" },
                },
            },
        },
    [...]
    },
    config = function(_, opts)
        require("nvim-tree").setup(opts)
    end,
}
```

### Steps to reproduce

1. Nvim
2. `<Tab>`, nvim-tree window opens
3. `<Tab>` again from inside nvim-tree window

### Expected behavior

nvim-tree window should be closed as `<Tab>` is configured to toggle it

### Actual behavior

It `Preview` the selected file/directory (because `<Tab>` default action is preview, I guess)

**Comment by oscarmlage** [comment]
Tried with commit `920868d` and the problem is still there.

**Comment by oscarmlage** [comment]
After reviewing the situation more closely, I realized that the issue was entirely my own fault due to not following the legacy mappings migration guide appropriately.

I sincerely apologize for any confusion or inconvenience my original issue may have caused. Upon reevaluation, I recognized that the issue stemmed from my misunderstanding of the recent changes in nvim-tree. I failed to properly adapt my mappings as per the updated guidelines provided in the migration guide.

To anyone else who may be encountering similar issues, I found the following resources particularly helpful:

- [Migrating To on_attach](https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach)
- [Reverting to a proper version that has :NvimTreeGenerateOnAttach command](https://github.com/nvim-tree/nvim-tree.lua/issues/2378)
- [Commit where legacy mappings were removed](https://github.com/nvim-tree/nvim-tree.lua/commit/18c7a3119839adc4599d838726deae662859c8b2)

Thank you for your understanding, and I'm looking forward to continuing my positive experience with nvim-tree.

**Comment by alex-courtis** [comment]
I think that many users are not seeing startup messages due to https://github.com/neovim/neovim/issues/17832

We could add a newline to the startup warning notifications. This will result in an empty terminal with the following:

```


[NvimTree] unknown option: foo | see :help nvim-tree-setup for available configuration options
Press ENTER or type command to continue
```

**Comment by alex-courtis** [comment]
See #2387
