### ISSUE TITLE
Git Zombies Following Timeout

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2386]
Finally, I've finished my migration.

> I'm not able to replicate. Attempted with git repo in `~/.local/share` which is 296G `.gitignore`

@alex-courtis The easiest way you can replicate it by going into `$HOME` and
```sh
cd $HOME
git init .
nvim
```

_Originally posted by @hinell in https://github.com/nvim-tree/nvim-tree.lua/issues/1966#issuecomment-1693396155_

**Comment by alex-courtis** [comment]
Reproduced.

The root git status will sometime time out. There are many ignored files:

```sh
:; time git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u >/dev/null
git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u >   0.37s user 0.45s system 98% cpu 0.824 total
```

```sh
:; time git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
...
0.36s user 0.72s system 64% cpu 1.659 total
```

```sh
:; git --no-optional-locks status --porcelain=v1 --ignored=matching -u | wc -l
401914
```

401K ignored files is the obvious cause here. The git processing time in addition to the stdout processing time will result in a timeout. No additional time is added when git logging is enabled, despite the massive size of the log file.

Zombies are left, although there will only ever be `MAX_TIMEOUTS = 5` of them.

There's nothing to do here around the git timeouts; this is to be expected in such a case, however we can address zombies.

**Comment by hinell** [comment]
https://github.com/nvim-tree/nvim-tree.lua/blob/00741206c2df9c4b538055def19b99790f0c95c8/lua/nvim-tree/git/runner.lua#L55-L63
Your approach to find untracked files is rather straightforwardly cumbersome and inefficient. I would suggest to do it in an opposite way.

### The Algorithm
First, check whether the current working directory is `$HOME`, roughly:

```lua
-- runner.lua
local CWD  = vim.fn.getcwd()
local HOME = vim.fn.getenv("HOME")
local uv   = vim.uv;

if HOME == CWD then
	local dird, err, name  = uv.fs_opendir(CWD .. "/.git") --, "r", 438)
	if err then
	        -- ...
		print("no git directory!")
	else
	        -- ...
		print("git directory, be careful with looking for untracked files")
		print("warn user that nvim-tree may hang!")
	end 
else
	print("not a home")
end
```

Then, find out how many commits the repo has:
```sh
# shell code as an example
GIT_COMMITS_COUNT=$(git rev-list --all --count)

case $GIT_COMMITS_COUNT; in                             
   (0) echo "no commits";;
   (1) echo "have some commits";; 
   (*) echo "over 1 commits";; 
esac
```

Then, if there are more than 1 or more comits, do:
```sh
git ls-tree --name-only --full-name @
> .config 
> .cache
> Downloads
> ...

```

This will conveniently provide you with all tracked files. Excluding tracked ones, you can mark all the others as untracked ones.

**Comment by hinell** [comment]
https://github.com/nvim-tree/nvim-tree.lua/blob/00741206c2df9c4b538055def19b99790f0c95c8/lua/nvim-tree/git/runner.lua#L55-L63
Your approach to find untracked files is rather straightforwardly cumbersome and inefficient. I would suggest to do it in an opposite way.

### The Algorithm
First, check whether the current working directory is `$HOME`, roughly:

```lua
-- runner.lua
local CWD  = vim.fn.getcwd()
local HOME = vim.fn.getenv("HOME")
local uv   = vim.uv;

if HOME == CWD then
	local dird, err, name  = uv.fs_opendir(CWD .. "/.git")
	if err then
	        -- ...
		print("no git directory!")
	else
	        -- ...
		print("git directory, be careful with looking for untracked files")
		print("warn user that nvim-tree may hang!")
	end 
else
	print("not a home")
end
```

Then, find out how many commits the repo has:
```sh
# shell code as an example
GIT_COMMITS_COUNT=$(git rev-list --all --count)

case $GIT_COMMITS_COUNT; in                             
   (0) echo "no commits";;
   (1) echo "have some commits";; 
   (*) echo "over 1 commits";; 
esac
```

Then, if there are more than 1 or more comits, do:
```sh
git ls-tree --name-only --full-name @
> .config 
> .cache
> Downloads
> ...

```

This will conveniently provide you with all tracked files. Excluding tracked ones, you can mark all the others as untracked ones.

**Comment by hinell** [comment]
https://github.com/nvim-tree/nvim-tree.lua/blob/00741206c2df9c4b538055def19b99790f0c95c8/lua/nvim-tree/git/runner.lua#L55-L63
Your approach to find untracked files is rather straightforwardly cumbersome and inefficient. I would suggest to do it in an opposite way.

### The Algorithm
First, check whether the current working directory is `$HOME`, roughly:

```lua
-- runner.lua
local CWD  = vim.fn.getcwd()
local HOME = vim.fn.getenv("HOME")
local uv   = vim.uv;

if HOME == CWD then
	local dird, err, name  = uv.fs_opendir(CWD .. "/.git")
	if err then
	        -- ...
		print("no git directory!")
	else
	        -- ...
		print("git directory, be careful with looking for untracked files")
		print("warn user that nvim-tree may hang!")
	end 
else
	print("not a home")
end
```

Then, find out how many commits the repo has:
```sh
# shell code as an example
GIT_COMMITS_COUNT=$(git rev-list --all --count)

case $GIT_COMMITS_COUNT; in                             
   (0) echo "no commits";;
   (1) echo "have some commits";; 
   (*) echo "over 1 commits";; 
esac
```

Then, if there are more than 1 or more comits, do:
```sh
git ls-tree --name-only --full-name @
> .config 
> .cache
> Downloads
> ...

```

This will conveniently provide you with all tracked files. Just exclude all tracked paths from current list of paths held by nvim-tree and mark them as untracked. That's it.

**Comment by alex-courtis** [comment]
> Your approach to find untracked files is rather straightforwardly cumbersome and inefficient.

Thank you for your feedback.

> I would suggest to do it in an opposite way.

Is this a generic means to identify untracked, or one specific to `$HOME`? I'm open to a generic solution but not one specific to that case.

Ignored performance was improved recently #2326 however there is always room for more improvements around git performance.

Please raise a pull request with your generic solution to improve untracked performance.

**Comment by alex-courtis** [comment]
This issue is for handling git zombies, not `$HOME` performance or general git performance. Let's keep those discussions in the pull request or another issue.
