### ISSUE TITLE
Marks / bookmarks symbol is misaligned if renderer.group_empty = true

### ISSUE THREAD

**Issue by tjex** [nvim-tree/nvim-tree.lua#2392]
### Description

When marking a file, and `renderer.group_empty = true` the mark symbol gets set one line above where the file actually resides. 

Here are screenshots to illustrate (cursor is located at the file which was marked): 

./parent/child:
![Screenshot 2023-08-29 at 12 44 16](https://github.com/nvim-tree/nvim-tree.lua/assets/83029642/3e4b97e3-abbb-4ea6-9d23-1f9a1e1585f7)

.parent/child/baby (e.g. the depth of folders with no files in them, does not affect mark placement):
![Screenshot 2023-08-29 at 12 44 57](https://github.com/nvim-tree/nvim-tree.lua/assets/83029642/012a5359-f9ec-4c9a-b670-571b54bcd72e)

./parent/child/baby (with marked file in child):
![Screenshot 2023-08-29 at 12 46 50](https://github.com/nvim-tree/nvim-tree.lua/assets/83029642/6ad571f0-ae00-47e6-8c1d-524f4bc03b36)

./parent/child/baby (with marked file in child - `renderer.group_empty = false`): 
![Screenshot 2023-08-29 at 13 01 44](https://github.com/nvim-tree/nvim-tree.lua/assets/83029642/e7920ef2-f59f-4478-a344-bae6cd8414b3)

here also in minimal config:
![Screenshot 2023-08-29 at 13 08 05](https://github.com/nvim-tree/nvim-tree.lua/assets/83029642/bb81dbcf-6378-4d75-afc5-c4ee52d26222)

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS 13.5

### nvim-tree version

0074120

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
    require("packer").startup {
        {
            "wbthomason/packer.nvim",
            "nvim-tree/nvim-tree.lua",
            "nvim-tree/nvim-tree.lua",
            "nvim-tree/nvim-web-devicons",
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
            display = { non_interactive = true },
        },
    }
end
if vim.fn.isdirectory(install_path) == 0 then
    print "Installing nvim-tree and dependencies."
    vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
    require("nvim-tree").setup {
        renderer = {
            group_empty = true
        },
    }
end
```

### Steps to reproduce

1. replicate folder / file structure from screenshots.
2. mark a file in a folder with an empty parent with `renderer.group_empty = true` -> mark is missaligned
3. same as above but set to `false` -> mark is alligned

### Expected behavior

mark symbols are aligned with the marked file when `renderer.group_empty = true` some folder above in the directory tree does not contain any files.

**Comment by tjex** [comment]
Would this be the place to add some logic?
(Maybe I can have a crack at this. But not something to put much trust in being pulled off)

`lua/marks/init.lua` line 55:

```lua
function M.draw()
  if not view.is_visible() then
    return
  end

  M.clear()

  local buf = view.get_bufnr()
  local add = core.get_nodes_starting_line() - 1
  Iterator.builder(core.get_explorer().nodes)
    :recursor(function(node)
      return node.open and node.nodes
    end)
    :applier(function(node, idx)
      if M.get_mark(node) then
        vim.fn.sign_place(0, GROUP, SIGN_NAME, buf, { lnum = idx + add, priority = 3 })
      end
    end)
    :iterate()
end

```

**Comment by alex-courtis** [comment]
regression since d8b154c

**Comment by alex-courtis** [comment]
I would be most grateful for a PR to resolve this: [wiki: Development](https://github.com/nvim-tree/nvim-tree.lua/wiki/Development)
