### ISSUE TITLE
adaptive window width?

### ISSUE THREAD

**Issue by yimingwangdell** [nvim-tree/nvim-tree.lua#2393]
**Is this a question?**

**Can this functionality be implemented utilising API?**
Don't know

**Is your feature request related to a problem? Please describe.**
I can only set a fixed window width, but when I open a java project, file name is out of tree window.

**Describe the solution you'd like**
if file path is deep and cannot be rendered well, adjust window size and cursor position.

**Describe alternatives you've considered**

**Additional context**

**Comment by gegoune** [comment]
Have a look at `:h nvim-tree.view.width`.

**Comment by saadjs** [comment]
@yimingwangdell something like this could work:
```lua
keymap.set("n", "<leader>=", "<cmd>NvimTreeResize +5<CR>", { desc = "Increase file explorer width" })
keymap.set("n", "<leader>-", "<cmd>NvimTreeResize -5<CR>", { desc = "Decrease file explorer width" })
```
