### ISSUE TITLE
statuscolumn support - blocked

### ISSUE THREAD

**Issue by gukz** [nvim-tree/nvim-tree.lua#2394]
Neovim has support the new feature: statuscolumn
https://github.com/neovim/neovim/pull/20621
please allow user config this property and set it to the tree window buffer.

currently, if I set the statuscolumn for global, the tree window's statuscolumn will not always update. 
see below, I set the `statuscolumn="%=%{v:relnum?v:relnum:v:lnum} "`

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/12511562/0f53a131-7c4e-4bb7-87d1-3bb5a1ce01c7)

what am I request for?
1, allow user customize the statuscolumn just like the signcolumn.
2, fix the statuscolumn update bug (optional)

**Comment by alex-courtis** [comment]
related: #1510 missing diagnostic placement

**Comment by alex-courtis** [comment]
This is fantastic news! It allows more flexibility for sign placement.

I don't think this is ready yet:
```
:; nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192
```

`nvim --clean README.md`

`:let &statuscolumn="%=%{v:relnum?v:relnum:v:lnum} "`

Cursor down and watch the line number become corrupted:
![20230902_111604](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/baf7adb7-551f-44f3-8f66-ef63ba5bab4b)

Let's revisit this once the feature is ready.

**Comment by gegoune** [comment]
@alex-courtis I can't replicate issue you described above. There were numerous fixes regarding `statuscolumn` on master since September.

**Comment by alex-courtis** [comment]
Still happening on 0.9.4

xterm:
![20231202_101113](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/714174ac-1183-453d-9e50-ec2f8a5e875c)

**Comment by alex-courtis** [comment]
master (983defd28) too.

I think I'm doing it wrong.

![20231202_101816](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/e6bc2cee-09e2-4ef6-ae2f-b20b7c988f32)

**Comment by YanWQ-monad** [comment]
@alex-courtis According to the documentation of [`statuscolumn`](https://neovim.io/doc/user/options.html#'statuscolumn'):
> When using [v:relnum](https://neovim.io/doc/user/vvars.html#v%3Arelnum), keep in mind that cursor movement by itself will not cause the ['statuscolumn'](https://neovim.io/doc/user/options.html#'statuscolumn') to update unless ['relativenumber'](https://neovim.io/doc/user/options.html#'relativenumber') is set.

It says that if one want to use `v:relnum`, one must also set `relativenumber` to keep line number updated.

So, if you set
```
:set relativenumber
:let &statuscolumn="%=%{v:relnum?v:relnum:v:lnum} "
```
the corrupted line numbers go away. :)

**Comment by alex-courtis** [comment]
Thank you.

Likely related: https://github.com/nvim-tree/nvim-tree.lua/discussions/2640

**Comment by alex-courtis** [comment]
> @alex-courtis According to the documentation of [`statuscolumn`](https://neovim.io/doc/user/options.html#'statuscolumn'):
> 
> > When using [v:relnum](https://neovim.io/doc/user/vvars.html#v%3Arelnum), keep in mind that cursor movement by itself will not cause the ['statuscolumn'](https://neovim.io/doc/user/options.html#'statuscolumn') to update unless ['relativenumber'](https://neovim.io/doc/user/options.html#'relativenumber') is set.
> 
> It says that if one want to use `v:relnum`, one must also set `relativenumber` to keep line number updated.
> 
> So, if you set
> 
> ```
> :set relativenumber
> :let &statuscolumn="%=%{v:relnum?v:relnum:v:lnum} "
> ```
> 
> the corrupted line numbers go away. :)

That works beautifully:  `view.relativenumber = true` results in `:let &statuscolumn="%=%{v:relnum?v:relnum:v:lnum} "` functioning correctly.

@gukz are you satisfied with this outcome?

**Comment by gukz** [comment]
@alex-courtis that's so cool, everything just works!!! a big thank you.
