### ISSUE TITLE
NvimTreeOpenedFileIcon  Highlight Group

### ISSUE THREAD

**Issue by LinuxIsCool** [nvim-tree/nvim-tree.lua#2398]
Why is there no NvimTreeOpenedFileIcon  Highlight Group? 

I see NvimTreeOpenedFolderIcon  highlight group. But files there is only NvimTreeOpenedFile.

**Comment by alex-courtis** [comment]
`highlight_opened_files` icon and name use `NvimTreeOpenedFile`

`NvimTreeOpenedFolderIcon` could be added, defaulting to `NvimTreeOpenedFile`

Those renderer `_highlight` and `_placement` options could use a refactor for better clarity, however that's a task for another day.
