### ISSUE TITLE
Highlight Overhaul

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2415]
#2410 demonstrated that highlighting can be additive e.g. add underline with a different colour.

There are some inconsistencies in how highlighting is applied e.g. `highlight_opened_files` vs `highlight_git`

- [x] Make all highlights additive as per #2410
  - [x] git
  - [x] diagnostics
  - [x] opened
  - [x] modified
  - [x] bookmarks
  - [x] clipboard
- [x] Make all highlights granular `"none", "icon", "name", "all"`
  - [x] highlight_git
  - [x] highlight_diagnostics
  - [x] highlight_opened_files
  - [x] highlight_modified
  - [x] highlight_bookmarks
  - [x] highlight_clipboard
- [x] Refactor highlight groups to be consistent and end with `HL` and `Icon`
  - [x] git
  - [x] diagnostics
  - [x] opened
  - [x] modified
  - [x] bookmarks
  - [x] clipboard
- [x] clean up and standardise `get_colours`
- [x] cterm compatibility
- [x] investigate term compatibility (e.g. linux) - colours and highlights are distinct and readable, just missing icons
- [x] legacy highlight group linking
- [x] simplify renderer builder for efficiency

Refactor may be silently done as per options.

**Comment by siduck** [comment]
hi @alex-courtis , Is it possible to use different colors & icons for some specific folders?

like vscode does

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/59060246/8b4be354-c685-404e-9258-cc39009ba687)

**Comment by alex-courtis** [comment]
There is precedent for a Highlight suffix:

`CocErrorHighlight`
`NeogitDiffAddHighlight`
`MasonHighlight`

**Comment by alex-courtis** [comment]
Colours are just not... correct e.g. green will always return a red: https://github.com/nvim-tree/nvim-tree.lua/blob/9689d0de4d6556b569e308cbf02169f8e7f0d1ac/lua/nvim-tree/colors.lua#L17

Possible solution: just use the regular colours `Green` `Red` etc. as they are always present.

**Comment by alex-courtis** [comment]
Strikethrough is not reliably coloured:
`nvim --clean`
`:hi CursorLine guifg=red gui=strikethrough guisp=green`

It should be used sparingly.

**Comment by alex-courtis** [comment]
Remove `picture_map` as it is handled by nvim-web-devicons
