### ISSUE TITLE
curret_window breaks split.

### ISSUE THREAD

**Issue by MKrbm** [nvim-tree/nvim-tree.lua#2418]
### Description

current_window breaks the split window

### Neovim version

```text
NVIM v0.9.1
```

### Operating system and version

WSL2

### nvim-tree version

920868dba13466586897a8f40220eca6b2caac41

### Clean room replication

```lua
just call require("nvim-tree.api").tree.toggle({current_window=true}) in command line.
```

### Steps to reproduce

1. split window e.g. vertically.
2. Open nvim-tree with `require("nvim-tree.api").tree.toggle({current_window=true})` on a split window.
3. after toggling back to the previous file by running above function once again, then the split window will also be closed.

**Comment by gegoune** [comment]
Isn't that the correct behaviour? It just toggles it, we don't store state of the window before injecting nvim-tree into it, I believe. Since you didn't fill in Expected behaviour field it's difficult to know what you expect.

**Comment by MKrbm** [comment]
As you say, I think this is expected behavior, and hence, it might be better to post in feature request.

But what I expected was after opening a file in injected nvim-tree, the file opens on the same split window and previous buffers also preserved.

**Comment by gegoune** [comment]
It depends on how you are opening file.

Don't think there is anything actionable here, if you have more usage related questions please open new discussion, or if you require new functionality please open new issue or better yet PR.
