### ISSUE TITLE
Missing Nerd font Glyphs referenced in tree. 

### ISSUE THREAD

**Issue by vonschutter** [nvim-tree/nvim-tree.lua#2421]
### Description

Missing Nerd font Glyphs referenced in tree. 
      { "󰈚  Recent Files", "Spc f o", "Telescope oldfiles" },
      { "󰈭  Find Word", "Spc f w", "Telescope live_grep" },

Several are missing, but these are 2 examples. Nerdfonts.com have updated the files and removed/replaces several glyphs. You developers likely use the old fonts. 

### Neovim version

```text
NVIM 0.9... Ubuntu snap.
```

### Operating system and version

Ubuntu 23.04

### nvim-tree version

Latest... installed nvchad today to check. 

### Clean room replication

```lua
Just install nvchad in a new system/vm and add the latest nerdfonts. I used Hack. No go.
```

### Steps to reproduce

1 Just install nvchad in a new system/vm and 
2 add the latest nerdfonts. I used Hack. No go.
3 try

### Expected behavior

By default with the nerd fonts it should look like on the screenshots.

### Actual behavior

you see the hex representations of the non-existing glyphs.

**Comment by gegoune** [comment]
Will not debug nvchad. Please provide replication steps as per form.

**Comment by alex-courtis** [comment]
Closing, insufficient information.
