### ISSUE TITLE
Opening files with Windows system viewer under WSL 

### ISSUE THREAD

**Issue by hendrikbursian** [nvim-tree/nvim-tree.lua#2428]
**Can this functionality be implemented utilising API?**
no

**Is your feature request related to a problem? Please describe.**
Under WSL I cannot and don't want to open files like a PDF within the WSL instance.

**Describe the solution you'd like**
I would like nvim_tree to open the files with the [`wslview`](https://manpages.ubuntu.com/manpages/jammy/man1/wslview.1.html) utility analog to how the [`vim.ui.open`](https://github.com/neovim/neovim/blob/b8103eece30dab8add09e134820b690d9fd00330/runtime/lua/vim/ui.lua#L146) api does it. 

**Describe alternatives you've considered**
For now I just do `require('nvim-tree.actions.node.system-open').config.system_open.cmd = 'wslview'`

**Additional context**
Maybe the [`nvim-tree.actions.node.system-open`](https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/actions/node/system-open.lua) function can make use of `vim.ui.open` itself.

Thank you for the plugin. I use it frequently and I am very happy how it turned out.

**Comment by alex-courtis** [comment]
`vim.ui.open` is rather useful. It will greatly reduce complexity and improve compatibility. Unfortunately it's not yet been released... #2430

In the interests of keeping things generic and flexible, perhaps we might allow `system_open` to take a function in, in the same manner as `view.width`. The user can then decide _how_ top open based on, say, file name.

**Comment by alex-courtis** [comment]
You could do something like this to replace system open:

```lua
  vim.keymap.set("n", "?", function()
    local api = require("nvim-tree.api")
    local node = api.tree.get_node_under_cursor()
    -- decide what to do with node.absolute_path
  end, opts("something something open"))
```

That might be preferable; changing system_open will be obsolete once ui.open is ready.

**Comment by hendrikbursian** [comment]
That sounds good. I can imagine a few scenarios where one would like to use different handling of filetypes/folders etc. `ui.open` could be the default behaviour.

**Comment by alex-courtis** [comment]
Closing this one. Proper solution will come with #2430
