### ISSUE TITLE
validate view.width.padding as number|function only

### ISSUE THREAD

**Issue by IZ-ZI** [nvim-tree/nvim-tree.lua#2440]
### Description

Getting a message on startup as follows, have been using the config for a long time without any issues:

[NvimTree]
Unknown option: view.width.padding

And when I looked at :help nvim-tree-opts-view, view.width.padding is definitely a valid option. I just finished migrating from packer to Lazy today and accidentally updated a lot of my plugins, is this related?

### Neovim version

```text
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10

### nvim-tree version

113e095

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    view = {
      width = {
        padding = 3,
        min = 33,
      },
      cursorline = true,
      centralize_selection = true,
    },
    renderer = {
      add_trailing = false,
    },
    actions = {
      file_popup = {
        open_win_config = {
          col = 1,
          row = 1,
          relative = "cursor",
          border = "single",
          style = "minimal",
        },
      },
    },
    hijack_cursor = false,
    modified = {
      enable = true,
    },
    update_cwd = true,
    update_focused_file = {
      enable = false,
      update_root = true,
      ignore_list = {},
    },
    --on_attach = require("modules.nvim-tree-mappings").on_attach,
  }
end
```

### Steps to reproduce

Just fire up nvim to get the "unknown option" message.

### Expected behavior

No warning messages.

### Actual behavior

Warning message regarding unknown option.

**Comment by alex-courtis** [comment]
Looks like a documentation issue. Only strings are supported.

**Comment by alex-courtis** [comment]
Lazy is not recommended. https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation#lazy-loading

If you have a valid use case, I'd love to hear it :)

**Comment by IZ-ZI** [comment]
> Lazy is not recommended. https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation#lazy-loading
> 
> If you have a valid use case, I'd love to hear it :)

I meant to say I switching to the package manager Lazy.nvim, and I am in fact not lazy-loading nvim-tree; it is loaded at the start of nvim.

I just tried setting view.width.padding with a string, still the same unknown option message.

**Comment by alex-courtis** [comment]
> I just tried setting view.width.padding with a string, still the same unknown option message.

I stand corrected, please accept my apologies, it seems I confused it with the renderer padding. It should be a number or function, not a string.

The option validator will need to be updated and the documentation updated to describe the function.
