### ISSUE TITLE
change_root(path) and symlinks 

### ISSUE THREAD

**Issue by andyl** [nvim-tree/nvim-tree.lua#2445]
**Is this a question?**
No

**Can this functionality be implemented utilising API?**
This is a request for change in the API behavior

**Is your feature request related to a problem? Please describe.**
My lua plugin runs `require("nvim-tree.api").tree.change_root(path)`.  When `path` is a symlink, NvimTree shows the symlink target, rather than the symlink.  Some of the symlink targets are very long, making it difficult to read the project root at-a-glance.

**Describe the solution you'd like**
Show the requested symlink, rather than the symlink target.

**Describe alternatives you've considered**
It might be nice for `change_root` to take an option `expand_path: T/F` if folks wanted to retain the current behavior...

**Additional context**
Maybe this is related to #2015 ?

Note that when I CD to the symlink directory and open NVIM, NVIM-tree shows the symlink path, not the symlink target.

**Comment by alex-courtis** [comment]
The case is the same - root path symlinks should be treated as "first class" folders. That's standard behaviour for most (all?) unix applications.

Tracking in #2015 

We do need and overhaul of symlink handling.
