### ISSUE TITLE
`NvimTreeImageFile` highlight not working for `webp` and `jxl` files

### ISSUE THREAD

**Issue by zootedb0t** [nvim-tree/nvim-tree.lua#2450]
### Description

Image files such as `png,jpg` are highlighted with `NvimTreeImageFile` highlight group, but this highlight group doesn't apply for `webp,jxl` image files.

![Screenshot_2023-10-07-06-51-26_1920x1080](https://github.com/nvim-tree/nvim-tree.lua/assets/62596687/c043f0f5-b8b9-4ff6-8dc0-5f17fb9def38)

### Neovim version

```text
NVIM v0.10.0-dev-1278+g1e7e9ee91
Build type: RelWithDebInfo
LuaJIT 2.1.1695653777
```

### Operating system and version

Linux archBTW 6.5.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 x86_64 GNU/Linux

### nvim-tree version

master, 85abe29

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua
2. Open NvimTree inside any project that has webp files.

### Expected behavior

webp files should have same highlight as png file.

### Actual behavior

webp file has different highlight than png,jpg files.

**Comment by Akmadan23** [comment]
You're right, as of now the only image extensions highlighted as `NvimTreeImageFile` are `jpg`, `jpeg`, `png` and `gif`. This can be easily fixed, I'll take care of it right away.

**Comment by Akmadan23** [comment]
Sorry I completely missed your PR... :sweat_smile:

**Comment by alex-courtis** [comment]
https://github.com/nvim-tree/nvim-web-devicons/pull/318 should be sufficient.
