### ISSUE TITLE
Navigation via `diagnostics.next` and `diagnostics.prev` doesn't work

### ISSUE THREAD

**Issue by hinell** [nvim-tree/nvim-tree.lua#2460]
### Description

I can't find similar issue.

Hitting both `]e` and `[e` doesn't move cursor to the next/previous diagnostic.
Neither it works via programmatic calls (you have to open `nvim-tree` window):
```lua
lua =require("nvim-tree.api").node.navigate.diagnostics.prev()

```

### Neovim version

```text
NVIM v0.10.0-dev-ac1c23442f
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux/Kubuntu

### nvim-tree version

53b0bcaadaffb505acff230578b56a86ec1ab38a

### Clean room replication

```lua
Experiencing same behavior
```

### Steps to reproduce

1. cd into git repo with changes
2. `:NvimTreeToggle`
3. Hit `]e` or `[e`

### Expected behavior

I've used that feature much and not sure how exactly it should work really.

**Comment by alex-courtis** [comment]
I'm not able to replicate, although that doesn't really prove anything.

`]e` and `[e` will navigate to `commands.lua` and `lib.lua`

![20231015_115105](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/22b42fbb-75ae-4136-abff-c51cc36ceb1f)

Let's dig deeper:
* Please test with stable nvim, `0.9.4` at time of writing.
* Please provide a clean room reproducer

**Comment by hinell** [comment]
> Please provide a clean room reproducer

It fails in clean room as well.

**Comment by alex-courtis** [comment]
> It fails in clean room as well.

In that case it could be data related - files/language or the LSP/COC in use.

Please provide a replicator that I can attempt:
* project to create / check out
* nvt-min.lua with the LSP/COC configured
* instructions to replicate e.g. run `nvim -nu /tmp/nvt-min.lua` in X directory, modify Y file, open tree etc.

**Comment by alex-courtis** [comment]
Here's an LSP nvt-min.lua template you could start from, which uses `lua-language-server`

Insert your own language server as required.

[nvt-min.lua.gz](https://github.com/nvim-tree/nvim-tree.lua/files/12910945/nvt-min.lua.gz)

**Comment by hinell** [comment]
Do the `[e` bindings open a file or just focus a ronw in `nvim-tree` window? I didn't use `[e` before

**Comment by gegoune** [comment]
Please provide necessary information to replicate your issue. Video proving that it doesn't work is of no help at all. Follow what have been requested in https://github.com/nvim-tree/nvim-tree.lua/issues/2460#issuecomment-1763533317.

**Comment by gegoune** [comment]
Also you didn't provide any configuration whatsoever.

```lua
lua require("nvim-tree.api").node.navigate.diagnostics.next()
```

works for me and Alex. Please reopen when you edit original post with all necessary steps.

**Comment by hinell** [comment]
@gegoune Seems like I've misconfuged `nvim-tree`. 

It turns out that by default diagnostics are NOT enabled. I'v tweaked config so now it works as expected:

```lua

require("nvim-tree").setup({
	diagnostics = {
		enable       = true,
		show_on_dirs = false
	}
	-- ..
})

```
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/8136158/b4ea8e71-f488-401d-9bfa-bb88eda7fe47)
