### ISSUE TITLE
Weird D&D behaviour with guis

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [nvim-tree/nvim-tree.lua#2462]
### Description

When using with neovide I d&d some folder it works perfectly, nvim tree shows the tree of the folder and everything, but if I then drop another folder on top I get:

Found a swap file by the name ....

and then any option I pick basically destroys nvim tree state and I see a blank buffer..

### Neovim version

```text
NVIM v0.10.0-dev-1327+gf79052fae
Build type: RelWithDebInfo
LuaJIT 2.1.1696795921
```

### Operating system and version

macOS 13.5

### nvim-tree version

53b0bca

### Clean room replication

```lua
install latest with something like lazy d&d a two folders twice and bug's there
```

### Steps to reproduce

1. open neovide
2. drag folder
3. drag folder again (doesn't matter if it's different or not)

### Expected behavior

Just opening a different folder instead of a current one

### Actual behavior

[screenshot](https://i.imgur.com/qVSV7uy.png)

**Comment by alex-courtis** [comment]
Unfortunately I'm unfamiliar with neovide. Please provide steps on how to set that up along with a ["Clean Room" Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) case.

> something like lazy d&d

Is that related to the issue? Is the issue present when that plugin is not present?

> NVIM v0.10.0-dev-1327+gf79052fae

Please re-test with nvim stable, 0.9.4 at time of writing.

**Comment by alex-courtis** [comment]
Closing stale issue.

Please reopen when you have a replication steps.
