### ISSUE TITLE
Can't prevent Nvim-Tree from updating root git directory

### ISSUE THREAD

**Issue by JaoSchmidt** [nvim-tree/nvim-tree.lua#2465]
### Description

**Is this a question?**
Yes

I'm working with two repositories, one of them is inside another in a sub-directory. 
Every time I open a file inside the nested repo, nvim-tree updates the root folder to the sub-directory where .git is located. And is annoying having to go back every time.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.4.11-arch2-1

### nvim-tree version

bb375fb

### Clean room replication

```lua
lvim.builtin.nvimtree.setup = {
  update_focused_file = {
    enable = false,
    update_root = false,
  },
  actions = {
    change_dir = {
      enable = false,
    }
  }
}
```

### Steps to reproduce

1. `git init`
2. `touch arbitrary_file.txt`
3. `mkdir nested`
4. `cd nested`
5. `touch arbitrary_nested.txt`
6.  `git init`

### Expected behavior

root directory will stay fixed when I open a file inside the nested repo

### Actual behavior

root directory changes to the same directory where .git is located

**Comment by alex-courtis** [comment]
I'm not able to reproduce this with a ["Clean Room" Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication)

It looks like you are using lunarvim which could be the cause of this.

Please provide a minimal configuration reproducer.

**Comment by alex-courtis** [comment]
Closing stale issue.

Please reopen when you have a replication steps.
