### ISSUE TITLE
How can I disable the new S-Tab mapping?

### ISSUE THREAD

**Issue by moniquelive** [nvim-tree/nvim-tree.lua#2473]
Howdy, @alex-courtis 

I noticed this [commit](https://github.com/nvim-tree/nvim-tree.lua/commit/aaee4cd896b74f85a81bed7eef2db7869960c4d0) added a new mapping to the plugin.

Which broke my workflow. I used to toggle nvim-tree with S-Tab, now I get stuck on it... How can I disable this new mapping?

TIA.

**Comment by alex-courtis** [comment]
You can remove mappings, see `:help nvim-tree-mappings`

```lua
    vim.keymap.del('n', '<s-tab>', { buffer = bufnr })
```

However I have removed that default mapping as it may indeed be disruptive.
