### ISSUE TITLE
Git Actions

### ISSUE THREAD

**Issue by hinell** [nvim-tree/nvim-tree.lua#2474]
https://github.com/nvim-tree/nvim-tree.lua/blob/aaee4cd896b74f85a81bed7eef2db7869960c4d0/lua/nvim-tree/actions/fs/rename-file.lua#L23-L40

### **Describe the solution you'd like**
The  `e` and `r` don't respect git repo: by renaming something we loose track of file path history. I would like to be able to rename filepath by using `git mv` (instead of system command) in order to keep track of file renames:
```
git mv <src_path> <dst_path>
```

Currently, `nvim-tree` doesn't provide this feature forcing me to rename file by using git manually.

### **Describe alternatives you've considered**
Running `!git mv % <path_no_new_name>` is rather clunky...
Running `!git -A <path_no_new_name>` is rather clunky and not something I want...

### **Can this functionality be implemented utilising API?**
NO.

### **Additional context**
I'ts difficult to easily contribute API feature, cause:
1. The [runner](https://github.com/nvim-tree/nvim-tree.lua/blob/aaee4cd896b74f85a81bed7eef2db7869960c4d0/lua/nvim-tree/git/runner.lua#L169-L173) is not a generic lua wrapper for git:
* it's hard-wired to run only single git subcommand: `status`
* quite intricate interally - it's hard to extend
* no docs/comments

3. This repo has no dedicated `git` wrapper for running & handling git output (there is a dedicated fast [libgit2 lua bindings](https://github.com/libgit2/luagit2) btw)
4. Intent of `nvim-tree.git` is unclear

**Comment by alex-courtis** [comment]
This comprehensive solution might help you out: [Git Stage Unstage Files And Directories From The Tree](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#git-stage-unstage-files-and-directories-from-the-tree)

I'm using a (dumber) approach for git operations, mapping this one to `gu`:
```lua
local function git_unstage()
  local path, dir = node_path_dir()
  if path and dir then
    vim.fn.system({ "git", "-C", dir, "restore", "--staged", path })
  end
end
```

Changes to `.git/index` are be seen and the tree status is updated.

**Comment by alex-courtis** [comment]
I'll investigate a git wrapper however I can't promise anything.

**Comment by hinell** [comment]
@alex-courtis For a low-cost solution, you may peek wrappers at (it would be best if all maintainers unite to create unified api):
* [gitsigns]
* [neogit](https://github.com/NeogitOrg/neogit/)
* [diffview](https://github.com/sindrets/diffview.nvim)

> _I'm using a (dumber) approach_

It's nice to have htis for paths; I usually stick to [gitsigns] to stage hunk-by-hunk

[gitsigns]: https://github.com/lewis6991/gitsigns.nvim/

**Comment by alex-courtis** [comment]
Unfortunately we can't practically move to [libgit2 lua bindings](https://github.com/libgit2/luagit2) as it requires native compilation. Almost no plugins use that due to installation dramas.

It could be an optional implementation for power users.

**Comment by alex-courtis** [comment]
> For a low-cost solution, you may peek wrappers at (it would be best if all maintainers unite to create unified api):

It would be sensible for many git plugins to use a single abstraction layer. That would be a large task...

**Comment by hinell** [comment]
@Unfortunately 

> Unfortunately we can't practically move

I'm not asking for that. I'm requesting a feture that would take renaming into account in git, so it kees to track of it. It's totally fine if we go with something like `vim.cmd([[!git mv ... ]])`.

**Comment by hinell** [comment]
I've changed title back. It's all about using git for renaming. Whether to use dedicated libraries or terminal git command or not - is up to implementer.

**Comment by alex-courtis** [comment]
We do have a mechanism for renaming - the recipe. A git executable call is the only "API" that git provides.

Is there an issue with the renaming? The git watcher should pick up changes immediately.

**Comment by hinell** [comment]
It's a feature request.

Currently if you rename a file by using `nvim-tree` in a git repo the git will count it as `deleted`  and the renamed file will be considered as `untracked` forcing me to make a full circle back to rename it back and then `git mv`.

It would be nice if `nvim-tree` avoids this situation by using `git mv` command for for tracked files so their renames is handled by git and history isn't lost.

**Comment by alex-courtis** [comment]
I see, no. `mv file file.newname` results in deleted / untracked as expected. When you stage, git will recognise the rename.

The tools are there, you just need to implement it yourself.

**Comment by hinell** [comment]
> When you stage, git will recognise the rename.

It won't unless `-A` flag is given to `git add`. Another consideration is that I use `gisings` for staging from within neovim, not from terminal i.e. to stage hunks, not entire files. Imagine it's already renamed and changes added.

**Comment by alex-courtis** [comment]
### Feature

API additions to allow git mutation. These may be mapped by default.

`gu`, `ga`, `gr` etc. would be intuitive mappings.

### Prior Art

Recipe: [Git Stage Unstage Files And Directories From The Tree](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#git-stage-unstage-files-and-directories-from-the-tree)

[neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/defaults.lua#L558)

**Comment by hinell** [comment]
Well, even if we make an extension, we can't hook into default `rename` action. Users will have to redefine it.

**Comment by alex-courtis** [comment]
See https://github.com/nvim-tree/nvim-tree.lua/pull/2551#issuecomment-1828908354
