### ISSUE TITLE
copy does not work

### ISSUE THREAD

**Issue by nimaai** [nvim-tree/nvim-tree.lua#2481]
### Description

After pressing `c` the content of the file does not get copied. After checking `:reg` I don't see the content of the file anywhere. 

Command reports `[NvimTree] ... added to clipboard.` though.

Also, all other copy commands work correctly.

Any idea what's wrong? How can I debug it?

### Neovim version

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
```

### Operating system and version

macOS 13.6

### nvim-tree version

40b9b88

### Clean room replication

```lua
https://github.com/nimaai/stuff/blob/master/dotfiles/init.vim
https://github.com/nimaai/stuff/blob/master/dotfiles/nvim_tree.lua

these are my both conf files i am using
```

### Steps to reproduce

1. install both conf files mentioned above
2. open nvim_tree
3. press `c` on any of the file names
4. check `:reg`

### Expected behavior

`c` should copy the contents of the files into the clipboard

### Actual behavior

`c` it does not

**Comment by gegoune** [comment]
Please provide minimal reproducible configuration.

**Comment by nimaai** [comment]
```
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
curl https://gist.githubusercontent.com/nimaai/abea061c6067301537661e7605e91386/raw/4ac55dce76169a9cb010920594259112583d325f/gistfile1.txt \
  > /tmp/init.vim
nvim -u /tmp/init.vim
:PlugInstall
:quit
echo "foo bar baz" > /tmp/test.txt
nvim -u /tmp/init.vim /tmp/
press c on test.txt
:reg
```

**Comment by gegoune** [comment]
BTW, aren't you after `y`, or `gy` rather than `c`? `c` is copying files, you should get a message after pressing it and can paste copy of the file by pressing `p`.

**Comment by hinell** [comment]
@nimaai Well `c` doesn't copy content; you use to `p`aste `c`opied path, not the content: see `h nvim-tree-api.fs.copy.node()`

I've checked it out, it works form me;

```lua
NVIM v0.10.0-dev-ac1c23442f
Build type: MinSizeRel
LuaJIT 2.1.0-beta
```

**Comment by nimaai** [comment]
argh. got it. thanks.
