### ISSUE TITLE
Mapping customization that works only in nvim-tree

### ISSUE THREAD

**Issue by spotsccc** [nvim-tree/nvim-tree.lua#2490]
Hi! 

I'd like to create a mapping that will only work in nvim-tree. In my case i'm tring to do something like this: 
```
local my_on_attach = function (bufnr)
  local api = require "nvim-tree.api"

    local function opts(desc)
      return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
    end

    -- default mappings
    api.config.mappings.default_on_attach(bufnr)

    -- custom mappings
    vim.keymap.set('n', 'l', api.node.open.edit)

end
```

I expect that "l" will work as usual in other buffers, and only when i focus nvim-tree it would open node in nvim tree. But it doesn't work like that. 

Are there some ways to do this? Or maybe i do something wrong? I can't find an answer for my question in documentation.

**Comment by gegoune** [comment]
You need to call `opts` function to return table as last argument in `vim.keymap.set`.
