### ISSUE TITLE
E5113: Error while calling lua chunk

### ISSUE THREAD

**Issue by ric980** [nvim-tree/nvim-tree.lua#2494]
### Description

After upgrading to latest version of the plugin, I get the following error on nvim start:

```
Error detected while processing /Users/ric980/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: attempt to call field 'setup' (a nil value)
stack traceback:
        ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: in function 'setup'
        /Users/ric980/.config/nvim/lua/plugins/nvim-tree.lua:1: in main chunk
        [C]: in function 'require'
        /Users/ric980/.config/nvim/lua/plugins/init.lua:6: in main chunk
        [C]: in function 'require'
        /Users/ric980/.config/nvim/init.lua:13: in main chunk

```

### Neovim version

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.5.2

### nvim-tree version

branch: master, commit: 78a9ca5ed6557f29cd0ce203df44213e54bfabb9

### Clean room replication

```lua
No configuration is needed. It fails with default empty settings.
```

### Steps to reproduce

1. Install the plugin using Lazy plugin manager.
2. Setup with default config: `require("nvim-tree").setup()`
3. Launch nvim.
4. Fails on start.

### Expected behavior

No error on start up.

### Actual behavior

Error on start up.

```
Error detected while processing /Users/ric980/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: attempt to call field 'setup' (a nil value)
stack traceback:
        ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: in function 'setup'
        /Users/ric980/.config/nvim/lua/plugins/nvim-tree.lua:1: in main chunk
        [C]: in function 'require'
        /Users/ric980/.config/nvim/lua/plugins/init.lua:6: in main chunk
        [C]: in function 'require'
        /Users/ric980/.config/nvim/init.lua:13: in main chunk
```

**Comment by gegoune** [comment]
Works just fine for me without lazy, seems like it's problem with lazy which we have no expertise with. Can you bisect to change which introduced an issue?

**Comment by hjhdsg** [comment]
I'm using Packer, and it can load nvim-tree on Linux, but I'm facing the same error on Windows.

**Comment by Akmadan23** [comment]
> Error on start up.
> 
> ```
> Error detected while processing /Users/ric980/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: attempt to call field 'setup' (a nil value)
> stack traceback:
>         ...c/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:804: in function 'setup'
>         /Users/ric980/.config/nvim/lua/plugins/nvim-tree.lua:1: in main chunk
>         [C]: in function 'require'
>         /Users/ric980/.config/nvim/lua/plugins/init.lua:6: in main chunk
>         [C]: in function 'require'
>         /Users/ric980/.config/nvim/init.lua:13: in main chunk
> ```

@ric980 can you show us the files referenced in the error message? It refers to specific lines that we can't see.

**Comment by ric980** [comment]
It fails on this line:

`require("nvim-tree.git.utils").setup(opts)`

I guess requiring nvim-tree.git.utils returns null.

**Comment by ric980** [comment]
I've deleted that line and now it works.

**Comment by Akmadan23** [comment]
> It fails on this line:
> 
> `require("nvim-tree.git.utils").setup(opts)`

Yeah, that's the only file we can see among those referenced in the error message, I was asking for the others (your `init.lua`, `plugins/init.lua` and `plugins/nvim-tree.lua`) so that we can try to reproduce the issue and understand why it happens.

> I guess requiring nvim-tree.git.utils returns null.

It's weird because that's not the case, the error states that the `setup` field is nil in the `nvim-tree.git.utils`, but it's actually a function...

> I've deleted that line and now it works.

This can be a temporary workaround but any time you will update the plugin the problem will come back.

**Comment by alex-courtis** [comment]
> It fails on this line:
> 
> `require("nvim-tree.git.utils").setup(opts)`
> 
> I guess requiring nvim-tree.git.utils returns null.

That one is internal to nvim-tree.

Please stick to public interfaces: `require("nvim-tree").setup(` and `local api = require("nvim-tree.api")`

**Comment by Akmadan23** [comment]
> Please stick to public interfaces: `require("nvim-tree").setup(` and `local api = require("nvim-tree.api")`

From what I understood @ric980 is not calling internal functions in his config, the root of the error he reported is on line 804 of the main `nvim-tree.lua`, which is indeed `require("nvim-tree.git.utils").setup(opts)`. The weird part is that this line shouldn't raise any error since `setup` is a valid field of that module...

**Comment by alex-courtis** [comment]
> From what I understood @ric980 is not calling internal functions in his config, the root of the error he reported is on line 804 of the main `nvim-tree.lua`, which is indeed `require("nvim-tree.git.utils").setup(opts)`.

Please accept my apologies @ric980 

lazy has been very problematic. With a minimal lazy reproducer we may be able to resolve this.

**Comment by ric980** [comment]
OK. I finally found some time to play with my dotfiles. The problem was requiring my mappings.lua before my plugins.lua. I am using the nvim-tree API in the mappings before it is setup in the plugins. Thanks a lot.

**Comment by gegoune** [comment]
So

> Clean room replication

> No configuration is needed. It fails with default empty settings.

wasn't entirely true.

**Comment by SurajSanyol** [comment]
Error detected while processing C:\Users\hp\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\hp\AppData\Local\nvim/lua/config/lazy.lua:17: module 'lazy' not found:
        no field package.preload['lazy']
        no file '.\lazy.lua'
        no file 'C:\Program Files\Neovim\bin\lua\lazy.lua'
        no file 'C:\Program Files\Neovim\bin\lua\lazy\init.lua'
        no file '.\lazy.dll'
        no file 'C:\Program Files\Neovim\bin\lazy.dll'
        no file 'C:\Program Files\Neovim\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\hp\AppData\Local\nvim/lua/config/lazy.lua:17: in main chunk
        [C]: in function 'require'
        C:\Users\hp\AppData\Local\nvim\init.lua:2: in main chunk


tell me how to fix it , I am using windows  machine

**Comment by gegoune** [comment]
This is two years old closed issue. Put some effort into asking for assistance. If you think it's a big open new issue with minimal reproduction config and steps.
