### ISSUE TITLE
skip through empty directories 

### ISSUE THREAD

**Issue by JosefLitos** [nvim-tree/nvim-tree.lua#2497]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a java project and have to open 10 nested directories before I get to the file I am looking for.

**Describe the solution you'd like**
When I want to expand a directory that contains just another directory, expand them all until the directory contents differ from 1.

**Describe alternatives you've considered**
Expanding all subfolders, but that is too much.

**Comment by gegoune** [comment]
Set `nvim-tree.renderer.group_empty` to `true`.

**Comment by JosefLitos** [comment]
From the looks of the code there is not a way to use a custom function to label these possibly very long paths like we can with `root_folder_label`. It would be very handy if such a feature was possible.

**Comment by alex-courtis** [comment]
That should be possible. Your function may be a little... complex.

Please open a new feature request specifying exactly how you think the option should behave as well as with an example function.
