### ISSUE TITLE
change default value to ui.confirm.remove/trash

### ISSUE THREAD

**Issue by debboutr** [nvim-tree/nvim-tree.lua#2498]
Would it be possible to add a default for the `ui.confirm` so that when prompted on `delete` or `trash` it would be `Y` instead of `N`?
`Remove file.txt ? y/N:` -> `Remove file.txt ? Y/n:`

I tried setting `ui.confirm.remove` to `false`, but then there is no prompt at all. I'd prefer to just hit enter on prompt so I don't have to type the `y`

**Comment by Akmadan23** [comment]
Having `N` by default is better for security, this way it's harder to accidentally delete files, but we could add an option to set `Y` by default, which seems a good idea.

**Comment by alex-courtis** [comment]
Users who want to go fast will likely set `ui.confirm.*` anyway so this makes sense.

Yes it's a break, but a desirable one.
