### ISSUE TITLE
Icon in message after rename file

### ISSUE THREAD

**Issue by Dongyomi** [nvim-tree/nvim-tree.lua#2507]
Hi.
Thanks for your plugin.

This is not important but it is for no nvim-web-devicons.

I suggest changing rename-file.lua.

before 

![스크린샷 2023-11-02 08-25-04](https://github.com/nvim-tree/nvim-tree.lua/assets/101002432/c06988fb-eb62-4c8e-8689-584a7364d4a1)

after

![스크린샷 2023-11-02 08-25-15](https://github.com/nvim-tree/nvim-tree.lua/assets/101002432/de81feff-2b0c-4796-8c42-6f9c43ff0d25)

**Comment by Akmadan23** [comment]
Seems reasonable, feel free to submit a PR
