### ISSUE TITLE
Diagnostics Info icon highlight group is incorrect: Expected "NvimTreeLspDiagnosticsInfo" but found "NvimTreeLspDiagnosticsInformation"

### ISSUE THREAD

**Issue by juhaku** [nvim-tree/nvim-tree.lua#2516]
### Description

The diagnostics highlight group used for `info` icon is incorrect. NvimTree has set following highlight groups:
```
NvimTreeLspDiagnosticsWarningFolderText xxx links to NvimTreeLspDiagnosticsWarningText
NvimTreeLspDiagnosticsWarningText xxx links to NvimTreeLspDiagnosticsWarning
NvimTreeLspDiagnosticsErrorFolderText xxx links to NvimTreeLspDiagnosticsErrorText
NvimTreeLspDiagnosticsErrorText xxx links to NvimTreeLspDiagnosticsError
NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
...
NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
NvimTreeLspDiagnosticsError xxx links to DiagnosticError
NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
```
However the highlight group wanted for the `info` icon is `NvimTreeLspDiagnosticsInfo` as defined here: https://github.com/nvim-tree/nvim-tree.lua/blob/c763861afb32f839555f9e797f4392f54ef4ad23/lua/nvim-tree/renderer/components/diagnostics.lua#L73-L76.

I assume the highlight group should be renamed to `*Information` or the NvimTree highlight groups should be corrected with `*Info`

### Neovim version

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958
```

### Operating system and version

Linux 6.1.55-1-MANJARO

### nvim-tree version

master

### Clean room replication

```lua
require("nvim-tree").setup({
	reload_on_bufenter = true,
	select_prompts = true,
	hijack_netrw = false,
	view = {
		width = 50,
	},
	renderer = {
		root_folder_label = ":~:s?$?/?",
		special_files = {},
		highlight_git = true,
		highlight_diagnostics = true,
		highlight_modified = "all",
		indent_markers = {
			enable = true,
		},
		icons = {
			show = {
				folder_arrow = true,
			},
		},
	},
	modified = {
		enable = true,
		show_on_dirs = true,
		show_on_open_dirs = true,
	},
	hijack_directories = {
		enable = false,
		auto_open = true,
	},
	update_focused_file = {
		enable = true,
	},
	diagnostics = {
		enable = true,
		show_on_dirs = true,
		show_on_open_dirs = true,
		debounce_delay = 50,
		icons = {
			hint = "",
			info = "",
			warning = "",
			error = "",
		},
	},
	filters = {
		git_ignored = true,
		dotfiles = true,
		git_clean = false,
		no_buffer = false,
		custom = {},
		exclude = {
			"node_modules",
		},
	},
	actions = {
		expand_all = {
			exclude = {
				"node_modules",
				"target",
				"build",
				".git",
			},
		},
	},
	tab = {
		sync = {
			open = true,
			close = true,
			ignore = {},
		},
	},
})
```

### Steps to reproduce

1. Open nvim with diagnostic enabled workspace (literally any project will do)
2. Open nvim-tree and a file that has info level diagnostics available
3. See results on the nvim-tree the icon color is not highlighted correctly but remains grey color.

### Expected behavior

Should highlight color the icon according to used color theme:
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/26358664/7f8f9708-f181-4135-aa66-700fc53bce42)

### Actual behavior

But the color remains grey:
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/26358664/560c6f28-1a37-40d7-a2b2-5099bbd54ee4)

**Comment by juhaku** [comment]
Quick fix is to link the information highlight group with the info one and the nvim-tree highlights get fixed.
```
hi link NvimTreeLspDiagnosticsInfo NvimTreeLspDiagnosticsInformation
```
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/26358664/4c1cf580-2dcc-403b-8f06-e83c8b31a54c)

**Comment by alex-courtis** [comment]
The highlights are somewhat problematic in their inconsistency. A proper overhaul is in progress #2415

The nvim build-in groups all use `Info` e.g. `DiagnosticInfo`, we should follow that pattern.

In the meantime we can class this as a bug: correct the icon's highlight group to match the documentation.

**Comment by alex-courtis** [comment]
@juhaku thanks for finding this one.

I'd be grateful if you tested #2518

**Comment by juhaku** [comment]
> @juhaku thanks for finding this one.
> 
> I'd be grateful if you tested #2518

Yup, works like a magic, thanks for quick fix :tada:
