### ISSUE TITLE
Diagnostics Not Updated When Tree Not Visible

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2519]
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/2517

<div type='discussions-op-text'>

<sup>Originally posted by **juhaku** November  7, 2023</sup>
Hey,

I'd like a support for functionality where the diagnostics status and what not would be updated / reloaded upon NvimTree  reveal? Is that currently possible? I did not see any configuration option that would enable such thing.

EDIT: There is `nvim-tree.auto_reload_on_write` that allows tree to update while being opened and a file is being written to. Also there is `tree.reload()` API that is tied to `R` command command and `reload_on_bufenter` configuration flag but non of these seem to give remedy to the situation. Like hitting `R` button does not seem to affect much to the state of the tree at least the diagnostics does not get updated. Same happens no matter I travel between different buffers. The only way for diagnostics to actually get updated seems to be by way of writing on buffer while keeping the NvimTree open. 

-Juha</div>

**Comment by alex-courtis** [comment]
Thanks for finding this one @juhaku

Diagnostic events are being received whilst the tree is closed however the nodes are not being updated:

```
[2023-11-07 10:32:58] [diagnostics] DiagnosticChanged
[2023-11-07 10:32:58] [diagnostics] DiagnosticChanged
```

Should see
```
[2023-11-07 10:33:40] [diagnostics] DiagnosticChanged
[2023-11-07 10:33:40] [profile] START diagnostics update
[2023-11-07 10:33:40] [diagnostics] update
...
```

**Comment by juhaku** [comment]
Anytime :slightly_smiling_face:
