### ISSUE TITLE
Error when trying to open NvimTree while Telescope is open

### ISSUE THREAD

**Issue by bryankenote** [nvim-tree/nvim-tree.lua#2520]
### Description

I am seeing this error when trying to open NvimTree with Telescope open with the minimal config I pasted.

```
Error executing Lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:97: Vim:E95: Buffer with this name already exists
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:97: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:246: in function 'open'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:130: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:190: in function 'open'
        ...tart/nvim-tree.lua/lua/nvim-tree/actions/tree/toggle.lua:48: in function 'toggle'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/commands.lua:36: in function <...ck/packer/start/nvim-tree.lua/lua/nvim-tree/commands.lua:35>
```

But this looks a little different in my case. I am using https://github.com/nvim-lua/kickstart.nvim. When I add a minimal configuration of NvimTree to kickstart and follow the same steps I see
```
Error executing Lua callback: .../nvim/lazy/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:66: Invalid window id: 1009
stack traceback:
        [C]: in function 'nvim_win_get_cursor'
        .../nvim/lazy/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:66: in function 'draw'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:132: in function 'open_view_and_draw'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:190: in function 'open'
        ...lazy/nvim-tree.lua/lua/nvim-tree/actions/tree/toggle.lua:48: in function 'toggle'
        ...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:36: in function <...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:35>
```

### Neovim version

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905
```

### Operating system and version

Linux 6.5.9-arch2-1, macOS 13.4.1

### nvim-tree version

commit 0a99c4a

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

`:Telescope`
`<Esc>`
`:NvimTreeToggle`

### Expected behavior

NvimTree should open with no errors.

### Actual behavior

Error with minimal config:
```
Error executing Lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:97: Vim:E95: Buffer with this name already exists
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:97: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:246: in function 'open'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:130: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:190: in function 'open'
        ...tart/nvim-tree.lua/lua/nvim-tree/actions/tree/toggle.lua:48: in function 'toggle'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/commands.lua:36: in function <...ck/packer/start/nvim-tree.lua/lua/nvim-tree/commands.lua:35>
```

**Comment by alex-courtis** [comment]
Reproduced.

Telescope is funny about doing _anything_ whilst its input window is open and loses focus. I often get telescope errors when doing similar things.

We can at least guard against this.

**Comment by geril2207** [comment]
@bryankenote  As a workaround you can setup a map with check, if telescope is open close it. For example:
```
vim.keymap.set("n", "<leader>e", function()
	if vim.bo.filetype == "TelescopePrompt" then
		require("telescope.actions").close(vim.api.nvim_get_current_buf())
	end
	vim.cmd("NvimTreeFocus")
end)
```

**Comment by geril2207** [comment]
@alex-courtis I think the root problem there is that `nvim_open_win` and `vsp` creates new window with telescope buffer(0 in `nvim_open_win` and `vsp` auto), but telescope have `autocmd BufLeave` and it deletes the buffer, therefore new windows close.
https://github.com/nvim-tree/nvim-tree.lua/blob/4ee6366ff1fc5d66231516ed05beffb50004261b/lua/nvim-tree/view.lua#L153-L162


If you change folowing line: https://github.com/nvim-tree/nvim-tree.lua/blob/4ee6366ff1fc5d66231516ed05beffb50004261b/lua/nvim-tree/view.lua#L157 to `vim.api.nvim_command("vsp #" .. M.get_bufnr())` You may see tree buffer, but full screen. 

To open float tree you can change this one : https://github.com/nvim-tree/nvim-tree.lua/blob/4ee6366ff1fc5d66231516ed05beffb50004261b/lua/nvim-tree/view.lua#L155 to `vim.api.nvim_open_win(M.get_bufnr(), true, vim.tbl_extend("force", open_win_config(), { noautocmd = true }))
`  but this one prevents from closing telescope windows.

**Comment by alex-courtis** [comment]
Great work @geril2207  - no telescope specifics.

I'd be most grateful for a PR for the complete solution.

>  this one prevents from closing telescope windows.

Is that an issue? What could we do to resolve it?

We might be able to reuse this bit of functionality instead of the explicit noautocmd:
https://github.com/nvim-tree/nvim-tree.lua/blob/aaee4cd896b74f85a81bed7eef2db7869960c4d0/lua/nvim-tree/actions/node/open-file.lua#L215-L222

**Comment by geril2207** [comment]
@alex-courtis Currently i am not having complete solution, just some drafts, i hope i'll have time during the week to resolve.

**Comment by alex-courtis** [comment]
Hey no worries, there's no pressure.

Many thanks for all your fantastic contributions!

**Comment by geril2207** [comment]
Hi @bryankenote, seems to be fixed by telescope, can you please update telescope to latest commit and check it?

**Comment by bryankenote** [comment]
@geril2207 https://github.com/nvim-telescope/telescope.nvim/commit/18774ec7929c8a8003a91e9e1f69f6c32258bbfe seems to have addressed the issue in my personal config. Even after reverting https://github.com/nvim-tree/nvim-tree.lua/issues/2520#issuecomment-1801342927. Thank you for working on this.
