### ISSUE TITLE
[Feature] icon placement to the end of the line

### ISSUE THREAD

**Issue by sand4rt** [nvim-tree/nvim-tree.lua#2536]
An option to place the icons at the end of the Neo-tree:

![image](https://github.com/nvim-tree/nvim-tree.lua/assets/17591696/6eaf812b-1c64-4140-94e5-fdf36e11b64c)

Perhaps with?:

- `nvim-tree.renderer.icons.modified_placement = "end"`
- `nvim-tree.renderer.icons.diagnostics_placement = "end"`
- `nvim-tree.renderer.icons.bookmarks_placement = "end"`

**Comment by gegoune** [comment]
Duplicate #2349
