### ISSUE TITLE
Gitignore filter doesn't work without .git directory

### ISSUE THREAD

**Issue by dmtrKovalenko** [nvim-tree/nvim-tree.lua#2562]
### Description

I use sapling https://sapling-scm.com/docs/introduction/getting-started which is also compatible with gitignore but nvim-tree does not enable git filter because there is no git folder.

Alternative:
Please consider supporting .ignore file which is a workaround I use for different tools like `rg`.

I can submit PR if there would be a 🟢

### Neovim version

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699180677
```

### Operating system and version

MacOS 13.1

### nvim-tree version

05f55c1

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

1. Remove .git folder 
2. Add .gitignore file
3. Observe that `I` doesnt work

### Expected behavior

`I` does work as expected  

### Actual behavior

`I` doesn't work or a different way to power the ignore files like `.ignore` file support

**Comment by Akmadan23** [comment]
The gitignore filter does not work without a `.git` directory because nvim-tree doesn't parse the `.gitignore` file directly, instead retrieves the git status of each file.
Having a custom filter like `.ignore` was requested in #2367, so let's keep track of it there.
However a PR would be much appreciated!

**Comment by alex-courtis** [comment]
> Having a custom filter like `.ignore` was requested in #2367, so let's keep track of it there.

This is a difficult problem which has no common standard or approach.

Most tools have built their own custom parser / solution.
