### ISSUE TITLE
Problem displaying folder/directories icons

### ISSUE THREAD

**Issue by AmaelMSC** [nvim-tree/nvim-tree.lua#2565]
### Description

When I open the Nvim Tree, thats the view I have : 
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/123114269/402831bf-ab23-4e88-9467-c498876f98b9)

(As we can see, the folder icons are not displaying correctly)
But funny enough, when I open the terminal introduction (using :h nvim-tree-introduction)
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/123114269/c56d0c6d-3abc-4f1f-9202-31f8f37632ea)
It displays correctly.
If anybody has any thoughts about it, well let me know
Thanks in advance

### Neovim version

```text
NVIM v0.9.4
```

### Operating system and version

Debian 11

### nvim-tree version

05f55c1

### Clean room replication

```lua
A setup with CousineNerdFont (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Cousine.zip) installed
- Need nvim-tree
- Need nvim-web-devicons
```

### Steps to reproduce

Just run nvim then access to the tree

### Expected behavior

Should have displayed the folder icons

### Actual behavior

Didnt quite display them

**Comment by gegoune** [comment]
Your font most likely lacks glyphs we use by default. You will either have to patch your font, use different font or configure nvim-tree to use glyphs your font has.

**Comment by AmaelMSC** [comment]
Thanks a lot for the fast answer !
Could you remind me how you do tell nvim-tree to use specific glyphs ? I tried to look for it in nvim-web-devicons but couldnt find where i could configure folder glyphs.

**Comment by gegoune** [comment]
Configuration path to folder glyph is: `renderer.icons.glyphs.folder`. It's a table, you can see it if you search documentation for `arrow_closed`.

**Comment by AmaelMSC** [comment]
Thanks a lot again,
After a few research I found out a really odd thing :
When all special characters are in quotes (either simple or double) this is the view I get :
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/123114269/90a637ad-295f-4395-9988-a9166ccbe81f)
But when they are out of quotes, thats what I get : 
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/123114269/47b239cb-c4a2-4f84-b1c0-4a3aedda6e56)
Is it normal ? Should i try to look out in other places ? Thanks a lot again for all you've done for me

**Comment by gegoune** [comment]
This is quite bizarre indeed. Points to your terminal emulator, which one are you using? Can you try some other one?

**Comment by alex-courtis** [comment]
Could you try a different font? I'm using hack:

```sh
: ; fc-match mono
HackNerdFontMono-Regular.ttf: "Hack Nerd Font Mono" "Regular"
```

**Comment by brdacost** [comment]
I am also having the exact same problem on macos monterey. Also checked a couple fonts, same issue. I'm trying to use MesloLGLDZ Nerd Font (should contain the icons tho)

**Comment by AmaelMSC** [comment]
Hey y'all sorry for not answering for a long long time I had my final exams !
I made it !!!! Just managed to go to the parameters of the gruvbox plugin, then changed the parameter "bold" of NvimTreeFolderIcon to false and it worked!!
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/123114269/0987943e-d3f3-4347-8823-a05f074fe0d3)

Thank you for all your time and efforts and sorry again!
