### ISSUE TITLE
stack traceback

### ISSUE THREAD

**Issue by bty102** [nvim-tree/nvim-tree.lua#2605]
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/125985488/675efa8f-ba04-4e8f-be4a-5be24b29bd12)
when i use the "nvim .\"  command, i get "stack traceback".

**Comment by gegoune** [comment]
Please follow https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication and don't remove default issue template.

**Comment by bty102** [comment]
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/125985488/e7b304bd-aa7d-4d58-85a7-c294d533febf)

**Comment by alex-courtis** [comment]
As @gegoune said, please raise an issue with ALL the fields and a clean room replicator.
