### ISSUE TITLE
E5108 when calling help with g?

### ISSUE THREAD

**Issue by cschult** [nvim-tree/nvim-tree.lua#2609]
### Description

Run "nvim -nu /tmp/nvt-min.lua". Open nvim-tree with :NvimTreeOpen. Press g? to get help screen. Help screen doesn't open, but gives error message:

E5108: Error executing lua: ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:49: attempt to call upvalue 'f' (a nil value)                                                                          
stack traceback:
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:49: in function <...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:47>

### Neovim version

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742
```

### Operating system and version

Arch Linux, Kernel 6.6.8-arch1-1 

### nvim-tree version

f779aba

### Clean room replication

```lua
$ cat /tmp/nvt-min.lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua
2. :NvimTreeOpen
3. g?

### Expected behavior

help screen should appear

### Actual behavior

error message:

E5108: Error executing lua: ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:49: attempt to call upvalue 'f' (a nil value)                                                                          
stack traceback:
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:49: in function <...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/api.lua:47>

**Comment by alex-courtis** [comment]
Thanks for bringing this up.

Since f779aba

**Comment by alex-courtis** [comment]
Please fetch latest for fix.

**Comment by samgranieri** [comment]
Thank you @alex-courtis for fixing this! works like a charm
