### ISSUE TITLE
Renaming of file to different case does not work

### ISSUE THREAD

**Issue by ashish10alex** [nvim-tree/nvim-tree.lua#2610]
### Description

Renaming a file e.g  `rename-file.lua` to `rename-File.lua` does not work as it complains that the file already exists. 
I tested the [underlying code](https://github.com/nvim-tree/nvim-tree.lua/blob/f779abaf2a6aba20107cb84bb468599327128202/lua/nvim-tree/utils.lua#L221)  which checks if the file already exists which seems to be a case insensitive check.  Apologies if this is by design.

### Neovim version

```text
NVIM v0.10.0-dev-565+g3688735c2-Homebrew
Build type: Release
LuaJIT 2.1.1700008891
```

### Operating system and version

Mac OS 14.2.1 (23C71)

### nvim-tree version

f779aba

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua
2. :NvimTreeFindFileToggle
3. Put cursor on the file which I want to rename
4. Change case of the file and press enter

<img width="1589" alt="image" src="https://github.com/nvim-tree/nvim-tree.lua/assets/34306898/26810a73-d2c0-4a2e-886a-189f9371df67">

### Expected behavior

File should be renamed with a different case. 

### Actual behavior

Plugin complaints that the file already exists but it does not.

**Comment by alex-courtis** [comment]
Sorry mate, can't be done: `:help nvim-tree-os-specific`

**Comment by lawrence-laz** [comment]
For anyone with an older version of the plugin, this is already fixed - update the plugin.
