### ISSUE TITLE
Ungroup empty folders

### ISSUE THREAD

**Issue by juefeiyan** [nvim-tree/nvim-tree.lua#2646]
**Is this a question?**
no

**Can this functionality be implemented utilising API?**
no

**Is your feature request related to a problem? Please describe.**
sometimes I need to add files in the middle folder, for example, if the main class of my java project is in 
com/a/b/c/app/Main.java, I might need to add a folder under 
com/a/b/c/config, for now, I am not able to do it.

**Describe the solution you'd like**
1. When a user `expand_or_collapse`  a folder, it will first group the empty folders and show the files in the last folder
2. When a user `expand_or_collapse` a grouped open folder, it will ungroup all empty folders, but the status of all folders is still 'open'
3. When a user `expand_or_collapse` an ungrouped open folder, it will close all folders and files, and the status will be back to step 1

**Describe alternatives you've considered**
nothing

**Additional context**

**Comment by juefeiyan** [comment]
Can anyone assign this task to me? I am happy to implement this future as my first PR on the GitHub

**Comment by geril2207** [comment]
If I undrestood you correctly, you can do it by changing path input
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/62308020/bf322621-65c8-4166-a629-bc1e13c22c27)
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/62308020/e926cafc-10bd-412d-b9f6-ad376b273d87)

**Comment by juefeiyan** [comment]
> If I undrestood you correctly, you can do it by changing path input ![image](https://private-user-images.githubusercontent.com/62308020/299929520-bf322621-65c8-4166-a629-bc1e13c22c27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDczMjEsIm5iZiI6MTcwNjMwNzAyMSwicGF0aCI6Ii82MjMwODAyMC8yOTk5Mjk1MjAtYmYzMjI2MjEtNjVjOC00MTY2LWE2MjktYmMxZTEzYzIyYzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIyMTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZWYwYzE1OGYyMmJjZTI3ZjQ2YjhkYWVhMWZjOTM4YzMwMmU5NGZiZmEwY2JhNDI3YjBkNmJhZjQwY2ZjYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GXOwBAAtG4qXaWrkaRE3JxnaYWsaB62ioE_2vO6WW1Q) ![image](https://private-user-images.githubusercontent.com/62308020/299929954-e926cafc-10bd-412d-b9f6-ad376b273d87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDczMjEsIm5iZiI6MTcwNjMwNzAyMSwicGF0aCI6Ii82MjMwODAyMC8yOTk5Mjk5NTQtZTkyNmNhZmMtMTBiZC00MTJkLWI5ZjYtYWQzNzZiMjczZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIyMTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDQzMWFhYjM2MTAzNjVjMGFiNjNmYzM1YjBiNDg1NDk1ZDllZmEwYjg1MWMyODU4NjY4ZGEzN2NlZGNkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tu6GGhdJJ_jEM_us0HS9ph5vF6EZ1uyIC0hX_989Exc)

thanks, I used this way before, but some times the path is complicated and long, it is painful if I need to figure out the correct path
