### ISSUE TITLE
Bad contrast for NvimTreeWindowPicker & NvimTreeBookmarkHL on default colorscheme

### ISSUE THREAD

**Issue by nmattia** [nvim-tree/nvim-tree.lua#2705]
### Description

I've recently updated `nvim-tree` and I can't see the window pickers anymore! The contrast on the default nvim colorscheme is quite bad. Here's the output from `NvimTreeHiTest` (`NvimTreeBookmarkHL` is pretty bad too):

<img width="516" alt="Screenshot 2024-03-13 at 16 54 56" src="https://github.com/nvim-tree/nvim-tree.lua/assets/6930756/eed4160e-8030-4303-b629-246b358d7dfe">

Do I have my colors set up wrong?

### Neovim version

```text
$ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

### Operating system and version

macOS 14.4

### nvim-tree version

github:kyazdani42/nvim-tree.lua/efafd73efa9bc8c26282aed563ba0f01c7465b06

### Steps to reproduce

```
:colorscheme default
:NvimTreeHiTest
```

**Comment by alex-courtis** [comment]
I was afraid of this. #2415 applied normal vim highlight groups links for all but `NvimTreeWindowPicker` and `NvimTreeFolderIcon`. There were no close groups and the hardcoded highlights were left unchanged.

Are you running `notermguicolors` and a 256 color term? I get similar results when I do that.

Nothing we can do about `NvimTreeBookmarkHL` as that's the vim builtin `SpellLocal`. Most color schemes deal with that one.

`NvimTreeFolderIcon` looks OK on most backgrounds as it's a blue.

That leaves `NvimTreeWindowPicker` `"guifg=#ededed guibg=#4493c8 gui=bold ctermfg=White ctermbg=Cyan"`...

**Comment by alex-courtis** [comment]
Can you please experiment with `NvimTreeWindowPicker` to find cterm values that work for you?

**Comment by nmattia** [comment]
Yep I’ll give it a try! What’s the best way to try this out and what constraints do you have on the colors? For instance, should other palettes not be reused?

**Comment by alex-courtis** [comment]
> > 
> 
> Ok, I was indeed running `notermguicolors`. With `termguicolors` it looks much nicer! I can definitely work with that.

You shouldn't have to use `termguicolors`, things should look good on 8,16,256,truecolor terminals with and without it, as it's not always available.

> One note though, now it's the NvimTreeNormalFloat that's a bit hard to read, though not as bad as the window picker with notermguicolors:

That is indeed annoying, the standard `NormalFloat` is a bad colour. Unfortunately some colour schemes and users rely on changing `NormalFloat` instead of `NvimTreeNormalFloat` so we can't do anything about that without breaking.

**Comment by nmattia** [comment]
Very cool, thank you!

**Comment by nmattia** [comment]
For the record, before:

<img width="516" alt="Screenshot 2024-03-13 at 16 54 56" src="https://github.com/nvim-tree/nvim-tree.lua/assets/6930756/eed4160e-8030-4303-b629-246b358d7dfe">

after:

<img width="236" alt="Screenshot 2024-03-15 at 11 25 49" src="https://github.com/nvim-tree/nvim-tree.lua/assets/6930756/22168724-164d-4419-8a63-5e45e1758483">

`NvimTreeWindowPicker` is much, much more readable! Though now that I've learned about `termguicolors` I think I'll stick to that, it's much softer on the eyes. Still, fix & feedback much appreciated!
