### ISSUE TITLE
update_root won't update with respect_buf_cwd when open file

### ISSUE THREAD

**Issue by BenjaminHao** [nvim-tree/nvim-tree.lua#2716]
### Description

I don't know if it's clear.
I want to let nvim-tree only show current working directory, so I set 
respect_buf_cwd = true
update_focused_file enabled
update_root = true
reload_on_bufenter = true
sync_root_with_cwd = true
so that if I open another buffer, nvim-tree will update cwd to the new one.
However, when the first time opening nvim-tree while changing directory, the cwd does not change

Not a big issue but it bothers me
![Screenshot 2024-03-18 184111](https://github.com/nvim-tree/nvim-tree.lua/assets/16693443/91cfb51e-0132-4dab-8e7e-e1e5c3024317)
(did't show core/ folder but plugins/ folder with random focus)

### Neovim version

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### Operating system and version

Windows 11

### nvim-tree version

master branch

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
	  respect_buf_cwd = true,
          reload_on_bufenter = true,
          sync_root_with_cwd = true,
	  actions = {
		  open_file = {
			  quit_on_open = true,
		  }
	  },
	  update_focused_file = {
		  enable = true,
		  update_root = true,
	  }
  }
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

Here's how to reproduce the bug:
1. 2 files in 2 different directorys
2. open nvim for the first file, toggle nvim-tree. nvim-tree shows cwd and the first file
3. change_root_to_parent, open second directory then open the second file, nvim-tree is closed by default
4. open nvim-tree, cwd is still in the first one and focus on a random file
5. reopen nvim-tree, cwd is updated to the second one and focus on the second file

### Expected behavior

update cwd when opening a new file

### Actual behavior

cwd dose not change the first time opening nvim-tree

**Comment by alex-courtis** [comment]
I'm not sure I quite understood the test case, however it looks like `actions.change_dir.global` is the option are after. It directs nvim-tree to change vim's global cwd rather than the buffer local's, which I imagine you were seeing.

The following allowed me to achieve what I think you are after.

```lua
actions.change_dir.global = true
update_focused_file.update_root = true
update_focused_file.enable = true
```

**Comment by alex-courtis** [comment]
Please do specify more information if the above isn't correct e.g.
add shell working directory and vim commands to 1, how you opened the tree in 4 etc.

**Comment by BenjaminHao** [comment]
oh. you are right! that fixed the issue
also, it seems like a neovide issue. It works fine on my terminal
Thanks for the feedback!
