### ISSUE TITLE
how to use one instance in different tab

### ISSUE THREAD

**Issue by BingCoke** [nvim-tree/nvim-tree.lua#2718]
### Description

I wanto use one nvim-tree in different tab page.
in page 1 i use NvimTree_1 but page 2 use NvimTree_2
<img width="751" alt="截屏2024-03-19 18 32 46" src="https://github.com/nvim-tree/nvim-tree.lua/assets/81607010/3b2d95c5-81a6-4934-8864-44360412e46f">
<img width="751" alt="截屏2024-03-19 18 33 09" src="https://github.com/nvim-tree/nvim-tree.lua/assets/81607010/0f50d733-7014-4504-88c3-893cdb9e2aa0">

### Neovim version

```text
NVIM v0.10.0-dev-2559+g3814750d3
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```

### Operating system and version

mac os 14.2 (23C64)

### nvim-tree version

f7c09bd

### Clean room replication

```lua
require("nvim-tree").setup({
 view = {
    float = {
      enable = true,
      quit_on_focus_loss = true,
      open_win_config = function()
        local screen_w = vim.opt.columns:get()
        local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
        local window_w = screen_w * 0.6
        local window_h = screen_h * 0.6
        local window_w_int = math.floor(window_w)
        local window_h_int = math.floor(window_h)
        local center_x = (screen_w - window_w) / 2
        local center_y = ((vim.opt.lines:get() - window_h) / 2)
            - vim.opt.cmdheight:get()
        return {
          border = 'rounded',
          relative = 'editor',
          row = center_y,
          col = center_x,
          width = window_w_int,
          height = window_h_int,
        }
      end,
    },
    width = function()
      return math.floor(vim.opt.columns:get() * 0.6)
    end,
  },


})
```

### Steps to reproduce

no

**Comment by gegoune** [comment]
DupIicate https://github.com/nvim-tree/nvim-tree.lua/issues/2255

**Comment by BingCoke** [comment]
> DupIicate #2255

OK thanks!~
