### ISSUE TITLE
Parent folder deleted when deleting a folder starting with $

### ISSUE THREAD

**Issue by sleewoo** [nvim-tree/nvim-tree.lua#2733]
### Description

If deleted folder starts with `$` then parent folder deleted instead!

In video trying delete `api/$crud` but whole `api` deleted instead!

https://github.com/nvim-tree/nvim-tree.lua/assets/74734701/7713f462-993f-4a23-be84-70c9d495787a

### Neovim version

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Operating system and version

Linux 6.5.13-7-MANJARO x86_64

### nvim-tree version

ddd1d6e

### Clean room replication

```lua
my lazy config:

  {
    "nvim-tree/nvim-tree.lua",
    cmd = {
      "NvimTreeOpen",
      "NvimTreeClose",
      "NvimTreeToggle",
      "NvimTreeFindFile",
      "NvimTreeFindFileToggle",
    },
    keys = {
      { "<leader>e", "<cmd>lua require('nvim-tree.api').tree.toggle()<cr>", desc = "Tree" },
    },
    config = function()
      require("nvim-tree").setup()
    end
  }
```

### Steps to reproduce

```
mkdir api/\$crud
nvim
```

open tree and delete `$crud` inside `api` folder

### Expected behavior

should delete `$crud` folder

### Actual behavior

it is deleting whole `api` folder

**Comment by alex-courtis** [comment]
Reproduced for trash, not for delete.

I'd be grateful if you tested a fix #2735

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2733-escape-trash-path
```

When you're finished testing:
```sh
git checkout master
```

**Comment by sleewoo** [comment]
just tested `2733-escape-trash-path` branch and it works as expected.
thanks for quick resolution.

**Comment by alex-courtis** [comment]
Apologies @sleewoo : on consideration I made a further change: https://github.com/nvim-tree/nvim-tree.lua/pull/2735#issuecomment-2030847999

I'd be most grateful if you could test again.

**Comment by sleewoo** [comment]
@alex-courtis 
tested new commit, works perfect,
thanks
