### ISSUE TITLE
Make it easy to discover useful shortcuts

### ISSUE THREAD

**Issue by thomsebastin** [nvim-tree/nvim-tree.lua#2740]
I was trying to read the help document. I have to say, it is really difficult to find some really basic commands that I would expect to find quick for what an explore/file tree does like renaming, deleting, marking, creating directory folder etc. So this is a request to have them somewhere easily accessible for the users.

**Comment by alex-courtis** [comment]
#2712 aims to improve the help screen with categories somewhat like you mentioned.

See #2710 for further discussion. We considered adding an extra `?` binding however agreed to follow the convention of `g?` to launch help.

Is that what you were looking for?

**Comment by thomsebastin** [comment]
Thanks @alex-courtis this is exactly what I was looking for. The new layout looks incredible. Thanks for taking the time to respond. Loving the plugin and excited to see it moving in the right direction. Please close this from your end as it addresses my query.
