### ISSUE TITLE
Unable to open file in new tab

### ISSUE THREAD

**Issue by adeelcap15** [nvim-tree/nvim-tree.lua#2770]
### Description

I am not able to open file when I open file in a folder which is 2 level down in hierarchy. The file opening fine in new tab if it's level is 1 or 2. 

### Neovim version

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Operating system and version

Linux archlinux 6.8.5-arch1-1  

### Windows variant

No

### nvim-tree version

64f61e4

### Clean room replication

```lua
I am using Lazy package manager with lazy=false.
		
config = function()
require("nvim-tree").setup({})
vim.keymap.set("n", "<c-n>", "<CMD>NvimTreeToggle<CR>", { desc = "Toggle NvimTree" })
vim.keymap.set("n", "<leader>n", "<CMD>NvimTreeFindFile<CR>", { desc = "Find file in NvimTree" })
end
```

### Steps to reproduce

1. Open Neovim
2. Open nvim-tree by mapping (Ctrl+N)
3. Select file from root level and Open
4. Go to folder with level (>2) and open file e.g. resources/js/Shared/SearchFilter.js
5. Ctrl + T cause the error 
6. Ctrl + V (open file in vertical split) also not working and causes cursor to move to buffer. 

### Expected behavior

It should open file in new tab

### Actual behavior

It is showing following error.

![nvim-tree-error](https://github.com/nvim-tree/nvim-tree.lua/assets/139114/b737925f-0fe2-45f0-a137-a9651bc527e8)

**Comment by alex-courtis** [comment]
Sorry, I can't replicate this and I'm not able to download the error file linked above.

```sh
mkdir -p foo/bar/baz
echo one > foo/bar/baz/one
echo root > root
nvim -nu nvt-min.lua
```

![20240512_134531](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/976b4f30-9eb9-4e4b-a945-65eb610572b8)

`<C-T>` or `<C-V>` from here work as expected.

I'm using the [clean room replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication). It may be something in your configuration that is causing this.

1. Please replicate using clean room
2. Please post the error; text in a comment is fine

**Comment by adeelcap15** [comment]
@alex-courtis Thanks for the support. The problem I faced is because of `nvim-lint` which is configured for `standardjs` which was not available after node version switching. After installing, it worked.
