### ISSUE TITLE
The path to open files is always displayed as an absolute path

### ISSUE THREAD

**Issue by epheien** [nvim-tree/nvim-tree.lua#2803]
### Description

The path to open files is always displayed as an absolute path.
NERDTree work fine.

### Neovim version

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Operating system and version

macOS 12.7.5

### nvim-tree version

2086e56

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. nvim -u nvt-min.lua
2. cd ~/.vim
3. :NvimTreeOpen
4. select `init.vim` and press `<CR>`
5. `<C-g>`

### Expected behavior

`"init.vim" xxxx lines --0%--` message in cmdline

### Actual behavior

`"~/.vim/init.vim" xxxx lines --0%--` message in cmdline

**Comment by CcccX2017** [comment]
I have the same problem with nvim 0.9.5 and lunarvim 1.4-release
![image](https://github.com/nvim-tree/nvim-tree.lua/assets/33515652/a95da63b-1d0b-4710-adef-f29d08cb89f8)
I just want to show the 'HelloWorld' folder as the root path

**Comment by epheien** [comment]
In `open_in_new_window()` function in `open-file.lua`
```
local fname = utils.escape_special_chars(vim.fn.fnameescape(filename))
```
will be
```
local fname = utils.escape_special_chars(vim.fn.fnameescape(vim.fn.fnamemodify(filename, ':.')))
```

but nvim-tree will change cwd, so `open_in_new_window()` function need `vim_cmd` parameter

**Comment by gegoune** [comment]
That was discussed in the past, please search other issues but from top of my head it's a noop.

**Comment by alex-courtis** [comment]
@CcccX2017 you can change the vim/nvim-tree root at startup to match your requirements, see wiki [Open At Startup](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup)

**Comment by alex-courtis** [comment]
@epheien see #2127 for the feature that will meet your requirements. PRs are always welcome.

Closing as duplicate.
