### ISSUE TITLE
The path is not displayed

### ISSUE THREAD

**Issue by mr-shifty** [nvim-tree/nvim-tree.lua#2816]
### Description

Instead of the path, ??? is displayed

### Neovim version

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Linux Mint 21.3 Cinnamon

### nvim-tree version

commit 8b2c5c6

### Clean room replication

```lua
-
```

### Steps to reproduce

-

### Expected behavior

Display root_folder_label

### Actual behavior

![Снимок экрана от 2024-07-03 16-38-11](https://github.com/nvim-tree/nvim-tree.lua/assets/118600823/cf082354-eade-48a8-a05c-c2c56744ef62)

**Comment by gegoune** [comment]
Please complete issues form in order to have this looked at.
