### ISSUE TITLE
Multi Instance: Refactor: nvim-tree.view

### ISSUE THREAD

**Issue by alex-courtis** [nvim-tree/nvim-tree.lua#2826]
* #2255 

`nvim-tree.view` is a stateful singleton. Make it an instantiable class owned by `Explorer`.

All usages must go through the `TreeExplorer` singleton.

This will be more difficult than other such refactors, as configuration and state are conflated and both mutated. See #2811

**Comment by raaymax** [comment]
I’m stepping away from this task for now as my workload has increased significantly with the upcoming big release. I'll revisit it once things settle down a bit on my end.

**Comment by alex-courtis** [comment]
> I’m stepping away from this task for now as my workload has increased significantly with the upcoming big release. I'll revisit it once things settle down a bit on my end.

No worries; there's no hurry to implement this any time soon. nvim-tree is grateful for the incredible amount of work you've done so far.

**Comment by alex-courtis** [comment]
I've made many attempts, however it is impractical, unsafe and of little value.

View's functionality will have to be completely rewritten during the remainder of this project.
