### ISSUE TITLE
Error while opening nvim-tree in Vue 

### ISSUE THREAD

**Issue by mslawins** [nvim-tree/nvim-tree.lua#2834]
### Description

Hi, I'm experiencing weird problem in Vue.js project, when trying to open nvim-tree. As far as I can tell it only happens if current visible buffer is .vue file. This error happens only sometimes and gives error like this:

```lua
Error executing Lua callback: ...cal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/view.lua:168: WinEnter Autocommands for "*.vue"..function matchtag#HighlightMatchingTag[19]..<SNR>56_HighlightTag, line 43: Vim(call):E801: ID already taken: 1000
stack traceback:
        [C]: in function 'nvim_command'
        ...cal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/view.lua:168: in function 'open_window'
        ...cal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/view.lua:264: in function 'open'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:193: in function 'open_view_and_draw'
        ...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/lib.lua:275: in function 'open'
        ...lazy/nvim-tree.lua/lua/nvim-tree/actions/tree/toggle.lua:48: in function 'toggle'
        ...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:98: in function <...share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/commands.lua:97>
Error detected while processing CursorMoved Autocommands for "*.vue"..function matchtag#HighlightMatchingTag[19]..<SNR>56_HighlightTag:
line   35:
E801: ID already taken: 999
```

Traceback suggests nvim-tree, but I don't know what is the real reason for this bug. 

Any tip pointing my debugging efforts into correct direction appreciated. Not sure how to move from here. Thanks.

### Neovim version

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Operating system and version

macOS Sonoma 14.5

### nvim-tree version

version: 1.5.0, tag: v1, branch: master, commit  f9ff00b

### Clean room replication

```lua
None at the moment
```

### Steps to reproduce

None at the moment

**Comment by alex-courtis** [comment]
Looks like it might be an issue with another plugin or customisation: `matchtag#HighlightMatchingTag`

Please provide a clean room replication so that we may resolve this.

**Comment by mslawins** [comment]
I found the real culprit. Adding this plugin:

https://github.com/leafOfTree/vim-matchtag

together with `nvim-tree` causes my problem, only for `.vue` files.  

Thank you for assistance. 😄
