### ISSUE TITLE
api.fs.create_directory

### ISSUE THREAD

**Issue by thepenguinthatwants** [nvim-tree/nvim-tree.lua#285]
Right now
- type 'a' to add a file

Could be nice if 
- type 'A' to add a folder

**Comment by kyazdani42** [comment]
type `a` and then add a trailing `/` will create folders (see #3).
If you really want a command to do that, please reopen this :)

**Comment by twiddli** [comment]
Hi, great plugin but I think this is a bit unintuitive for new people (like me).
It would be great to have a dedicated command for it as well. That would at least save people from having to google.

I have been trying to match Vim's default file explorer's keymappings and would really like to dedicate `d` to creating folders.

**Comment by gegoune** [comment]
On Unix systems directory is just a type of node, same as file. Should we make it more generic, like create_node?

**Comment by alex-courtis** [comment]
> On Unix systems directory is just a type of node, same as file. Should we make it more generic, like create_node?

Yes. We could be more generic and extend the existing create like:

```help
fs.create({node}, {opts})                          *nvim-tree-api.fs.create()*
    Prompt to create a file or directory. Use a trailing `/` for a directory.

    Parameters: ~
      • {node} (Node) parent, uses the parent of a file.
      • {opts} (table) optional parameters

    Options: ~
      • {type} (string) `"file"` or `"directory"`, default `"file"`
```

Only problem is how we would pass those opts in, with the node populated. Passing `nil` would work, we'd need to note it in the doc.

**Comment by alex-courtis** [comment]
If I were designing the API from scratch today, I'd make the `{node}` optional parameters for all such functions. Node really optional.

e.g.
```help
fs.create({opts})                                  *nvim-tree-api.fs.create()*
    Prompt to create a file or directory. Use a trailing `/` for a directory.

    Parameters: ~
      • {opts} (table) optional parameters

    Options: ~
      • {node} (Node) default node under cursor
      • {type} (string) `"file"` or `"directory"`, default `"file"`
```

The problem is backwards compatibility. It was achieved for functions like `ApiTreeToggleOpts` via looking at parameter types. We can't do that in this case as node and opts are both tables.

One option is to look for fields like `absolute_path`, `fs_stat` etc. in the table parameter, to determine whether it is a node or opts. Not a great solution.

**Comment by alex-courtis** [comment]
Created #2146

**Comment by gegoune** [comment]
Personally I am not that bothered either. `/` suffix is what I use every time I need to create directory.

This is an old issue that Kiyan closed promptly. Also premise that "That would at least save people from having to google." isn't entirely true if documentation is provided with plugin itself (it is).

**Comment by alex-courtis** [comment]
Added FAQ: https://github.com/nvim-tree/nvim-tree.lua/wiki/FAQ

Clarified: https://github.com/nvim-tree/nvim-tree.lua/pull/2572
