### ISSUE TITLE
Visual bug when opening nvim tree bar

### ISSUE THREAD

**Issue by chgara** [nvim-tree/nvim-tree.lua#2876]
### Description

When opening nvim tree bar it makes a weird visual bug  if a buffer it is currently open, It kinda duplicates the buffer in the screen and 0.5s later it is not there.

I attatch a video in slow mo with the thing, it is in the second 7.

Also my config for nvim tree lua is the following:

```
{
        "nvim-tree/nvim-tree.lua",
        lazy = true,
        init = function()
	        vim.opt.termguicolors = true
        end,
        ---@module "nvim-tree"
        ---@type nvim-tree.config
        opts = {
            view = {width = 40},
            actions = {
                open_file = {
                    window_picker = {
                        enable = false,
                    }
                }
            }

        },
        dependencies = { "nvim-tree/nvim-web-devicons" },
        keys = require("config.keymaps").nvim_tree,
 }
```

https://github.com/user-attachments/assets/49d13857-0959-438b-99d5-7da3e360d930

### Neovim version

```text
☁  ~  nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
☁  ~
```

### Operating system and version

arch1-1.1

### nvim-tree version

ad0b95d

### Clean room replication

```lua
{
        "nvim-tree/nvim-tree.lua",
        lazy = true,
        init = function()
	        vim.opt.termguicolors = true
        end,
        ---@module "nvim-tree"
        ---@type nvim-tree.config
        opts = {
            view = {width = 40},
            actions = {
                open_file = {
                    window_picker = {
                        enable = false,
                    }
                }
            }

        },
        dependencies = { "nvim-tree/nvim-web-devicons" },
        keys = require("config.keymaps").nvim_tree,
    }
```

### Steps to reproduce

1. Open buffer
2. Open nvim tree bar
3. See bug

### Expected behavior

To not make weird visual bugs

**Comment by gegoune** [comment]
Please follow clean room replication as per issue template (don't use lazy).

**Comment by simonmandlik** [comment]
Had a similar issue because of numbertoggle plugin which calls `:redraw` (https://github.com/sitiom/nvim-numbertoggle/issues/15). Because of that, new nvim-tree window is redrawn immediately after being created and before being resized to actual size
