### ISSUE TITLE
Directory empty

### ISSUE THREAD

**Issue by loeffel-io** [nvim-tree/nvim-tree.lua#2889]
### Description

I can't see files in this directory

<img width="276" alt="Bildschirmfoto 2024-08-30 um 10 43 42" src="https://github.com/user-attachments/assets/b25c5131-7be5-4240-8297-2b3563cda20f">
<img width="311" alt="Bildschirmfoto 2024-08-30 um 10 44 09" src="https://github.com/user-attachments/assets/2b01f4fc-2431-4c66-9081-bb8ac377b0cd">

### Neovim version

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

### Operating system and version

macOS 14.4

### nvim-tree version

d43ab67

### Clean room replication

```lua
-
```

### Steps to reproduce

-

**Comment by loeffel-io** [comment]
telescope can see this files btw

**Comment by gegoune** [comment]
Please don't omit any steps from bug reporting template. There is nothing here for us to work with. Most likely those files are git (or otherwise) ignored. Closing for now, please reopen if you think it is an issue and bug template is filled in fully.

**Comment by loeffel-io** [comment]
this files are not git ignored and the reproduction is to create two 2 directories and files? 😅

**Comment by loeffel-io** [comment]
```
			filters = {
				custom = { "^.DS_Store$", "^.git$", "^.idea$" },
				dotfiles = false,
			},
``` 

solved it somehow, thank you anyways!

**Comment by alex-courtis** [comment]
> solved it somehow, thank you anyways!

@loeffel-io please describe your solution for others.

https://xkcd.com/979/
