### ISSUE TITLE
Do not ignore `right_aligned` icons when computing max window width

### ISSUE THREAD

**Issue by simonmandlik** [nvim-tree/nvim-tree.lua#3015]
**Is your feature request related to a problem? Please describe.**
I like the nvim-tree window to take as much width as needed as long as it doesn't cover over `60%` of the screen. For this reason, I'm using

```lua
view.width = {
   min = -1,
   max=60%
}
```

This works very nice, but when used together with `right_align`ed icon extmarks, the longest paths are not always shown in full, even if there is plenty of width in the window. This is likely because the max width computation doesn't take these extmarks into account.

It would be great to have the width computation take extmarks into account.

I guess the modification could be done here?
https://github.com/nvim-tree/nvim-tree.lua/blob/ca7c4c33cac2ad66ec69d45e465379716ef0cc97/lua/nvim-tree/view.lua#L302-L335

**Comment by alex-courtis** [comment]
> I guess the modification could be done here?

That looks correct, a pull request would be most gratefully appreciated, see [CONTRIBUTING.md](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md)

> `max=60%`

Should this be `max="60%"`

**Comment by simonmandlik** [comment]
> a pull request would be most gratefully appreciated

Here https://github.com/nvim-tree/nvim-tree.lua/pull/3022

> Should this be `max="60%"`

Sure, sorry, made a typo here :)
