### ISSUE TITLE
nvim-tree integration: winid might be nil when floating view is enabled

### ISSUE THREAD

**Issue by joseffilzmaier** [nvim-tree/nvim-tree.lua#3016]
### Description

I am using nvim-tree and fidget.nvim and received error messages once i enabled view.float.enable = true inside of my nvim-tree plugin.

The error occurs every time i start nvim

Error Message:
```
[NvimTree] Handler for event TreeOpen errored. "...im/lazy/fidget.nvim/lua/fidget/integration/nvim-tree.lua:39: Invalid 'window': Expected Lua number"
```

### Neovim version

```text
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Run "nvim -V1 -v" for more info
```

### Operating system and version

Linux 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### nvim-tree version

99db23d

### Clean room replication

```lua
for lsp:
{
    'neovim/nvim-lspconfig',
    dependencies = {
      'williamboman/mason.nvim',
      'williamboman/mason-lspconfig.nvim',
      'WhoIsSethDaniel/mason-tool-installer.nvim',
      { 'j-hui/fidget.nvim', opts = {} },
    },
  config = function()
... some keymaps
end
}
For
```

### Steps to reproduce

Open any file

### Expected behavior

No error message is shown

### Actual behavior

Error Message:
```
[NvimTree] Handler for event TreeOpen errored. "...im/lazy/fidget.nvim/lua/fidget/integration/nvim-tree.lua:39: Invalid 'window': Expected Lua number"
```

**Comment by joseffilzmaier** [comment]
oh, wrong repository, sorry for the noise :confused:

**Comment by alex-courtis** [comment]
> oh, wrong repository, sorry for the noise 😕

No worries. Is there an issue in another project that I should watch?

**Comment by joseffilzmaier** [comment]
The problem is in the fidget nvim-tree integration, i opened an issue and a pull request there if you're curious: https://github.com/j-hui/fidget.nvim/issues/259
