### ISSUE TITLE
git submodule icons in nvim-tree

### ISSUE THREAD

**Issue by adimail** [nvim-tree/nvim-tree.lua#3035]
This feature idea was originally discussed here: [Does nvim-tree have webicon for git submodules?](https://github.com/nvim-tree/nvim-tree.lua/discussions/3034).

Raised a similar issue in nvim-tree/nvim-tree.lua#3038 

Should this go into nvim-tree itself?

#### Proposed Solution
Allow users to define a custom icon for Git submodules in the `renderer.icons.git` configuration. For example:

```lua
renderer = {
    -- other configurations...
    icons = {
        -- other icons...
        git = {
            -- existing git icons...
            submodule = '',  -- Git submodule icon
        },
    },
},
```

It would be helpful to have a dedicated icon for Git submodules in the `nvim-tree` file explorer. Currently, while `nvim-tree` supports various Git status icons (e.g., staged, unstaged, untracked), there isn’t an option to display a unique icon for submodules.

**Comment by alex-courtis** [comment]
Tracked in #3038
