### ISSUE TITLE
Create lua callback when tree closes and opens

### ISSUE THREAD

**Issue by ahmedkhalf** [nvim-tree/nvim-tree.lua#575]
Currently, I have this:
```lua
  vim.cmd "au FileType NvimTree lua require('core.nvimtree').on_type()"
end
--
M.on_type = function()
  local buf = vim.fn.expand "<abuf>"
  vim.cmd("au BufWinEnter <buffer=" .. buf .. "> lua require('core.nvimtree').on_open()")
  vim.cmd("au WinClosed   <buffer=" .. buf .. "> lua require('core.nvimtree').on_close()")
end
--
M.on_open = function()
  if package.loaded["bufferline.state"] and lvim.builtin.nvimtree.side == "left" then
    require("bufferline.state").set_offset(lvim.builtin.nvimtree.width + 1, "")
  end
end
--
M.on_close = function()
  if package.loaded["bufferline.state"] then
    require("bufferline.state").set_offset(0)
  end
end
```
It works, but the other lunarvim devs are not willing to accept it because it features 3 autocmds [#1351](https://github.com/LunarVim/LunarVim/pull/1351#discussion_r691962236). It would be great if nvim-tree could provide a lua callback whenever the tree opens or closes.

**Comment by kyazdani42** [comment]
why not just overriding the open/close functions ? like `:NvimTreeOpen | some_other_func`

**Comment by ahmedkhalf** [comment]
This works for opening, but for closing, there are many methods of closing, one of them is by doing `:q`, so unfortunately for closing, we need a callback.

**Comment by kyazdani42** [comment]
not sure i can manage all the different methods for closing, it depends on how users use nvim. You could actually bind keymaps for your use case by hacking around the ex commands.

**Comment by alex-courtis** [comment]
See also #917

**Comment by alex-courtis** [comment]
Implemented. See `:help nvim_tree_events_kind`
