### ISSUE TITLE
[Feature Request] Please please let us remove [NvimTree] following options are now set in the setup (:help nvim-tree.setup): nvim_tree_follow

### ISSUE THREAD

**Issue by nesper8** [nvim-tree/nvim-tree.lua#699]
Please please let us remove this

`[NvimTree] following options are now set in the setup (:help nvim-tree.setup): nvim_tree_follow`
I'm tired of seeing it
Its just way too distracting
Please

**Comment by avatsavirs** [comment]
What is the equivalent of nvim_tree_follow in the setup function?

**Comment by LuisxSullivaN** [comment]
how hard is to press `:help nvim-tree.setup` and read a bit...

**Comment by dvsociety** [comment]
I don't understand how to fix the loading error when starting lvim. Could someone explain it in a way that a newbie in both English and programming understands.
![pic-full-220531-1544-19](https://user-images.githubusercontent.com/102924958/171262199-cfd44e80-07fc-44e5-a25a-b21b904b1d99.png)

**Comment by gegoune** [comment]
Looks like an issue that lunar vim should fix since it's them pairing new version of plugin with obsolete version of that plugin's configuration.

**Comment by dvsociety** [comment]
> see #674 but i believe indeed lunarvim should update nvim-tree configuration

I've seen it and I don't understand what I have to do.

**Comment by alex-courtis** [comment]
It looks like lunarvim is now [fixing](https://github.com/LunarVim/LunarVim/pull/2681/files#diff-63b70cc9adb8829caa30d818aa5e43d350ebf5fdad156346d64e8b896eaf1629R69) their nvim-tree version to a commit.
