### ISSUE TITLE
Error when using require'nvim-tree'.setup()

### ISSUE THREAD

**Issue by alexander-born** [nvim-tree/nvim-tree.lua#714]
I get the following error on startup when using 

```lua
    use {'kyazdani42/nvim-tree.lua', config = function() require'nvim-tree'.setup {} end }
```

```
packer.nvim: Error running config for nvim-tree.lua: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:91: Vim(call):E742: Cannot change value of insert() argument
```

**Comment by alexander-born** [comment]
I just start it via console with `nvim`.

I am using the current neovim nightly. I'll check if it is conflicting with another plugin.

**Comment by kyazdani42** [comment]
i guess you should ignore this autocmd for nvim tree somehow (filetype or bufname i think).

**Comment by kyazdani42** [comment]
yes the nvim-tree buffer is kept alive all the time which is a little strange. some things i must fix yet.
