### ISSUE TITLE
How to open file/directory with a single mouse-click?

### ISSUE THREAD

**Issue by astier** [nvim-tree/nvim-tree.lua#731]
Right now `2-leftmouse` is required to open a file/directory. I tried mapping to just `leftmouse` but it doesn't work properly. `leftmouse` does open the directory/file under the cursor with a single clock but it doesn't move the cursor to the file/directory I actually clicked.

```lua
local tree_cb = require'nvim-tree.config'.nvim_tree_callback
require'nvim-tree'.setup {
  view = {
    mappings = {
      list = {
        { key = { '<leftmouse>' }, cb = tree_cb("edit") },
      }
    }
  }
}
```

**Comment by atishay** [comment]
@kyazdani42 I have been able to achieve single mouse click using the following code:

```
local function action_callback_for_tree(node)
  vim.cmd [[
  execute "normal! \<LeftMouse>"
  ]]
  local lib = require'nvim-tree.lib'
  local node = lib.get_node_at_cursor()
  if not node then return end
  print(node.absolute_path)
end
```

The idea was copied from https://github.com/preservim/nerdtree/blob/81f3eaba295b3fceb2d032db57e5eae99ae480f8/autoload/nerdtree/ui_glue.vim#L387

You can use the execute approach for all mouse events to make them possible on a single click.

**Comment by kyazdani42** [comment]
I'll see what i can do about this :) If someone want's to open a PR, it would be gladly welcome too.

**Comment by atishay** [comment]
There was a focus bug in nvim. It was able to show the menu with one click but the focus needed to be on the right pane. The concept works in vim. I will like the nvim issue to this thread once I find it.

**Comment by danielo515** [comment]
That may explain my problem. Thanks for letting me know (and for linking the issue when you find it)

**Comment by atishay** [comment]
https://github.com/neovim/neovim/issues/14921

**Comment by atishay** [comment]
Got this to work in nvim 0.8

```lua
local function single_click_edit(node)
  vim.defer_fn(function ()
    local win = vim.api.nvim_get_current_win()
    local view = require "nvim-tree.view"
    if view.get_winnr() ~= win then return end
    local actions = require'nvim-tree.actions.dispatch'
    actions.dispatch("edit")
  end, 10)
end

require('nvim-tree').setup({
  view = {
    mappings = {
      list = {
        { key = "<LeftRelease>", action= "single_click_edit", action_cb = single_click_edit},
      }
    }
  }
});

```

**Comment by alex-courtis** [comment]
> ```lua
> LeftRelease
> ```

Very nice! Added to `:help nvim-tree-mappings`.

**Comment by alex-courtis** [comment]
Closing as we have a valid workaround.

**Comment by louwers** [comment]
For people coming here:

> Setting your own mapping in the configuration will soon be deprecated, see `nvim-tree.on_attach` for experimental replacement.

**Comment by danielo515** [comment]
> For people coming here:
> 
> > Setting your own mapping in the configuration will soon be deprecated, see `nvim-tree.on_attach` for experimental replacement.

Deprecated and substituted with an experimental API?

**Comment by alex-courtis** [comment]
> > For people coming here:
> > > Setting your own mapping in the configuration will soon be deprecated, see `nvim-tree.on_attach` for experimental replacement.
> 
> Deprecated and substituted with an experimental API?

The transition will be seamless, with no action needed or expected from users:
* existing mappings will continue to work
* an optional mechanism to automatically generate and migrate your mappings to `on_attach` will be available
* comprehensive transition documentation will be available

See #1579 for full details.

**Comment by danielo515** [comment]
Thanks

**Comment by ZeChArtiahSaher** [comment]
How do you do it now? The mapping config thing's changed ;'(

**Comment by gaoqiangks** [comment]
> How do you do it now? The mapping config thing's changed ;'(.
> 
> *edit:
> 
> Nevermind:
> 
> ```
> local function my_on_attach(bufnr)
> 	local api = require "nvim-tree.api"
> 
> 	vim.keymap.set('n', '<LeftRelease>', function() 
> 		local api = require('nvim-tree.api')
> 		local node = api.tree.get_node_under_cursor()
> 
> 		if node.nodes ~= nil then
> 			api.node.open.edit()
> 		end
> 	end, {})
> end```
> ```

How should I do?  I copy this code to my config, and set `require("nvim-tree").setup({ on_attach = my_on_attach})`, it didn't work.

**Comment by alex-courtis** [comment]
> How should I do? I copy this code to my config, and set `require("nvim-tree").setup({ on_attach = my_on_attach})`, it didn't work.

Take a look at `:help nvim-tree-quickstart-custom-mappings` for a working example you can copy and extend.
