### ISSUE TITLE
Overwhelming `git` processes if using Telescope git_files from nvim-tree

### ISSUE THREAD

**Issue by hahuang65** [nvim-tree/nvim-tree.lua#733]
On macOS 10.15.7
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

If I have `nvim-tree` installed, and I run `require"telescope.builtin".git_files`, it spawns thousands of `git` processes, to the point where I run out of `pty`s to fork on macOS, and I cannot use my shell for anything.
If I spawn a new terminal, I just see:

```
-bash: fork: Resource temporarily unavailable
```

This only happens if I have `nvim-tree` installed, and I run the telescope command IMMEDIATELY after starting nvim, such that the `nvim-tree` screen is what is focused. It doesn't happen when I'm already on a file buffer, or in `netrw` (no nvim-tree).

The reproduction steps are to open nvim, and immediately run `require"telescope.builtin".git_files` and open a file. It will trigger the problem.

This is what I see when I run `ps` and the problem doesn't occur (if I navigate to a file first, or don't use nvim-tree):

```
  PID TTY           TIME CMD
23761 ttys000    0:00.03 -bash
26194 ttys000    0:00.63 watch ps
35727 ttys000    0:00.00 watch ps
25991 ttys001    0:00.04 -bash
35141 ttys001    0:00.89 nvim .
35160 ttys001    0:03.84 /Users/hhhuang/.cache/nvim/lua-language-server/bin/macOS/lua-language-server
 -E /Users/hhhuang/.cache/nvim/lua-language-server/main.lua
35165 ttys001    0:00.00 (git)
```

And if it does occur:

```
$ ps | grep git | wc -l
202
$ ps | grep git | wc -l
339
$ ps | grep git | wc -l
459
$ ps | grep git | wc -l
561
$ ps | grep git | wc -l
651
$ ps | grep git | wc -l
760
$ ps | grep git | wc -l
860
$ ps | grep git | wc -l
952
$ ps | grep git | wc -l
1385
$ ps | grep git | wc -l
1538
$ ps | grep git | wc -l
1708
$ ps | grep git | wc -l
2036
```
It just keeps growing until the system is overwhelmed.

For what it's worth, changing my `nvim-tree` config doesn't do anything, but this is my config:

```
require'nvim-tree'.setup {
  disable_netrw = true,
  auto_close = true,
  update_cwd = true,
  update_focused_file = {
    enable = true
  }
}

vim.g.nvim_tree_ignore = { '.git', 'node_modules' } -- Ignore certain subdirectories/files
vim.g.nvim_tree_indent_markers = 1                  -- Show indentation markers for subdirectories
vim.g.nvim_tree_add_trailing = 1                    -- Adds a trailing `/` to denote directories
vim.g.nvim_tree_group_empty = 1                     -- If a directory has a single child, combine into 1 entry
```

**Comment by kyazdani42** [comment]
hi @hahuang65 sorry i completely didn't catch this. Does this issue still happen ?

**Comment by hahuang65** [comment]
Yup, it does

**Comment by kyazdani42** [comment]
hum could not reproduce on linux with the provided configuration :( This might be macos related, i do not own a macos machine, so i'd need someone to do the debugging.

**Comment by kyazdani42** [comment]
Thanks, i use nixos so i should be able to reproduce if it's happening on arch.

**Comment by hahuang65** [comment]
@kyazdani42 I just tried on Arch and macOS. This doesn't seem to be a problem anymore. Hooray!

Thanks for following up with this!
