### ISSUE TITLE
Multiple directories in the same tree

### ISSUE THREAD

**Issue by jrafaaael** [nvim-tree/nvim-tree.lua#757]
Is there a way to have more than one directory open in the same tree?

Let's say something like `/projects/backend/` and `/desktop/test/`

I find it useful especially to facilitate access to code that is hosted in another directory

**Comment by kyazdani42** [comment]
you mean multiple workspaces ? It's already been asked, but there is no way to do that currently.

**Comment by alex-courtis** [comment]
Maybe multiple trees in one tab...

**Comment by kyazdani42** [comment]
yes multiple trees, but following current implementation it would be quite hard to do and need a lot of refactoring in order to achieve.

**Comment by alex-courtis** [comment]
Thanks for the feature request.

Unfortunately, nvim-tree is in a stable, feature complete state and we do not intend to add such features.
