### ISSUE TITLE
Add support for scanning down files by using treesitter / tags

### ISSUE THREAD

**Issue by phaazon** [nvim-tree/nvim-tree.lua#764]
[treemacs](https://github.com/Alexander-Miller/treemacs) has this super cool feature where pressing `<tab>` on a directory opens a it to show the files, but pressing tab on a file opens it in the tree view and show it contents too! For Markdown, it shows the the titles / sub-titles, etc.; for any files written in a Treesitter-compatible language, it shows the nodes directly.

Example:

![Screenshot 2021-11-02 at 15 37 43](https://user-images.githubusercontent.com/506592/139868545-bf28885b-04b0-4c50-a635-a7e3fe3f447c.png)

**Comment by kyazdani42** [comment]
we would need to add another rendering view for that feature. Although i'm not particularly interested in that, but i'll welcome a PR that does this in a clean way, but maybe after the refactorings are merged.

**Comment by alex-courtis** [comment]
Thanks for the feature request.

Unfortunately, nvim-tree is in a stable, feature complete state and we do not intend to add such features.
