### ISSUE TITLE
Event when the nvim-tree buffer is closed

### ISSUE THREAD

**Issue by augustocdias** [nvim-tree/nvim-tree.lua#990]
I don't know which commit introduced this "issue". (I'm not sure if its a bug or intended behavior)

I have this autocommand that stopped working since I updated this morning:

```lua
vim.api.nvim_command(
    [[autocmd BufHidden NvimTree lua vim.schedule(function() require('bufferline.state').set_offset(0) end)]]
)
```

So basically I have a special bufferline for NvimTree and when I open a file from it, it was not updating the bufferline. So I added this auto-command to update it for me. It was working fine but it is not anymore.

Did the behavior change? Is the buffer not hidden anymore? Is there a way to make this work again?

**Comment by kyazdani42** [comment]
the buffer is not hidden anymore it's wiped out completely :) Could you try BufWipeout ? or BufDelete ?
